### ISSUE TITLE
Cannot open file tbb.dll

### ISSUE THREAD

**Issue by Jomot** [oneapi-src/oneTBB#101]
I'm setting up my environment for a project and I'm getting the error 'LNK1104 cannot open file tbb.dll'.
I'm running VS 2017 and the latest version of TBB.
I have unzipped TBB into the a folder containing the project folder. (So the folder has 'TestProject01' folder name and 'Library' foldername. Inside libary is the unzipped tbb from github)
 VC++ include directory is: 'Libary\tbb2019_20181010oss\include' 
and Library Directory is: 'Libary\tbb2019_20181010oss\lib\ia32\vc14'
Also Additinal Dependencies include 'tbb.dll' which I got from 'Libary\tbb2019_20181010oss\bin\ia32\vc14'
tbb.dll has been copied into the debug folder in my project folder

The programme I'm running is a simple hello world. 

#include "pch.h"
#include <iostream>
#include <tbb/tbb.h>

int main()
{
    std::cout << "Hello World!\n"; 
}

Any suggestions on how I can fix this error? 
Thanks :)

**Comment by aleksei-fedotov** [comment]
Perhaps, the code is compiled for 64-bit processor, while the library being linked is 32-bit. If that is the case, consider changing either target bitness in VS to 32 or specify path to 64-bit tbb.dll.

Closing the issue as outdated, sorry for not reaching you timely. If it is still relevant and the suggestion above was not helpful, please reopen it again.
