### ISSUE TITLE
Missing symbol `tbb::detail::d1::task_arena_base::automatic`

### ISSUE THREAD

**Issue by ryan-gunderson** [oneapi-src/oneTBB#1011]
I make use of `oneapi::tbb::task_arena::automatic` when making task arenas in a library.  If I compile against tbb without optimization (`-O0`) my shared object is left looking for an undefined symbol `tbb::detail::d1::task_arena_base::automatic`.  

When compiling with `-O2` this does not happen (presumably because the reference has been optimized out).  This can also be fixed by declaring the global variable `const int oneapi::tbb::detail::d1::task_arena_base::automatic;` in my source.  I think this is related to how static class variables don't allocate storage or something?.

This is all being done on linux with gcc 12.2.0 with gcc/tbb installed via conda.

Should this static variable declaration be done in the tbb source cpp files so this symbol is exported in the library and gets storage?

**Comment by pavelkumbrasev** [comment]
Seems to be a duplication of https://github.com/oneapi-src/oneTBB/issues/529

**Comment by pavelkumbrasev** [comment]
Closing this issue because it is a duplication.
