### ISSUE TITLE
task arenas: how it works

### ISSUE THREAD

**Issue by exldna** [oneapi-src/oneTBB#1012]
Hello. I have a [question](https://stackoverflow.com/q/75153428/18017660) on stackoverflow. Can someone please help me? In short:
- Is it guaranteed that all tasks in the task_arena will be executed on the same threads set?
- If i have two arenas, can their threads sets be intersected?

**Comment by pavelkumbrasev** [comment]
Hi @exldna, if you don't mind I will post the answer here.
1) Based on first example you provided:
```
auto rendering_arena = tbb::task_arena(1, 0);
rendering_arena.execute([](){
    while (window_available) {
        // draw something
    }
});
```
The thread that call `task_arena::execute` will proceed with task execution. 
However, the code sample that you provided make things a bit more complicated. Why did you try to use  `tbb::task_arena(1, 0);`? 

>Is it guaranteed that all tasks in the task_arena will be executed on the same threads set?

The short answer is no. Threads might migrate between arenas. For example let's consider: machine with 8 threads and two arenas A1,A2 with concurrency on 8 threads. (so each A1 and A2 can simultaneously fit 8 threads in sum 16 but only 8 available)
Let's follow such sequence: 

1. Work submitted to A1.
2. A1 requested 8 threads from scheduler.
3. A1 granted all available threads (8 in our case).
4. All threads started execute tasks in A1.
5. Work submitted to A2.
6. A2 requested 8 threads from scheduler.
7. Scheduler partition threads between this arenas 4 threads in A1 and 4 in A2.
8. 4 threads leave A1 and join to A2

>If i have two arenas, can their threads sets be intersected?

When there is no available work in arenas threads will leave them and block(sleep) until further work submission.
Once new work will be submitted threads might join to arenas in unpredictable manner.

**Comment by exldna** [comment]
Ok, thank you. I used task_arena(1, 0) because I searched the cases to delegate threading management to tbb. So, old std::thread is my best friend in there.
