### ISSUE TITLE
Useless(?) shebangs in python modules

### ISSUE THREAD

**Issue by jwakely** [oneapi-src/oneTBB#1014]
https://github.com/oneapi-src/oneTBB/blob/master/python/TBB.py and all the files in https://github.com/oneapi-src/oneTBB/tree/master/python/tbb/ have a `#!/usr/bin/env python3` shebang, but none of them is executable. That means the shebang is useless, because you can never execute them.

Are those python files actually *supposed* to be executed? Or are they only intended to be used as modules, e.g. `python -m TBB user_app.py`?

I note that in tbb-2020.3 not all those files had a shebang, only `TBB.py`, `tbb/__init__.py` and `tbb/__main__.py`. But in oneTBB the others have gained a shebang too.

This causes problems for downstream packagers, e.g. Fedora has packaging checks that do not allow non-executable files with shebangs, because it doesn't make sense (if they're supposed to be executable they should have the 'x' bit set in their file mode, and if they're not supposed to be executable they shouldn't have a shebang). So currently the Fedora package for `tbb` uses `chmod` to make those files executable, and if the package is updated to oneTBB then the packaging config will need to be updated to `chmod` the other files that didn't used to have a shebang. Maybe we should really be stripping the shebang from them instead.

If I'm right that those shebangs are useless then I can submit a PR to remove them, but I wanted to check if I'm misunderstanding something.

**Comment by isaevil** [comment]
Hi @jwakely. See [README](https://github.com/oneapi-src/oneTBB/tree/master/python#command-line-interface):
> python3 -m tbb your_script.py - Run your_script.py in context of with tbb.Monkey(): when oneTBB is enabled. By default only multi-threading will be covered.
> python3 setup.py build -b ... - Build and install oneTBB module for Python.
> python3 -m tbb test - run test for oneTBB module for Python

I am not actually an expert in TBB's Python module but looks like that tbb4py is expected to be used as module but its code also allows to execute it directly: 
> TBB.py - Alternative entry point for Python module.

And there is classic `if __name__ == "__main__` statement.

So shebangs should make sense here, but missing executable permissions for that do not make so :)

**Comment by jwakely** [comment]
You can run it as the "main" program by using `python3 /path/to/TBB.py` which doesn't require a shebang or executable permission. So I don't think that's conclusive.

If the files like `TBB.py` and `tbb/api.py` are not installed somewhere in `PATH` like `/usr/bin` then the benefit of being able to run them directly (without saying `python3 TBB.py`) is very questionable.

**Comment by jwakely** [comment]
And all the examples in the README show it being run as `python3 ...` not by executing the script directly as e.g. `./TBB.py` or `/path/to/TBB.py`.

**Comment by isaevil** [comment]
> And all the examples in the README show it being run as `python3 ...` not by executing the script directly as e.g. `./TBB.py` or `/path/to/TBB.py`.

That is what I meant by "expected to be used as module" :)

> If the files like TBB.py and tbb/api.py are not installed somewhere in PATH like /usr/bin then the benefit of being able to run them directly (without saying python3 TBB.py) is very questionable.

I guess `TBB.py` is not available in PATH when you install it via package managers like conda so you won't be able to run them as `TBB.py script.py`.

**Comment by isaevil** [comment]
@jwakely Seems like there is no need to have shebangs because:
1) TBB.py script is not available in PATH by default.
2) There are no exec permissions for them. 

I would kindly suggest you to submit a corresponding PR for that as you mentioned earlier :)
