### ISSUE TITLE
Which benchmark suites are suggested to run with TBB?

### ISSUE THREAD

**Issue by RandySheriffH** [oneapi-src/oneTBB#1021]
Recently we are planning to test TBB's performance on varied platforms, may I know which benchmark suites are suggested to run with TBB?

**Comment by pavelkumbrasev** [comment]
You can measure performance using oneTBB [examples](https://github.com/oneapi-src/oneTBB/tree/master/examples).

**Comment by RandySheriffH** [comment]
@isaevil : they probably fine for the job ... reguarly does TBB team do benchmarking on varied cpus/configurations and annouce results somewhere?

**Comment by isaevil** [comment]
@RandySheriffH you may check [Intel's oneTBB page](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onetbb.html#gs.q0iai7) for "Benchmarks" section.

**Comment by pavelkumbrasev** [comment]
Please reopen this issue if you still have a questions.
