### ISSUE TITLE
Libtbb.so cannot be loaded under Android Studio？

### ISSUE THREAD

**Issue by linyuan0** [oneapi-src/oneTBB#103]
I created a new test program under android studio to link to libtbb.so.Only when libtbb.so is loaded, flash retreat occurs when app is running.I tried loading the other so again, proving that I had no problem loading the library.
Later, I tried releases's libtbb.so, and found that there was a problem. Once I ran the APP, I quit the program and loaded the other so.
I just want to ask, have you tested android calling it libtbb.so?Maybe I'm calling it the wrong way?
I use the android - the NDK - r12b;
Ndk-build TBB tbbmalloc arch=arm64-v8a target=android compiler=clang ndk_version= 12 -j -B

**Comment by anton-potapov** [comment]
@linyuan0 is this problem still reproducible with oneTBB ? 
oneTBB should work for Android build out of the box (it known to work with NDK-r20 for sure)

**Comment by anton-potapov** [comment]
@linyuan0 please reopen if the problem still exists
