### ISSUE TITLE
There may be an error when concurren_hash_map only has one item

### ISSUE THREAD

**Issue by Spear-Neil** [oneapi-src/oneTBB#1041]
** The following code can't stop.**
 ```
 tbb::concurrent_hash_map<int, int> hash_map;
  tbb::concurrent_hash_map<int, int>::accessor accessor;
  hash_map.insert(accessor, 10);
  accessor->second = 10;

  tbb::concurrent_hash_map<int, int>::accessor a;
  hash_map.find(a, 10);
  std::cout << a->second << std::endl;
```

**but these code work well.**

```
  tbb::concurrent_hash_map<int, int> hash_map;
  tbb::concurrent_hash_map<int, int>::accessor accessor;
  hash_map.insert(accessor, 10);
  accessor->second = 10;
  
  hash_map.find(accessor, 10);
  std::cout << accessor->second << std::endl;

```

```

  tbb::concurrent_hash_map<int, int> hash_map;
  tbb::concurrent_hash_map<int, int>::accessor accessor;
  hash_map.insert(accessor, 10);
  accessor->second = 10;
  hash_map.insert(accessor, 11);
  accessor->second = 11;

  tbb::concurrent_hash_map<int, int>::accessor a;
  hash_map.find(a, 10);
  std::cout << a->second << std::endl;
```

**Comment by JhaShweta1** [comment]
Thank you @Spear-Neil . Code 1 and 3 are calling 'find' with an empty accessor. According to the specification if accessor is not empty result is released . I changed 'hash_map.find(a, 10);' to 'hash_map.find(a, 11);' in code 3 and it also starts hanging. If possible could you use a non-empty accessor, meanwhile we will investigate the issue more, and see if we can exit instead of hanging.

**Comment by kboyarinov** [comment]
@Spear-Neil, the problem in the first code snippet (and in the third as well) is that you have write accessor `accessor` that provides write access to the inserted element `{10, 10}`. On the implementation level it means that `accessor` holds write-lock on the mutex associated with the inserted element.
When you are calling `find(a, 10)` with the same key, but different accessor, the hash map tries to provide write access to the same element using the accessor `a` and hence acquire the write-lock associated with the element. But `accessor` already holds this lock, so `a` waits infinitely on the mutex.  
So you should either release the accessor manually by calling `accessor.release()` before calling `find` or use the same accessor object as it is done in the second code snippet - in this case accessor would be released by the hash map.

**Comment by Spear-Neil** [comment]
Thank you, I get it.

**Comment by kboyarinov** [comment]
@Spear-Neil, I will close the issue if you don't mind. If you still have any questions, don't hesitate to re-open this issue or create a separate one.
