### ISSUE TITLE
Does the project's flow graph support subgraphs?

### ISSUE THREAD

**Issue by libaineu2004** [oneapi-src/oneTBB#1043]
Does the project's flow graph support subgraphs?
Subgraph - Also a node that contains a complete graph

**Comment by libaineu2004** [comment]
> Yes, nested flowgraph is supported. You can find more tips : https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Flow_Graph_nested_parallelism_tips.html

1. How to transfer data between nodes?
2. How to stop the graph? Stop safely without causing memory leaks?

**Comment by sarathnandu** [comment]
How to transfer data between nodes?
You might need a Data Flow Graph. The detailed explanation on how to create a data flow graph
with different types of node can be found here.
https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Data_Flow_Graph.html 

How to stop the graph? Stop safely without causing memory leaks?
 It's better to use  wait_for_all() API.  Placing a graph.wait_for_all() at the end of the function
 prevents the premature destruction of the graph and node.

**Comment by pavelkumbrasev** [comment]
Closing this since no response, please feel free to reopen if it is still relevant.
