### ISSUE TITLE
Support RISC-V

### ISSUE THREAD

**Issue by ElEHsiang** [oneapi-src/oneTBB#1051]
I noticed that `__TBB_USE_ITT_NOTIFY` is disabled in both `src/tbb/CMakeLists.txt` and `src/tbbmalloc/CMakeLists.txt`.
Do we need to do the same thing to support the RISC-V target?

**Comment by pavelkumbrasev** [comment]
Hi @ElEHsiang since `ITT_NOTIFY` doesn't support RISC-V you can disable it or propose a PR to enable such support.

**Comment by ElEHsiang** [comment]
@pavelkumbrasev 
I will submit a pull request to enable the support. Thank you.

By the way, is it proper to add a 'riscv.cmake' file in the 'cmake/toolchains/'?

**Comment by isaevil** [comment]
@ElEHsiang Yeah, makes sense.
