### ISSUE TITLE
concurrent_unordered_map.reserve(0) hangs.

### ISSUE THREAD

**Issue by bwhitchurch** [oneapi-src/oneTBB#1056]
I've observed that calling reserve on a concurrent_unordered_map with a size of 0 causes the program to hang. Here is an MWE that reproduces the problem on Ubuntu 22.10 with gcc 12.2.0 

```
#include<iostream>
#include<oneapi/tbb/concurrent_vector.h>
#include<oneapi/tbb/concurrent_unordered_map.h>

template <typename Container>
void do_work(Container& t_cont){
    std::cout << "Printing container size to make sure compiler doesn't optimize it away: " << t_cont.size() << std::endl;
}

int main() {
   /* Vector works fine. Should see the print statement happen */
   oneapi::tbb::concurrent_vector<int> my_vec;
   my_vec.reserve(0);
   do_work(my_vec);

   oneapi::tbb::concurrent_unordered_map<int,int> my_map;
   my_map.reserve(0); 
   do_work(my_map); // Never gets here.
   return 0;
}
```

I have not tested with other container types nor have I dug deep into the source to figure out why this happens, but I imagine a quick `if (requested_size == 0) { return;}` would fix it.

**Comment by kboyarinov** [comment]
@bwhitchurch, thank you for reporting the issue. I will take a look into sources more deeply to fix that.

**Comment by bwhitchurch** [comment]
The fix appears to be working both in my test program and the context where I first encountered the issue. Thanks for the fix @kboyarinov!
