### ISSUE TITLE
Is SYCL-implemented kernel able to utilize SSE/AVX on CPU?

### ISSUE THREAD

**Issue by ghostplant** [oneapi-src/oneTBB#1069]
SYCL kernel doesn't allow to use non-standard instructions / functions. Whether and how to let SYCL kernel to utilize SSE/AVX?

**Comment by isaevil** [comment]
@ghostplant I am not sure how this question is related to oneTBB... Could you please clarify a little bit more?

**Comment by ghostplant** [comment]
Sorry, I am not sure which repo is a suitable place for advanced kernel programming. Let's look at this example: https://github.com/oneapi-src/oneAPI-samples/blob/master/DirectProgramming/C%2B%2BSYCL/ParallelPatterns/PrefixSum/src/PrefixSum.cpp#L76-L80

Assume I am writing an SYCL kernel code in above link, when I want to do an 256bit int32-add, writing _mm_adds_epi16(xx) is not allowed there and it reports that instruction is not allowed by SYCL IR, so whether there is alternative way of coding in SYCL kernel bodies to enable those SSE-like efficient adding?

Is it something not supported by current SYCL? or I should program "z[i] = x[i] + y[i]; z[i + 1] = x[i + 1] + y[i + 1]; .." so that OneAPI compiler can turn it into SSE-optimized code for CPU?

**Comment by dnmokhov** [comment]
> Is it something not supported by current SYCL? or I should program "z[i] = x[i] + y[i]; z[i + 1] = x[i + 1] + y[i + 1]; .." so that OneAPI compiler can turn it into SSE-optimized code for CPU?

@ghostplant, I believe you should ask this question on the [oneAPI compiler](https://github.com/intel/llvm) repo.

**Comment by aleksei-fedotov** [comment]
Closing the issue as it is irrelevant to oneTBB. Feel free to re-open if you think I am wrong.
