### ISSUE TITLE
Possible to unbreak older macOS, broken by a recent commit, forcing usage of libdispatch?

### ISSUE THREAD

**Issue by barracuda156** [oneapi-src/oneTBB#1083]
This commit https://github.com/oneapi-src/oneTBB/commit/0f0d1cb994733cde5f93e34b1fe845f334e4240c breaks the build on macOS 10.6 ppc and 10.5. Possibly also any macOS when build is with GCC, or at least 10.6 x86 (GCC does not support blocks).
Is it possible to amend it, making usage of libdispatch conditional?

**Comment by pavelkumbrasev** [comment]
This was introduced to support Thread Sanitizer on macOS since the this feature was introduced in macOS 10.6 I would like to keep it unconditionally in master.
Please consider fix it in https://github.com/oneapi-src/oneTBB/pull/840
