### ISSUE TITLE
About the Performance Testing.Strange Result

### ISSUE THREAD

**Issue by babA409866** [oneapi-src/oneTBB#1092]
i  write a simple test. request to request 1000 times https://www.google.com.
use c11-thread-and-curl-test1 vs oneTbb-and-curl-test2
at test1 , i use 150 and request 1000 times target url . successful times can reach 300-500 times.
at test2, i already change the limit, but still very slow. successful rate is higher .but only 50-70 times.
both test in same pc and network resource.
how can i get faster than test1 by using onetbb.

change the limit:
``` C++
    tbb::global_control gc(oneapi::tbb::global_control::max_allowed_parallelism, 100000);
    tbb::task_arena arena(300,0);
    tbb::parallel_for(tbb::blocked_range<size_t>(0, urls.size()), [&](const tbb::blocked_range<size_t>& range) {
          for (size_t i = range.begin(); i != range.end(); ++i) {
              CURL* curl = curl_easy_init();
              // do request
          });
    });
```

**Comment by pavelkumbrasev** [comment]
Closing this since no response, please feel free to reopen if it is still relevant.
