### ISSUE TITLE
<compare> header not found for `clang 13.0.1 with g++ 8.5.0 -std=c++20`

### ISSUE THREAD

**Issue by solidtony** [oneapi-src/oneTBB#1093]
Still encountering the same include not found error as in issue: #379  while compiling with `clang 13.0.1 with g++ 8.5.0 -std=c++20`

https://github.com/oneapi-src/oneTBB/blob/c9497714821c3d443ee44c732609eb6850195ffb/include/oneapi/tbb/detail/_config.h#L265-L269

Should the code read
```c++
#else
    #define __TBB_CPP20_COMPARISONS_PRESENT 0
#endif
```
indicating that if the std library features are not defined, then default to `false`?

__NOTE__: We are using `onetbb/2021.8.0` but the the body of code in `_config.h` has not changed so I did not bother testing latest.

_Originally posted by @solidtony in https://github.com/oneapi-src/oneTBB/issues/379#issuecomment-1529993378_

**Comment by sarathnandu** [comment]
I believe the check is other way round. Can you please provide the value of __cpp_impl_three_way_comparison  and __cpp_lib_three_way_comparison in your system ?

**Comment by solidtony** [comment]
> Can you please provide the value of __cplusplus, __cpp_impl_three_way_comparison and __cpp_lib_three_way_comparison in your system ? I believe you are correct, if those macros are not defined then __TBB_CPP20_COMPARISONS_PRESENT should be set to 0. Currently we assume __cplusplus version >= 202002L has three way comparison feature available.

Both `__cpp_impl_three_way_comparison` and `__cpp_lib_three_way_comparison` are undefined.

**Comment by sarathnandu** [comment]
what about __cplusplus macro ?

**Comment by solidtony** [comment]
> 
`__cplusplus=202002`

**Comment by solidtony** [comment]
For my own edification, why is `__cpp_impl_three_way_comparison` used if `__cpp_lib_three_way_comparison` is the indicator that `<compare>` is available? https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros

**Comment by kboyarinov** [comment]
@solidtony,

This is a bug for sure. I found that `__cpp_lib_three_way_comparison` is defined in `<compare>` header so it is definitely not the indicator that this header is available. Could you please share the detailed `g++` version on which you faced the issue to make us able to test the new fix?

**Comment by solidtony** [comment]
`g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)`
Also with
`clang version 13.0.1 (Red Hat 13.0.1-1.module+el8.6.0+14118+d530a951)`

**Comment by kboyarinov** [comment]
@solidtony, could you please check if the problem was fixed on the latest `master`? If you still face any problems, feel free to reopen the issue.
