### ISSUE TITLE
no parallelization

### ISSUE THREAD

**Issue by Albert65** [oneapi-src/oneTBB#110]
Hi All,
I compiled TBB on Linux Redhat 7 and manually copied headers/libraries into my folder. Everything was fine except "parallel_for" runs only one thread on 44 core machine. The same application works as expected on Mac OS (tbb installed via brew).

**Comment by alexey-katranov** [comment]
Hi,
Do you use any other libraries in your application?

**Comment by Albert65** [comment]
Hi Alexey, thank you for reply. Yes, I found who causes a problem - the  Armadillo library, which actually disables multi-threading in a specific way, namely, all threads are running but they are all bounded to a single CPU. I am wondering, if it is possible to detect such a situation and print out a warning message.

**Comment by alexey-katranov** [comment]
It looks strange. I.e. TBB creates as many threads as necessary but some third party library changes the affinity setting for each TBB worker thread?

**Comment by Albert65** [comment]
Eventually, I recompiled Armadillo/Arpack without OpenBlas and for now the multi-threading operates as expected. My impression is that nested parallelism causes a problem. TBB runs a function body inside thread context where Armadillo vector/matrices are manipulated with OpenBlas parallelisation. The issue was reported to OpenBlas developers.

**Comment by alexey-katranov** [comment]
If the issue persists, feel free to reopen it.
