### ISSUE TITLE
how to isolate some lcores in TBB?

### ISSUE THREAD

**Issue by tianyx** [oneapi-src/oneTBB#1107]
hello,
    I try to use TBB in dpdk, dpdk need isolate and bind some lcores to use,  but TBB use all lcores. I can't find any method to control TBB to not use the lcores that dpdk has alreay bound. the configuration ' isolcpus' in grub look like not worked  with TBB.
    please give me some ideas, thank you.

**Comment by tianyx** [comment]
Hi @isaevil,
**CPU architecture**
    the cpu is Intel(R) Xeon(R) Gold 6144 CPU @ 3.50GHz
    system is ubuntu server 20.04
 
**What version of TBB do you use?**
    TBB version is 2021.9.0.43484
**What are lcores?**
 lcores = Logical CPU core
root@zq-PowerEdge-R740:~# cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.15.0-72-generic root=UUID=cd4e2f7b-f104-412b-b479-45d5b7999f1c ro quiet splash iommu=pt intel_iommu=on default_hugepagesz=1G hugepagesz=1G hugepages=8 isolcpus=1,3,5,7,9,11,13,15  

**What interface do you use to bind threads?**
   what do you mean "bind threads"?  
  only dpdk need bind some lcores, I don't bind any lcore to use TBB, I use TBB in normal thread,  just like that:
            tbb::parallel_for(0, nCpStep, [&](int hh) {
                 。。。。
            });

for example， 
first,  edit file  /etc/default/grub, add text " isolcpus=5" to   GRUB_CMDLINE_LINUX_DEFAULT
second, start my process, the dpdk lib bind cpu core 5 to use，and I use TBB in other thread,
 I don't want any other thread to use core 5， but I can see TBB thread used core 5 in top view(top -H -p pid).

**Comment by isaevil** [comment]
@tianyx TBB doesn't control on its own where threads are going to be executed at (this a work for an OS scheduler). There are two ways to pin threads to a particular set of cores (i.e. affinity mask):
* TBB will respect process affinity mask provided for execution (for example, using `taskset -c 1,3,5,7,9,11,13,15 <your app>`). 
* Use [tbb::task_scheduler_observer](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/task_arena/task_scheduler_observer_cls.html) to set thread affinity mask during run time (see example in spec or you can refer here https://github.com/oneapi-src/oneTBB/blob/master/test/common/utils_concurrency_limit.h#L243)

**Comment by tianyx** [comment]
@isaevil:
   thanks a lot, I will try it.
