### ISSUE TITLE
Incorporating oneTBB parallelism in openBLAS

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneTBB#1116]
Hello,
I have following doubts:
1. how to build openBLAS with oneTBB parallelism support instead of openmp?
2. do oneTBB monkey patching mimics 100% of oneTBB which is used in onedal(scikit-learn-intelex)? oneTBB monkey patching is proposed in this paper ( https://conference.scipy.org/proceedings/scipy2016/pdfs/anton_malakhov.pdf) where we patch oneTBB by simply executing command: python -m tbb code.py as in (https://github.com/IntelPython/composability_bench)

**Comment by dnmokhov** [comment]
> how to build openBLAS with oneTBB parallelism support instead of openmp?

You might want to ask this in the OpenBLAS repo. I don't think it can though, since it is written in C, while oneTBB is a C++ library. Please also see https://github.com/xianyi/OpenBLAS/issues/1282#issuecomment-375990458 for some proposed workarounds.

> do oneTBB monkey patching mimics 100% of oneTBB which is used in onedal(scikit-learn-intelex)?

Yes, it does. Please see https://github.com/oneapi-src/oneTBB/tree/master/python for more details.

**Comment by dnmokhov** [comment]
@vineel96, do you have any additional questions, or should we close this issue?

**Comment by vineel96** [comment]
Hi @dnmokhov,
Thanks for the reply. How to prove that oneTBB monkey patching mimics onedal's oneTBB as in onedal, its written natively at c++ level. Also profiling a oneTBB monkey patched program shows calls to both openmp module and oneTBB module, which says all openmp calls are not replaced with oneTBB calls. Also will there be any performance degradation if there are two thread owners (openmp and oneTBB) in single program?

**Comment by vineel96** [comment]
Hi @dnmokhov,
Can i get any suggestions/help/answer regarding the question?

**Comment by dnmokhov** [comment]
Hi @vineel96,

Sorry for the delayed response.

You can look in https://github.com/oneapi-src/oneTBB/tree/master/python/tbb to understand more about how oneTBB monkey patching works. Specifically, [python/tbb/pool.py](https://github.com/oneapi-src/oneTBB/blob/master/python/tbb/pool.py) describes the Python Pool implementation, where `self._tasks = task_group()`. The Python wrappers for task_group and oneTBB APIs are in [python/tbb/api.i](https://github.com/oneapi-src/oneTBB/blob/master/python/tbb/api.i).

Hence, oneTBB monkey patching does not replace OpenMP with oneTBB but provides the standard [multiprocessing.Pool](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing.pool) interface mapped onto oneTBB tasks.

Oversubscription (and potential performance degradation) can occur when using OpenMP and oneTBB together. I believe that the last few comments in xianyi/OpenBLAS#1282 describe how to disable OpenMP in OpenBLAS and enable TBB parallelism.

**Comment by dnmokhov** [comment]
@vineel96, do you have any additional questions, or should we close this issue?

**Comment by vineel96** [comment]
Hi @dnmokhov, no questions. I will close this issue.
Thanks.
