### ISSUE TITLE
How tbb monkey patching is working

### ISSUE THREAD

**Issue by akote123** [oneapi-src/oneTBB#1118]
When the python module is monkey patched with tbb , how the tbb calls are being called . Is there any sources which we can refer to understand more about how tbb monkey patching works.

And also this tbb patching works well only if we use with mkl, but if we use tbb with openblas there is no performance improvement.

**Comment by dnmokhov** [comment]
> Is there any sources which we can refer to understand more about how tbb monkey patching works.

Please refer to https://github.com/oneapi-src/oneTBB/tree/master/python, specifically https://github.com/oneapi-src/oneTBB/tree/master/python/tbb.

> if we use tbb with openblas there is no performance improvement

OpenBLAS uses OpenMP, not oneTBB, for parallelism. Please see https://github.com/xianyi/OpenBLAS/issues/1282#issuecomment-375990458 for some proposed workarounds.

**Comment by dnmokhov** [comment]
@akote123, do you have any additional questions, or should we close this issue?
