### ISSUE TITLE
QUESTION: avoiding deadlock while adding dependencies between simple graphs

### ISSUE THREAD

**Issue by aarav191** [oneapi-src/oneTBB#1126]
I have what seems to be a relatively simple use case:
Task A consists of multiple task Bs, followed by a task C (after all it's Bs have completed).
The interesting constraint is that all task Cs must execute in the order that the Task As were created.
B tasks can be completely concurrent, even across multiple A tasks.

I tried implementing this by giving every A it's own task_group, so I could call task_group.wait() to wait for all of the Bs to finish. Then call task_group.wait() of the previous A task to make sure the previous C had finished.  Then add my own C task.
This deadlocks because calling task_group.wait() can launch another A task, which ends up transitively waiting for the first A task already running on the same thread.

Is there a simple solution to this type of concurrency?

**Comment by AnuyaWelling2801** [comment]
Hi ! 
I am unsure what you mean by - Then call task_group.wait() of the previous A task to make sure the previous C had finished. 
Could you provide us with a code snippet or an example?

**Comment by AnuyaWelling2801** [comment]
Also, It looks like you are trying to track dependencies, maybe [oneTBB Flowgraph](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/flow_graph.html) is a better way to go than task groups?

**Comment by aarav191** [comment]
Let's assume one implements a top level flowgraph for "A". The issue is how to implement the dependency between multiple instances of "A".   A new "A" task can be started asynchronously at any time, but part of it has a dependency on the previous task (the Cs must finish in order the As were started)

As a concrete example:
  A1=( (B1,B2)->C1 )
  A2=( (B3,B4,B5)->C2 )

A2 is started asynchronously at some point after A1 (and there can be any number of A tasks started asynchronously)
B1,B2,B3,B4,B5 can all execute concurrently
C1,C2 must execute in order

> I am unsure what you mean by - Then call task_group.wait() of the previous A task to make sure the previous C had finished.

In the example above, each A task has it's own task_group that is used to run the B tasks.  Task A2, seeing it has a predecessor, 
waits on C1 to be finished by checking A1.done flag, and if not done calls A1.my_task_group.wait() in a loop before executing C2().  But task stealing can create a loop. 

That's just one possible strategy though.  I'm looking for any / the simplest strategy.

**Comment by pavelkumbrasev** [comment]
@aarav191 I'm not sure why you have a dead-lock loop with spawn new `A` tasks. Will new A tasks be spawned/runed in separate `task_group` or into the `task_group` that of current `A` task?

**Comment by pavelkumbrasev** [comment]
Hi @aarav191, do you have any updates for this issue?

**Comment by aarav191** [comment]
> @aarav191 I'm not sure why you have a dead-lock loop with spawn new `A` tasks. 

A simple example: Thread1 launches A1, but before it finishes moonlights by grabbing task A2.  A2 waits for A1 to finish, which will now never happen.

> Will new A tasks be spawned/runed in separate `task_group` or into the `task_group` that of current `A` task?

All the A tasks were in the same task group.  But it doesn't seem to matter.  I think isolation could solve the problem (by preventing moonlighting), but it's not optimal for concurrency reasons.

Another possibility is a single task flow graph with a sequencer node to handle the ordering dependency between "A" tasks.
