### ISSUE TITLE
scalable_allocator.h doesn't provide oneapi namespace

### ISSUE THREAD

**Issue by Nekto89** [oneapi-src/oneTBB#1136]
scalable_allocator.h is missing header that injects tbb namespace into oneapi namespace. This leads to compilation error if there are no other tbb includes.

```
#include <oneapi/tbb/scalable_allocator.h>
void f() {
  [[maybe_unused]] oneapi::tbb::scalable_allocator<int> x;
}
```

error C2653: 'oneapi': is not a class or namespace name

**Comment by pavelkumbrasev** [comment]
Seems `scalable_allocator.h` is missed `#include "detail/_namespace_injection.h"`
