### ISSUE TITLE
How use set implicit task_arena thread slot number in oneTBB for each master thread

### ISSUE THREAD

**Issue by jzsh** [oneapi-src/oneTBB#1140]
Dear teams,
In old project we use task_scheduler_init to use control implicit task_arena thread slot number for master threads. And we are guided by migration doc to use global_control to set max thread number. However, global_control can not set different task_arena thread slot, that is "return of this_task_arena::max_concurrency(), for each master thread". 

Below is the code example.
```cpp
#define TBB_PREVIEW_GLOBAL_CONTROL 1
#include <iostream>
#include <tbb/parallel_for.h>
#include <tbb/task_arena.h>
#include <tbb/task_scheduler_init.h>
#include <tbb/global_control.h>
#include <tbb/concurrent_unordered_set.h>
#include <tbb/task_group.h>
#include <cassert>
#include <thread>
#include <mutex>

using namespace std;

static void printPids(const tbb::concurrent_unordered_set<size_t>& pidSet)
{
    cout << "pids:" << pidSet.size() << endl;
    for (auto i : pidSet) {
        cout << i << endl;
    }
}

std::mutex g_mutex;
void test1_sub_thread()
{
    int num = 0;
#ifdef USE_SCHED
    num = 8;
    tbb::task_scheduler_init schler(8);
#else
    tbb::global_control limit(tbb::global_control::max_allowed_parallelism, 8);
    num = 16;
#endif

    tbb::concurrent_unordered_set<size_t> pidSet1;
    tbb::parallel_for( 0, 1000, [&](int&) {
        // cout << tbb::this_task_arena::max_concurrency() << endl;
        assert(tbb::this_task_arena::max_concurrency() == num);
        std::this_thread::sleep_for(10ms);
        pidSet1.insert(pthread_self());
    });

    std::lock_guard<std::mutex> guard(g_mutex);
    cout << "test1_sub_thread" << endl;
    printPids(pidSet1);
}

void test1()
{
    int num = 0;
#ifdef USE_SCHED
    tbb::task_scheduler_init schler(4);
    num = 4;
#else
    tbb::global_control limit(tbb::global_control::max_allowed_parallelism, 4);
    num = 16;
#endif

    std::thread t1(test1_sub_thread);

    tbb::concurrent_unordered_set<size_t> pidSet1;
    tbb::parallel_for( 0, 1000, [&](int&) {
        // cout << tbb::this_task_arena::max_concurrency() << endl;
        assert(tbb::this_task_arena::max_concurrency() == num);
        std::this_thread::sleep_for(10ms);
        pidSet1.insert(pthread_self());
    });
    {
        std::lock_guard<std::mutex> guard(g_mutex);
        cout << "test1" << endl;
        printPids(pidSet1);
    }

    t1.join();
}

int main()
{
    cout << "main thread id:" << pthread_self() << endl;
    test1();
}

```
#### Use global_control:
main thread id:140737353455424
test1_sub_thread
pids:3
140737332033280
140737317345024
140737313146624
test1
pids:4
140737317345024
140737313146624
140737321543424
140737353455424
---> both test1_sub_thread() and test1() use 3 work threads.

#### Use task_scheduler_init:
main thread id:140737353455424
test1_sub_thread
pids:8
140737329936128
140737292154624
140737308948224
140737300551424
140737313146624
140737296353024
140737304749824
140737081501440
test1
pids:4
140737085699840
140737317345024
140737321543424
140737353455424
---> test1_sub_thread() use 7 worker thread, and test1() use 3 work threads.

so here is my question, how use set implicit task_arena thread slot number in oneTBB for each master thread?
Looking forward to your reply
Thanks.

**Comment by pavelkumbrasev** [comment]
Hi @jzsh, the `task_scheduler_init` was quite overloaded with functions that it does. (And this is a error prone) That's why it was deprecated and removed in oneTBB. 
There is no API to set num slots for `implicit arena` that's why it is called implicit. Please consider to use explicit [task_arena](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.html):
```cpp
void test1_sub_thread() {
    int num = 8
    tbb::task_arena a(/* concurrency = */ num);
    tbb::concurrent_unordered_set<size_t> pidSet1;
   
    a.execute([&] {
        tbb::parallel_for( 0, 1000, [&](int&) {
            // cout << tbb::this_task_arena::max_concurrency() << endl;
            assert(tbb::this_task_arena::max_concurrency() == num);
            std::this_thread::sleep_for(10ms);
            pidSet1.insert(pthread_self());
        });
    });

    std::lock_guard<std::mutex> guard(g_mutex);
    cout << "test1_sub_thread" << endl;
    printPids(pidSet1);
}
```

**Comment by jzsh** [comment]
hi @pavelkumbrasev 
Thanks for confirming my query. I'll consider explicit task_arena in next step.

**Comment by jzsh** [comment]
hi @pavelkumbrasev 
May i ask one more thing, as it is not easy to revamp all usage to use explicit task_arena with specified thread num or guaratee other R&Ds not to use implicit task_arena all the time.
In some scenario, where there is only ONE logic core, how do we prevernt program hang due to task can not get available work thread. This is really coner case, but it happdens. 
for exmaple:
```cpp
    tbb::task_group group;
    group.run([&]{ --> spawn a task to producue data
        tbb::parallel_for(0, 10000, [&](int&) {
            cout << "run task" << endl;
            std::this_thread::sleep_for(10ms);
        });
    });

   // here master thread will try to access producued data from task and process it.
  while(task_has_data()) {
    std::this_thread::sleep_for(10s); // it will wait infinitely waiting to process data.
  }
    cout << "master thread idle" << endl;
    group.wait();
```
What comes to me is to new a global_control object with max_allowed_parallelism=2(or lager) at the begining of program when i detect the default concurrency is 1. Do you see any bad effect on this solution or would you share some programming guideline, thanks.

**Comment by pavelkumbrasev** [comment]
Hi @jzsh, specification of [task_group::run ](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/task_group/task_group_cls.html#_CPPv4I0EN6oneapi3tbb10task_group3runEvRR4Func) doesn't guarantee that submitted task will be executed so to execute them you must call `task_group::wait`.
Here you use it only to submit async work into TBB for this purpose you should use [task_arena::enqueue](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/task_group/task_group_cls.html#_CPPv4I0EN6oneapi3tbb10task_group3runEvRR4Func) or [this_task_arena::enqueue](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/task_group/task_group_cls.html#_CPPv4I0EN6oneapi3tbb10task_group3runEvRR4Func) if can not create `task_arena` explicitly. Its guarantees to execute task even if there is no available workers.

**Comment by jzsh** [comment]
hi @pavelkumbrasev 
Thanks, this infomation helps me.
