### ISSUE TITLE
Failed to link on macOS for Release builds (Debug is fine)

### ISSUE THREAD

**Issue by jay3d** [oneapi-src/oneTBB#1143]
I'm getting the following "undefs" when linking my app with tbb dylib on macOS in Release mode:
```
undef: __ZN3tbb6detail2r110deallocateERNS0_2d117small_object_poolEPvmRKNS2_14execution_dataE
undef: __ZN3tbb6detail2r110initializeERNS0_2d115task_arena_baseE
undef: __ZN3tbb6detail2r110initializeERNS0_2d118task_group_contextE
undef: __ZN3tbb6detail2r114execution_slotEPKNS0_2d114execution_dataE
undef: __ZN3tbb6detail2r114notify_waitersEm
undef: __ZN3tbb6detail2r115allocate_memoryEm
undef: __ZN3tbb6detail2r115current_contextEv
undef: __ZN3tbb6detail2r115max_concurrencyEPKNS0_2d115task_arena_baseE
undef: __ZN3tbb6detail2r115throw_exceptionENS0_2d012exception_idE
undef: __ZN3tbb6detail2r116execute_and_waitERNS0_2d14taskERNS2_18task_group_contextERNS2_12wait_contextES6_
undef: __ZN3tbb6detail2r117assertion_failureEPKciS3_S3_
undef: __ZN3tbb6detail2r117deallocate_memoryEPv
undef: __ZN3tbb6detail2r122cache_aligned_allocateEm
undef: __ZN3tbb6detail2r122cancel_group_executionERNS0_2d118task_group_contextE
undef: __ZN3tbb6detail2r124cache_aligned_deallocateEPv
undef: __ZN3tbb6detail2r128is_group_execution_cancelledERNS0_2d118task_group_contextE
undef: __ZN3tbb6detail2r14waitERNS0_2d112wait_contextERNS2_18task_group_contextE
undef: __ZN3tbb6detail2r15resetERNS0_2d118task_group_contextE
undef: __ZN3tbb6detail2r15spawnERNS0_2d14taskERNS2_18task_group_contextE
undef: __ZN3tbb6detail2r16createERNS0_2d114global_controlE
undef: __ZN3tbb6detail2r17destroyERNS0_2d114global_controlE
undef: __ZN3tbb6detail2r17destroyERNS0_2d118task_group_contextE
undef: __ZN3tbb6detail2r17executeERNS0_2d115task_arena_baseERNS2_13delegate_baseE
undef: __ZN3tbb6detail2r18allocateERPNS0_2d117small_object_poolEm
undef: __ZN3tbb6detail2r18allocateERPNS0_2d117small_object_poolEmRKNS2_14execution_dataE
undef: __ZN3tbb6detail2r19terminateERNS0_2d115task_arena_baseE
Undefined symbols for architecture arm64:
```
Debug builds link and run correctly. I'm using 2021.9.0

**Comment by isaevil** [comment]
Hi @jay3d could you please add more details on your environment: 

1. Is that arm64 Mac?
2. Do you build oneTBB 2021.9 from sources or you use prebuilt packages?
3. If you have a small reproducer which gets the same issue you are facing when linking your application with oneTBB, it would be nice to get it.

**Comment by jay3d** [comment]
> Hi @jay3d could you please add more details on your environment:
> 
>     1. Is that arm64 Mac?
> 
>     2. Do you build oneTBB 2021.9 from sources or you use prebuilt packages?
> 
>     3. If you have a small reproducer which gets the same issue you are facing when linking your application with oneTBB, it would be nice to get it.

Yes it's arm64 Mac.
oneTBB built from sources

I have noticed that setting `TBB_ENABLE_IPO=OFF` fixed that issue in release mode.

**Comment by isaevil** [comment]
> I have noticed that setting TBB_ENABLE_IPO=OFF fixed that issue in release mode.

Can you share your build environment then (compiler, version of compiler, `cmake` command with options)? 
I see no issues when do compilation of oneTBB 2021.9 using Apple Clang 13.1.6 and then trying to link some application to TBB.

**Comment by Nekto89** [comment]
I have to use "onetbb*:tools.apple:enable_visibility=True" on macOS with conan because of this.

**Comment by nofuturre** [comment]
@jay3d is this issue still relevant?

**Comment by nofuturre** [comment]
If anyone encounter this issue in the future please open new issue with a link to this one
