### ISSUE TITLE
The link interface of target "TBB::tbb" contains:  Threads::Threads  but the target was not found.

### ISSUE THREAD

**Issue by leleliu008** [oneapi-src/oneTBB#1145]
**build from:** https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.9.0.tar.gz

**usage:**
```cmake
find_package(TBB REQUIRED)
target_link_libraries(mold PRIVATE TBB::tbb)
```

**reported messages:**
```cmake
CMake Error at /home/leleliu008/.ndk-pkg/installed/android-21/arm64-v8a/tbb/lib/cmake/TBB/TBBTargets.cmake:61 (set_target_properties):
  The link interface of target "TBB::tbb" contains:

    Threads::Threads

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /home/leleliu008/.ndk-pkg/installed/android-21/arm64-v8a/tbb/lib/cmake/TBB/TBBConfig.cmake:1 (include)
  CMakeLists.txt:184 (find_package)
```

**reason:** It seems that `find_package(Threads REQUIRED)` is missing in `TBBTargets.cmake`

**Comment by AnuyaWelling2801** [comment]
A PR for this issue is already in progress - #912

**Comment by isaevil** [comment]
@leleliu008 Do you build oneTBB as a static library?

**Comment by leleliu008** [comment]
@isaevil Yes, I need build some fully statically linked executables. Although, https://github.com/oneapi-src/oneTBB/blob/master/CMakeLists.txt#L118 told me that building oneTBB as a static library is highly discouraged, but it is just a wanning.
