### ISSUE TITLE
2021.10 is broken on macOS with GCC due to unsupported -z flags passed unconditionally

### ISSUE THREAD

**Issue by barracuda156** [oneapi-src/oneTBB#1148]
This PR added flags which are unsupported on macOS unconditionally: https://github.com/oneapi-src/oneTBB/pull/1022
Specifically, these: https://github.com/oneapi-src/oneTBB/blob/f91f55f25ad121a39c5de3a1cacbd6c56ed7313c/cmake/compilers/GNU.cmake#L76
Unsurprisingly, it has broken the build with GCC. (Notice, they are not passed for Apple Clang.)

It is a known thing with numerous reports online:
https://github.com/Opendigitalradio/dablin/issues/44
https://github.com/rbsec/sslscan/issues/137
https://github.com/EionRobb/purple-discord/issues/294

Either an Apple equivalent is needed, or flags should be under `if(NOT APPLE)`.

**Comment by isaevil** [comment]
> Notice, they are not passed for Clang

Looks like they are passed for Clang as well:
https://github.com/oneapi-src/oneTBB/blob/master/cmake/compilers/Clang.cmake#L55

**Comment by barracuda156** [comment]
> > Notice, they are not passed for Clang
> 
> 
> 
> Looks like they are passed for Clang as well:
> 
> https://github.com/oneapi-src/oneTBB/blob/master/cmake/compilers/Clang.cmake#L55

Not for Apple Clang, there is a separate settings file. But yes, I would have specified it.

P. S. This will likely break the build with LLVM Clangs on Apple too, though I cannot verify it right now.

**Comment by oleksandr-pavlyk** [comment]
This issue prevent conda-forge build of tbb library too: https://github.com/conda-forge/tbb-feedstock/pull/116
