### ISSUE TITLE
TBB Warning on task arena reinitialization

### ISSUE THREAD

**Issue by emptyVoid** [oneapi-src/oneTBB#115]
I'm getting this warning after reinitializing a task arena:
```TBB Warning: The number of workers is currently limited to 15. The request for 16 workers is ignored. Further requests for more workers will be silently ignored until the limit changes.```

Here's a small repro:
```c++
#include <tbb/parallel_for.h>
#include <tbb/task_arena.h>
#include <thread>

int main()
{
    tbb::task_arena arena( tbb::task_arena::automatic, 0 );
    arena.initialize();
    arena.terminate();

    tbb::parallel_for( 0, 100, [] ( int ) { std::this_thread::sleep_for( std::chrono::milliseconds( 100 ) ); } );

    arena.initialize( tbb::task_arena::automatic, 0 );
    return 0;
}
```

I'm not really sure what is the point of this warning, since:
1) After the first arena initialization I never get 16 worker threads, it seems the number is by default capped at 15 no matter the load.
2) I thought the global market is initialized once, and there's no way to change the number of workers in it (aside from using ```tbb::global_control```).

 Why am I not seeing the warning on the first initialization? Am I missing something?

**Comment by alexey-katranov** [comment]
`arena.terminate();` terminates the global market as well because it is the last reference. When ` tbb::parallel_for( 0, 100, ...` is called it creates the global market again (but with one thread less).

**Comment by emptyVoid** [comment]
Ok, thanks for the clarification on the global market part.

I think the logic emitting this warning is flawed: by invoking arena's constructor with ``` tbb::task_arena::automatic``` I'm entrusting TBB to decide on the actual number of slots, whereas the warning implies I'm setting the number of workers explicitly.

How can I change the source code to silence the warning while retaining the same ```automatic``` logic?

**Comment by anton-malakhov** [comment]
> by invoking arena's constructor with tbb::task_arena::automatic I'm entrusting TBB to decide on the actual number of slots, whereas the warning implies I'm setting the number of workers explicitly.

You did it explicitly by specifying 0 slots reserved for masters, default is 1. This caused the warning.

**Comment by alexey-katranov** [comment]
If the issue persists, feel free to reopen it.
