### ISSUE TITLE
Suggestion: run code spellchecker on master

### ISSUE THREAD

**Issue by luzpaz** [oneapi-src/oneTBB#1174]
1. Download latest codespell dictionaries: `pip install --upgrade git+https://github.com/codespell-project/codespell.git`
2. Run `codespell -q 3 -L aci,acii,clen,correctt,ot,parms,ressize,seh,som,statics` to show suggested typo fixes
3. Run `codespell -i 3 -w -L aci,acii,clen,correctt,ot,parms,ressize,seh,som,statics` to iterate each type and prompt for fix

**Comment by JhaShweta1** [comment]
Hi, We do have spellchecker internally. Did you face any issues because of this?

**Comment by JhaShweta1** [comment]
We fixed these. Thank you for reporting them. We are closing this issue.
