### ISSUE TITLE
Stack size calculation goes wrong when setting up threads

### ISSUE THREAD

**Issue by adamtassier** [oneapi-src/oneTBB#1187]
When using `tbb::parallel_for` for the first time the stack setup goes wrong and the following assert is triggered inside `governer.cpp:get_stack_base`:
 https://github.com/oneapi-src/oneTBB/blob/1ddebef8ac703ded4d5330f9d2135dfadbc992be/src/tbb/governor.cpp#L157

Where `get_stack_base(stack_size=4194304)` results in  `&stack_limit = 0x8a13d30` and  `stack_limit = 0x7fffff7fe000`

`parallel_for` is called from the main thread (os: fedora linux 38, gcc13.2)

My calling code is of the form :

```cpp
tbb::parallel_for(tbb::blocked_range<int>(0, num), [&](const tbb::blocked_range<int>& r)
{
    for(int i = r.begin(); i != r.end(); ++i)
    {
        m_ents[i].transform(m_mat);
    }
});
```

In debug builds this assert brings down the application, however in release builds  where the stack size is 'wrong' the result from `parallel_for` seems to be correct even with the incorrect stack limits.

**Comment by adamtassier** [comment]
Hi, we are still having this issue,  we ended up just commenting out the assert. But I'd like to know if this is something we should look into further (maybe something wrong with the way our threads are set up?) or if there is any information you need to diagnose this further.

**Comment by pavelkumbrasev** [comment]
Hi @adamtassier, there is a problem with this issue we cannot reproduce it in our environment (could you please describe yours). 
I also would not expect such assert while you just use `parallel_for`.

**Comment by nofuturre** [comment]
@adamtassier is this issue still relevant?
