### ISSUE TITLE
cmake instructions are not clear

### ISSUE THREAD

**Issue by nikhil-swamix** [oneapi-src/oneTBB#1194]
![image](https://github.com/oneapi-src/oneTBB/assets/54004431/cc4b1fd4-2ec5-420c-a874-64e8db114d8d)
i have no clue what to do, or how to install after careful reading of readme. and i had issues setting up bazel!
need one liner command, i require this library as prerequsite for opencv

it would be good if like:
`pip install onetbb`
`winget install onetbb`
`npm install @oneapi/onetbb`

or simple one liner command is available!
please focus on ease of use or prebuild binaries.
i will spin up EC2 instance if you want for continuous build! but please do and give some instructions.

**Comment by dnmokhov** [comment]
`pip install tbb tbb-devel` works. (Install tbb-devel only if you need header files or debug prebuilt binaries.)

**Comment by dnmokhov** [comment]
BTW, for CMake, a typical one-liner would be
```shell
cmake -B build && cmake --build build
```

**Comment by dnmokhov** [comment]
@Nikhil-Software-Cartel, do you have any additional questions, or should we close this issue?
