### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by jdumas** [oneapi-src/oneTBB#1199]
Hi,

What is the status of WASM support in OneTBB right now? The [readme](https://github.com/oneapi-src/oneTBB/blob/master/WASM_Support.md) mentions a development branch with wasm support but the link is dead, the branch it references doesn't exist.

**Comment by omalyshe** [comment]
@jdumas Related changes were merged to the master. See https://github.com/oneapi-src/oneTBB/pull/1006.
The documentation will be updated soon.

**Comment by jdumas** [comment]
Thanks. Is this also tested as part of the CI process? I don't think I saw any change related to emscripten/wasm in the github action side of this repo.

**Comment by isaevil** [comment]
@jdumas You are right, this is not tested as part of this repository Github Actions. Failing tests (mostly due to non working FPU settings on WASM) are disabled when WASM is used.

**Comment by jdumas** [comment]
Should I be concerned about these failing tests in practice or is it something I can safely ignore? I'm not exactly sure why FPU settings should affect a library like OneTBB.

**Comment by JhaShweta1** [comment]
FPU setting is mainly affecting parts of task_arena- may be you can run a quick test for your application to check if it is affected by this. FPU setting are picked up from emscripten (esp the way it is set and reset) and we currently don't have any workaround for this. All the other failures are due to artifacts of testing. #1006 description lists all the failures and their respective workarounds.

**Comment by pavelkumbrasev** [comment]
The development branch was merged into master. Please reopen this issue if necessary.

**Comment by jdumas** [comment]
Sorry but the page about [WASM Support](https://github.com/oneapi-src/oneTBB/blob/master/WASM_Support.md) in the main branch readme still references a non-existing development branch. I think this readme file should be updated to reflect the latest status of support (and maybe summarize the remaining failures mentioned in #1006 so users don't have to dig through PR comments to figure it out).

**Comment by jdumas** [comment]
Also I don't have permission myself to reopen issues. Happy to create a new one if you want though...

**Comment by dnmokhov** [comment]
> Sorry but the page about [WASM Support](https://github.com/oneapi-src/oneTBB/blob/master/WASM_Support.md) in the main branch readme still references a non-existing development branch. I think this readme file should be updated to reflect the latest status of support (and maybe summarize the remaining failures mentioned in #1006 so users don't have to dig through PR comments to figure it out).

Hi @jdumas, please check the updated documentation in #1207, which should be merged shortly.

**Comment by jdumas** [comment]
Perfect, thanks!
