### ISSUE TITLE
Officially published MD5 (or better) for the releases?

### ISSUE THREAD

**Issue by gbin** [oneapi-src/oneTBB#121]
Do you publish somewhere the md5sums for the official tbb tarballs for distributions to use?

If not, would it be possible to include that or something equivalent in your releases?

**Comment by Lastique** [comment]
You can checkout from git by SHA1 commit revision that corresponds to the release.

**Comment by anton-potapov** [comment]
@gbin [2021.5.0](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.5.0) has a sha256 sums for packages. Following releases are expected to contain that sums as well.  

@AlexVeprev thanks a lot for doing this!
