### ISSUE TITLE
If node A crashes

### ISSUE THREAD

**Issue by libaineu2004** [oneapi-src/oneTBB#1212]
If node A crashes or becomes abnormal. How to make graph end automatically instead of continuing to execute node C/D. Because C/D relies on A's data.

**Comment by AnuyaWelling2801** [comment]
Just making sure you are talking about flowgraphs when you nodes and data being passed.  Please refer to the “Do: Use Cancellation and Exception Handling in Flow Graphs” section in Chapter 10 (https://link.springer.com/chapter/10.1007/978-1-4842-4398-5_17) of the proTBB book to see examples.

**Comment by nofuturre** [comment]
@libaineu2004 is this issue still relevant?

**Comment by nofuturre** [comment]
If anyone encounter this issue in the future please open new issue with a link to this one
