### ISSUE TITLE
concurrent_vector usage

### ISSUE THREAD

**Issue by anassmeskini** [oneapi-src/oneTBB#1214]
In the documentation of concurrent_vector:

> It is safe to use the iterators while the concurrent_vector is being grown, as long as the iterators never go past the current value of end(). However, the iterator may reference an element undergoing concurrent construction. You must synchronize construction and access.

I am a little confused by what is meant by 'must synchronize construction and access'. Does it mean to add a mutex for read and write? It seems to defeat the purpose of this class.

For example, consider this code
```
struct S
{
double x;
double y;
};

int main()
{
    concurrent_vector<S> v;
    std::thread produce([&v]() {
    for(int i = 0;; ++i)
        v.push_back({.x=i,.y=i});
   });
   auto it = v.begin();
   while(true)
  {
     if(it < v.end())
    {
       auto s = *it;
       std::cout << s.x << s.y << std::endl;
       ++it;
    }
   }
}
```

is this an incorrect use of the class since I might read an element that was not fully constructed yet?

**Comment by pavelkumbrasev** [comment]
Hi @anassmeskini, are there any other questions or we can close this issue?
