### ISSUE TITLE
Cannot use intel-tbb repo

### ISSUE THREAD

**Issue by rache1tang** [oneapi-src/oneTBB#1222]
Hello,

I followed your guides (linked below) to set up the intel-tbb repo and install `intel-tbb` using `yum`
https://www.intel.com/content/www/us/en/developer/articles/guide/installing-free-libraries-and-python-yum-repo.html
https://www.intel.com/content/www/us/en/docs/onetbb/get-started-guide/2021-6/install-onetbb-on-linux-os.html

Adding the repo was successful, but running a `yum install intel-tbb-devel` produced an error:
```
Error: Failed to download metadata for repo 'intel-tbb-repo': repomd.xml GPG signature verification error: Bad GPG signature
```

I've tried to install with version numbers and also the non-devel vesion of the packages, but get the same error in all cases:
```
yum install intel-tbb-devel
yum install intel-tbb-2021.5-1.738
yum install intel-tbb-devel-2020.3-304.x86_64
```

Based on the error message, it seems like it is something with the repo and not the package I'm trying to install. Could it be a key expiration issue or is there something I'm missing?

**Comment by omalyshe** [comment]
@rache1tang What is your OS?

**Comment by prstrnn** [comment]
Hi @rache1tang! We have update public key in this repository, could you please try again and see if it helped or not?

**Comment by rache1tang** [comment]
Hi! I just tried again and get a similar error, though it does seem to be using a different GPG key from before:
```
Intel(R) Threading Building Blocks                                                                                                                   851  B/s | 287  B     00:00
Intel(R) Threading Building Blocks                                                                                                                    27 kB/s | 943  B     00:00
Importing GPG key 0x53D04109:
 Userid     : "CN=Intel(R) Software Development Products"
 Fingerprint: E9BF 0AFC 46D6 E8B7 DA58 82F1 BAC6 F0C3 53D0 4109
 From       : https://yum.repos.intel.com/tbb/setup/PUBLIC_KEY.PUB
Intel(R) Threading Building Blocks                                                                                                                   2.9 kB/s | 287  B     00:00
Error: Failed to download metadata for repo 'intel-tbb-repo': repomd.xml GPG signature verification error: Bad GPG signature
```

**Comment by prstrnn** [comment]
@rache1tang We have fixed an issue while we were updating signature on this repository.
I have tested within CentOS 8 container, not everything should be installable.
Sorry for inconvenience!

**Comment by rache1tang** [comment]
works! thanks so much :)
