### ISSUE TITLE
PyPI license classifiers do not match project documentation

### ISSUE THREAD

**Issue by WilliamRoyNelson** [oneapi-src/oneTBB#1233]
When I check the Classifiers on the PyPI page for the Python package [tbb](https://pypi.org/project/tbb/) they indicate that the license is "Other/Proprietary License"
![image](https://github.com/oneapi-src/oneTBB/assets/7910938/5563847b-4d32-4ba1-9c5d-d75acdd24c56)

The license file for the oneTBB project on Github indicates Apache 2.0: https://github.com/oneapi-src/oneTBB/blob/master/LICENSE.txt
As does the contributing guide: https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md

I initially planned to create a PR to fix it, but the config I found for setup.py seems very different from what's currently on PyPI, making me think that I don't understand the deployment process for PyPI artifacts:
https://github.com/oneapi-src/oneTBB/blob/6ae3df4c8f7ff842d9129bdbd9d44365dcedc9c4/python/setup.py#L93-L110

If someone can point me in the right place, I'll make a PR, but otherwise I need help getting the PyPI license declaration to match what's in Github.

**Comment by omalyshe** [comment]
@WilliamRoyNelson That is by intention. 
Pypi packages are part of Intel(R) oneAPI distribution where oneTBB is distributed under ISSL - Intel Simplified Software License (proprietary). 
Distribution to GitHub is done under Apache 2.0; that's correct.

**Comment by WilliamRoyNelson** [comment]
I'm not very familiar with this project overall, so I don't know the right approach, but I feel like the documentation for the Python API, the license specifically, could be more straightforward.

Maybe include a link to the Intel Simplified Software License in the readme for the Python API? https://github.com/oneapi-src/oneTBB/blob/master/python/README.md

Alternately, is there a better homepage for the PyPI package than this repository?

**Comment by omalyshe** [comment]
@WilliamRoyNelson I forgot to mention that the Pypi packages include LICENSE.txt file with the text of ISSL license. 

All this repo content (including Python API) is licensed under Apache when you use it as-is from the open source repository. But here on GitHub we don't provide neither pip packages nor possibility to create them (this option will probably be added soon because we received such request recently).

**Comment by WilliamRoyNelson** [comment]
I guess it can't hurt to ask: Could you change the license for the PyPI package to Apache 2.0?
But in any case, I definitely understand what I came here to find out. It sounds like both GitHub and PyPI have accurate information, even if it may seem contradictory at first glance.

Thank you for explaining it to me!

**Comment by sarathnandu** [comment]
This issue is now considered resolved as it has been addressed. Feel free to reopen if you have additional questions or related inquiries.
