### ISSUE TITLE
oneTBB MSVC 2019 compile ERROR

### ISSUE THREAD

**Issue by s9317741** [oneapi-src/oneTBB#1242]
Including windows.h and tbb\concurrent_vector.h in my A.cpp file will compile with errors.

Error message:
tbb\concurrent_vector.h(640): error C2062: type 'unknown-type' unexpected
tbb\concurrent_vector.h(640,1): error C2059: syntax error: ')'

If I move "include window.h" to the end, the compilation succeeds.

How to fix it using other methods?
I have many files with the same problem

**Comment by pavelkumbrasev** [comment]
Hi @s9317741, which version of TBB do you use?
Include of `windows.h` might confuse several `defines` that will lead to compilation problem so including `windows.h` after it should be appropriate W/A.

**Comment by nofuturre** [comment]
@s9317741 is this issue still relevant?

**Comment by s9317741** [comment]
Hi,
 The problem has been solved. Thanks.
 

    在 2024年7月12日 星期五 下午11:03:26 [GMT+8]， Karolina ***@***.***> 寫道：  
 
 


@s9317741 is this issue still relevant?
