### ISSUE TITLE
TBB_PREVIEW_CONCURRENT_ORDERED_CONTAINERS

### ISSUE THREAD

**Issue by afabri** [oneapi-src/oneTBB#1243]
In an older version of TBB  we encounter the error message
```
C:\dev\tbb2019_20191006oss_win\tbb2019_20191006oss\include\tbb/concurrent_map.h(24,1): fatal error C1189: #error:  Set TBB_PREVIEW_CONCURRENT_ORDERED_CONTAINERS to include concurrent_map.h
```
Is it safe to assume that we can add the `#define`  without impact on newer versions ?

We do not have the problem with `2021.8.0`  but we can't find any TBB change log when the preview became standard, in case we had to  `#ifdef`  the `#define`  with a minimal version.

**Comment by kboyarinov** [comment]
@afabri,
I would not expect any impact from defining the `TBB_PREVIEW_CONCURRENT_ORDERED_CONTAINERS` macro on the newer version of TBB, I guess you can do it safely. @pavelkumbrasev please correct me if I am wrong.

**Comment by nofuturre** [comment]
@afabri is this issue still relevant?

**Comment by sloriot** [comment]
@nofuturre we have been using the recommended macro without any issue. Thanks!
