### ISSUE TITLE
Question: Recommended Hwloc library type

### ISSUE THREAD

**Issue by uilianries** [oneapi-src/oneTBB#1247]
Greetings, 

In order to build oneTBB with hwloc linked, I would like to know what's the recommended library type for hwloc: static or shared?

Also, is there a restriction on using static hwloc linked to a shared oneTBB?

I found some points in the project that points to shared hwloc, but I want to confirm first.

- https://github.com/oneapi-src/oneTBB/blob/7b8018f0bc34e66c06e99551860551171ec60e31/cmake/hwloc_detection.cmake#L28

- https://github.com/oneapi-src/oneTBB/blob/7b8018f0bc34e66c06e99551860551171ec60e31/cmake/README.md?plain=1#L56

**Comment by isaevil** [comment]
Hi @uilianries. These CMake instructions for linkage of TBBBind and HWLOC were made in a sense to link them **dynamically**. But it can work with TBBBind statically linked with HWLOC, but it may require some slight modifications in CMake files.

**Comment by uilianries** [comment]
@isaevil Thank you for quick answer, so hwloc as shared is the recommended way, correct?

**Comment by isaevil** [comment]
@uilianries Correct.

**Comment by uilianries** [comment]
@isaevil Thank you!!
