### ISSUE TITLE
Missing NOTICE file for Apache license

### ISSUE THREAD

**Issue by mwestphal** [oneapi-src/oneTBB#1259]
To be complete, a Apache licensed code should not only contains the `LICENSE` file containing the content of the Apache 2.0 license but also a `NOTICE` file containing the copyright, see here for an example: https://gitlab.kitware.com/osc/apache-template

Please add a `NOTICE` file.

**Comment by omalyshe** [comment]
@mwestphal The original rule to apply Apache 2.0 license https://www.apache.org/licenses/LICENSE-2.0#apply says the following: _"Include a copy of the Apache License, typically in a file called LICENSE, in your work, **and consider also** including a NOTICE file that references the License"_.

I read it not as a mandatory requirement but as a recommendation. 

Also, note that the copyright notice is included into each source code file, e.g. https://github.com/oneapi-src/oneTBB/blob/master/include/oneapi/tbb.h

**Comment by mwestphal** [comment]
> I read it not as a mandatory requirement but as a recommendation.

Absolutely, this is correct

> e.g. https://github.com/oneapi-src/oneTBB/blob/master/include/oneapi/tbb.h

While this is a valid place to look for a copyright, clarifying it in a _non source_ file would make it clearer.
This could be in a NOTICE file, or in the README.md.

In any case, I'm fine without closing this if you think this is not needed.

**Comment by omalyshe** [comment]
I'm closing this issue since it is not a mandatory requirement.
