### ISSUE TITLE
TBB-0.2 conflicts tbb-2021.11.0 installation

### ISSUE THREAD

**Issue by mmokrejs** [oneapi-src/oneTBB#1263]
Hi,
  I cannot get installed tbb through conda because TBB gets somehow pulled in meanwhile. I think this is related to https://github.com/oneapi-src/oneTBB/issues/1008 where it was found that the package got renamed.

```
$ conda list  |  grep -i tbb
tbb                       2021.9.0             hf52228f_0    conda-forge
tbb4py                    2021.9.0        py311hb9d87df_0    conda-forge
$
$ conda upgrade tbb
Channels:
 - defaults
 - conda-forge
 - bioconda
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /some/path/apps/anaconda3

  added / updated specs:
    - tbb


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libhwloc-2.9.1             |       hd6dc26d_0         2.5 MB  conda-forge
    llvmlite-0.41.1            |  py311ha6695c7_0         3.1 MB  conda-forge
    numba-0.58.1               |  py311h96b013e_0         5.4 MB  conda-forge
    python_abi-3.11            |          2_cp311           5 KB  conda-forge
    tbb-2021.9.0               |       hf52228f_0         1.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        12.4 MB

...

Downloading tbb-2021.11.0-py2.py3-none-manylinux1_x86_64.whl (5.4 MB)

Installing collected packages: tbb, stdlib_list, pysam, openpyxl, natsort, igraph, array-api-compat, session-info, python-igraph, louvain, leidenalg, seaborn, pynndescent, anndata, umap-learn, scanpy, splitpipe
  Attempting uninstall: tbb
    Found existing installation: TBB 0.2
ERROR: Cannot uninstall 'TBB'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

...
$
```

See [conda__with_TBB_package_appearing.txt](https://github.com/oneapi-src/oneTBB/files/13380384/conda__with_TBB_package_appearing.txt)  for details.

Thank you.

**Comment by isaevil** [comment]
Based on your log you initially had `2021.8` installed from `main`  and it is the latest one in that channel and then you upgrade it, but it now takes from `conda-forge` channel. I am not sure, but can it be due to the fact that these packages are taken from different channels?
Maybe `--ignore-installed` in `pip install` command should help here?

**Comment by mmokrejs** [comment]
```
$ pip install --ignore-installed tbb
Collecting tbb
  Downloading tbb-2021.11.0-py2.py3-none-manylinux1_x86_64.whl.metadata (1.0 kB)
Downloading tbb-2021.11.0-py2.py3-none-manylinux1_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 37.2 MB/s eta 0:00:00
Installing collected packages: tbb
Successfully installed tbb-2021.11.0
$
$ conda list  |  grep -i tbb
$
```

then I re-started installation of the package and it went through:  
[conda__with_TBB_package_followup.txt](https://github.com/oneapi-src/oneTBB/files/13413369/conda__with_TBB_package_followup.txt)

Thank you for the workaround tip.

**Comment by dnmokhov** [comment]
@mmokrejs, closing the issue. Please reopen if you have any other questions related to this.

**Comment by yes-github** [comment]
Deleting the file **TBB-0.2-py3.9-egg-info** can solve the problem. The file path is, for example：_D:\bin\Anaconda3\Lib\site-packages\TBB-0.2-py3.9.egg-info_

**Comment by omalyshe** [comment]
@yes-github Starting from oneTBB 2021.13.0 *egg files were removed from Conda and PIP packages. Please, verify.
