### ISSUE TITLE
oneTBB on system with both P- and E-cores

### ISSUE THREAD

**Issue by hkleynhans** [oneapi-src/oneTBB#1270]
Is there a good way to guarantee performance on systems with both P- and E-cores?  Specifically, how do we avoid situations where tasks on faster cores end up waiting for ones on slower ones?

**Comment by isaevil** [comment]
You can use `tbb::task_arena::constraints` to schedule tasks, which are supposed to be executed on P-cores or E-cores, by passing these constraints to different `tbb::task_arena`. 
https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Guiding_Task_Scheduler_Execution.html

**Comment by hkleynhans** [comment]
Thank you @isaevil !
