### ISSUE TITLE
Compile to WASM without threads?

### ISSUE THREAD

**Issue by timmyL17** [oneapi-src/oneTBB#1280]
Is it possible to compile to wasm through emscripten without using pthreads? I have code which uses tbb. With older versions, I was able to compile but just not set the `-pthread` compile/link flag, and it would run single threaded (I'm assuming tbb has an internal single threaded scheduler if it doesn't find pthreads?). This is useful for running on sites that are not yet setting cross origin headers correctly. Newer versions of tbb force the use of the `-pthread` flag: https://github.com/oneapi-src/oneTBB/blob/58653a3729f343c48fecb4809a894cd4ba0b8574/CMakeLists.txt#L195C1-L202C31

**Comment by timmyL17** [comment]
Awesome, this will be a big help!

**Comment by JhaShweta1** [comment]
'EMSCRIPTEN_WITHOUT_PTHREAD=true' should should compile without pthreads.

**Comment by timmyL17** [comment]
Thank you!
