### ISSUE TITLE
When find() of tbb::concurrent_hash_map is used in parallel with iteration, the amount of data obtained is inconsistent with the size of the map?

### ISSUE THREAD

**Issue by ystraw-ah** [oneapi-src/oneTBB#1284]
I have two threads, one is doing find() on a tbb::concurrent_hash_map and the other is traversing this map without doing any insertion or deletion. The strange thing is that if find() is not executed, the iterative traversal is normal, but when find() is executed, the amount of data obtained by iteration using HashMap::iterator is inconsistent. Why is this happening?

For a more detailed description and test code, see: [https://stackoverflow.com/questions/77673606/when-find-of-tbbconcurrent-hash-map-is-used-in-parallel-with-iteration-the](https://stackoverflow.com/questions/77673606/when-find-of-tbbconcurrent-hash-map-is-used-in-parallel-with-iteration-the)

**Comment by kboyarinov** [comment]
@ystraw-ah 

Traversing the `concurrent_hash_map` container is [not thread-safe](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_hash_map_cls/iterators.html#:~:text=All%20member%20functions%20in%20this%20section%20can%20only%20be%20performed%20serially.%20The%20behavior%20is%20undefined%20in%20case%20of%20concurrent%20execution%20of%20these%20member%20functions%20with%20other%20(either%20concurrently%20safe)%20methods.). 
The design of the container allows even the constant methods (such as `find`) to re-organize internals (e.g. to rehash the container) that can affect iteration over the map. 
If your use-case requires concurrent traversal while doing lookup, consider using `concurrent_unordered_map` instead. Please note that it does not support concurrent erasure.
Currently, oneTBB do not provide a hash map that supports concurrent insertion, lookup, erasure and traversal at the same time.
`concurrent_hash_map` supports insertion, lookup and erasure.
`concurrent_unordered_map` supports insertion, lookup and traversal.

**Comment by ystraw-ah** [comment]
> @ystraw-ah
> 
> Traversing the `concurrent_hash_map` container is [not thread-safe](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_hash_map_cls/iterators.html#:~:text=All%20member%20functions%20in%20this%20section%20can%20only%20be%20performed%20serially.%20The%20behavior%20is%20undefined%20in%20case%20of%20concurrent%20execution%20of%20these%20member%20functions%20with%20other%20(either%20concurrently%20safe)%20methods.). The design of the container allows even the constant methods (such as `find`) to re-organize internals (e.g. to rehash the container) that can affect iteration over the map. If your use-case requires concurrent traversal while doing lookup, consider using `concurrent_unordered_map` instead. Please note that it does not support concurrent erasure. Currently, oneTBB do not provide a hash map that supports concurrent insertion, lookup, erasure and traversal at the same time. `concurrent_hash_map` supports insertion, lookup and erasure. `concurrent_unordered_map` supports insertion, lookup and traversal.

Thank you for your response!
