### ISSUE TITLE
Disable TBBmalloc info message when compiling VS2022

### ISSUE THREAD

**Issue by hrvthzs** [oneapi-src/oneTBB#1292]
Switched to Visual Studio 2022 and now TBBmalloc messages are printed several times when compiling source files:
```
TBBmalloc: SPECIFICATION VERSION  1.0
TBBmalloc: VERSION    2021.4
TBBmalloc: INTERFACE VERSION  12040
TBBmalloc: TBB_USE_DEBUG  0
TBBmalloc: TBB_USE_ASSERT  0
TBBmalloc: huge pages  not requested

```
Is it possible to disabled this? Thanks!

**Comment by isaevil** [comment]
Looks like you have [TBB_VERSION](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/configuration/version_information.html#tbb-version-environment-variable) environment variable set to 1. You may try to unset it or set to 0.

**Comment by hrvthzs** [comment]
Thanks!
