### ISSUE TITLE
Is resumable task exception safe?

### ISSUE THREAD

**Issue by feverzsj** [oneapi-src/oneTBB#1293]
I know windows fiber is exception safe with proper compiler flags. But gcc/llvm based implementations typically require save/restore cxa global states while switching context to assure correct exception behaviour, which I didn't find in the source.

**Comment by sarathnandu** [comment]
I believe save/restore cxa global states is managed as part of the C++ runtime support for exception handling. In the case of TBB, exception handling is facilitated through functions available in stdexcept/exception header. Nevertheless for any parallel algorithm with resumable task any exceptions that arise are captured and subsequently thrown on the thread that initiated the algorithm.
Do you have any specific use-case or example in mind?

**Comment by feverzsj** [comment]
> I believe save/restore cxa global states is managed as part of the C++ runtime support for exception handling. In the case of TBB, exception handling is facilitated through functions available in stdexcept/exception header. Nevertheless for any parallel algorithm with resumable task any exceptions that arise are captured and subsequently thrown on the thread that initiated the algorithm. Do you have any specific use-case or example in mind?

libc++/libstdc++ based exception handling uses per thread cxa globals, so when you switch the context, you better also switch these globals. Here is a example:

https://github.com/userver-framework/userver/blob/3cdb435a57d91df88124cbfdddaac714ba07b1d6/core/src/engine/task/cxxabi_eh_globals.cpp#L53-L60

https://github.com/userver-framework/userver/blob/3cdb435a57d91df88124cbfdddaac714ba07b1d6/core/src/engine/task/task_context.cpp#L82-L98

Without switching those globals, simple throw and catch are just fine, but when you try switching the context in the middle of stack unwinding (for doing some async cleanup maybe), crashes may happen. On win/msvc, structured exception handling is stack based, so win fiber is also exception safe.

Popular implementation like boost.coroutine doesn't do this, because it wants a portable way to control the stack space, while win fiber won't let you do this, and cxa globals only work in libc++\libstdc++. So such implementation would forbid switching context while unwinding.

**Comment by sarathnandu** [comment]
Thank you for providing more information! We were previously unaware  that libc++/libstdc++ based exception handling  relies on per thread cxa global. We will investigate further and provide necessary patch to support exception safety in resumable task.

**Comment by sarathnandu** [comment]
Would you be able to provide us a reproducer which cause the issue with TBB suspend/resume API?

**Comment by sarathnandu** [comment]
I am assuming this has been resolved. Please provide a reproducer and feel free to reopen the issue if you think we could implement exception safety in a better way.
