### ISSUE TITLE
Is there any reason we cannot implement a parallel_reduce for a rvalue range?

### ISSUE THREAD

**Issue by sukeya** [oneapi-src/oneTBB#1299]
Hello,

I'm writing a program merging many `std::set`s. I would like to parallelize it with joining two sets by `std::set::merge`, but oneTBB doesn't seem to provide any move join function like `T join(T&&, T&&)` as far as I can see [Reduction](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/design_patterns/Reduction.html#reduction), [parallel_reduce.h](https://github.com/oneapi-src/oneTBB/blob/4dfcb6d2e91ba240f3ab529cd80f5417d3cecac8/include/oneapi/tbb/parallel_reduce.h#L395) and [enumerable_thread_specific.h](https://github.com/oneapi-src/oneTBB/blob/4dfcb6d2e91ba240f3ab529cd80f5417d3cecac8/include/oneapi/tbb/enumerable_thread_specific.h#L1017).
Is there any reason we cannot implement it?

**Comment by dnmokhov** [comment]
You should be able to use the lvalue-reference version of `std::set::merge`, e.g.,

```cpp
struct Body {
  std::vector<std::set<int>> &sets;
  std::set<int> result;

  Body(std::vector<std::set<int>> &data) : sets(data) {}
  Body(Body &left, tbb::split) : sets(left.sets) {}

  void operator()(tbb::blocked_range<int> range) {
    for (int i = range.begin(); i < range.end(); ++i) {
      result.merge(sets[i]);
    }
  }

  void join(Body &right) { result.merge(right.result); }
};
```

In the example above, `right` is an lvalue reference to the subtask and`right.result` is an lvalue reference to its result.

Specifying a `parallel_reduce` body is further documented at https://oneapi-src.github.io/oneTBB/main/tbb_userguide/parallel_reduce.html

**Comment by sukeya** [comment]
I didn't know that an `Body` can have the `join` member function which argument is a lvalue-reference without `const`.
Thank you!
