### ISSUE TITLE
Mac installation instructions?

### ISSUE THREAD

**Issue by antoniomedrano** [oneapi-src/oneTBB#130]
Are there any instructions/tutorials on how to install tbb to work with python on a mac? Much appreciated.

**Comment by anton-potapov** [comment]
@antoniomedrano , here is the oneAPI(which oneTBB is the part of) [installation  guide for macOS](https://www.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-macos/top.html)

**Comment by antoniomedrano** [comment]
@anton-potapov lol, thanks!

**Comment by anton-potapov** [comment]
@antoniomedrano  you are welcome :)
