### ISSUE TITLE
How to build TBB with static-libgcc  and static-libstdc++ ?

### ISSUE THREAD

**Issue by fdiedler** [oneapi-src/oneTBB#1301]
Hi everyone,

I need to build TBB with static-libgcc  and static-libstdc++ but I see no option in Cmake to do it.
I don't know with line to edit for the makefiles.

Can you help me ? I want to avoid the dependency of the libgcc_s_seh-1.dll file

Thanks,

**Comment by dnmokhov** [comment]
You can use the [TBB_LIB_LINK_FLAGS](https://github.com/oneapi-src/oneTBB/tree/master/cmake#options-group) option:

`cmake -DTBB_LIB_LINK_FLAGS="-static-libgcc;-static-libstdc++" ..`

or set it directly in https://github.com/oneapi-src/oneTBB/blob/2a6bd1e198106e1447ee885db92b0a3223c9cc1e/cmake/compilers/GNU.cmake#L75-L77

**Comment by fdiedler** [comment]
Thanks @dnmokhov it works fine. Maybe add this option in the Cmake GUI for the next release ?

**Comment by dnmokhov** [comment]
@fdiedler, you can use the native `CMAKE_SHARED_LINKER_FLAGS`, which is available in the CMake GUI and has similar functionality.
