### ISSUE TITLE
ASAN with gcc11 (RTLD_DEEPBIND flag which is incompatible with sanitizer runtime)

### ISSUE THREAD

**Issue by sbudenkov** [oneapi-src/oneTBB#1329]
Hi,

I'm trying to debug my shared library with ASAN.
Compiler: gcc11
ObeTBB: 2021.10.0

Error message:
libtbbbind_2_5.so.3 shared library with RTLD_DEEPBIND flag which is incompatible with sanitizer runtime (see https://github.com/google/sanitizers/issues/611 for details). If you want to run libtbbbind_2_5.so.3 library under sanitizers please remove RTLD_DEEPBIND from dlopen flags.

Any ideas?

**Comment by sarathnandu** [comment]
Hi,
The Address Sanitizer will not work properly if the RTLD_DEEPBIND flag is passed to dlopen. We need to pass this flag by default  in TBB build to support different HWLOC versions. There is an environment variable **TBB_ENABLE_SANITIZERS** to prevent this flag to be passed to dlopen.
 https://github.com/oneapi-src/oneTBB/blob/8b87444d2caaf66facf19bfad50495ac9a6ba011/src/tbb/dynamic_link.cpp#L418
Can you please try setting this environment variable to false?

**Comment by sbudenkov** [comment]
Does it stated in documentation?

The problem is invisible when I've commented:
```cpp
    // if ((tbb::info::numa_nodes().size() > 0) && (numa_id >= 0))
    // {
    //     std::vector<tbb::numa_node_id> numa_indexes = tbb::info::numa_nodes();
    //     if (numa_id < int(numa_indexes.size()))
    //     {
    //         arena_constraints.set_numa_id(numa_indexes[numa_id]);
    //     }
```

> Can you please try setting this environment variable to true?
I'll try ...

**Comment by sarathnandu** [comment]
Thanks for reporting this. We'll update the documentation.
