### ISSUE TITLE
Pip reports TBB version 0.1

### ISSUE THREAD

**Issue by quantumsteve** [oneapi-src/oneTBB#133]
Pip reports the TBB version as `0.1` instead of `2019` and therefore appears outdated.

Should the version listed in [python/setup.py](https://github.com/01org/tbb/blob/tbb_2019/python/setup.py#L99) be obtained from or made to match that in [include/tbb/tbb_stddef.h](https://github.com/01org/tbb/blob/tbb_2019/include/tbb/tbb_stddef.h#L25)?

**Comment by ivankochin** [comment]
Hi @quantumsteve,

No, it should not, since the version specified in `setup.py` is a version of the Python oneTBB module. This version is different from the oneTBB library version.

**Comment by ivankochin** [comment]
Hi @quantumsteve,
We hope that `runtime_version` and` runtime_interface_version` interfaces that were introduced as part of the Beta08 OneTBB release may help you to solve your problems. These interfaces allow you to obtain the current oneTBB string and interface versions from the Python module.
