### ISSUE TITLE
Setting `__TBB_DEFAULT_PARTITIONER` doesn't set partitioner in `parallel_for` with step

### ISSUE THREAD

**Issue by blonded04** [oneapi-src/oneTBB#1331]
`__TBB_DEFAULT_PARTITIONER` is not used for `parallel_for` overload that utilizes step over a range, so even if I expect it to use `affinity_partitioner`, by setting `__TBB_DEFAULT_PARTITIONER` to `affinity_partitioner`, it still uses `auto_partitioner` (which is btw default value of `__TBB_DEFAULT_PARTITIONER`)

**Comment by blonded04** [comment]
I opened a [pull-request](https://github.com/oneapi-src/oneTBB/pull/1327) which is meant to fix it

**Comment by blonded04** [comment]
How can I make "triage" (whatever it means??) CI run pass in PR that fixes this issue

**Comment by pavelkumbrasev** [comment]
@blonded04, you can ignore this fail.
