### ISSUE TITLE
2021.12.0: missing tag/release?

### ISSUE THREAD

**Issue by Nekto89** [oneapi-src/oneTBB#1337]
Hi,

Installer for 2021.12.0 is already available on Intel's website https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#inpage-nav-8-7-undefined

Will there be official release in https://github.com/oneapi-src/oneTBB/releases ?

**Comment by isaevil** [comment]
FYI @omalyshe

**Comment by omalyshe** [comment]
2021.12.0 release will be uploaded to GitHub till the end of this week. Sorry for delay.
