### ISSUE TITLE
doc/README.md is misleading

### ISSUE THREAD

**Issue by meator** [oneapi-src/oneTBB#1343]
I wasn't able to build documentation of oneTBB while following [doc/README.md](https://github.com/oneapi-src/oneTBB/blob/master/doc/README.md).

Here is what I've tried:
[![asciicast](https://asciinema.org/a/654012.svg)](https://asciinema.org/a/654012)

(Here is a plaintext version: [654012.txt](https://github.com/oneapi-src/oneTBB/files/14967972/654012.txt))

The Makefile looks like it's in a wrong directory or it's inspecting wrong ones. There also seems to be a Doxygen file. Does this project use multiple documentation systems?

**Comment by omalyshe** [comment]
@meator  doc/README.md describes how to build oneTBB documentation in https://oneapi-src.github.io/oneTBB/ format. 
It doesn't use Doxygen but use Sphinx. Doxygen file is used internally to generate oneTBB Test Specification. 
Regarding your concern about incorrect Makefile location - we'll check it.

**Comment by aepanchi** [comment]
@meator thanks for raising the issue! https://github.com/oneapi-src/oneTBB/pull/1351 should fix it.
