### ISSUE TITLE
Visual Studio 2019 Installation ?

### ISSUE THREAD

**Issue by desertDesel** [oneapi-src/oneTBB#137]
Hello !
I'm quite new with Visual and encounters some trouble with installation. I need TBB in order to optimize a motion sensing algorithm. Anyone has ideas about the way to install TBB on Visual 2019 ?

**Comment by anton-potapov** [comment]
@desertDesel , here is the oneAPI (which oneTBB is the part of) [installation guide for windows ](https://www.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-windows/top.html)
