### ISSUE TITLE
Compiling TBB with recent GCC 13.2, 11.4 fails 

### ISSUE THREAD

**Issue by gshamov** [oneapi-src/oneTBB#1384]
I was trying to compile oneTBB 2021.2.5 on a Alma8 machine using GCC (GCC built from sources).  
The machine has an Intel Cascade Lake 6230R CPU. With newer GCC 13.2 and 11.4 I get immediately the following error (the one below is from 11.4) .

 make
[  0%] Building CXX object src/tbb/CMakeFiles/tbb.dir/allocator.cpp.o
[  0%] Building CXX object src/tbb/CMakeFiles/tbb.dir/arena.cpp.o
In file included from xxx/lib/gcc/x86_64-pc-linux-gnu/11.4.0/include/x86gprintrin.h:89,
                 from xxx/lib/gcc/x86_64-pc-linux-gnu/11.4.0/include/immintrin.h:27,
                 from yyy/tbb/oneTBB-2021.2.5/src/tbb/../../include/oneapi/tbb/detail/_machine.h:33,
                 from yyy/tbb/oneTBB-2021.2.5/src/tbb/../../include/oneapi/tbb/detail/_utils.h:26,
                 from yyy/tbb/oneTBB-2021.2.5/src/tbb/task_dispatcher.h:20,
                 from yyy/tbb/oneTBB-2021.2.5/src/tbb/arena.cpp:17:
xxx/lib/gcc/x86_64-pc-linux-gnu/11.4.0/include/waitpkgintrin.h: In function ‘void tbb::detail::r1::prolonged_pause()’:
xxx/lib/gcc/x86_64-pc-linux-gnu/11.4.0/include/waitpkgintrin.h:53:1: error: inlining failed in call to ‘always_inline’ ‘unsigned char _tpause(unsigned int, long long unsigned int)’: target specific option mismatch
   53 | _tpause (unsigned int __A, unsigned long long __B)
      | ^~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/tbb/CMakeFiles/tbb.dir/build.make:90: src/tbb/CMakeFiles/tbb.dir/arena.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:451: src/tbb/CMakeFiles/tbb.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

The build seem to work with Alma8's system GCC suite that is 8.5.0, coming from the OS RPMs.

**Comment by omalyshe** [comment]
@gshamov Is there any specific reason why you are trying to build 2021.2.5? 
The latest release is https://github.com/oneapi-src/oneTBB/tree/v2021.12.0, so please use it.

**Comment by gshamov** [comment]
Ok. I guess it is just me: the 2021.2.5 comes up first in the Tags , as of today. the v2021.12.0 seem to build ok.
