### ISSUE TITLE
Potential Array Out of Bounds and Redundant Code in create_record Function

### ISSUE THREAD

**Issue by cccbbaa** [oneapi-src/oneTBB#1393]
**Description:**

I have identified a potential issue in the `create_record` function within the codebase. The function aims to transfer characters from a `char` array `src` into an `unsigned` array `dst`, but there are several problems that may lead to incorrect behavior or runtime errors.

**File Path:**
https://github.com/oneapi-src/oneTBB/blob/master/examples/parallel_for/game_of_life/Update_state.cpp#L25

**Code in Question:**

```cpp
inline void create_record(char* src, unsigned* dst, unsigned width) {
    dst[0] |= src[width - 1];
    for (unsigned i = 0; i < 31u; ++i)
        dst[0] |= src[i] << (i + 1);
    unsigned col;
    for (unsigned col = 31u; col < width; ++col)
        dst[(col + 1) / 32u] |= src[col] << ((col + 1) % 32u);
    dst[(col + 1) / 32u] |= src[0] << ((col + 1) % 32u);
}
```

**Identified Issues:**

1. **Redundant Declaration of `col`:** The variable `col` is declared twice, which is unnecessary and might cause confusion.
2. **Array Out of Bounds:** In the last line of the function, the variable `col` is used outside its scope, potentially leading to out-of-bounds access on the `dst` array.

**Suggested Fix:**

```cpp
inline void create_record(char* src, unsigned* dst, unsigned width) {
    dst[0] |= src[width - 1];
    for (unsigned i = 0; i < 31u; ++i)
        dst[0] |= src[i] << (i + 1);
    unsigned col;
    for (col = 31u; col < width; ++col)
        dst[(col + 1) / 32u] |= src[col] << ((col + 1) % 32u);
    dst[(col + 1) / 32u] |= src[0] << ((col + 1) % 32u);
}
```

Thank you for your attention to this matter. Please feel free to reach out if further clarification is needed.

**Comment by dnmokhov** [comment]
@cccbbaa, thank you for identifying the issue and proposing the fix.
