### ISSUE TITLE
Unable to use tbb.framework in an iOS app

### ISSUE THREAD

**Issue by jtressle** [oneapi-src/oneTBB#1415]
Hi, 

Thanks for adding the TBB_BUILD_APPLE_FRAMEWORKS earlier this year.  I'm able to compile the tbb.framework.  However, I'm still trying to get it to work in a release app.  

Basically, I found two issues.  First is that MinimumOSVersion isn't being set in the Info.plist.  The App Store complained with this:

Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. 

I was able to fix this by manually adding a MinimumOSVersion entry to the Info.plist.  Am I missing a step?

Second, the headers are not being included in the .framework file.  What is the correct way to link them?  Do I need to do something with xcodebuild?

These are the two cmake commands I tried to use.

cmake -DCMAKE_SYSTEM_NAME=iOS -DTBB_TEST=OFF -DTBBMALLOC_BUILD=OFF -DTBB_BUILD_APPLE_FRAMEWORKS=ON -DCMAKE_INSTALL_PREFIX=/tmp/tbb ..

- using ios toolchain - still need to add MinimumOSVersion
cmake -DCMAKE_TOOLCHAIN_FILE=/Users/jmt/Downloads/ios-cmake/ios.toolchain.cmake \
      -DPLATFORM=OS64 \
      -DCMAKE_INSTALL_PREFIX=/tmp/tbb \
      -DCMAKE_CXX_STANDARD=17 \
      -DCMAKE_SYSTEM_NAME=iOS \
      -DTBB_TEST=OFF -DTBBMALLOC_BUILD=OFF \
      -DTBB_BUILD_APPLE_FRAMEWORKS=ON ..
      
 Thanks in advance.  Really appreciate this library.
 
 Thanks,

**Comment by isaevil** [comment]
FYI @geertbleyen

**Comment by geertbleyen** [comment]
@isaevil @jtressle .
The inclusion of the "correct" headers is not trivial due to that onetbb has a main library and a couple of 'supporting' libraries (tbbmalloc, tbbmalloc_proxy). If embedding the headers, the frameworks for tbbmalloc and tbbmalloc_proxy would need to also provide the tbb header, but not have symbols for it, and you'd end up in a jumble of duplicate include files (you could even accidentally mix up headers from different tbb versions when mixing the .frameworks from different versions). Apple's .framework logic just doesn't work well in this kind of scenario.
I expect that in most cases the device where the frameworks are built is also the device where they get linked, so the include paths for them are known, no?
Regarding, minimum version, I'm unsure as I didn't encounter this issue. We do further postprocessing on our .frameworks (bundle the different platforms into .xcframeworks in which we modify the Info.plist and resign everthing).
Setting CMAKE_OSX_DEPLOYMENT_TARGET should do the trick (https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html) I guess?.

**Comment by jtressle** [comment]
@isaevil @geertbleyen 

Thanks for the quick response.  I was able to get the tbb.framework to work by putting it into a xcframework:

xcodebuild -create-xcframework -framework /private//tmp/tbb/lib/tbb.framework/ -output /private/tmp/frameworks/tbb.xcframework

I did have to add MinimumOSVersion manually first (I couldn't get CMAKE_OSX_DEPLOYMENT_TARGET to work properly, but I didn't spend too much time on it).

I also did not have to add the headers to the xcframwork.

Appreciate the help and closing this for now.  Thanks

**Comment by Treata11** [comment]
Hi @jtressle

I've done the very same but I'm running into a different issue... 
```bash
mkdir build && cd build

cmake -DCMAKE_INSTALL_PREFIX=/Users/.../oneTBB/my_installed_onetbb -DTBB_TEST=OFF -DCMAKE_SYSTEM_NAME=iOS DTBB_BUILD_APPLE_FRAMEWORKS=ON .. 
```
and then build & installed the project:
```bash
cmake --build . && cmake --install .
```
And then, I tried creating the iOS binaries:
```bash
cmake -DCMAKE_TOOLCHAIN_FILE=/Users/.../ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64 -DCMAKE_INSTALL_PREFIX=/Users/.../oneTBB/my_installed_onetbb -DCMAKE_CXX_STANDARD=17 -DCMAKE_SYSTEM_NAME=iOS -DTBB_TEST=OFF -DTBBMALLOC_BUILD=OFF -DTBB_BUILD_APPLE_FRAMEWORKS=ON ..
```

And it has created two directories with names `appleclang_16.0_cxx11_64_relwithdebinfo` and `appleclang_16.0_cxx17_64_relwithdebinfo` in the `build` directory.
The former contains some `dylib`s with a `vars.sh` & the latter contains a `tbb.framework` which is empty (only contains an `info.plist`).

I appreciate your help in advance!

**Comment by Treata11** [comment]
For anyone bumping to the same issue, be sure to disable `TBBMALLOC` & `TBBTEST` builds off, eg:
```bash
cmake -B _build -DCMAKE_TOOLCHAIN_FILE=/Users/alaa/ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64 -DTBB_BUILD_APPLE_FRAMEWORKS=ON -DTBBMALLOC_BUILD=OFF -DTBB_TEST=OFF
```

**Comment by jtressle** [comment]
hi @Treata11 sorry for the delay:

These were the commands I got to work:

**Create Framework**
```
 cmake -DCMAKE_TOOLCHAIN_FILE=/Users/jmt/Downloads/ios-cmake/ios.toolchain.cmake \
      -DPLATFORM=OS64 \
      -DCMAKE_INSTALL_PREFIX=/tmp/tbb \
      -DCMAKE_CXX_STANDARD=17 \
      -DCMAKE_SYSTEM_NAME=iOS \
      -DTBB_TEST=OFF -DTBBMALLOC_BUILD=OFF \
      -DTBB_BUILD_APPLE_FRAMEWORKS=ON ..
```

**Create xcFramework**

`xcodebuild -create-xcframework -framework /private//tmp/tbb/lib/tbb.framework/ -output /private/tmp/frameworks/tbb.xcframework`

I finally had to update the tbb.xcframwork MinimumOSVersion in Info.plist

After that, I used the framework in my iOS project.

For your directories, did you try running xcodebuild pointing at `/Users/.../oneTBB/my_installed_onetbb/lib/tbb.framework`?

Also, I never got the dynamic binaries to work.

Thanks,

**Comment by drwjf** [comment]
@jtressle 

I tried the command you posted and got the following error message:
```
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:227 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:591 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake/Modules/FindThreads.cmake:226 (find_package_handle_standard_args)
  CMakeLists.txt:243 (find_package)
```

How can I install "Threads" here?

Many thanks.
