### ISSUE TITLE
TBB_VERSION_MINOR is misaligned with package versions

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#142]
Intel provides packages on official channels with versions like 2019.6. However, `tbb/tbb_stddef.h` always defines TBB_VERSION_MINOR to 0. Moreover, it describes itself as 2019.0 in strings. For example:
```bash
$ conda list | grep tbb
tbb                       2019.6               hc9558a2_0    conda-forge
tbb-devel                 2019.6               hc9558a2_0    conda-forge
$ strings /local/miniconda3/envs/arrow/lib/libtbb.so.2 | grep VERSION
TBB: VERSION            2019.0
TBB: INTERFACE VERSION  11006
``````
See also related https://github.com/intel/parallelstl/issues/28

**Comment by tbbdev** [comment]
Fixed. For example: 2020.2 https://github.com/oneapi-src/oneTBB/blob/tbb_2020/include/tbb/tbb_stddef.h#L22
