### ISSUE TITLE
Dangling pointer

### ISSUE THREAD

**Issue by jwakely** [oneapi-src/oneTBB#1427]
https://github.com/oneapi-src/oneTBB/blob/db334fc49b62ef8463e343c272da9bd9544b8514/test/tbb/test_eh_flow_graph.cpp#L514

The call to `ss.str()` returns a temporary `std::string`, then calling `c_str()` gets a pointer to that string's contents, which is immediately invalidated when the temporary is destroyed.

**Comment by kboyarinov** [comment]
Thanks @jwakely for reporting this and @phprus for providing a fix:)
