### ISSUE TITLE
7 versioning schemes for TBB!!! Or we need one simple, consistent package and product versioning

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#143]
Currently, TBB [releases in this repo ](https://github.com/intel/tbb/releases) have unpredictable names of files. For example, who can guess that `tbb2019_20190410oss_lin.tgz` corresponds to 2019.6 release, which is also encoded in non-standard form of `2019_U6` tag!
It is impossible to guess the filename in scripts, it is non-trivial to transform `2019.6` into `2019_U6` in simple packaging scripts, and as result, it is hard to maintain TBB as a dependency. For example, Arrow holds a [simple list of versions and URLs ](https://github.com/apache/arrow/blob/master/cpp/thirdparty/versions.txt#L56), which depend on the desired version, e.g.:
```
BOOST_VERSION=1.67.0
BROTLI_VERSION=v1.0.7
##### 8< cut >8 ######
  "ARROW_BOOST_URL boost-${BOOST_VERSION}.tar.gz https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//./_}.tar.gz"
  "ARROW_BROTLI_URL brotli-${BROTLI_VERSION}.tar.gz https://github.com/google/brotli/archive/${BROTLI_VERSION}.tar.gz"
```
Perhaps, it is impossible to write such a string for TBB. And even if it is possible, one can never guess what's the 'date' part for a certain version of TBB unless goes and checks on the site and hand-codes it here, which is extremely inconvenient.

Moreover, full-fledged open-source projects like Arrow and TBB itself have to support multiple target environments like different OS distros, package management and CI/CD systems - at the same time! Now, if we have multiple ways to encode TBB version, it puts additional burden on users and developers for switching between these schemes and converting versions between multiple places where the version is specified.

Another inconsistency comes from TBB interface version, which is yet another versioning scheme existing in parallel (is pun intended?) and *the only* way to check version of the library in run-time. This interface version isn't reflected in package versioning and not guaranteed to be aligned.. Since we cannot remove it at this point, I'd recommend to commit to a predictable conversion formula between both and add runtime calls to get TBB version in package versioning format.

To sum-up, TBB has 7 (!!!) different versioning schemes:
1. Marketing defines TBB as e.g. "TBB 2019" for Gold version, "TBB 2019 Update 4" for update releases.
1. [tbb_stddef.h defines](https://github.com/intel/tbb/blob/tbb_2019/include/tbb/tbb_stddef.h#L21) TBB_VERSION_MAJOR, TBB_VERSION_MINOR. Please note: MINOR is not equal to the Update number, basically it is == 0 for the whole 2019 line of releases. These macros define response for CMake, TBB_VERSION=1, Windows file property, and strings, e.g. `TBB: VERSION 2019.0` (for Update 4)
1. Also, [tbb_stddef.h defines](https://github.com/intel/tbb/blob/tbb_2019/include/tbb/tbb_stddef.h#L25) self-sufficient TBB_INTERFACE_VERSION, which is not guaranteed to be related to Major.Minor in any obvious way but contains Update number as remainder of division % 1000.  Described in strings as `TBB: INTERFACE VERSION  11004`. This is the only version available with API request to the runtime library.
1. PSXE and official Intel redistribution channels (APT, YUM, [Conda](https://anaconda.org/intel/tbb) define TBB packages as Year.Update, starting with 2019), e.g. 2019.4. I.e. it omits the MINOR portion TBB defines replacing it by the Update number, which directly conflicts to the way the product defines itself.
1. Github tags are in completely different format which is non-standard among open-source projects and requires additional conversion, e.g: `2019_U4`
1. Github release files contain additional component: the date, so the URL to download a TBB release looks like https://github.com/intel/tbb/releases/download/2019_U6/tbb2019_20190410oss_lin.tgz
1. SONAME on Linux is 2.. which is just not reflected anywhere as the product version (it is the most major component indicating backward compatibility epoch, [mentioned in tbb_stddef.h](https://github.com/intel/tbb/blob/tbb_2019/include/tbb/tbb_stddef.h#L30) as TBB_COMPATIBLE_INTERFACE_VERSION)

The easy way to fix this mess for 2020 line of releases is:
1. Commit to sync MINOR and Update numbers in (1) and (2)
2. Commit to new INTERFACE version format, e.g. `19040`. It is bigger than current `11004` thus does not break its promise. It has obvious connection to the marketing versioning, reserves the lowest digit for marking builds with local changes, and provides access to the marketing version via existing API.
3. Establish new format for Github tags and release files which is trivially deductible from the product version, e.g. github.com/intel/tbb/releases/download/**2020.1**/**_tbb2020.1-lin.tgz_**

**Comment by nofuturre** [comment]
@anton-malakhov is this issue still relevant?
