### ISSUE TITLE
"Set the oneAPI Environment" every time when I start VSCode!?!

### ISSUE THREAD

**Issue by khteh** [oneapi-src/oneTBB#1433]
# Summary
I find out that I have to CTRL+SHIFT+P > Intel oneAPI: Initialize environment variables every time when I start up VSCode. Otherwise there are build errors "fatal error: oneapi/tbb.h: No such file or directory". Any way to automate this?

# Version
How to find out the version? I just installed the latest one recently.

# Environment
Provide any environmental details that you consider significant for reproducing the issue.
The following information is important:
* Hardware
* OS name and version: Ubuntu 24.04
* Compiler version: g++ 13.2.0

# Observed Behavior
I have to manually CTRL+SHIFT+P > Intel oneAPI: Initialize environment variables every time when I start up VSCode. 

# Expected Behavior
Automate the environment setup

# Steps To Reproduce
Check that the issue is reproducible with the latest revision
of the master branch. Include all the steps to reproduce the issue.

**Comment by omalyshe** [comment]
@khteh Did you install oneTBB package from this site  [this site](https://github.com/oneapi-src/oneTBB/releases) or  from Intel(R) oneAPI https://www.intel.com/content/www/us/en/developer/tools/oneapi/onetbb.html ?

**Comment by khteh** [comment]
None of the above. Installed from here https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-2/install-with-gui.html#GUID-EB48DA86-FEF8-48E9-9428-D22F8E1633DC

**Comment by omalyshe** [comment]
> None of the above. Installed from here https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-2/install-with-gui.html#GUID-EB48DA86-FEF8-48E9-9428-D22F8E1633DC

Well.. this is oneAPI installation. You should have got to that link from https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-2/overview.html. 
Then look at the Next Steps section and read https://www.intel.com/content/www/us/en/docs/oneapi-base-toolkit/get-started-guide-linux/current/overview.html. You will have to run setvars.sh script as I mentioned before.
