### ISSUE TITLE
Glibc version detection is broken for Clang

### ISSUE THREAD

**Issue by Timmmm** [oneapi-src/oneTBB#146]
TBB tries to detect the glibc version by looking at `__GNUC__`, `__GNUC_MINOR__` etc. which is the version of GCC. However Clang always seems to set this to 4. The code notes this.

```
// note that when ICC or Clang is in use, __TBB_GCC_VERSION might not fully match
// the actual GCC version on the system.
#define __TBB_GCC_VERSION (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__)
```

This is pretty annoying because GCC 4 is pretty ancient at this point, and you get warnings about deprecated functions if you try compiling the code with Clang.

Also there *are* proper macros for the glibc version now (easily since 6). See https://sourceforge.net/p/predef/wiki/Libraries/

**Comment by Timmmm** [comment]
Note there has been a rather hacky attempt to fix this in [`linux.inc`](https://github.com/intel/tbb/blob/tbb_2019/build/linux.inc#L58) and [`linux.clang.inc`](https://github.com/intel/tbb/blob/tbb_2019/build/linux.clang.inc#L51):

        export gcc_version:=$(shell gcc -dumpversion)
...
       # TODO: do not assume that GCC minor and patchlevel versions are always single-digit.
       CPLUS_FLAGS += -DTBB_USE_GLIBCXX_VERSION=$(subst .,0,$(gcc_version))

This is rubbish because:

a) It can't handle non-single digit GCC versions (as noted in the comment). Somewhat surprisingly that hasn't actually happened since GCC 2.95.
b) `-dumpversion` only prints the major version since some time ago. Now you need to do `-dumpfullversion -dumpversion` (the second `-dumpversion` is for backwards compatibility) otherwise it will think GCC 7.0.0 is actually GCC 0.0.7.
c) This is only in the TBB build system - when you come to actually `#include` TBB headers in your project that depend on this value you don't get this `#define`! It doesn't get written to a `config.h` or anything like that.

**Comment by Timmmm** [comment]
I had a further investigation, and it seems like there are no available macros to check the `libstdc++` version.:

* `__GNUC__` checks the GCC version but is always 4 for Clang.
* `__GLIBC__` checks the glibc version (i.e. not libstdc++).
* `__GLIBCXX__` is the *date* of the libstdc++ release, but it's useless because minor versions released after a newer major version have a higher number. I.e. 4.9 might have a higher number than 5.0.

In any case, the highest number you check is GCC 5.1 which is now 4 years old. I would consider just dropping support for libstdc++ older than that.

**Comment by akukanov** [comment]
Thanks for the contributed improvement for GCC version detection in the makefiles.

`__TBB_GCC_VERSION` is exactly what it says, i.e. the [compatible] GCC version reported by the compiler. We do not care of the version of glibc. We do care of the version of libstdc++, but as you found, there is no good way to check for it. Therefore this is what we do:
https://github.com/intel/tbb/blob/cc2c04e2f5363fb8b34c10718ce406814810d1e6/include/tbb/tbb_config.h#L43-L55
I.e. we provide a way for the user to explicitly specify the version of libstdc++ via the `TBB_USE_GLIBCXX_VERSION` macro; this is for the case of Clang etc.; if it is not specified, we do the best guess based on various macros provided by the library and the compiler. 

The code in makefiles is just to simplify building TBB - it tries to define the special macro based on the actual GCC version on the system. For the use, one would need to specify the above macro in the application build scripts. By the way, this is documented: https://www.threadingbuildingblocks.org/docs/help/reference/appendices/known_issues/linux_os.html

**Comment by Timmmm** [comment]
No idea, sorry. I don't work on our TBB-using code anymore.
