### ISSUE TITLE
Is tbb::concurrent_hash_map's copy constructor thread safe?

### ISSUE THREAD

**Issue by h-barthwal** [oneapi-src/oneTBB#1472]
I have a `tbb::concurrent_hash_map` object that is being modified by several threads. I want a thread safe way of iterating over the map entries and read them. Therefore, I create a copy of the map and then loop over it. However, I am not sure whether the copy constructor will give me a non-corrupt copy of the map or not. Here is the psuedo code for what I am trying to achieve:

```cpp
using InfoMap = tbb::concurrent_hash_map<std::string, Info>;
void examine_info_map(const InfoMap& info_map)
{
  const InfoMap info_map_copy(info_map); // Is this thread safe?
  for (const auto& info_entry: info_map) {
    // read key and value and maybe print them based on a certain condition
  }
}

void erase_info_entry(const string& key) {
  info_map.erase(key);  
}

void insert_info_entry(const string& key, const Info& value) {
  info_map.insert(std::make_pair(key, value));  
}
```

In the above example `erase_info_entry` and `insert_info_entry` functions modify the map while `examine_info_map` is trying to copy it and then iterate over the copy. Can someone tell me whether I am doing the right thing here? If not, then what is the correct way of grabbing a copy of the map while it is being modified in several other threads? Thanks in advance.

**Comment by pavelkumbrasev** [comment]
As the [specification ](https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onetbb/source/containers/concurrent_hash_map_cls/iterators) states iteration through container cannot be performed concurrently with `insert/erase`.
Therefore, you will need to have additional synchronization on your side. You can try `rw_mutex` where all operation will lock it for `read` and `examine_info_map` will lock it for `write`. Such approach should not damage performance of the application.

**Comment by h-barthwal** [comment]
Thanks for the quick response and the link to documentation. My application crashed due to exactly this reason and that is why I wanted to create a copy of the map and then iterate on it. Does it mean that the map cannot even be copied in a thread safe manner (as that also involves iterating over the internal representation of the map)?

**Comment by pavelkumbrasev** [comment]
> Does it mean that the map cannot even be copied?

Yes.

> as that also involves iterating over the internal representation of the map

Exactly.

**Comment by h-barthwal** [comment]
Thanks for confirming. Closing the issue.
