### ISSUE TITLE
concurrent vector compiler errors

### ISSUE THREAD

**Issue by adelossantos59** [oneapi-src/oneTBB#1475]
# Summary
Provide a short summary of the issue. 
See the sections below
for factors important for the reproduction of an issue.

# Version
2021.13

# Environment
Provide any environmental details that you consider significant for reproducing the issue.
The following information is important:
* Hardware
Processor	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.41 GHz
Installed RAM	16.0 GB

* OS name and version
Edition	Windows 10 IoT Enterprise
Version	22H2
OS build	19045.4651

* Compiler version
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33813 for x86
# Observed Behavior

```
> Compiler errors:
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): error C2589: '(': illegal token on right side of '::'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): error C3878: syntax error: unexpected token '(' following 'expression'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: '( ( this . . . identifier'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): message : parsing resumes here
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): error C2760: syntax error: ')' was unexpected here; expected ';'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): error C3878: syntax error: unexpected token ')' following 'jump_statement'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: ') ) <'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): error C3878: syntax error: unexpected token ')' following 'expression_statement'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: ') ?'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): error C2760: syntax error: ':' was unexpected here; expected ';'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): error C3878: syntax error: unexpected token ':' following 'expression_statement'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: ':'
> 1>C:\Program Files (x86)\Intel\oneAPI\tbb\latest\include\oneapi\tbb\concurrent_vector.h(488,21): message : error recovery skipped: ')'
```

# Expected Behavior
Should be no compiler errors.

# Steps To Reproduce

1. Create Visual Studio DLL project.
2. Set project Configuration Properties  > Intel oneAPI Threading Building Blocks > Use oneTBB  to Yes 
3. Include concurrent_vectorheader file:
`#include <oneapi/tbb/concurrent_vector.h>`
4. Instantiate any simple vector:  
`tbb::concurrent_vector<int>vec;`
6. Add some data: 
`vec.push_back(1);`
8. Then compile

**Comment by nofuturre** [comment]
Hi @adelossantos59,

I was able to reproduce the issue. In my case defining NOMINMAX before including windows.h resolved it. 

The problem is explained broader here: [Issues with windows.h](https://belaycpp.com/2021/05/11/windows-h-breaks-the-stl-and-my-will-to-live/)

Let me know if it works for you too

**Comment by adelossantos59** [comment]
Thank you @nofuturre, it fixed it.
