### ISSUE TITLE
TBB_USE_EXCEPTIONS define is used incorrectly in movable_exception

### ISSUE THREAD

**Issue by t0x1c** [oneapi-src/oneTBB#151]
The code uses either RTTI or static name for **tbb::movable_exception** based on TBB_USE_EXCEPTIONS flag, which is incorrect. If project **does use exceptions** but **doesn't use RTTI** the build will fail. There should be another flag itroduced, like TBB_USE_RTTI. Affected file is tbb_exception.h
```
#if TBB_USE_EXCEPTIONS
        typeid(self_type).name()
#else /* !TBB_USE_EXCEPTIONS */
        "movable_exception" // 
#endif /* !TBB_USE_EXCEPTIONS */
```

**Comment by alexey-katranov** [comment]
It is not common to use exceptions without RTTI (how is the `catch` block works in that case?). Moreover, `tbb::movable_exception` is unnecessary starting with C++11. It looks like the issue has a minimal expose and will be considered as low priority.
Can you explain how important the fix can be for you? In any case, we are ready to consider a PR with a fix.

**Comment by t0x1c** [comment]
Well, catch works with -fno-rtti, but typeid doesn't. I use GCC 8.1, BTW.
I fixed it for my local copy, so I don't think there's a need to push a PR specifically for this. But I will be glad to see it in next planned release (be it C++11 compiler check or RTTI check).

**Comment by anton-potapov** [comment]
Closing this, as `tbb::movable_exception` was [removed ](https://software.intel.com/content/dam/develop/external/us/en/documents/tbbrevamp.pdf)during revamp.
