### ISSUE TITLE
onetbb task Scheduler Bypass

### ISSUE THREAD

**Issue by sejabs** [oneapi-src/oneTBB#1523]
Dear OneTbb developers:
In the section "Migrating from low-level task API" of _oneAPI Threading Building Blocks Developer Guide and API Reference_, I just followed the code to implement a simplest Scheduler Bypass.

int main() {

    tbb::task_group tg;

    tg.run_and_wait([&tg] {
        std::println("spawned task.");

        return tg.defer([]{std::println("other task.");});
    });

    tg.wait();

    return 0;}

However, there is no "other task." string printed on the screen. The used onetbb is 2021.13 and built with msvc 17.11. I also noticed the last sentence in section "Task Scheduler Bypass" which said "_the only way to use this optimization is to use preview feature of ``onepai::tbb::task_group`_". I tried set the **TBB_PREVIEW_TASK_GROUP_EXTENSIONS** macro to 1 but it didn't work.

**Comment by vossmjp** [comment]
Did you set TBB_PREVIEW_TASK_GROUP_EXTENSIONS in the source or via compiler flag? If in source, was it before including any of the TBB headers?

**Comment by sejabs** [comment]
@vossmjp Thx! I put the `#define` sentence before any `include` in the test.cpp, so the problem is solved.
By the way, I hope the OneTBB Guide could be enhanced with more detailed and practical examples like the book "**Pro TBB**". Or Any plan to update "**Pro TBB**"?
