### ISSUE TITLE
Incorrect compiler/linker options on Linux.

### ISSUE THREAD

**Issue by max0x7ba** [oneapi-src/oneTBB#153]
When compiling on Linux the library uses `-lpthread` for linking. This is both unnecessary and insufficient.

The correct way to build multi-threaded applications on Linux is to specify `-pthread` for both compiling and linking. See https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Preprocessor-Options.html#Preprocessor-Options

> **-pthread**
> Define additional macros required for using the POSIX threads library. **You should use this option consistently for both compilation and linking.** This option is supported on GNU/Linux targets, most other Unix derivatives, and also on x86 Cygwin and MinGW targets.

**Comment by ms178** [comment]
I also wonder why Makefiles for several compilers on Linux use the "-g" flag for the release build which increases the size of the binary dramatically. Someone should clean all of the Makefiles up.

**Comment by alexey-katranov** [comment]
It surely makes sense to use `-pthread` instead of `-lpthread`.

As for `-g`, the debug info is useful with profiling tools that gives some value even with bigger binary cost. Perhaps, debug information can be separated from the binary but it is unclear if all profilers and checkers can work with external debug information.

**Comment by ms178** [comment]
> As for -g, the debug info is useful with profiling tools that gives some value even with bigger binary cost. 

What is the intended distinction between debug and release builds then? I don't see a coherent strategy here as e.g. the Android builds don't use -g in their release target builds. Also on Windows, there is no debug info in the release builds and I would have thought that profiling is done solely with debug builds.

As the bigger binary size is quite substantial (ca. 330 kb vs 1.6 MB for libtbb.so.2) this could have negative performance implications on CPUs with small caches.

**Comment by alexey-katranov** [comment]
Debug info is not executable code and should not affect performance (hopefully, the loader might omit mapping the debug info into memory). So, it is just a question of the package size and disk occupation.
As for debug info on other platforms, on Windows you can find *.pdb files shipped with release versions. E.g. VTune Amplifier provides better profiling information and Visual Studio provides better stack traces.
As for profiling, I am not sure that someone optimize performance with debug build.

**Comment by ms178** [comment]
> As for profiling, I am not sure that someone optimizes performance with debug builds but profiling release builds is usually easier with debug information.

There was a logic error on my side, my bad. Thanks for clearing up the profiling part and the performance implications as I am not a programmer. Enabling debug info by default on release builds seems still a bit odd though, but if the majority of users do find it useful that might be more understandable for me now. I alter the Makefile anyway with my custom flags mentioned here: https://github.com/intel/tbb/issues/145 - btw. any comments on that one?

**Comment by anton-potapov** [comment]
in oneTBB this option is added implicitly via CMake. 

First, find the required package:
https://github.com/oneapi-src/oneTBB/blob/51277f0e588183b162f9d60b987406eebb02135c/CMakeLists.txt#L176-L177
And then make targets depends on it: 

https://github.com/oneapi-src/oneTBB/blob/51277f0e588183b162f9d60b987406eebb02135c/src/tbb/CMakeLists.txt#L116-L121
