### ISSUE TITLE
oneapi/tbb/detail/_flow_graph_impl.h:350:71: error: no matching function for call to ‘wait::wait(tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&)’

### ISSUE THREAD

**Issue by Mifodix** [oneapi-src/oneTBB#1555]
# Summary
oneapi/tbb/detail/_flow_graph_impl.h:350:71: error: no matching function for call to ‘wait::wait(tbb::detail::d1::wait_context&, tbb::detail::d1::task_group_context&)’

# Version
2022.0

# Environment
Provide any environmental details that you consider significant for reproducing the issue.
The following information is important:
* Intel
* Linux
* GCC 11

# Observed Behavior
Document behavior you observe.

# Expected Behavior
Document behavior you expect.

# Steps To Reproduce
Check that the issue is reproducible with the latest revision
of the master branch. Include all the steps to reproduce the issue.

**Comment by Mifodix** [comment]
Possible fix:
`
+++ _flow_graph_impl.h
@@ -347,7 +347,7 @@
         caught_exception = false;
         try_call([this] {
             my_task_arena->execute([this] {
-                wait(my_wait_context_vertex.get_context(), *my_context);
+                d1::wait(my_wait_context_vertex.get_context(), *my_context);
             });
             cancelled = my_context->is_group_execution_cancelled();
         }).on_exception([this] {
`

**Comment by dnmokhov** [comment]
Thank you for reporting this issue. It has already been fixed in 9c9ace2.

**Comment by omalyshe** [comment]
@Mifodix Please, check if https://github.com/oneapi-src/oneTBB/commit/9c9ace26863cf50853f39b2d0b78146d20a981a6 fixes it.

**Comment by Mifodix** [comment]
Фиксед :)
