### ISSUE TITLE
2019_U8 hang on ppc64le in test_thread_monitor.exe

### ISSUE THREAD

**Issue by jamesjer** [oneapi-src/oneTBB#160]
I have been in communication with Alexey Veprev about issues building 2019_U8 on ppc64le for the Fedora Linux distribution.  I found some hardware to test on.  The issue is that test_thread_monitor.exe hangs most of the time.  GDB has this to say about such a hung process:

```
(gdb) info threads
  Id   Target Id                                        Frame
* 1    Thread 0x7ffff7ff5510 (LWP 48) "test_thread_mon" 0x00007ffff7aeff1c in sched_yield () from /lib64/libc.so.6
  5    Thread 0x7ffff76bf160 (LWP 54) "test_thread_mon" 0x00007ffff7b0a334 in syscall () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7aeff1c in sched_yield () from /lib64/libc.so.6
#1  0x0000000100005ea4 in rml::internal::thread_monitor::yield ()
    at ../../src/rml/server/thread_monitor.h:232
#2  TestMain () at ../../src/rml/test/test_thread_monitor.cpp:105
#3  0x0000000100004840 in main (argc=<optimized out>, argv=<optimized out>)
    at ../../src/test/harness.h:420
(gdb) bt
#0  0x00007ffff7b0a334 in syscall () from /lib64/libc.so.6
#1  0x0000000100005ad0 in tbb::internal::futex_wait (comparand=2,
    futex=<optimized out>) at ../../include/tbb/machine/linux_common.h:81
#2  tbb::internal::binary_semaphore::P (this=<optimized out>)
    at ../../src/tbb/semaphore.h:205
#3  rml::internal::thread_monitor::commit_wait (c=..., this=0x100041eb8)
    at ../../src/rml/server/thread_monitor.h:255
#4  ThreadState::loop (this=0x100041eb8)
    at ../../src/rml/test/test_thread_monitor.cpp:51
#5  0x00000001000067c8 in ThreadState::routine (arg=<optimized out>)
    at ../../src/rml/test/test_thread_monitor.cpp:31
#6  0x00007ffff7f399a8 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff7b11d18 in clone () from /lib64/libc.so.6
```

The ThreadState object for thread 5 is:
```
$2 = {monitor = {my_cookie = {
      my_epoch = {<tbb::internal::atomic_impl_with_arithmetic<unsigned long, unsigned long, char>> = {<tbb::internal::atomic_impl<unsigned long>> = {
            my_storage = {
              my_value = 3585}}, <No data fields>}, <No data fields>}},
    in_wait = {<tbb::internal::atomic_impl<bool>> = {my_storage = {
          my_value = true}}, <No data fields>}, skipped_wakeup = false,
    my_sema = {<tbb::internal::no_copy> = {<tbb::internal::no_assign> = {<No data fields>}, <No data fields>},
      my_sem = {<tbb::internal::atomic_impl_with_arithmetic<int, int, char>> = {<tbb::internal::atomic_impl<int>> = {my_storage = {
              my_value = 2}}, <No data fields>}, <No data fields>}}},
  request = 419, ack = 420, clock = 7165, stamp = 7155}
```

As you can see, request != ack, so this thread was supposed to call monitor.cancel_wait(), but instead it called monitor.commit_wait(c).

Questions:

1. Consider lines 49-51 of test_thread_monitor.cpp.  Is something supposed to prevent request from changing between reading it in the if condition and calling monitor.commit_wait(c)?  If so, what is that something?  If not, this test has a race.

2. Is something supposed to cause a memory barrier between the main thread writing request and the other thread reading it?  If so, what is that something?  If not, then this test needs such a barrier.

**Comment by jamesjer** [comment]
I tried skipping this test to see if everything else was okay on ppc64le.  Everything is not okay:

./test_mutex_v2.exe  1
done
./test_mutex_v2.exe  2
ERROR: 36342!=36343
ERROR for Spin RW Mutex at 320860: read,  lock kept, impl/expl
ERROR: 46309!=46310
ERROR for Spin RW Mutex at 94537: read,  lock kept, impl/expl
ERROR: 93395!=93396
ERROR for Spin RW Mutex at 192995: read, upgrade, lock not kept, expl/impl
ERROR: 93395!=93396
ERROR: 93395!=93396
ERROR for Spin RW Mutex at 430588: read,  lock kept, impl/expl
ERROR: 93395!=93396
ERROR for Spin RW Mutex at 430589: read,  lock kept, impl/expl
ERROR: 93395!=93396
ERROR for Spin RW Mutex at 430590: read,  lock kept, impl/expl
ERROR: 93396!=93397
ERROR for Spin RW Mutex at 192996: read,  lock kept, expl/impl
ERROR: 93396!=93397
ERROR for Spin RW Mutex at 192997: read,  lock kept, expl/impl
ERROR: 93396!=93397
ERROR for Spin RW Mutex at 192998: read,  lock kept, expl/impl
ERROR: 93397!=93398
ERROR for Spin RW Mutex at 192999: write, downgrade, lock kept, expl/impl
ERROR: 93397!=93398
ERROR for Spin RW Mutex at 430592: read,  lock kept, expl/impl
ERROR: 93397!=93398
ERROR for Spin RW Mutex at 430593: read,  lock kept, expl/impl
ERROR: 93397!=93398
ERROR for Spin RW Mutex at 430594: read,  lock kept, expl/impl
ERROR: 93397!=93398
ERROR: 93398!=93399
ERROR for Spin RW Mutex at 430595: read, upgrade, lock kept, expl/impl
ERROR: 93398!=93399
ERROR for Spin RW Mutex at 430596: read,  lock kept, expl/impl
ERROR: 93398!=93399
ERROR for Spin RW Mutex at 193000: read,  lock kept, impl/expl
ERROR: 93398!=93399
ERROR for Spin RW Mutex at 193001: read,  lock kept, impl/expl
ERROR: 93398!=93399
ERROR for Spin RW Mutex at 430597: read,  lock kept, expl/impl
ERROR: 93398!=93399
ERROR for Spin RW Mutex at 430598: read,  lock kept, expl/impl
ERROR: 93399!=93400
ERROR for Spin RW Mutex at 430599: write, downgrade, lock kept, expl/impl
ERROR for Spin RW Mutex at 193002: read,  lock kept, impl/expl
[...]

And so on for thousands and thousands of lines before I noticed this was happening and stopped the test.

**Comment by akukanov** [comment]
The `test_mutex_v2` issue on  is known, and can be safely ignored. This test exists to check the backward compatibility entry points with a really old version of TBB which is very unlikely to be used by any application right now. Perhaps we should remove these backward-compatibility tests from the `test` target. Alternatively, specifying `-DTBB_NO_LEGACY=1` (e.g. adding it to `CPLUS_FLAGS` for PowerPC architectures inside `build/linux.gcc.inc` might help.

The issue with `test_thread_monitor` is not clear, especially without having access to a PowerPC machine. We will double-check the questions you asked, and get back; however it's unclear what more we could do. Also, this test is for an optional TBB binary, which is not of much use even on Intel's architectures, so perhaps building and testing it on PowerPC makes little sense and should be disabled.

**Comment by jamesjer** [comment]
I patched tbb to skip test_thread_monitor and reran the build.  Now src/rml/test/test_thread_monitor.cpp is hanging.  It is exactly the same situation as above.  Thread 1 is in the while loop on lines 104-5, waiting for thread 2 to respond.  Thread 2 is stuck in a futex_wait call, below the call to monitor.commit_wait(c) on line 51.  The value of ack is 976.  The value of request is 975, so monitor.cancel_wait() should have been called.

See https://cfarm.tetaneutral.net/ for one way of gaining access to ppc64le hardware.

**Comment by jamesjer** [comment]
Two possibilities for gaining access to a PowerPC machine:
1. https://cfarm.tetaneutral.net
2. Have someone on your team become a Fedora packager, and help maintain the Fedora package.  That person will gain access to these machines: https://fedoraproject.org/wiki/Test_Machine_Resources_For_Package_Maintainers

Tonight, I patched tbb to skip test_thread_monitor.  The build went on for awhile, but then test_task_scheduler_init.exe hung.  Two threads are left, both on line 281 of src/test/test_task_scheduler_init.cpp, neither able to make progress.

On a whim, I decided to see if there might be something wrong with the ppc64 primitives in include/tbb/machine/mac_ppc.h.  I changed every isync and lwsync to sync.  All of the tests passed.  I won't have time for a few more days, but whenever I can look at this next, I will try doing a binary search to figure out which one is causing the problem.  Hopefully it is just one. :-)  It might be worth looking through the gcc 9 release notes to see if any changes were made to inline asm.

**Comment by jamesjer** [comment]
Ignore that last paragraph.  I was looking at the wrong header file.

The problem with test_task_scheduler_init.exe is that ExceptionTest2 creates a barrier for 4 threads, but we're using an arena with my_num_slots == 2.  So 2 threads enter the barrier, then wait there forever for the other 2 threads to show up.  How is the maximum number of threads for the arena decided?

**Comment by alexey-katranov** [comment]
What arena do you mean? There is no explicit arenas in ExceptionTest2 and it uses task_scheduler_init to specify the required number of threads. Have you modified the test?
