### ISSUE TITLE
thread cache cleaning

### ISSUE THREAD

**Issue by alenauus** [oneapi-src/oneTBB#172]
Which functions can be used to forcefully clean thread caches (assuming that "scalable_allocation_command(TBBMALLOC_CLEAN_ALL_BUFFERS, 0);" does not work in a certain case)?

Thanks,
Alena

**Comment by nik-ponomarev** [comment]
Hi @alenauus, you can use `scalable_allocation_command(TBBMALLOC_CLEAN_THREAD_BUFFERS, 0)` to force the certain thread to clear its cache.

**Comment by alenauus** [comment]
Thank you for your reply.

I've tried running this simple example [https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/498725] (tbbmem.cpp file) with TBBMALLOC_CLEAN_THREAD_BUFFERS instead and the result is the same:  

 ./tbbmem 
108856
Pre-allocation:                         0.0252 GByte process size
108856
After parallel allocation:                1.87 GByte process size
108856
After parallel deallocation:              1.87 GByte process size
108856
After tbbmalloc clean:                    1.87 GByte process size

Are there any specific requirements for scalable_allocation_command to work?

Thank you again.

**Comment by nik-ponomarev** [comment]
@alenauus, ok, then try to follow our guide for TBB allocator caches cleanup. Despite its name, the global cleanup command (`TBBMALLOC_CLEAN_ALL_BUFFERS`), will not free all the cached memory: clearing local buffers of all threads would require much additional synchronization, increasing memory allocation overheads. That is why developers who want to avoid excessive memory footprint and return most of the unused memory back to OS should use the following scenario for the cleanup procedures:
1)  Free all the memory you want to be released. If affordable, synchronize across all threads to ensure memory got freed before the next step.
2)  For **all allocating** threads, call `TBBMALLOC_CLEAN_THREAD_BUFFERS` (or shut down the threads if everything is bad). If affordable, synchronize with/join to the \***main**\* thread.
3)  Call `TBBMALLOC_CLEAN_ALL_BUFFERS` on the \***main**\*  thread.

This is especially important for applications where threads heavily allocate and exchange data, and allocation and deallocation of an object are often done by different threads.

Important to mention, that calling these commands may result in increased time for subsequent memory allocation requests. The command is not designed for frequent use, and careful evaluation of the performance impact is recommended.

**Comment by alenauus** [comment]
Thank you for the suggestion.

Yes, it will be more logical to deallocate everything within the threads rather than after (it works if we do it in this example). 

Sorry, the last question - how can I terminate a specific thread directly from code?

Thanks,
Alena

**Comment by anton-potapov** [comment]
@alenauus , in general it iы not good idea to terminate random threads from outside.  More correct is to give a thread a "signal" to quit, and wait for it to quit (This implies that thread should be ready for those "signals" ). 

However, from  technical standpoint there is such API, but it is non-portable and OS-dependent.
