### ISSUE TITLE
No rule to make target 'install'

### ISSUE THREAD

**Issue by realtime-neil** [oneapi-src/oneTBB#175]
The `Makefile` has no `install` target.

```
$ make install
make: *** No rule to make target 'install'.  Stop.
```

The `Makefile` should _really_ have an `install` target. Because that would be the way people get to use the library when they build it from source; i.e., after it's _installed_.

**Comment by kubaroth** [comment]
I was thinking about it recently as well. Have a look this [commit](https://github.com/kubaroth/tbb/commit/9a06b847b27659427e1585a6be7f0a2b133d7830) 
It allows to install into specified beforehand tbb_install_prefix
`tbb_install_prefix=./install_dir2 make -j 20 install`

**Comment by anton-potapov** [comment]
oneTBB uses CMake as the build system.  See [Installation from Sources](https://github.com/oneapi-src/oneTBB/blob/master/INSTALL.md) for ,ore details.
