### ISSUE TITLE
incorrect index parameter type description of parallel_for

### ISSUE THREAD

**Issue by anton-potapov** [oneapi-src/oneTBB#176]
from here : https://www.threadingbuildingblocks.org/docs/help/index.htm and here https://software.intel.com/en-us/node/506153  : 

```cpp
template<typename Index, typename Func>
Func parallel_for( Index first, **Index_type** last, const Func& f
                   [, partitioner[, task_group_context& group]] );
```

Second argument has type `Index_type` while probably should `Index`

**Comment by alexey-katranov** [comment]
Thank you for the report.
