### ISSUE TITLE
Reallocating memory using scalable_realloc when emulating Haswell crashes in tbbmalloc (32 bit only).

### ISSUE THREAD

**Issue by J-cztery** [oneapi-src/oneTBB#18]
`size_t size = 63;
void *ptr = scalable_malloc(size);
size += 4;
ptr = scalable_realloc(ptr, size);`

And then when running the following command: 
sde  -hsw -- TestTbbMalloc.exe
An access violation is received in tbbmalloc.dll!___intel_memcpy

The problem does not happen when compiling tbbmalloc from source using Visual Studio. I guess this is related to memcpy substituted by ICL. 
Reproduced on 2017 Update 5(Windows). 
The same code does not crash on real Haswell CPU without emulator.

**Comment by alexey-katranov** [comment]
Hello! It turned out that I failed to reproduce the issue. Could you provide more details about your experiment, please? What compiler and options are used? Can you share the complete reproducer? What versions of the software are used (e.g. sde, compiler, OS). Any other relevant information that can be useful in your opinion.

Thank you in advance.

**Comment by J-cztery** [comment]
Hi, 
Are you using tbbmalloc.dll as available in 2017 Update 5 binary?

I am sorry but i do not have access to that environment anymore. The compiler was Visual Studio 2015. 
It is a complete reproducer, a main method consisting only of the above code.

**Comment by alexey-katranov** [comment]
It seems we did not move forward with the investigation. If the issue still affects you, feel free to reopen issue.

**Comment by J-cztery** [comment]
? Why did you close the issue if it is not fixed?

**Comment by alexey-katranov** [comment]
We failed to reproduce it. If it still persists, lets reopen and try something else to figure out the root cause.

**Comment by J-cztery** [comment]
>We failed

Agreed.
