### ISSUE TITLE
[New Feature] Customer TBB Extension and Atomic element manipulation

### ISSUE THREAD

**Issue by yiakwy** [oneapi-src/oneTBB#180]
== Quick Sketch ==

Hi, I implemented a modern `thread_pool` -- not the old ones, discarded, using `semaphore`, with std::promise, std::future, and std::async enabled. Moreover, I have built Task, TaskGroup on top of my threads pool and tbb::task_group. Thanks to the help from author Jonathan R. Madsen from PTL. Here is an usage example:

```c++
typename Task<F, Args...>::Ptr task (new Task<F, Args...>(f, args...));

void* tag = tag(task);
tasks_.push_back(tag);
typename Task<F, Args...>::FutureType fut = task->get_future();
task_group_->run([&] {
(*task)();
});
return fut; 

```

Outside of the codes, a customer SWE can write codes in such a manner

```c++11
...
auto fut = pool_->enqueue([&] {

})
...
// you can also extract `get_future` from tasks_ by casting to base class `TaskBase`
fut.wait();
pool_->enqueue([&]{

})

```

== Further Help On Extension Development Needed ==

I am especially interested in the following topics from intel tbb:

1) atomic operation for elements in a concurrent container:

It is unrealistic to create a lot mutexes for some elements in some data structure : `map`, `unordered_map`, and so on.

unordered_map for example, I can create a lock by passing an `concurrent_hash_map<Type1, Type2>::accessor/const_accessor`  into `insert` method for writing/reading. However, customer SWE might also want to use the lock to do other operations later. How is that implemented and how could we achieve the above goal?

2) Integrate task, task group into flow_graph:

It seems that they are totally different. I am working on making my work flow as graph nodes where I can execute my computation graph engine. I want unify the concepts of task, task_group, concurrency container and flow graph.

3) integrate customer computation graph with tbb support(threads control, atomic operations):
3-1) is it possible, any examples?
3-2) I want to add a task dispatch (I have gprc support already), to make it a distributed executor. Any plan in intel?

**Comment by nofuturre** [comment]
@yiakwy is this issue still relevant?

**Comment by nofuturre** [comment]
If anyone encounter this issue in the future please open new issue with a link to this one
