### ISSUE TITLE
[Python] Add runtime version interface function

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#189]
joblib/threadpoolctl project needs TBB version in tbb4py API: https://github.com/joblib/threadpoolctl/pull/47#pullrequestreview-306211000

**Comment by ivankochin** [comment]
Hi @anton-malakhov,
Thanks for reporting!
This interface will be published as part of one of the future releases.

**Comment by ivankochin** [comment]
Hi @anton-malakhov,
The `runtime_version` and `runtime_interface_version` interfaces were introduced as part of the [Beta08 OneTBB](https://github.com/oneapi-src/oneTBB/tree/onetbb_2021) release.
