### ISSUE TITLE
Linking tbb cause ld process memory increase huge 

### ISSUE THREAD

**Issue by haolujun** [oneapi-src/oneTBB#191]
Hi .
    My env:
    gcc: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
    cpu: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
#include "tbb/tbb.h"
#include <stdio.h>
using namespace tbb;
class ApplyFoo {
    float *const my_a;
public:
    void operator()( const blocked_range<size_t>& r ) const {
        float *a = my_a;
        for( size_t i=r.begin(); i!=r.end(); ++i ) {
           //Foo(a[i]);
          printf("%f\n", a[i]);
        }
    }
    ApplyFoo( float a[] ) :
        my_a(a)
    {}
};

void ParallelApplyFoo( float a[], size_t n ) {
    parallel_for(blocked_range<size_t>(0,n,2), ApplyFoo(a),
                 simple_partitioner());
}
int main () {
  float a[10];
  ApplyFoo foo(a);
  return 0;
} 

When I compile the code and linking tbb with -ltbb, the ld process memory increase very fast and cpu aways 100%,  and finally failed. The memory can reach very very big util there is not enough memory on my computer.

**Comment by anton-potapov** [comment]
Hi @haolujun is the problem still reproducible with [v2021.4](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.4.0) or latest master ?

**Comment by anton-potapov** [comment]
Closing as original problem reported against TBB (not oneTBB).
@haolujun please re-open if the problem still reproducible with oneTBB
