### ISSUE TITLE
Use tbb malloc proxy instead of the ntdll.dll implementation

### ISSUE THREAD

**Issue by akhaled86** [oneapi-src/oneTBB#193]
I had a c++ code that uses tbbmalloc_proxy and this improved the performance alot on Windows 10
I wrapped the code using pybind11 but it seems that pybind ignores tbb and just uses the malloc implmenetation from ntddll.dll
Any ideas how to overcome this issue ?

**Comment by anton-potapov** [comment]
@akhaled86, 
the easiest way is: 
>Add the following header to a source code of any binary which is loaded during application startup.
>```cpp
>#include "oneapi/tbb/tbbmalloc_proxy.h"
>```



see [Windows* OS C/C++ Dynamic Memory Interface Replacement](https://oneapi-src.github.io/oneTBB/tbb_userguide/Windows_C_Dynamic_Memory_Interface_Replacement.html) for more details.

**Comment by anton-potapov** [comment]
@akhaled86 please reopen if problem still exists
