### ISSUE TITLE
Please merge CMakeLists.txt into tbb source.

### ISSUE THREAD

**Issue by expnkx** [oneapi-src/oneTBB#194]
https://github.com/wjakob/tbb/blob/master/CMakeLists.txt

**Comment by AlexVeprev** [comment]
Hi, I commented on the CMake topic in https://github.com/oneapi-src/oneTBB/issues/6#issuecomment-670434792:

> Hi all, I'm glad to announce that TBB migrated to CMake in [oneAPI 2021.1-beta08](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.1-beta08) release. Source code was published to [onetbb_2021](https://github.com/oneapi-src/oneTBB/tree/onetbb_2021) branch. Some instructions are provided in [cmake/README.md](https://github.com/oneapi-src/oneTBB/blob/onetbb_2021/cmake/README.md).
> 
> Feel free to provide your feedback and contributions.
