### ISSUE TITLE
error : '_ReadWriteBarrier' is deprecated: use other intrinsics or C++11 atomics instead [-Werror,-Wdeprecated-declarations]

### ISSUE THREAD

**Issue by rubenvb** [oneapi-src/oneTBB#200]
Using Clang-cl (Clang 8.0.1) that ships with VS2019 and compiling something that includes `tbb/parallel_for_each.h` (which includes indirectly `tbb/machine/msvc_ia32_common.h`) triggers this warning:
```
tbb/tbb_machine.h(616,9): error : '_ReadWriteBarrier' is deprecated: use other intrinsics or C++11 atomics instead [-Werror,-Wdeprecated-declarations]
tbb/machine/msvc_ia32_common.h(95,44): message : expanded from macro '__TBB_release_consistency_helper'
tbb/machine/msvc_ia32_common.h(84,39): message : expanded from macro '__TBB_compiler_fence'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\lib\clang\8.0.1\include\intrin.h(186,16): message : '_ReadWriteBarrier' has been explicitly marked deprecated here
```

It seems the Clang header `intrin.h` explicitly deprecates `_ReadWriteBarrier` and suggests to use C++11 intrinsics instead:
https://github.com/llvm-mirror/clang/blob/master/lib/Headers/intrin.h#L172

This prevents a `-Werror` compilation of anything with TBB.

**Comment by anton-potapov** [comment]
@rubenvb this part was removed during revamp, so this is not applicable to oneTBB
