### ISSUE TITLE
Make libtbb.so reproducible

### ISSUE THREAD

**Issue by jelly** [oneapi-src/oneTBB#202]
Compiling intel-tbb twice on two different machines leads to [two different binaries](https://tests.reproducible-builds.org/archlinux/extra/intel-tbb/intel-tbb-2019.9-2-x86_64.pkg.tar.xz.html#intel-tbb-----.----x--_--.pkg.tar---usr-lib-libtbb.so.-) which makes it unreproducible. Not recording the hostname and build time in BUILD_HOST and __TBB_DATETIME would make the build reproducible.

The movitation for wanting reproducible builds can be found here:
https://reproducible-builds.org/

**Comment by jelly** [comment]
https://github.com/intel/tbb/pull/82 already fixes part of this isuse.

**Comment by anton-potapov** [comment]
@jelly builds of oneTBB is expected to be reproducible ( as per : https://github.com/oneapi-src/oneTBB/pull/37#issuecomment-870809904 )
@alexey-katranov , please correct me if I'm wrong
