### ISSUE TITLE
parallel iteration of a concurrent hash map

### ISSUE THREAD

**Issue by abasak24** [oneapi-src/oneTBB#204]
Hi, 
I am new to TBB. May I please request you to help me with an issue?
I have a TBB concurrent hash map which I first populate with a bunch of insert and erase. 
Once I am done with the above population, I wish to iterate through the entire hash map and sum all the values (i.e., the value of each key-value pair) into a single variable. I do not know how to parallelize this iteration.  Could you please help me point out what is the right syntax for that? 

I am trying the following but this is not compiling:
typedef tbb::concurrent_hash_map<int64_t,int64_t> degreeMap;
degreeMap hMap;
int64_t y = 0;

tbb::parallel_for( hMap.range(), [y](const degreeMap::range_type &r) {
                for( degreeMap::iterator i = r.begin(); i != r.end(); i++){
                     compare_and_swap(&y, i->second); 
          };
 } );

Is there any example in the TBB source code which shown how to do something like this? 

Many thanks,
Abanti

**Comment by anton-potapov** [comment]
@abasak24 there is an [example in oneTBB Developer Guide ](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/concurrent_hash_map.html) on how to use `concurrent_hash_map`, including parallel iteration over it. 

As for you particular use case I believe [`parallel_reduce`](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/algorithms/functions/parallel_reduce_func.html) is the best fit here :  
```c++
int64_t sum_of_map_via_reduce(const degreeMap& hMap) {
    int64_t left_identity_value = 0;

    return tbb::parallel_reduce( hMap.range(), left_identity_value, 
        [](degreeMap::const_range_type &r,  int64_t init_value){
            int64_t local_sum = init_value;
            for( auto i = r.begin(); i != r.end(); i++){
                local_sum += i->second;
            }
            return local_sum;
        },
        std::plus<int64_t>{}
    );
}
```

As for using `parallel_for` it can look like this: 
```c++
int64_t sum_of_map(const degreeMap& hMap) {
    std::atomic<int64_t> y {0};

    tbb::parallel_for( hMap.range(), 
        [&y](degreeMap::const_range_type &r)  {
            int64_t local_sum = 0;
            for( degreeMap::const_iterator i = r.begin(); i != r.end(); i++){
                local_sum += i->second;
            }
            y += local_sum;
        }
    );

    return y;
}
```
Please note that : 
 - variable for accumulating total result is `std::atomic`
 - for sake of performance it is  better to minimize number of operations on shared variables , 
 local accumulator is used to for partial sum first


[Full version code sample](https://gcc.godbolt.org/z/PMcasvovh)

**Comment by anton-potapov** [comment]
@abasak24 please reopen if needed
