### ISSUE TITLE
[Feature Request] Add tbbmalloc memory usage statistics

### ISSUE THREAD

**Issue by Nyoh** [oneapi-src/oneTBB#205]
Hello! Since tbb malloc does not release allocated memory to operating system it is now impossible to know how much memory an application can get before running out of RAM.
It would be nice to have a way to find out how much memory allocated through tbb malloc is really used/unused.

**Comment by anton-potapov** [comment]
@Nyoh FYI there is way to clean internal buffers which might be useful : 
```c++
scalable_allocation_command(TBBMALLOC_CLEAN_ALL_BUFFERS, 0)
```
see more details [here ](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/memory_allocation/c_interface_to_scalable_allocator.html).

**Comment by anton-potapov** [comment]
@Nyoh, feel free to re-open (or open new issues/feature requests) if the existing statistic is not enough
