### ISSUE TITLE
How to make a debug build?

### ISSUE THREAD

**Issue by arihannu** [oneapi-src/oneTBB#207]
Take a look at Makefile. How are we supposed to build a debug build of TBB if all paths and cfg are hard coded to release?

**Comment by alexey-katranov** [comment]
Consider using [src/Makefile](https://github.com/intel/tbb/blob/tbb_2020/src/Makefile). It provides debug capabilities.

**Comment by Timmmm** [comment]
I also literally just spent 30 minutes trying to work out why our debug builds don't work after upgrading. The root makefile even has this line:

    cfg?=release

But then it goes on to completely ignore it and hard-code everything to release. I suggest you add an error if the user sets `cfg` to anything other than `release`:

```
ifneq ($(cfg),release)
  $(error "The root Makefile only supports release mode. Use src/Makefile instead.")
endif
```

Or whatever (I have successfully avoided learning Make so far).

**Comment by arihannu** [comment]
Well I have spent hours figuring out when using CMake to include TBB into our project and only getting release build of TBB when building debug build. It seems CMake is using the tbb_root/Makefile, not src/Makefile. Any help would be appreciated..

**Comment by alexey-katranov** [comment]
It makes sense. Pay attention that `cfg=debug` never can be used to build debug version of TBB library.
Or it can be even better to remove `cfg?=release` from the top-level Makefile.

**Comment by Timmmm** [comment]
Yes it seems like `cfg=debug` does not work in `src/Makefile` either - instead you should build `tbb_release` or `tbb_debug`. Some other issues I noticed:

* No way to build `tbb` without `tbbmalloc` and `tbbmalloc_proxy` (and it doesn't seem to depend on them).
* `make` builds and runs tests by default! Very slow, and unexpected.
* `make tbb` builds both debug and release, but `make` only does release. Not very consistent.

I did have a look at your CMake code but honestly it is very un-idiomatic and difficult to integrate with existing CMake projects.

What it *should* do is pretty much just `add_library(tbb  ${TBB_SOURCES}))  install(tbb)`. But actually it exposes some functions that you can call to build TBB, and then generate the CMake config files. But:

* It generates the CMake config files in the source directory! Not very good.
* The config files have full paths to the build output, which is in some temporary build directory. That is not useful.
* It just calls through to `make` or `gmake` anyway!

Honestly I would burn your build system to the ground and start again with a proper CMake system.

**Comment by alexey-katranov** [comment]
> Honestly I would burn your build system to the ground and start again with a proper CMake system.

We are considering this option as a part of [TBB Revamp](https://software.intel.com/en-us/articles/tbb-revamp) effort but there is no final decision yet.

**Comment by arihannu** [comment]
Also I find it odd that currently TBB (release) is actually built during CMake configure, and not during cmake build, which is the right way. Very strange approach.

Here is how I added it to our master CMakeLists.txt:
```
set(TBB_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/dependencies/tbb)
include(${TBB_ROOT}/cmake/TBBBuild.cmake)
tbb_build(TBB_ROOT ${TBB_ROOT})
```
So are there any arguments that I could give to tbb_build() so that it would actually build both release and debug libraries?

**Comment by amadio** [comment]
I've had to deal with this problem when updating TBB's package in Gentoo Linux yesterday. Here is the patch I applied to the Makefile to recover debug builds:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-cpp/tbb/files/tbb-2020.1-makefile-debug.patch

If you apply this patch, you can use `make ... cfg=debug` to make the debug build. I will create a pull request with this change later. Cheers,

**Comment by landwehrj** [comment]
That doesn't fix it through cmake btw. Only make. Needs to pass the cfg to the make file as well I believe.

I sent them a patch on 2/21 through the tbb submission site to fix it. No response so far.

Here is that patch for those who wish to fix cmake as well: https://drive.google.com/file/d/1qaUyF7qSbIcBLSaHlRwLb9lGbPC5Y7qw/view?usp=sharing

**Comment by alexey-katranov** [comment]
> > Honestly I would burn your build system to the ground and start again with a proper CMake system.
> 
> We are considering this option as a part of [TBB Revamp](https://software.intel.com/en-us/articles/tbb-revamp) effort but there is no final decision yet.

We finally switched to cmake in [next version of TBB] (https://github.com/oneapi-src/oneTBB/tree/onetbb_2021)

**Comment by arihannu** [comment]
Great thank you for the CMake switch! However it did not work for me quite yet. I have a CMake project, which builds also TBB for Win, Mac and Linux. So I added this new branch with add_subdirectory to my main CMakeLists.txt. Then during configuration I get an error: CMake Error: INSTALL(EXPORT) given unknown export "myprojectTargets". I was looking at the TBB CMakeLists.txt and in the install part, you are using ${CMAKE_PROJECT_NAME}, which is actually myproject, and I suspected you meant to refer to the TBB project name. So after I replaced ${CMAKE_PROJECT_NAME} with ${PROJECT_NAME}, configuration worked without errors.

Then trying to build (MSVC 2019 x64). First error was a warning treated as error in test_malloc_whitebox. Ok that I was able to fix with TARGET_COMPILE_OPTIONS(test_malloc_whitebox PRIVATE "/WX-"). Then there is an error where strangely cmake tries to call <myproject>\integration\cmake\generate_vars.cmake from myproject's root source directory, which is not correct, it should be pointing to oneTBB source directory? I am still trying to figure out how to fix this. To be continued... :)

**Comment by AlexVeprev** [comment]
@arihannu thank you very much for trying to integrate our CMake! We will check and address the issues you found, feel free to submit new issues.

About generate_vars.cmake: I believe the problem is in `CMAKE_SOURCE_DIR` used in [cmake/vars_utils.cmake](https://github.com/oneapi-src/oneTBB/blob/onetbb_2021/cmake/vars_utils.cmake). Replacing it with `CMAKE_CURRENT_SOURCE_DIR` should help. If it doesn't and you don't need the generated vars at all you can just remove `cmake/vars_utils.cmake` file :)

**Comment by arihannu** [comment]
Ok I fixed the vars_utils.cmake issue. Replaced ${CMAKE_SOURCE_DIR} with "${CMAKE_CURRENT_SOURCE_DIR}/../..". Not very elegant but you can make it prettier.

Next, I have a warning causing an error (our project using "/WX" flag): 
oneTBB\include\tbb\detail/_task.h(213,1): warning C4324: 'tbb::detail::d1::task': structure was padded due to alignment specifier

In TBB main CMakeLists.txt you have
option(TBB_STRICT "Treat compiler warnings as errors" ON)

But setting that OFF has no effect, I still get this warning->error. It seems this option is not used anywhere..

**Comment by AlexVeprev** [comment]
@arihannu, how does you project set `/WX` flag? Using `CMAKE_CXX_FLAGS`?

`TBB_STRICT=OFF` doesn't remove user-specified flags, but it just skips adding own `/WX`. I need to check if we can properly handle flags coming from user side, but I'd suggest to consider specifying `/WX` more precisely: e.g. via `target_compile_options` to not impact other targets.

**Comment by arihannu** [comment]
Yes we define "global" build flags in the main CMakeLists.txt with add_compile_options(). I was able to undefine the /WX for tbb targets (TARGET_COMPILE_OPTIONS(tbb PUBLIC "/WX-")) and now the project builds successfully. Waiting for the issues I reported before to be fixed.. Anyhow, great job! Finally we will be able integrate the latest and greatest TBB (after the fixes).

**Comment by AlexVeprev** [comment]
@arihannu great! `/WX-` may work, we'll consider it. Thank you again for the integration and reporting the problems!

**Comment by AlexVeprev** [comment]
@arihannu I've submitted a couple of new issues based on our discussion, do you need something else to be addressed in scope of this issue?

**Comment by arihannu** [comment]
@AlexVeprev Thanks! I think these should be enough for now. Do you have any estimates when these will be fixed and available?

**Comment by AlexVeprev** [comment]
@arihannu unfortunately I don't have information when it's going to be available, but I'll do my best to deliver it asap. I'll let you know about any updates once I have them. From technical perspective everything is clear about #271, but #272 needs some investigations from design and implementation points of view to make it working consistently and reliably for all supported platforms. If you have any particular comments regarding the created issues I'd propose to discuss them there to have a full context.

**Comment by arihannu** [comment]
Then I would say, this debug build issue can be closed. Building a debug build works now (after the new issues are fixed).
