### ISSUE TITLE
Cyclic flow graph

### ISSUE THREAD

**Issue by test-dt** [oneapi-src/oneTBB#211]
Hi, this [webpage](https://software.intel.com/en-us/blogs/2011/09/08/the-intel-threading-building-blocks-flow-graph-is-now-fully-supported) mentions that starting from TBB 4.0 the flow graph model can express cyclic messaging graphs. Is there any example to demonstrate how to create a cyclic messaging graph in TBB?

Thanks.

**Comment by aleksei-fedotov** [comment]
Hi,

Sorry for such late response.

For the idea behind cyclic messaging graphs you can read [this page](https://www.threadingbuildingblocks.org/docs/help/hh_goto.htm?index.htm#tbb_userguide/create_token_based_system.html) in TBB documentation.

Please let me know if you need something more to clarify about the topic.

**Comment by aleksei-fedotov** [comment]
Closing the issue as addressed. Please reopen it if you think something is not clear and more info is required.
