### ISSUE TITLE
[doc][site] Old links to TBB documentation from StackOverflow are broken

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#212]
I've noticed that www.threadingbuildingblocks.org effectively disappeared as it is redirected to this GitHub repo. Many StackOverflow answers (like [1](https://stackoverflow.com/a/29727659/2527797) [2](https://stackoverflow.com/a/45986184/2527797) [3](https://stackoverflow.com/a/23437076/2527797) and their comments below like [here](https://stackoverflow.com/a/52082642/2527797)) suffer now having incorrect link to the documentation. Also, the links to official documentation (e.g. https://software.intel.com/en-us/node/506336) are not as self-explanatory as the links to the old TBB web-site (e.g. https://www.threadingbuildingblocks.org/docs/help/reference/task_scheduler/task_arena_cls.html).
Please fix the redirection for sake of internet users looking for answers about TBB.

**Comment by omalyshe** [comment]
Unfortunately, it is not possible to fix the redirection link. If somebody encounters an issue with finding specific documentation topic the team is ready to help.
