### ISSUE TITLE
initialize_cilk_interop keeps on getting called when cilk fails to load.

### ISSUE THREAD

**Issue by GuillaumeSideFX** [oneapi-src/oneTBB#213]
I noticed some suspicious dlopen() calls while profiling my application and I tracked the origin of the calls back to tbb::internal::governor::one_time_init().

void governor::one_time_init() {
    if( !__TBB_InitOnce::initialization_done() )
        DoOneTimeInitializations();
#if __TBB_SURVIVE_THREAD_SWITCH
    atomic_do_once( &initialize_cilk_interop, cilkrts_load_state );
#endif /* __TBB_SURVIVE_THREAD_SWITCH */
}

The line:
atomic_do_once( &initialize_cilk_interop, cilkrts_load_state );
calls atomic_do_once, but initialize_cilk_interop is a function that returns a bool.

There is an overloaded run_initializer in atomic_do_once, and the return value of initialize_cilk_interop is passed to cilkrts_load_state. This means the initialization callback runs all the time if cilk fails to load.

I think turning initialize_cilk_interop into a void callback would be enough to fix the issue.

bool initialize_cilk_interop() {
    // Pinning can fail. This is a normal situation, and means that the current
    // thread does not use cilkrts and consequently does not need interop.
    return dynamic_link( CILKLIB_NAME, CilkLinkTable, 1,  /*handle=*/0, DYNAMIC_LINK_GLOBAL );

//! One-time initialization function
/** /param initializer Pointer to function without arguments
           The variant that returns bool is used for cases when initialization can fail
           and it is OK to continue execution, but the state should be reset so that
           the initialization attempt was repeated the next time.
    /param state Shared state associated with initializer that specifies its
            initialization state. Must be initially set to #uninitialized value
            (e.g. by means of default static zero initialization). **/
template <typename F>
void atomic_do_once ( const F& initializer, atomic<do_once_state>& state ) {
    // tbb::atomic provides necessary acquire and release fences.
    // The loop in the implementation is necessary to avoid race when thread T2
    // that arrived in the middle of initialization attempt by another thread T1
    // has just made initialization possible.
    // In such a case T2 has to rely on T1 to initialize, but T1 may already be past
    // the point where it can recognize the changed conditions.
    while ( state != do_once_executed ) {
        if( state == do_once_uninitialized ) {
            if( state.compare_and_swap( do_once_pending, do_once_uninitialized ) == do_once_uninitialized ) {
                run_initializer( initializer, state );
                break;
            }
        }
        spin_wait_while_eq( state, do_once_pending );
    }
}

// Run the initializer which can not fail
inline void run_initializer( void (*f)(), atomic<do_once_state>& state ) {
    f();
    state = do_once_executed;
}

// Run the initializer which can require repeated call
inline void run_initializer( bool (*f)(), atomic<do_once_state>& state ) {
    state = f() ? do_once_executed : do_once_uninitialized;
}

**Comment by alexey-katranov** [comment]
It is the expected behavior because each new thread should call `initialize_cilk_interop` to be sure that this thread does not related to Intel Cilk Plus runtime. However, Intel Cilk Plus is deprecated and the interop support will be removed from TBB.
