### ISSUE TITLE
third-party-programs.processed.txt should not be in source tarball

### ISSUE THREAD

**Issue by ismail** [oneapi-src/oneTBB#215]
Hi,

This file contains the string

> C Runtime Library (CRT): (c) 2015 Microsoft Corporation.

which should not apply to the TBB source code. At this moment this is blocking the update for openSUSE.

**Comment by tbbdev** [comment]
@ismail thank you for reporting the issue! This section was removed in v2020.2: https://github.com/oneapi-src/oneTBB/blob/v2020.2/third-party-programs.txt
