### ISSUE TITLE
tbbvars script isn`t usable if tbb built in folder with spaces

### ISSUE THREAD

**Issue by dr-pain** [oneapi-src/oneTBB#216]
I see following variables definition in tbbvars:
SET LIB=C:\_E\build\tbb tbb\build\windows_intel64_cl_vc14.1_release;%LIB%
SET PATH=C:\_E\build\tbb tbb\build\windows_intel64_cl_vc14.1_release;%PATH%
Such script can`t be used in some cases - spaces in variables should be shielded.Something like this:
SET "LIB=C:\_E\build\tbb tbb\build\windows_intel64_cl_vc14.1_release;"%LIB%
SET "PATH=C:\_E\build\tbb tbb\build\windows_intel64_cl_vc14.1_release;"%PATH%

**Comment by anton-potapov** [comment]
@dr-pain, as I see from https://github.com/oneapi-src/oneTBB/blob/master/integration/windows/env/vars.bat and https://github.com/oneapi-src/oneTBB/blob/master/integration/windows/env/vars.bat.in quotes are in place. 

Could please confirm that problem is not reproducible with oneTBB?
