### ISSUE TITLE
Android compile

### ISSUE THREAD

**Issue by netcat88** [oneapi-src/oneTBB#219]
Hi,

I'm trying to compile tbb to include it in my Android project for both armeabi-v7a and arm64-v8a architectures.
After positioning my cmd into the jni folder I'm calling the ndk-build but I'm really lost about any option or command I should properly use.
I'm a newbie in this as you can imagine. Can anyone please support me?
I'm using the latest version of tbb and I've installed NDK since version 16.
I've already seen the response from https://github.com/intel/tbb/issues/99 but the command reported there doesn't work or maybe I should set something before ... really I don't know and I would need a clear step-by-step how-to 'cause I'm ignorant :P

Thanks!!

**Comment by islem19** [comment]
make sure you have installed these packages as mentioned in the [release note ](https://github.com/intel/tbb/blob/tbb_2019/doc/Release_Notes.txt) : GCC (min v4.1) and glibc (min v2.4), as mentioned in issue #99 run the following commands: 
`export PATH=$PATH:/path/to/NDK/` 
`ndk-build tbb tbbmalloc arch=arm target=android compiler=clang ndk_version=16 -j -B`
**NOTE**: make sure the ndk-build binary file already exist in your path exported above.

**Comment by bookzhan** [comment]
I used NDK16B to build successfully, NDK download address:
https://dl.google.com/android/repository/android-ndk-r16b-windows-x86_64.zip?hl=zh_cn

**Comment by alexey-katranov** [comment]
@netcat88 , do you need any additional support related to your question?
