### ISSUE TITLE
how to make libtbb.a for android?

### ISSUE THREAD

**Issue by bookzhan** [oneapi-src/oneTBB#221]
Hi, I want to use a static library under Android. How do I build it?

**Comment by bookzhan** [comment]
I found the tbb static library in OpenCV, so I don't have to compile it myself, happy
https://nchc.dl.sourceforge.net/project/opencvlibrary/4.2.0/opencv-4.2.0-android-sdk.zip
![20200311220044](https://user-images.githubusercontent.com/11169519/76425071-15f08900-63e4-11ea-9614-2ae4a7084b28.png)

**Comment by tbbdev** [comment]
@bookzhan, TBB doesn't officially support static library, so there are no instructions how to build it. Feel free to reopen the issue if you have more questions.
