### ISSUE TITLE
No Soft links

### ISSUE THREAD

**Issue by shersoni610** [oneapi-src/oneTBB#224]
Hello,

When I compile the source code I get the following libraries build;

libtbbmalloc_proxy.so    libtbbmalloc.so    libtbb.so
libtbbmalloc_proxy.so.2  libtbbmalloc.so.2  libtbb.so.2

However, I do not see that *.so files are soft linked to *.so.2 files. Do I need to do it manually?

**Comment by AlexVeprev** [comment]
Hi @shersoni610,

It is expected for `*.so` files created during TBB build: they are not links, but linker scripts which contain references to `*.so.2` files, e.g. `libtbb.so` contains `INPUT (libtbb.so.2)`.

Related issue: https://github.com/intel/tbb/issues/98.

**Comment by shersoni610** [comment]
All the comments did not clarify why we need to create links manually.

**Comment by AlexVeprev** [comment]
Linker scripts here are used _instead of_ symbolic links, so you don't need to create them manually.
