### ISSUE TITLE
libdl in LIBS += $(LIBDL) need -pthread

### ISSUE THREAD

**Issue by ghost** [oneapi-src/oneTBB#230]
if you become a error like this:
`g++ -o test_job_automaton.exe -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -DDO_ITT_NOTIFY -DUSE_PTHREAD test_job_automaton.o cache_aligned_allocator_rml.o dynamic_link_rml.o  tbb_misc_rml.o tbb_misc_ex_rml.o -lrt -ldl -Wl,-rpath-link=. -rdynamic 
/usr/bin/ld: test_job_automaton.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: /lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:131: test_job_automaton.exe] Error 1
make: Leaving directory '/repm/src/rpm/BUILD/tbb-2020_U1/python/rml'
error: Bad exit status from /home/quait/src/tmp/rpm-tmp.UXbM4w (%build)

RPM build errors:
    Bad exit status from /home/quait/src/tmp/rpm-tmp.UXbM4w (%build)`

than you can solve with:
`diff a/python/rml/Makefile b/python/rml/Makefile
--- a/python/rml/Makefile
+++ b/python/rml/Makefile
@@ -66,7 +66,7 @@
 else
 TBB_DEP_RML_TEST?= $(RML_ASM.OBJ)
 endif
-LIBS += $(LIBDL)
+LIBS += $(LIBDL) -pthread
 TBB_DEP_RML_TEST =  rml_tbb.$(OBJ) dynamic_link_rml.$(OBJ)
 
 INCLUDES += $(INCLUDE_KEY)$(RML_ROOT)/include $(INCLUDE_KEY).
`

**Comment by ivankochin** [comment]
Hi!
Thanks for reporting.
This issue will be fixed in one of the future releases.

**Comment by ivankochin** [comment]
Hi!
This issue was fixed in the [oneTBB Beta08 release](https://github.com/oneapi-src/oneTBB/tree/onetbb_2021).
