### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by varunagrawal** [oneapi-src/oneTBB#232]
I am new to using TBB (but not software in general), and I noticed just how non-trivial it is to get started due to a lack of a simple document with installation instructions.

A previous commit supposedly had a file called `INSTALL.txt` which is no longer present and the Intel website docs either do not have straightforward installation directions (e.g. it says "after you have installed TBB you need to set up the environment"), or are grossly under-documented (it does not explain that running `source tbbvars.sh` should actually be `source tbbvars.sh intel64` or whatever architecture you are using). I only figured out the latter after reading the shell script, which no newbie should have to do.

It would be really nice to have a simple document in the repo itself that explains the install process especially since many 3rd party providers don't provide the debug versions of the library (neither apt nor pacman have this currently) and Intel recommends testing with the debug version before using the release version, and Intel's download website seems to be bugging out as of writing this. Thus installing from the repo is the only option left in these circumstances.

**Comment by hjmjohnson** [comment]
@varunagrawal This has been a long standing issue. Installing TBB or building from source and setting up a valid environment for build TBB is extremely difficult, hardly documented, and very frustrating.

I have been fighting with the installation process for many years, and to be honest, I have never found a reliable way to build it.  I usually spend several days per year trying to figure out the magic incantation needed to allow building.  I have never succeded in finding a robust way to use TBB in non-trivial applications.  

I would love to use TBB more, but the current build mechanisms prevent wider adoption.

I am not a TBB developer, but I hope my experiences help you make informed decisions.

**Comment by varunagrawal** [comment]
Thanks for your comments @hjmjohnson. My first crack at this problem would be to understand the installation and build scripts for this project (which is another issue is already in progress). My hope is to contribute that documentation as well as a dockerfile to serve as a template for dependencies and install gotchas. Hopefully you and other will find that helpful.

**Comment by AlexVeprev** [comment]
Thanks for raising the issue! The issue is planned to be addressed in one of future [oneTBB](https://github.com/oneapi-src/oneTBB/tree/onetbb_2021) releases.

**Comment by AlexVeprev** [comment]
@varunagrawal, @hjmjohnson using of vars.sh (former tbbvars.sh) scripts is not clearly documented in the repo yet, but I just to highlight that oneTBB has moved to CMake that makes integration much more clear and "standardized". Default branch is not switched to the version with CMake yet, but you can find it in master and onetbb_2021 branches:
https://github.com/oneapi-src/oneTBB/tree/master
https://github.com/oneapi-src/oneTBB/tree/onetbb_2021

**Comment by varunagrawal** [comment]
That's good enough for me. Closing.
