### ISSUE TITLE
Crash in concurrent_unordered_base<>::unsafe_erase()

### ISSUE THREAD

**Issue by os12** [oneapi-src/oneTBB#234]
I am getting a crash on Linux when calling `concurrent_unordered_set::unsafe_erase()`:

```*** SIGSEGV (@0x0) received by PID 28589 (TID 0x7fc046ffd700) from PID 0; stack trace: ***
    @     0x7fc058b10099 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fc05831e730 (unknown)
    @     0x55837d06451d tbb::interface5::internal::flist_iterator<>::operator++()
    @     0x55837d0629ca tbb::interface5::internal::solist_iterator<>::operator++()
    @     0x55837d0607cc tbb::interface5::internal::concurrent_unordered_base<>::internal_distance()
    @     0x55837d05ee15 tbb::interface5::internal::concurrent_unordered_base<>::unsafe_erase()
```

Some notes:
- The concurrent_unordered_set stores raw pointers on this x64-64 machine
- No other thread is accessing that same key at the same time
- The crash is quite easy to reproduce in the Debug build of my application and much harder in the Release
- gcc 8 on Debian: `linux_intel64_gcc_cc8.3.0_libc2.28_kernel4.19.0_debug`
- debug tests pass for TBB

How do I debug this issue? My usage of the set is very basic, just two calls:
```
_set.insert(ptr);
_set.unsafe_erase(ptr);
```

**Comment by alexey-katranov** [comment]
> * No other thread is accessing that same key at the same time

Is it possible that `unsafe_erase(ptr)` can be called within several threads for different keys at the same time?

**Comment by os12** [comment]
> Is it possible that `unsafe_erase(ptr)` can be called within several threads for different keys at the same time?

Absolutely, yes. I am relying on (well, hoping for) the concurrent trait of the `set` to add/remove different keys with no additional locking. Is it not supported?

**Comment by alexey-katranov** [comment]
Unfortunately, the erase operation is not thread safe. See [documentation](https://www.threadingbuildingblocks.org/docs/help/index.htm#reference/containers_overview/concurrent_unordered_map_cls.html):
> The erase and extract methods are prefixed with unsafe_, to indicate that they are not concurrency safe.

If you need concurrent erase, consider using tbb::concurrent_hash_map

**Comment by os12** [comment]
Wow, I thought `unsafe_erase()` was unsafe just w.r.t. another thread reading the same value, which would be very reasonable. Yet the lack of a concurrent erase makes this container useless for my case.

Let me try concurrent_hash_map.

Thanks!

**Comment by os12** [comment]
Hey Alexey, I've just moved the code to `tbb::concurrent_hash_map` and things work well. Thank you for the tip!

Leaving some notes here for posterity:
- The `unsafe_xxxx()` methods in `concurrent_unordered_map` and `concurrent_unordered_set` are completely unsafe and rely on the user to serialize calls (by doing external locking)
- `concurrent_hash_map` is completely thread-safe, yet it imposes a heavy locking mechanism via its "accessor". In my use case that is only about 50% faster than doing PThread locking and then storing data in STL containers. I expect the savings will increase with increased concurrency.

Side note, I wish there was a lighter container that didn't impose the accessor-based protocol. I can implement that myself with a std::shared_ptr as the value when need be. Basically, I need a map/set that provides thread-safe, concurrent and non-blocking `insert()` and `erase()` operations.

**Comment by alexey-katranov** [comment]
> concurrent and non-blocking insert() and erase() operations.

It is a tricky question. In short, there are multiple issues related to the lifetime synchronization. Therefore, `concurrent_hash_map` provides accessor stuff.
