### ISSUE TITLE
errors from sourcing compilervars.sh

### ISSUE THREAD

**Issue by daniel-dsouza** [oneapi-src/oneTBB#244]
Hello all,

This issue applies to the 2020.1.217 binary packages.

# Steps to reproduce

1. install `intel-mkl-64bit-2020.1-102` from the apt repositories
1. source `/opt/intel/bin/compilervars.sh intel64 -platform linux`

# Expected outcome
All variables should be set without errors

# Actual outcome
this error: 

```
ERROR: libtbb.so.2 library does not exist in SUBSTITUTE_INSTALL_DIR_HERE/lib/intel64/gcc4.8.
```

# Workaround
edit `/opt/intel/bin/compilervars.sh` and change

```bash
113 if [ -e "${PROD_DIR}/tbb/bin/tbbvars.sh" ]; then
114     . "${PROD_DIR}/tbb/bin/tbbvars.sh" ${INTEL_TARGET_ARCH} ${INTEL_TARGET_PLATFORM} auto_tbbroot
115 fi
```

to this, adding `auto_tbbroot`

```bash
113 if [ -e "${PROD_DIR}/tbb/bin/tbbvars.sh" ]; then
114     . "${PROD_DIR}/tbb/bin/tbbvars.sh" ${INTEL_TARGET_ARCH} ${INTEL_TARGET_PLATFORM} auto_tbbroot
115 fi
```
The `TBBROOT`variable is not set in `/opt/intel/compilers_and_libraries_2020/linux/tbb/bin/tbbvars.sh` without that flag.

**Comment by tbbdev** [comment]
@daniel-dsouza thank you for reporting the issue! We are investigating it and will come back with results. You've applied the right workaround.

**Comment by daniel-dsouza** [comment]
To the best of my knowledge, `SUBSTITUTE_INSTALL_DIR_HERE` is supposed to be replaced in tbbvars.sh as part of the package installation. However on my system (Ubuntu 18.04), the install process doesn't always work. This bug also appears to affect PSTL.

**Comment by tbbdev** [comment]
@daniel-dsouza the fix was already implemented in 2020.1.**219**. Please try it.

**Comment by daniel-dsouza** [comment]
I'm not seeing 2020.1.219 in the repositories. Below are the versions I am seeing on Ubuntu 18.04.

```
intel-tbb-devel-2020.0-166 - Intel(R) Threading Building Blocks 2020 for Linux*
intel-tbb-devel-2020.2-217 - Intel(R) Threading Building Blocks 2020 Update 2 for Linux*
```

---
response to update: are you referring to 2020.3? If so, I'll keep an eye out for it.

**Comment by tbbdev** [comment]
@daniel-dsouza, we are referring to the next update available in the APT repository. It may be TBB 2020 Update 3 or newer since sometimes we have GitHub-only releases which are not published in the APT repository (for example, TBB 2020 Update 1).

**Comment by leonardotrp** [comment]
I'm using oneAPI version 2021.2.0 on Linux Ubuntu. When running the command `/opt/intel/oneapi/setvars.sh ia32` I'm getting the following error below, but I don't know what I need to do.
```
:: initializing oneAPI environment ...
   compile.sh: BASH_VERSION = 5.0.17(1)-release
:: advisor -- latest
:: ccl -- latest
:: clck -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: inspector -- latest
:: intelpython -- latest
:: ipp -- latest
:: ippcp -- latest
:: ipp -- latest
:: itac -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
ERROR: libtbb.so.12 library does not exist in /opt/intel/oneapi/tbb/2021.2.0/env/../lib/ia32/gcc4.8.
:: vpl -- latest
:: vtune -- latest
:: oneAPI environment initialized ::
```
Is this just a warning, or is it a mandatory feature?

**Comment by AlexVeprev** [comment]
@leonardotrp do you install from official `apt` repositories? I'd recommend you to open a new oneTBB issue to continue discussion, your case looks differently, so it would be better to track it separately.

Meanwhile I'd expect that the original issue with `SUBSTITUTE_INSTALL_DIR_HERE` has been resolved a while ago, @daniel-dsouza have you had a chance to work with newer versions?

**Comment by leonardotrp** [comment]
@AlexVeprev Yes, I installed it through the official repositories, on the Intel website. Thank you for your attention.

**Comment by isaevil** [comment]
@leonardotrp to have oneTBB 32bit version installed on your Ubuntu you need to install 32bit version of package (default version under `intel-basekit` is 64bit).
You can install 32bit version by using these commands:
`sudo dpkg --add-architecture i386`
`sudo apt update`
`sudo apt install intel-basekit-32bit # Or intel-oneapi-tbb-32bit if you need only oneTBB`

**Comment by leonardotrp** [comment]
Thank you all for the attention. We managed to get success using **intel64** even. Big hug.

**Comment by daniel-dsouza** [comment]
Pretty sure this issue has long since been fixed and can be closed.
