### ISSUE TITLE
Stack Size Computation in scheduler.cpp

### ISSUE THREAD

**Issue by felixguendling** [oneapi-src/oneTBB#247]
I am using Clang's undefined behaviour sanitizer on my binaries and it triggers that something is fishy with the stack size computation. Taking a closer look, this can be confirmed. At least, I have some questions regarding the code:

The `stack_size` variable is definitely a positive integer (`size_t`) so it cannot store negative values:
https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/src/tbb/scheduler.cpp#L162

So the check for positivity obviously does not make sense:
https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/src/tbb/scheduler.cpp#L240

The variable is assigned here:
https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/src/tbb/scheduler.cpp#L235

And in my case (Linux), the value would be negative:
```cpp
(gdb) p (char*)stack_base - (char*)stack_limit
$5 = -4260896
```

However, this won't be detected because the corresponding assert is commented out:
https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/src/tbb/scheduler.cpp#L233

From the definition in the comment, this should not happen:
https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/src/tbb/scheduler.cpp#L159-L160

Maybe, it will not crash, but I think this was not intended?

**Comment by nik-ponomarev** [comment]
You can see the comment above the commented assertion that sheds a light on the problem.  Intel(R) Cilk(TM) Plus allocates stack frames on the heap, so the ```stack_limit``` will have incorrect value here (```pthread_attr_getstacksize``` cannot handle it).
It looks like in your case the ```stack_base`` value is either zero or ```stack_limit``` is calculated wrong (higher on the ~4MB (default stack size) then the local stack address variable).

**Comment by felixguendling** [comment]
Would it make sense to use `std::abs` in this line?

https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/src/tbb/scheduler.cpp#L235

Assigning a negative value to a `size_t` should be avoided.

Or would it make sense to chose a reasonable default value in case the computed value did not make sense? This would prevent UB and make Undefined Behaviour Sanitizer happy :-)
