### ISSUE TITLE
Obtain tbb::task_scheduler_init::default_num_threads() after deprecation

### ISSUE THREAD

**Issue by xvallspl** [oneapi-src/oneTBB#248]
Hi,

We are adapting our codebase to the deprecation of task_scheduler_init, but couldn't find a replacement for task_scheduler_init::default_num_threads() . I can't see anything exposed on tbb::task_arena or tbb::global_control, the two classes suggested as replacement.

Is it there a better solution for this than declaring an uninitialized task_arena and calling max_concurrency() on it?

**Comment by alexey-katranov** [comment]
Consider using [`tbb::this_task_arena::max_concurrency`](https://software.intel.com/en-us/node/506359) (it is described almost at the end of the page). 

Thank you for the report, we definitely need to improve the documentation.

**Comment by xvallspl** [comment]
Thanks, @alexey-katranov! I missed that.

Does this mean there's still an implicit task arena? When is it instantiated/initialized? I always assumed it happened when initializing tbb::task_scheduler_init, but it doesn't look like that's the case.

**Comment by xvallspl** [comment]
Thanks, @alexey-katranov! I missed that.

First line of my program: `auto x = tbb::this_task_arena::max_concurrency()`. I guess this_task_arena refers to the implicit (uninitialized?) task arena if not called within an explicit one. Does this mean the scheduler is initialized at this point? If the scheduler is not initialized at this point, when does it initialize? Lazily, f.e. on my first call to task_arena::init or any other function that holds a reference to it?

**Comment by alexey-katranov** [comment]
`tbb::this_task_arena::max_concurrency()` does not initialize an implicit task arena. It is initialized when parallel algorithms are used at first time. Since such task arena is implicitly created for the calling thread, this thread will hold its own reference until thread termination.

**Comment by alexey-katranov** [comment]
@xvallspl , the question seems to be resolved. Feel free to reopen the issue if not.
