### ISSUE TITLE
CMake support files missing from binary oneapi installation

### ISSUE THREAD

**Issue by jeremyong** [oneapi-src/oneTBB#249]
Hi TBB team,

Unless I'm missing something, the cmake files provided in this repo to provide convenient link targets and populate common cmake variables are not found in the oneapi binary installation which makes it difficult to distribute software that depends on TBB. Is the expectation that we should we mirror cmake files in this git repo ourselves?

Thanks

**Comment by AlexVeprev** [comment]
Hi @jeremyong! I assume you mean TBBConfig files, right? If so, could you please clarify which package do you mean?

I checked `oneapi-tbb-2021.1-beta05-lin.tgz` and `oneapi-tbb-2021.1-beta05-win.zip`: TBBConfig files are available under `oneapi-tbb-2021.1-beta05/cmake`.
Probably you're getting failure because of renaming subfolder in the binary archives: `tbb` became `oneapi-tbb-2021.1-beta05`.

Feel free to provide your feedback regarding binary packages for oneTBB, any proposals will be considered.

**Comment by jeremyong** [comment]
@AlexVeprev No I'm not referring to the standalone TBB release but the packaged TBB within the oneAPI base toolkit installer. All cmake files appeared to be missing.

**Comment by AlexVeprev** [comment]
Yes, currently there is no CMake support for TBB in oneAPI toolkits. You asked:

> Is the expectation that we should we mirror cmake files in this git repo ourselves?

Short answer is no. CMake config files are quite specific for each package layout, so TBB uses and provides generators to create these files ([TBBMakeConfig](https://github.com/oneapi-src/oneTBB/tree/tbb_2020/cmake#tbbmakeconfig) and [TBBInstallConfig](https://github.com/oneapi-src/oneTBB/tree/tbb_2020/cmake#tbbinstallconfig)). It is usually done on packaging side, but as a workaround it can be done on customer side if there is a strong demand.

Anyway, thank you for raising this question! I'll investigate how inclusion of CMake integration features in TBB in oneAPI toolkits can be done and come back with results.

**Comment by jeremyong** [comment]
Great thanks, for looking into that. It would be great if shipping binaries supported Cmake as well because it's common to ship code (not binaries) to the enduser that relies on one-api software. I could author cmake files to link against the oneAPI toolkit but this would be brittle if the targets or directory structures change in the future. As such, it's preferable if the cmake files be shipped with the binaries to maintain atomicity.

**Comment by jeremyong** [comment]
Never mind my request, I have unfortunately decided to move on from TBB to an in-house solution. I like many of the ideas of TBB a great deal but the ergonomics of the library are lacking.

**Comment by AlexVeprev** [comment]
@jeremyong, thank you for letting us know about your decision. I've already made some progress regarding this request and plan to continue.
We'd very appreciate if you explain more about lacking ergonomics.
I know [you submitted other issues](https://github.com/oneapi-src/oneTBB/issues?q=author%3Ajeremyong+), do you have something else that prevents you from using TBB? Thank you.

Feel free to use inteltbbdevelopers@intel.com for feedback if it's more suitable for you.
