### ISSUE TITLE
_tbb_windef.h does not support standard _WIN32_WINNT macros

### ISSUE THREAD

**Issue by kenba** [oneapi-src/oneTBB#25]
The file `include\tbb\internal\_tbb_windef.h` uses the `_WIN32_WINNT` macro to ensure that the Windows version supports TBB. See lines 25-29:
```
// Check that the target Windows version has all API calls requried for TBB.
// Do not increase the version in condition beyond 0x0500 without prior discussion!
#if defined(_WIN32_WINNT) && _WIN32_WINNT<0x0501
#error TBB is unable to run on old Windows versions; _WIN32_WINNT must be 0x0501 or greater.
#endif
```
Macros for specific versions of Windows are defined in `SDKDDKVer.h`, see [Using the Windows headers](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383745.aspx).  
It is recommended to use the macros instead of the specific Windows version numbers, e.g.:

    #define _WIN32_WINNT _WIN32_WINNT_WINXP

instead of:

    #define _WIN32_WINNT 0x0501

Also, some libraries require a Windows macro and *not* a Windows version number.  
However, this causes the `tbb` build to fail and line 28 of `include\tbb\internal\_tbb_windef.h` to be output.

It would be good for `tbb` to support the standard macros as well as the Windows version numbers.

Note: MSVC 2017 no longer supports Windows versions older than XP, see: [Modifying WINVER and _WIN32_WINNT](https://docs.microsoft.com/en-gb/cpp/porting/modifying-winver-and-win32-winnt).

**Comment by vladimir-polin** [comment]
Hello, in the article link you have provided there is no requirements to use text macros instead of number. And I do not see such recomendation there. 

--Vladimir

**Comment by kenba** [comment]
Hello, you are correct, the Microsoft articles I linked are vague when it comes to recommending the macros. However, using the macros is recommended elsewhere because it makes code much clearer than using "magic" numbers like `0x0501`...

The standard Microsoft macros can be supported by just adding the following line to `include\tbb\internal\_tbb_windef.h`:

    #include <sdkddkver.h>

In which case lines 27-29 of  `include\tbb\internal\_tbb_windef.h` could then be changed to the clearer:

    #if defined(_WIN32_WINNT) && _WIN32_WINNT<_WIN32_WINNT_WINXP
    #error TBB is unable to run on old Windows versions; _WIN32_WINNT must be _WIN32_WINNT_WINXP or newer.
    #endif

instead of:

    #if defined(_WIN32_WINNT) && _WIN32_WINNT<0x0501
    #error TBB is unable to run on old Windows versions; _WIN32_WINNT must be 0x0501 or greater.
    #endif

Note: `sdkddkver.h` is the name of the file on my filesystem, not `SDKDDKVer.h`  as per the Microsoft documentation, in case of a case sensitive compiler...

**Comment by vladimir-polin** [comment]
Hello,

If you look at the TBB build system there are a few places where _WIN32_WINNT is defined. And since it is defined outside of sources there can't bew used lexical macro. So in my opinion mixing text and number for the same macro in the same code is not very gracefully from engineering practices prospective. but of course, it is discussible:) 

--Vladimir

**Comment by kenba** [comment]
Hello Vladimir,

I've just searched through the TBB source code and seen places where `_WIN32_WINNT` is both used and redefined. I agree that it's not graceful from engineering practices prospective, but then neither is using macros in the first place... You can debate whether to fix this issue with your management.

My issue is that valid code won't build because `_WIN32_WINNT`  is defined as `_WIN32_WINNT_WIN10`  for clarity.

It can be fixed by simply adding `#include <sdkddkver.h>` to `include\tbb\internal\_tbb_windef.h` prior to the test for `_WIN32_WINNT`.

Best regards
Ken

**Comment by alexey-katranov** [comment]
If the issue is still relevant, feel free to reopen it.
