### ISSUE TITLE
`tbb::parallel_for_each` (and others) should throw if it is canceled, not quietly exit prematurely

### ISSUE THREAD

**Issue by BenFrantzDale** [oneapi-src/oneTBB#253]
I posted this a bit ago on SO, but I see this fundamentally as a bug so I'll reproduce it here: https://stackoverflow.com/questions/59846340/tbbparallel-for-each-not-executing-while-canceling

I'm running `tbb::parallel_for_each` deep within a `task_group`. The `task_group` is being canceled and that causes `tbb::parallel_for_each` to exit without satisfying its postcondition. Here's minimal test case:
```
tbb::task_group g;
std::vector<int> x { 0, 0, 0, 0 };
std::atomic<std::size_t> counter {0};
g.run([&x, &counter]() {
    std::cout << "in run()\n" << std::flush;
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    std::cout << "in run(): slept\n" << std::flush;
    assert(tbb::task::self().is_cancelled());

    tbb::parallel_for_each(x, [&counter](int& y) {
        std::cout << "in run(): in parallel_for_each\n" << std::flush;
        ++y;
        ++counter;
    });
    assert(counter == x.size());
});
std::cout << "canceling\n" << std::flush;
g.cancel();
std::cout << "canceled " << g.is_canceling() << " " << tbb::task::self().is_cancelled() << std::endl;
assert(g.is_canceling());
std::cout << "canceled " << g.is_canceling() << " " << tbb::task::self().is_cancelled() << std::endl;
g.wait();
std::cout << "canceled " << g.is_canceling() << " " << tbb::task::self().is_cancelled() << std::endl;
```
That is: It has tbb::task_group call run on a function that waits for 0.1 s, then loops over a vector. It counts how many iterations that loop does. It then cancel()s the task group. The output is
```
canceling
in run()
canceled 1 0
canceled 1 0
in run(): slept
Assertion failed: (counter == x.size()), function operator(), file test.cpp
```
My mental model is that it's `tbb::parallel_for_each`'s job to either do what it's told, or throw an exception. I would be OK with having to check `tbb::task::self().is_cancelled()` to see if I should be bailing out. But the sane thing would be for the doomed call to `tbb::parallel_for_each` to throw an exception, which would be caught by the tbb code executing the task group, giving the following output (I think):
```
canceling
in run()
canceled 1 0
canceled 1 0
in run(): slept
canceled 1 0
```

**Comment by alexey-katranov** [comment]
The cancellation is propagated to all nested algorithms. So, when you cancel `task_group`, the nested `parallel_for_each` is also cancelled.
If you do not want nested parallelism to be cancelled, consider using an explicit `task_group_context` with `relatation_with_parent` (the first ctor argument) as `isolated` (https://software.intel.com/en-us/node/506312).

**Comment by BenFrantzDale** [comment]
@alexey-katranov i do want nested parallelism to be canceled, but I consider it to be an exception for an algorithm to be canceled “out from under” nested code. After all, the nested code dissent necessarily know it’s nested. So it seems like right now I need to always check the cancelation status after every parallel algorithm since otherwise it could have completed abnormally without doing what I asked. Instead, it could throw an exception, which would make my example Just Work.

**Comment by alexey-katranov** [comment]
TBB does not throw exceptions in case of cancellation. It is works in opposite order, if exception is observed from the user code, the TBB algorithm will be cancelled.
 So, if you want to get an exception if the nested algorithm has cancelled (because outer algorithm has cancelled) you can add a check after the nested construction, e.g.
```
g.run([] {
    tbb::parallel_for_each(...);
    if  (tbb::task::self().is_cancelled()) {
        throw <nested_algorithm_cancelled>
    }
}

**Comment by BenFrantzDale** [comment]
@alexey-katranov I understand. But consider the example in the tutorial https://www.threadingbuildingblocks.org/tutorial-intel-tbb-task-based-programming:
```
    using namespace tbb;
    
    int Fib(int n) {
        if( n<2 ) {
            return n;
        } else {
            int x, y;
            task_group g;
            g.run([&]{x=Fib(n-1);}); // spawn a task
            g.run([&]{y=Fib(n-2);}); // spawn another task
            g.wait();                // wait for both tasks to complete
            return x+y;
        }
    }
 ```
Suppose I do
```
int foo(int n) {
    if (n <= 0 || 5 < n) { return -1; }
    constexpr int x[] = { -1, 1, 2, 3, -1, 5 , -1, -1, 8, -1 };
    return x[Fib(n)];
}
```
While `foo` is a stupid function, it looks correct. But the above is undefined behavior because `Fib` could return anything and then overrun the array, because the task context could be canceled, causing `Fib(2)` to evaluate `int x, y; return x+y;`. I find this deeply troubling that a simple example does not behave correctly. Does this concern make sense?

**Comment by alexey-katranov** [comment]
Such examples are impossible to implement without exceptions. As I understand you want to trigger exception (cancellation) externally. TBB does not provide such capability but it can be implemented if you add a check after the wait:
```
    int Fib(int n) {
        if( n<2 ) {
            return n;
        } else {
            int x, y;
            task_group g;
            g.run([&]{x=Fib(n-1);}); // spawn a task
            g.run([&]{y=Fib(n-2);}); // spawn another task
            //g.wait();                // wait for both tasks to complete  // ---
            if  (g.wait()==tbb::canceled)) {                               // +++
                throw <algorithm_is_cancelled>                             // +++
            }                                                              // +++
            return x+y;
        }
    }

**Comment by BenFrantzDale** [comment]
That’s right. I consider the fact that `wait()` doesn’t throw an exception to be a bug in that it is hostile to writing concise correct code, illustrated by the fact that the documentation’s `task_group` example can return an unspecified result if it’s called from within a canceled context.

It sounds like you are saying if I want this behavior I should wrap `task_group` myself.

**Comment by BenFrantzDale** [comment]
For reference, the `TaskGroup` wrapper class shown here: https://godbolt.org/z/Ex1obr is what I have in mind.

**Comment by alexey-katranov** [comment]
Yes, it seems correct. Are you interested only in `task_group` or other parallel algorithm as well?

**Comment by BenFrantzDale** [comment]
I'm interested in all of them. I feel like a function that cannot do its thing must throw (or maybe have a `[[nodiscard]]` return value, but that forces us to clutter everything with error handling).

**Comment by BenFrantzDale** [comment]
I'm closing this because it would be a major change. I may wrap our own calls to the tbb algorithms to check cancelation.

**Comment by stgatilov** [comment]
We have various algorithms, some of them are parallel, some of them call each other. And the user may cancel an algorithm at any moment, which is implemented via throwing an exception. This TBB issue means that our algorithms may crash on cancel.

I always thought that TBB is composable and exception-safe, but in my opinion this issue breaks at least one of these promises.

I guess we'll have to wrap the whole TBB to workaround this issue.

**Comment by dnmokhov** [comment]
Please see https://uxlfoundation.github.io/oneTBB/main/tbb_userguide/Cancellation_Without_An_Exception.html, which might be helpful.
