### ISSUE TITLE
common.inc should not clear `MAKEOVERRIDES`

### ISSUE THREAD

**Issue by MikeWeller** [oneapi-src/oneTBB#256]
The `MAKEOVERRIDES` variable is cleared in common.inc here:

https://github.com/oneapi-src/oneTBB/blob/60b7d0a78f8910976678ba63a19fdaee22c0ef65/build/common.inc#L159-L170

The comment suggests this allows command-line overrides to propagate to sub-make commands (i.e. `$(MAKE)` commands). However, this is the *opposite* of what the flag does. Clearing it disables the propagation of variable overrides to sub-make commands (see documentation at https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html).

In my case I'm trying to override `DEBUG_SUFFIX` to remove the `_debug` suffix from the built products in debug configurations, but I am unable to do this unless I remove these lines.  Note that explicitly exported variables will still be propagated even if this is removed (https://www.gnu.org/software/make/manual/html_node/Variables_002fRecursion.html) so I don't see any reason to keep these lines.

Unless anyone knows the reasoning here I would like to put in a PR to remove this.

**Comment by alexey-katranov** [comment]
AFAIR, `MAKEOVERRIDES =` was used to support offload configuration for Intel(R) Xeon Phi(tm). There was a complicated logic with environment variables (unfortunately, I do not remember all the logic). I suppose it is not needed any more but it should be checked that some other platforms did not start to rely on this behavior.

**Comment by alexey-katranov** [comment]
The issue will not be fixed because we migrated on CMake. If you have any additional questions, feel free to reopen the issue.
