### ISSUE TITLE
Allow tbb::task_group to work with callbacks from non-tbb threads

### ISSUE THREAD

**Issue by Dr15Jones** [oneapi-src/oneTBB#259]
The application I work on (https://github.com/cms-sw/cmssw) uses TBB to do our task scheduling. We have a mechanism using the tbb::task API to allow tbb::tasks to be enqueued from non-TBB threads. This is useful when dealing with GPUs or for sending work to a remote process. With the deprecation of the tbb::task APIs, I have been exploring how to achieve the same goal using tbb::task_group. The three strategies I've found are demonstrated here

https://github.com/Dr15Jones/test_tbb_group

One of the strategies involved extending tbb::task_group to include a helper class to allow tbb::task_group::wait to only exit if all tasks for the group have finished and all instances of the helper have been destroyed. I have a commit in my own fork of oneTBB which implements the helper

https://github.com/Dr15Jones/oneTBB/commit/9ca7e0dada1b9846930f9495c86b398b046dbcfa

My question is what is the TBB developer's prefered way to accomplish this goal?

**Comment by alexey-katranov** [comment]
I've looked through the examples. Thank you for the detailed description.
1. It seems that direct reference count manipulation of `task_group` can solve your problem. In other words, the start task adds additional reference, the callback task removes the additional reference.
2. Have you considered [resumable tasks](https://software.intel.com/en-us/node/841361) for the asynchronous activities?
3. It is not elegant solution but you can use flow graph just to run tasks (not to describe the dependencies). To run the tasks you can create a `function_node` (e.g. pass `std::function` as a message). To run asynchronous tasks you can create an [async_node](https://software.intel.com/en-us/node/589743). The flow graph aggregates `arena` and `task_group` approaches as well as explicit reference count manipulation (`async_node::gateway_type::reserve_wait` and `async_node::gateway_type::release_wait`)

As I understand, you do not need enqueue tasks rather than mechanism to return a task to a particular arena?

**Comment by Dr15Jones** [comment]
I apologize for not replying earlier.

> 1. It seems that direct reference count manipulation of `task_group` can solve your problem. In other words, the start task adds additional reference, the callback task removes the additional reference.

That would definitely work. The only reason I suggested using RAII is it might be less likely to accidently cause the task_group to never finish waiting if one is not manually incrementing and decrementing the count.

> 2. Have you considered [resumable tasks](https://software.intel.com/en-us/node/841361) for the asynchronous activities?

I had not looked at it before. I do not believe we would want to use that functionality as we have in the past seen performance problems using a tbb::for_loop within a tbb::task and the tbb::for_loop does task stealing on the waiting thread. The problem is the stolen task may have a very long execution time which delays the second part of the 'waiting' task from being able to proceed. To alleviate that particular case we had to use task isolation. Our actual best solution was to allow asynchronous callbacks so that when the working tasks finish they can launch a new task on any available thread to finish the work. [The GPU ability is just an extension of that callback mechanism where the callback isn't guaranteed to be from a TBB controlled thread].

> 3. It is not elegant solution but you can use flow graph just to run tasks (not to describe the dependencies). To run the tasks you can create a `function_node` (e.g. pass `std::function` as a message). To run asynchronous tasks you can create an [async_node](https://software.intel.com/en-us/node/589743). The flow graph aggregates `arena` and `task_group` approaches as well as explicit reference count manipulation (`async_node::gateway_type::reserve_wait` and `async_node::gateway_type::release_wait`)
> 
I have not looked into that but I can give it a try and report back. It would be nice to have something 'elegant' :).

> As I understand, you do not need enqueue tasks rather than mechanism to return a task to a particular arena?

That would be even better, yes.

**Comment by anton-potapov** [comment]
@Dr15Jones  It seems that recently added deferred tasks of a task_group ([task_group::defer](https://software.intel.com/content/www/us/en/develop/documentation/onetbb-documentation/top/onetbb-api-reference/task-group-extensions.html)) is perfect match for your goal.  

Here is the migration guide chapter with pseudo code with all the needed pieces of the puzzle : [Deferred task creation](https://software.intel.com/content/www/us/en/develop/documentation/onetbb-documentation/top/onetbb-developer-guide/migrating-from-threading-building-blocks-tbb/migrating-from-low-level-task-api.html#migrating-from-low-level-task-api_deferred-task-creation)

**Comment by anton-potapov** [comment]
@Dr15Jones, this functionality is added into upcoming version (1.2) of [oneAPI specification ](https://oneapi-src.github.io/oneAPI-spec/elements/oneTBB/source/task_scheduler/task_group/task_group_cls.html). Once the spec is finally released/approved - which I believe should happen soon - oneTBB is to catch up and move this functionality from [preview feature](https://oneapi-src.github.io/oneTBB/reference/reference.html) to implementation of the spec. 

N.B.  [Scheduler Bypass](https://oneapi-src.github.io/oneTBB/tbb_userguide/Migration_Guide/Task_API.html#scheduler-bypass) is not a part of the Spec, at least for now.

**Comment by anton-potapov** [comment]
@Dr15Jones,   [spec is out](https://github.com/oneapi-src/oneAPI-spec/releases/tag/oneapi-v1.1-rev-1).

**Comment by Dr15Jones** [comment]
@anton-potapov thanks!
