### ISSUE TITLE
The source code in released package are not match the pdb and dll

### ISSUE THREAD

**Issue by wingfiring** [oneapi-src/oneTBB#260]
Checked custom_scheduler.h, arena.cpp in both 2019_U1 and 2019_U6, none of them privides matched PDB and source code.
Hope this can be fixed, or at least fixed in the future releases

**Comment by AlexVeprev** [comment]
@wingfiring could you please provide some clarifications?

Do you mean [2019_U6](https://github.com/oneapi-src/oneTBB/tree/2019_U6) code doesn't match with [2019_U6/tbb2019_20190410oss_win.zip](https://github.com/oneapi-src/oneTBB/releases/download/2019_U6/tbb2019_20190410oss_win.zip)? And the same for 2020_U1.
How did you check matching?

**Comment by anton-potapov** [comment]
@wingfiring please reopen if this is still applicable to [oneTBB 2021.4](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.4.0)
