### ISSUE TITLE
how do I install it to the system?

### ISSUE THREAD

**Issue by AndreV84** [oneapi-src/oneTBB#262]
```
/oneTBB-2020.3$ sudo make install
make: *** No rule to make target 'install'.  Stop.
```

**Comment by AlexVeprev** [comment]
Please take a look at the following issues: #175, #222, #232.

Short answer is: currently installation via `make install` is not supported, but it is planned to be addressed in future releases with migration to CMake.

**Comment by AndreV84** [comment]
how do I get it installed?
what solution for installing of the TBB do you suggest?
However, thank you for following up!

**Comment by AndreV84** [comment]
May I know how to install TBB to the system, please?

**Comment by AlexVeprev** [comment]
Are you interested in installation of TBB which is built from sources? If yes, then currently there is no official system installation. You can build TBB and source tbbvars script (generated in build directory). So you'll have TBB available in your environment.
Otherwise you can consider installing TBB from official [Conda](https://anaconda.org/intel/tbb-devel)/[APT](https://software.intel.com/content/www/us/en/develop/articles/installing-intel-free-libs-and-python-apt-repo.html)/[YUM](https://software.intel.com/content/www/us/en/develop/articles/installing-intel-free-libs-and-python-yum-repo.html) repositories or from any other repositories.

Build and installation from sources will be better supported after migration to CMake build system.

Could you please provide details about your use case? Maybe I'll be able to advise smth more specific.

**Comment by AndreV84** [comment]
@AlexVeprev 
Thank you for your response!
source method should work.
My concern was to get numba installed;
it wouldhn't bvuild without the latest TBB: https://github.com/numba/numba/issues/5998#issuecomment-659961074
numba seems required as a component for nvidia IsaaC SDK "sight" to work e.g. with realsense d435: https://github.com/IntelRealSense/realsense-ros/issues/1287#issuecomment-660858936

**Comment by AndreV84** [comment]
where exactly is the tbbvars script in the build folder?
```
/oneTBB-2020.3/build$ ls
AIX.gcc.inc                detect.js                                                 macos.gcc.inc          SunOS.inc
AIX.inc                    FreeBSD.clang.inc                                         macos.icc.inc          SunOS.suncc.inc
android.clang.inc          FreeBSD.gcc.inc                                           macos.inc              test_launcher.bat
android.gcc.inc            FreeBSD.inc                                               Makefile.rml           test_launcher.sh
android.icc.inc            generate_tbbvars.bat                                      Makefile.tbb           version_info_aix.sh
android.inc                generate_tbbvars.sh                                       Makefile.tbbbind       version_info_android.sh
android.linux.inc          index.html                                                Makefile.tbbmalloc     version_info_linux.sh
android.linux.launcher.sh  ios.clang.inc                                             Makefile.tbbproxy      version_info_macos.sh
android.macos.inc          ios.macos.inc                                             Makefile.test          version_info_sunos.sh
android.windows.inc        linux_aarch64_gcc_cc7.5.0_libc2.27_kernel4.9.140_release  mic.icc.inc            version_info_windows.js
big_iron.inc               linux.clang.inc                                           mic.linux.inc          vs2013
BSD.clang.inc              linux.gcc.inc                                             mic.linux.launcher.sh  windows.cl.inc
BSD.inc                    linux.icc.inc                                             mic.offload.inc        windows.gcc.inc
build.py                   linux.inc                                                 OpenBSD.clang.inc      windows.icl.inc
codecov.txt                linux.pathcc.inc                                          OpenBSD.inc            windows.inc
common.inc                 linux.xl.inc                                              suncc.map.pause
common_rules.inc           macos.clang.inc                                           SunOS.gcc.inc

```

**Comment by AndreV84** [comment]
the apt has obsolete version that doesn't match the latest numba requirements

**Comment by AlexVeprev** [comment]
tbbvars should be in `linux_aarch64_gcc_cc7.5.0_libc2.27_kernel4.9.140_release` in your case

**Comment by AndreV84** [comment]
thank you for the update!

**Comment by notld** [comment]
Is anyone able to make a wheel similar to https://pypi.org/project/tbb/#files 

for windows?

**Comment by AlexVeprev** [comment]
Closing the issue as the original question is resolved.
BTW, oneTBB has moved to CMake that makes integration/installation much more clear and "standardized". Default branch has not been switched to the version with CMake yet, but you can find it in master and onetbb_2021 branches:
https://github.com/oneapi-src/oneTBB/tree/master
https://github.com/oneapi-src/oneTBB/tree/onetbb_2021

README for new build system: https://github.com/oneapi-src/oneTBB/blob/master/cmake/README.md

@notld please create a separate issue for your question (if it is still actual) as it is out of scope of this issue.
