### ISSUE TITLE
TBB requirement for Centos

### ISSUE THREAD

**Issue by TylerGubala** [oneapi-src/oneTBB#266]
When trying to work with OpenVDB on Centos, I am a little confused as to what the requirement is for TBB.

I am using OpenVDB to build Blender as a Python module to provide users `wheel` files to install Blender as a Python module. In Linux I need to make a `manylinux` `wheel` file. To achieve this I have to use an older version of Centos, circa 2010-2014.

When installing the `tbb-devel` package through `yum`, I get the version `4.1` on the 2014 manylinux image and `2.2` on the 2010 manylinux image.

However, OpenVDB seems to want a version newer than `2017.1`? The latest version I see on the [downloads page for opentbb](https://github.com/oneapi-src/oneTBB/blob/master/download.md) is `4.3`.

How do I go about getting the 2017.1 version?

Thanks for any help in advance.

**Comment by alexey-katranov** [comment]
All recent release are available on [the release page](https://github.com/oneapi-src/oneTBB/releases). You might want to download the latest release 2020 U3  (it is backward compatible with all previous versions (incl. 2017.1). If you want to download exactly 2017.1: https://github.com/oneapi-src/oneTBB/releases?after=2017_U2

**Comment by TylerGubala** [comment]
@alexey-katranov  Thank you for the suggestion.

After I download it is installation as simple as extracting to a known location, for instance `/usr/local/lib`?

I don't see an `install.sh` after downloading it.

Apologies if this is documented; my Google skills must be waning because I can't find what the next step would be after downloading.

Thank you in advance for the help!

**Comment by alexey-katranov** [comment]
There is not install option in the TBB package, the script (in the `bin` directory) to setup environment is available. Also some cmake integration is available in the `cmake` directory. Or you can manually copy the libraries to the required path.

**Comment by TylerGubala** [comment]
@alexey-katranov Thank you, with that guidance I have most of the TBB configuration set up. I think I will seek out the remaining configuration through the OpenVDB team. 

Thanks again!
