### ISSUE TITLE
TBB Thread oversubscription without use of task_scheduler_init

### ISSUE THREAD

**Issue by Dr15Jones** [oneapi-src/oneTBB#269]
We have often found that for testing it is quite useful to oversubscribe the machine and have TBB tasks that just do a `sleep`. I also know that for others in my field they depend on being able to oversubscribe the TBB threads because they are doing blocking waits inside TBB tasks.

When doing tests after removing the use of the deprecated `tbb::task_scheduler_init` I could find no way to oversubscribe the system. Is there such a way using only the approved TBB APIs?

**Comment by Dr15Jones** [comment]
Here is my simple test program to check for the ability to oversubscribe the threads to cores:

```C++
#include "tbb/global_control.h"
#include "tbb/task_scheduler_init.h"
#include "tbb/task_group.h"
#include "tbb/task_arena.h"
#include <thread>
#include <chrono>
#include <atomic>
#include <iostream>

int main() {

  auto nThreads = tbb::this_task_arena::max_concurrency();

  std::atomic<int> count{0};
  std::atomic<int> maxCount{0};

  tbb::global_control control(tbb::global_control::max_allowed_parallelism, nThreads+2);

  //comment these out individually or together to see behavior change                                                                                                                                                                       
  tbb::task_scheduler_init s( nThreads+2);
  tbb::task_arena arena(nThreads+2);

  tbb::task_group g;
  for(int i; i< nThreads+4; ++i) {
    g.run([&count,&maxCount]() {
        auto v = ++count;
        auto m = maxCount.load();
        while( v > m) {
          maxCount.compare_exchange_strong(m, count);
        }
        std::this_thread::sleep_for(std::chrono::seconds(10));
        --count;
      });
  }
  g.wait();

  std::cout <<"max count "<<maxCount.load()<<" overcommit: "<<nThreads+2<<std::endl;
}
```

**Comment by Dr15Jones** [comment]
@makortel FYI

**Comment by alexey-katranov** [comment]
To tell the truth, we never consider oversubscription as user intention (usually, oversubscription is not the best choice for performance). Currently, there is no possibility to oversubscribe the implicit arena bound to the main thread. In your example, you can wrap `g.run` and `g.wait` into `arena.execute` call to get more threads (the task_arena created on the stack does not affect the implicit arena). Does the explicit arena work for you or do you want to change the behavior of the implicit arena?
As you know, it is not recommended doing blocking waits inside TBB tasks. I'd recommend considering `async_node`, resumable tasks or other techniques not to block the worker threads.

**Comment by Dr15Jones** [comment]
@alexey-katranov thanks for catching my error with not actually using the arena on the stack in the example. I see that when I do use the explicit arena I can oversubscribe. 

> Does the explicit arena work for you or do you want to change the behavior of the implicit arena?

In principal I could most likely make that work (everwhere I do a 'top level' wait on the main thread of the application I could do the `arena.execute`). It would be nice if we had a way to make the implicit arena also be able to handle oversubscription in addition to undersubscription (which we can do now with `tbb::global_control`).

**Comment by Dr15Jones** [comment]
I was able to make the explicit arena work so this issue can be closed if you wish.

**Comment by alexey-katranov** [comment]
> I was able to make the explicit arena work

Great! 

Let's remain the issue open until we decide if such interface (to affect implicit arena) is really needed or such use case is complicated and it is acceptable to use explicit `task_arena`s. Do you have any thoughts about the necessity of API to affect implicit arenas?

**Comment by pavelkumbrasev** [comment]
Hi @Dr15Jones is this issue still relevant? Are you ok to use explicit task_arena for oversubscription tests? To my mind task_arena is direct API for such stuff.

**Comment by Dr15Jones** [comment]
The use of task_arena for oversubscribtion has worked just fine.
