### ISSUE TITLE
Cannot use input_node, missing flow_control function

### ISSUE THREAD

**Issue by nlw0** [oneapi-src/oneTBB#270]
I cannot build this example code:
https://software.intel.com/content/www/us/en/develop/documentation/tbb-documentation/top/intel-threading-building-blocks-developer-guide/parallelizing-data-flow-and-dependence-graphs/flow-graph-tips-and-tricks/flow-graph-tips-on-making-edges/using-sourcenode.html

It seems `input_node` requires the Body object to implement a function that takes a `flow_control`. Am i missing something or is this a bug?

**Comment by alexey-katranov** [comment]
The example is really broken. It seems the documentation was not updated correctly for the `input_node`. It should be something like
```
    const int limit = 10;
    int count = 0;
    tbb::flow::graph g;
    tbb::flow::input_node<int> src(g, [&](tbb::flow_control& fc) -> int {
        if (count < limit) {
            return ++count;
        }
        fc.stop();
        return {};
    });
    src.activate();

    tbb::flow::function_node<int, int> func1(g, 1, [](int i) -> int {
        std::cout << i << "\n";
        return i;
    });
    tbb::flow::function_node<int, int> func2(g, 1, [](int i) -> int {
        std::cout << i << "\n";
        return i;
    });

    make_edge(func1, func2);
    make_edge(src, func1);

    g.wait_for_all();
```

**Comment by alexey-katranov** [comment]
The documentation was significantly reworked for oneTBB. The Body of `input_node` should satisfy [the `InputNodeBody` requirements](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/named_requirements/flow_graph/input_node_body.html). There is no such example any more: https://spec.oneapi.com/versions/latest/elements/oneTBB/source/flow_graph/input_node_cls.html

If you still have any issues, feel free to reopen the issue.
