### ISSUE TITLE
CMake: misused variables from top level project

### ISSUE THREAD

**Issue by AlexVeprev** [oneapi-src/oneTBB#271]
@arihannu found multiple CMake-related issues in scope of #207.
I'm moving them into separate issues for better tracking:

- [CMakeLists.txt#L190](https://github.com/oneapi-src/oneTBB/blob/onetbb_2021/CMakeLists.txt#L190) and other install instructions: `CMAKE_PROJECT_NAME` should be replaced with `PROJECT_NAME`.
- [cmake/vars_utils.cmake#L25](https://github.com/oneapi-src/oneTBB/blob/onetbb_2021/cmake/vars_utils.cmake#L25) and other instructions in this file: paths should be built based on `CMAKE_CURRENT_SOURCE_DIR` instead of `CMAKE_SOURCE_DIR`.

**Comment by AlexVeprev** [comment]
@arihannu the issue should be addressed with a recent commit to [master](https://github.com/oneapi-src/oneTBB/blob/master/CMakeLists.txt#L206) branch. Could you please check if it works for you?

**Comment by arihannu** [comment]
@AlexVeprev Hi, just tried master branch and CMake configuration and build passed without problems. Are you going to include these fixes into an official branch or should I just use master branch from now on?

**Comment by AlexVeprev** [comment]
@arihannu, thank you for the verification! The fix should be available in onetbb_2021 with the next release (unfortunately I can't provide timeline for now). Generally the master branch should be updated more frequently than onetbb_2021. If you prefer to use official releases you can rely on onetbb_2021 and/or on tags v2021..., otherwise use master for the most recent sources.

**Comment by arihannu** [comment]
@AlexVeprev  Then I think this issue can be closed. Thanks for the support.
