### ISSUE TITLE
Add Clang+LLD MinGW toolchain support

### ISSUE THREAD

**Issue by longnguyen2004** [oneapi-src/oneTBB#275]
As LLD doesn't support version scripts in the MinGW frontend, we can't use the existing gcc ".def" file. We could use the MSVC style .def file, and replace the MSVC names with GNU names.

**Comment by alexey-katranov** [comment]
Currently, oneTBB uses CMake instead of Makefiles. Is the question still actual?

**Comment by longnguyen2004** [comment]
It still is. The GNU config still uses version scripts, which on Windows will only work with binutils ld, not LLVM lld. I can try to make a pull request though, it should only requires some copy pasting between the files.

**Comment by alexey-katranov** [comment]
> I can try to make a pull request though

It would be great.

**Comment by longnguyen2004** [comment]
It'd also be nice if we can decorate the code with the proper export keyword (`__declspec(dllexport)` on Windows, `__attribute__ ((visibility ("default")))` on Linux), but if there's a reason to use the current system then I understand.

**Comment by anton-potapov** [comment]
@longnguyen2004 , is this covered by #351 ?

**Comment by longnguyen2004** [comment]
Ah yes, I forgot to close this issue, thanks for notifying me.
