### ISSUE TITLE
Is it me or are there no instructions on how to compile TBB?

### ISSUE THREAD

**Issue by seanm** [oneapi-src/oneTBB#277]
I managed to figure out building the 2019 version, but the 2020 version seems to build only as release, a change in the behaviour of the 2019 version, which built debug & release.

So I though I'd look at build instructions, but couldn't find any.  Where are they?

Also, how does one build the 2020 version as debug?

Thanks.

**Comment by no-ponomarev** [comment]
Passing ``cfg=debug`` to the makefile command should build the debug version of the library.

**Comment by alexey-katranov** [comment]
@no-ponomarev ,
> Passing cfg=debug to the makefile command should build the debug version of the library.

It will not work with the recent changes when the debug build support was removed from top level makefile.

@seanm,
Consider the build instructions: https://github.com/oneapi-src/oneTBB/blob/tbb_2020/build/index.html#L112-L115
You can use src/makefile to build the debug version.

**Comment by seanm** [comment]
@alexey-katranov thanks for that link.  Somehow I did not find it myself. :(  I have it working now.

If I may ask a related question.  Is it possible to specify an exact compiler to use?  I see the `make compiler={icl, icc, gcc, clang}` option, but I have many different versions of clang installed... is it possible to provide a path to the compiler I want to use?

**Comment by alexey-katranov** [comment]
I do not remember if it works: you can try to set the full compiler path to the `CXX` variable (perhaps, you still need to set `compiler` to `clang`)

**Comment by seanm** [comment]
That works, thanks.
