### ISSUE TITLE
How to reduce cpu-usage when I apply TBB's flow_graph

### ISSUE THREAD

**Issue by Shaquille-Wu** [oneapi-src/oneTBB#278]
I applied intel TBB's flow_graph(TBB version is tbb_2020_v3) into my project in android platform(ARMv8).
I found its cpu-usage is higher than previous version.
cpu-usage of non_flow_graph version is about 20%, and the flow_graph version is about 32%.
sum of nodes' computation time cost is very similar with previous, non_flow_graph version and flow_graph version are almost the same.
there are 20+ nodes in my project(I guess there are 20+ threads), and, they are serial, instead of concurrent. so, I think its cpu-usage should be the same as non_flow_graph version.
Unfortunately， they are not the same.
I guess the context switch is frequent if the task_schedule's frequency is high, and then, the cpu-usage will be high. Is there any guys would tell me my guess is right or wrong?
so, I change the graph's priority as "priority_low" through TBB's interface, unfortunately, the result is the same as before.
TBB's code about task_schedule in user-space is very difficult for me, I cannot understand its principle and the detail logic, so, I don't know how to modify the time unit(or say: task's timeslice).
I know we just can specify the task's timeslice in kernel-space, so, I just can specify the thread's priority in user-space as above, but the result is useless.
I just want to reduce the cpu-usage, is there any expert would tell me how to do?

**Comment by aleksei-fedotov** [comment]
> cpu-usage of non_flow_graph version is about 20%, and the flow_graph version is about 32%.

To answer this we need more details about the application and the difference about how TBB is used in non-flow graph and flow graph versions.

> there are 20+ nodes in my project(I guess there are 20+ threads)

Why do you think so? Just to be clear, the number of nodes has nothing to do with the number of threads TBB creates. Usually, the number of threads is equal to the number of software execution units OS provides minus one. E.g. on four core processor with HT enabled TBB creates seven servicing threads.

> I just want to reduce the cpu-usage

Assuming each node executes large portion of serial work so that servicing threads are able to fall asleep and once next node starts its execution servicing threads wake up again. If this is the case and it happens multiple times during the work of the application, then it might be a problem. Try avoiding such schemes of execution since it brings much of the unnecessary overheads by e.g. splitting the work more granularly to have more code to execute concurrently. 

> there are 20+ nodes in my project(I guess there are 20+ threads), and, they are serial, instead of concurrent.

Just curious, why use parallel framework then? Are you describing a corner case and usually they work concurrently?

**Comment by Shaquille-Wu** [comment]
1.about your 1st question:
we didn't apply TBB in non-flow-graph version, it just normal code as serial style.
we think the flow-graph is easy to reuse our code in various of projects, so we applied flow-graph, so we use TBB.

2.about you 2nd question:
our node is a composite concept, each node do not just mean just one "function node" in TBB.
each node in our project is make up of many TBB's "function node".
it just a vivid description for "20+ to 20+". I just want to say that there are many threads in our project.
I really found many many threads during debugging with GDB in my project. 
maybe, you are right the number of threads created by TBB is just N-1

3. about 3rd question:
yes, you are right.
unfortunately, our flow_graph version is a framework, various of algorithms execute in each node.
our purpose is reusing our algorithm with an easy style, 
so, we cannot splitting the work more granularly.
by the way, I cannot understand, why more concurrent more low overhead?
I think more concurrent more cpu-usage.
sometimes, a computation cost 100ms, and it will be 60+ms if it is executed in 2 threads with concurrent style, 
note, it is 60+ms instead of 50ms. so, I think  more concurrent more waste

4. about 4th question:
I have mentioned our purpose as above, we just want to use flow_graph instead of TBB.
we just want to reuse code instead of pure concurrent computation.

at last,
maybe, the context_switch is the main cause for our trouble, or say it is a overhead. we just want to reduce this overhead.
1).for example, is it useful when we remove the task-stolen? unfortunately, we do not know how to remove it from TBB.
2).for example, we want to set the affinities of all of nodes into a fixed core, is it useful? I just found the interface for "root_task",  instead of each node, how to set  affinity for each node(or each task)?
maybe, there are other ways, so, we want to obtain suggestions from TBB's experts.

**Comment by alexey-katranov** [comment]
@Shaquille-Wu, have you tried to use profiling tools, e.g. [Intel Vtune Profiler](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/vtune-profiler.html) or [the perf tool](https://perf.wiki.kernel.org/index.php/Main_Page) to understand what is the CPU usage difference between flow graph and non flow graph version?

**Comment by isaevil** [comment]
@Shaquille-Wu is this issue still relevant for you? Could you please respond? Have you considered using oneTBB?

**Comment by isaevil** [comment]
Closing it since no response. Feel free to reopen if any questions are left.
