### ISSUE TITLE
CXXFLAGS is overused in Makefile

### ISSUE THREAD

**Issue by e-kwsm** [oneapi-src/oneTBB#279]
At present `CXXFLAGS` variable is improperly used in Makefiles.

For example, https://github.com/oneapi-src/oneTBB/blob/eca91f16d7490a8abfdee652dadf457ec820cc37/examples/Makefile#L97 should be split into
```
        override CPPFLAGS += -I$(tbb_root)$(SLASH)include
        override CXXFLAGS += -qsuppress=1540-0198:1540-1401
        override LDFLAGS += -L$(work_dir)_release -L$(work_dir)_debug
```

https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

**Comment by AlexVeprev** [comment]
@e-kwsm, thank you for the catch!

Recently TBB migrated from Makefiles to CMake, currently it is available on master and onetbb_2021 branches:
https://github.com/oneapi-src/oneTBB/tree/master
https://github.com/oneapi-src/oneTBB/tree/onetbb_2021
Please consider using this new build system.

**Comment by e-kwsm** [comment]
On the branches the directory has been removed, so this is fixed in a sense, but setting `TBB_EXAMPLES` to `YES` will fail.

https://github.com/oneapi-src/oneTBB/blob/978af3d9d707db09c9fbec6a4e21b72c6fcc47f4/CMakeLists.txt#L226-L228

**Comment by AlexVeprev** [comment]
@e-kwsm, yes, it is expected since examples are not released yet. You can find supported variables at the top of https://github.com/oneapi-src/oneTBB/blob/master/cmake/README.md

**Comment by AlexVeprev** [comment]
@e-kwsm I'm closing the issue since current build system is CMake-based as I've explained above. If you have problems with it please submit issues.
