### ISSUE TITLE
scoped_lock name conflict c++17

### ISSUE THREAD

**Issue by sylvain-bougnoux** [oneapi-src/oneTBB#280]
The class `scoped_lock` seems to be in conflict with `c++17` that introduced this class as well.

It happens if `using namespace std;` is used prior to including `tbb`. As in:
```
using namespace std; // comment to remove the bug

#include <tbb/tbb.h>
```

Visual Studio (2017 aka 15.9.27) provides the following error.
```
1>d:\contrib\intel\tbb2019\include\tbb\reader_writer_lock.h(36): error C2990: 'std::scoped_lock': non-class template has already been declared as a class template
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\mutex(540): note: see declaration of 'std::scoped_lock'
```
The solution is to remove the `using` directive, **but it might not be always easy**.

I am not sure of which tbb version I am using (around 2019), but in the last file (`reader_writer_lock.h`), this class still exists. Sorry if it has been already fixed, but I did not find this issue in close ones.

**Comment by unterumarmung** [comment]
Hi
It's deprecated in TBB 2020
https://github.com/oneapi-src/oneTBB/blob/eca91f16d7490a8abfdee652dadf457ec820cc37/include/tbb/reader_writer_lock.h#L19-L44

And it's removed in oneTBB 2021 beta (`oneTBB_2021` branch)

**Comment by alexey-katranov** [comment]
@sylvain-bougnoux, if you still have issues feel free to reopen the issue.
