### ISSUE TITLE
Release notes links are broken

### ISSUE THREAD

**Issue by napetrov** [oneapi-src/oneTBB#281]
Here are Release Notes - those links are broken

https://software.intel.com/en-us/articles/intel-oneapi-threading-building-blocks-release-notes

**Comment by omalyshe** [comment]
Thanks for reporting the issue. Working on resolution.

**Comment by AlexVeprev** [comment]
Now it works for me. @napetrov, could you please check it on your side?

**Comment by napetrov** [comment]
Yep, looks good
