### ISSUE TITLE
variable TBB_INC not set

### ISSUE THREAD

**Issue by julianthelou** [oneapi-src/oneTBB#286]
Hello everyone,

i am new to tbb and I find it really hard to install tbb on my linux computer. I have found two ways to install tbb:

1. http://150.254.87.64/intel-manual/tbb/INSTALL.txt, but here I can't find the 'install.sh' file to execute it

2. https://community.intel.com/t5/Intel-oneAPI-Threading-Building/Installation-of-TBB-on-Linux/td-p/794823 and here the command 'gmake' does not work.

Can someone help me out?

Furthermore the error occuring after running my code is the following:
controller.py:356(checkEnvVariable):WARNING environment variable TBB_INC not set but required if code is built with TBB
controller.py:358(checkEnvVariable):WARNING environment variable TBB_SHLIB not set but required if code is built with TBB

**Comment by AlexVeprev** [comment]
Hi @julianthelou,

First of all: `TBB_INC` and `TBB_SHLIB` look like something specific for your project, probably they are expected to be set by some pre-configuration script on your side. TBB provides `tbbvars/vars` scripts, but they don't set such variables.

Do you have an information how `TBB_INC` and `TBB_SHLIB` are used? I can help you to set proper values for these variables, but I need to know how they used.

Meanwhile let me explain some integration approaches supported by TBB.

**For TBB 2020 or later**
There is no installation support in usual way, but you can use `tbbvars.sh` to make TBB visible in your environment.
Script tbbvars is available in packages on the [releases](https://github.com/oneapi-src/oneTBB/releases) page under `bin` directory. E.g. https://github.com/oneapi-src/oneTBB/releases/download/v2020.3/tbb-2020.3-lin.tgz
If you build TBB 2020 from sources tbbvars will be available in the build directory near the binaries.

**For oneTBB Beta**
Installation is supported through CMake if you build from sources: https://github.com/oneapi-src/oneTBB/tree/onetbb_2021/cmake#intallation-and-packaging.
Script `bin/tbbvars.sh` is moved to `env/vars.sh`, but acts as before.

Also you can integrate TBB using CMake `find_package`.

**Comment by AlexVeprev** [comment]
I'm closing since there is no new requests for a long time. Feel free to reopen if it is still relevant.
