### ISSUE TITLE
threadingbuildingblocks.org certificate expired

### ISSUE THREAD

**Issue by NikolausDemmel** [oneapi-src/oneTBB#287]
<img width="1165" alt="Screenshot 2020-10-12 at 20 54 25" src="https://user-images.githubusercontent.com/479562/95780957-2b58c900-0ccd-11eb-85f5-e72239f44515.png">

**Comment by KrisWragg-Certara** [comment]
Same problem here, cannot read documentation as cannot connect to website due to expired certificate.

**Comment by tbbdev** [comment]
The issue was resolved. Thank you for the report!
