### ISSUE TITLE
Function node doesn't process messages sequentially

### ISSUE THREAD

**Issue by frozZzen** [oneapi-src/oneTBB#289]
Hello TBB devs,

It seems we discovered a bug in flow graph. It occurs once in about every 10000 executions. The problem is that the order of message processing in the function node is not always deterministic.

I wrote a dedicated test to reproduce the issue. A sequence of numbers from 0 to N are entered into a chain of 3 function nodes and the same sequence of numbers is expected at the end of the chain.

Here's the test code:
```
#include <gtest/gtest.h>
#include <tbb/flow_graph.h>

TEST(TBB, function_node_message_order)
{
  const int MESSAGE_COUNT = 1'000'000;

  std::vector<int> received;
  received.reserve(MESSAGE_COUNT);
  tbb::flow::graph g;

  tbb::flow::function_node<int, int> funcNode1{
    g, tbb::flow::serial, [&](auto&& inp_) {
      return inp_;
    }
  };

  tbb::flow::function_node<int, int> funcNode2{
    g, tbb::flow::serial, [&](auto&& inp_) {
      return inp_;
    }
  };

  tbb::flow::function_node<int, int> funcNode3{
    g, tbb::flow::serial, [&](auto&& inp_) {
      received.push_back(inp_);
      return 0;
    }
  };

  tbb::flow::make_edge(funcNode1, funcNode2);
  tbb::flow::make_edge(funcNode2, funcNode3);

  for (int i = 0; i < MESSAGE_COUNT; ++i)
  {
    funcNode1.try_put(i);
  }

  g.wait_for_all();

  ASSERT_EQ(received.size(), MESSAGE_COUNT);
  for (int i = 0; i < MESSAGE_COUNT; ++i)
  {
    ASSERT_EQ(i, received[i]) << "Item " << i << " swapped with " << received[i];
  }
}
```
The last assertion fails at random positions.

I tried using an input node as well to feed the chain, but it didn't solve the issue.

When I replaced the function nodes with multifunction nodes without changing the functionality, the issue seemingly disappeared:
```
#include <gtest/gtest.h>
#include <tbb/flow_graph.h>

TEST(TBB, multifunction_node_message_order)
{
  const int MESSAGE_COUNT = 1'000'000;

  std::vector<int> received;
  received.reserve(MESSAGE_COUNT);
  tbb::flow::graph g;

  using multifunction_node = tbb::flow::multifunction_node<int, std::tuple<int>>;
  multifunction_node multiNode1{
    g, tbb::flow::serial,
    [&](auto&& inp_, [[maybe_unused]] auto&& outp_) {
      std::get<0>(outp_).try_put(inp_);
    }
  };

  multifunction_node multiNode2{
    g, tbb::flow::serial,
    [&](auto&& inp_, [[maybe_unused]] auto&& outp_) {
      std::get<0>(outp_).try_put(inp_);
    }
  };

  multifunction_node multiNode3{
    g, tbb::flow::serial,
    [&](auto&& inp_, [[maybe_unused]] auto&& outp_) {
      received.push_back(inp_);
    }
  };

  tbb::flow::make_edge(multiNode1, multiNode2);
  tbb::flow::make_edge(multiNode2, multiNode3);

  for (int i = 0; i < MESSAGE_COUNT; ++i)
  {
    multiNode1.try_put(i);
  }

  g.wait_for_all();

  ASSERT_EQ(received.size(), MESSAGE_COUNT);
  for (int i = 0; i < MESSAGE_COUNT; ++i)
  {
    ASSERT_EQ(i, received[i]) << "Item " << i << " swapped with " << received[i];
  }
}
```

**Comment by aleksei-fedotov** [comment]
Hi frozZzen,

Thank you for your interest in the TBB flow graph!

We are aware of such behavior in the function node. Indeed, serial concurrency does not guarantee the ordering, in which messages are processed. It only guarantees that the body of the function node will not execute concurrently with another copy of that body. If the ordering is desired between the flow graph nodes, one should use sequencer node. Or, in case of the single branch flow graph as in the example, one could use tbb::parallel_pipeline with filters of serial_in_order mode.

The difference you observe with regard to the multifunction node is that it puts the message to successors in its body, which executes serially, while putting the message to function node's successors is outside its body, hence can be made concurrently. However, even in the multifunction node case, the order in which messages are arrived and processed is an implementation-defined and can be changed.

**Comment by frozZzen** [comment]
Hi Aleksei,

Thanks for the explanation. I've got misled a bit by the serial and queueing keywords, but indeed the documentation doesn't mention anything about keeping the order of the messages.
So, as far as I understand your explanation, a sequencer node connected to any type of function node with serial concurrency, whether it has queueing policy, or not, will ensure that the messages are handed over to the function node's body in the same order as they were rearranged by the sequencer node.
Or does the function node need to have a lightweight policy to receive the messages in the correct order?

Thanks in advance!

**Comment by aleksei-fedotov** [comment]
Hi frozZzen,

Yes, `sequencer_node` ensures that the messages are `try_put` to its successors in the order specified in its sequencer functor.

> Or does the function node need to have a lightweight policy to receive the messages in the correct order?

No, lightweight policy has nothing to do with the order of the messages. The policy should be accurately used in case the body of the node is small. I write the word "accurately" intentionally, because using this policy might significantly reduce the available parallelism in the graph.

**Comment by frozZzen** [comment]
Hi Aleksei! Thanks for the explanation! I think I can close the issue then.
