### ISSUE TITLE
concurrent_unordered_set missing "contains()" method

### ISSUE THREAD

**Issue by mbBRCM** [oneapi-src/oneTBB#291]

**Comment by kboyarinov** [comment]
Hi, @mbBRCM 

Thank you for reporting the issue!
`contains()` method for concurrent unordered containers family was added in [oneTBB 2021](https://github.com/oneapi-src/oneTBB/tree/onetbb_2021).

For TBB 2020 the only available option is `set.find(key) != set.end()`.

**Comment by alexey-katranov** [comment]
@mbBRCM , if you still have issues, feel free to reopen the issue.

**Comment by mbBRCM** [comment]
Thank you @alexey-katranov!
