### ISSUE TITLE
"Ambiguous" operator() results in compiler error on gcc.

### ISSUE THREAD

**Issue by Yitzi2** [oneapi-src/oneTBB#292]
I have a class (call it Derived) that inherits from two base classes (Base1 and Base2).  Base1 and Base2 each implement operator()(args) (for some args; I doubt it matters which ones), and Derived does not.  (Thus, a call to derived(args) would be ambiguous).  When compiling on gcc, I get the error:
.../tbb/include/tbb/enumerable_thread_specific.h:729:75: error: request for member ‘operator()’ is ambiguous
  729 |             template<typename U> static yes& decide( decltype(declval<U>()())* );

This is probably a bug in GCC's implementation of SFINAE, but it might be good, if possible, to modify the code to avoid it, especially since it would probably not be a bug if args were in fact empty.

**Comment by anton-potapov** [comment]
@Yitzi2 can you provide a minimum reproducer with exact version of gcc it fails on ?

**Comment by anton-potapov** [comment]
It seems not applicable to oneTBB, as the code changed significantly. 
@Yitzi2,  please reopen if the problem exists on oneTBB (e.g. [v2021.4.0](https://github.com/oneapi-src/oneTBB/tree/v2021.4.0) or latest master)
