### ISSUE TITLE
CMake export set discrepancies

### ISSUE THREAD

**Issue by jdumas** [oneapi-src/oneTBB#295]
Hi there,

Thank you for updating your CMake to provide a more modern experience. I am trying to use TBB 2021 as a subdirectory in my project, and ran into issues regarding the CMake target export sets.

Should the following line
https://github.com/oneapi-src/oneTBB/blob/8632c278467f99941caff8a666fa33e57650c53f/CMakeLists.txt#L206
use `PROJECT_NAME` rather than `CMAKE_PROJECT_NAME`? If you want the client to inject their own name into TBB's CMake, they you should use a CMake `option()` rather than impose the structrure `${CMAKE_PROJECT_NAME}Targets`.

Also, `TBBTargets` is hardcoded in this line and should probably be fixed for consistency:
https://github.com/oneapi-src/oneTBB/blob/8632c278467f99941caff8a666fa33e57650c53f/src/tbb/CMakeLists.txt#L103

**Comment by AlexVeprev** [comment]
@jdumas, please try the code from master branch, it contains the fix for #271 that should help. Thank you for the note about alignment!

**Comment by AlexVeprev** [comment]
BTW here is my note about fix propagation to onetbb_2021 branch: https://github.com/oneapi-src/oneTBB/issues/271#issuecomment-701381208

**Comment by jdumas** [comment]
Thanks, the `master` branch indeed works. I'll close this issue then.
