### ISSUE TITLE
CMake: skip vars generation (POST_BUILD step) when building TBB via add_subdirectory()

### ISSUE THREAD

**Issue by jdumas** [oneapi-src/oneTBB#296]
See this line:
https://github.com/oneapi-src/oneTBB/blob/8632c278467f99941caff8a666fa33e57650c53f/cmake/vars_utils.cmake#L37

When building TBB via `add_subdirectory()`, `CMAKE_CURRENT_SOURCE_DIR` should be used rather than `CMAKE_SOURCE_DIR`

**Comment by jdumas** [comment]
Also, some CMake shenanigans are causing my build to fail due to the POST_BUILD rule defined in `vars_utils.cmake`, with the following error message:

```
Error	MSB3073	The command "setlocal
"C:\Program Files\CMake\bin\cmake.exe" -DBINARY_DIR=C:/Users/jedumas/workspace/myproject/build/_deps/tbb-build/src/tbb -DSOURCE_DIR=C:/Users/jedumas/workspace/myproject/build/_deps/tbb-src/src/tbb -DBIN_PATH=C:/Users/jedumas/workspace/myproject/build/msvc_19.27_cxx14_64_md_debug -DVARS_TEMPLATE=windows/env/vars.bat.in -DVARS_NAME=vars.bat -DTBB_INSTALL_VARS=OFF -P C:/Users/jedumas/workspace/myproject/build/_deps/tbb-src/src/tbb/integration/cmake/generate_vars.cmake
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd" exited with code 1.	tbb	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	149	
```

I am wondering whether the whole POST_BUILD command is unnecessary when building TBB via `add_subdirectory()`?

**Comment by AlexVeprev** [comment]
Hi @jdumas, have you tried the code from master branch? 
It contains the fix for the initial issue: CMAKE_SOURCE_DIR is replaced with PROJECT_SOURCE_DIR.
See https://github.com/oneapi-src/oneTBB/blob/master/cmake/vars_utils.cmake#L37

It was fixed in scope of #271 

> I am wondering whether the whole POST_BUILD command is unnecessary when building TBB via add_subdirectory()?

Sounds valid, we need to consider it a bit more deeply before removal.

BTW, please let me know if you see any issues with master branch, if you can try it.

**Comment by jdumas** [comment]
Master branch indeed works, but I'll leave this issue open regarding whether the `POST_BUILD` command should be made optional or not.

**Comment by AlexVeprev** [comment]
@jdumas there is a fix in master branch that blocks vars generation if CMAKE_PROJECT_NAME is not the same as PROJECT_NAME: https://github.com/oneapi-src/oneTBB/blob/master/cmake/vars_utils.cmake#L29

The solution may be changed in future, but it should already work for `add_subdirectory()` case.

**Comment by jdumas** [comment]
Awesome. I'll close this issue then, and will reopen if I encounter any further issue.

**Comment by yinzeq** [comment]
hello, @jdumas  I have meet the same problems when use add_subdirectory in windows with build type release. 
The building log is:

d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: 命令“setlocal [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: cd E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: E: [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E __create_def E:/viscanner/barcode-sdk/build_win_Release/modules/hpc/modules/oneTBB/src/tbb/tbb.dir/Release/exports.def E:/viscanner/barcode-sdk/build_win_Release/modules/hpc/modules/oneTBB/src/tbb/tbb.dir/Release//objects.txt [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: :cmEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: :cmErrorLevel [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: exit /b %1 [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: :cmDone [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: :VCEnd”已退出，代码为 -1073741819。 [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]

However, there is no problem when building type set to Debug, code branch is master.

How to fix it?
