### ISSUE TITLE
Output directory for binaries when using CMake

### ISSUE THREAD

**Issue by tadas-subonis** [oneapi-src/oneTBB#300]
Hello,

how can I specify the output directory for tbb.dll file when I am building the project? At the moment, it gets built in the dir that includes tbb as a dependency and I would like to specify that.

**Comment by AlexVeprev** [comment]
Hi @tadas-subonis,

You can set `TBB_OUTPUT_DIR_BASE`, but it will be appended with build type (CMAKE_BUILD_TYPE) or configuration in case of multi-config generators.

Just an example with multi-config generator (Visual Studio) on Windows:
```
cmake -DTBB_OUTPUT_DIR_BASE=demo ..
cmake --build . --config relwithdebinfo --target tbb
```

After execution of these commands you'll get `tbb.dll` in `demo_relwithdebinfo` folder.

Is it suitable solution for you?

**Comment by tadas-subonis** [comment]
@AlexVeprev  thanks

That looks like something I was looking for. However, I got this error:

```
    CMake Warning:
      Manually-specified variables were not used by the project:

        DTBB_OUTPUT_DIR_BASE
```
are there any specifics about its usage?

**Comment by AlexVeprev** [comment]
Seems you put extra `D` before the variable name. In my example `-D` is a CMake key to pass the variable, but the variable name is `TBB_OUTPUT_DIR_BASE` without initial `D`. Please check it.

**Comment by AlexVeprev** [comment]
Closing the issue as no more questions, @tadas-subonis, feel free to reopen the issue if it is still actual for you,

**Comment by tadas-subonis** [comment]
@AlexVeprev sorry, I forgot to reply back that it was an outstanding catch and that was indeed the problem :).

Thanks!
