### ISSUE TITLE
Do not use type aliases in CTAD declarations

### ISSUE THREAD

**Issue by tomilov** [oneapi-src/oneTBB#301]
Result type of class template argument deduction declaration must be explicit class template specialization, not one mediated by alias template or type alias, like it is [here](https://github.com/oneapi-src/oneTBB/blob/tbb_2020/include/tbb/concurrent_hash_map.h#L1230-L1255).

The code has mistake, that leads to hard error during compilation:

 > /usr/include/tbb/concurrent_hash_map.h(1247): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_hash_map.h(1253): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_priority_queue.h(536): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_priority_queue.h(540): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_map.h(282): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_map.h(287): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_map.h(292): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_map.h(297): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_map.h(464): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_map.h(469): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_map.h(474): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_map.h(479): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_set.h(235): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_set.h(240): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_set.h(245): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_set.h(250): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_set.h(420): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_set.h(425): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_set.h(430): error: the return type must directly designate a specialization of the associated class template
/usr/include/tbb/concurrent_unordered_set.h(435): error: the return type must directly designate a specialization of the associated class template

Compilers are:
 - clang version 10.0.1
 - g++ (GCC) 10.2.0

Both failed when running from within `/opt/cuda/bin/nvcc -std=c++17`:
 > nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

**Comment by kboyarinov** [comment]
Hi, @tomilov ,

Deduction guides for oneTBB components were reworked to avoid compilation issues in [oneTBB 2021.2.0](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.2.0).
If you still have any issues, feel free to contact us.

**Comment by tomilov** [comment]
Sadly I cannot check now, but I trust you. Thank you.
