### ISSUE TITLE
`task_group::is_cancel` missing on master branch

### ISSUE THREAD

**Issue by mmmm1998** [oneapi-src/oneTBB#308]
In previous TBB versions `task_group` class have had `cancel` method and related method `is_canceled`, which return `true`, if the task group have canceled and `false` otherwise.
But on current master `is_canceled` method is missing now. Is it planned changes in the class API or it is some sort of error?

**Comment by alexey-katranov** [comment]
It is really missed. I will try to investigate if it was intentionally.

As a work around, is it possible to use [`tbb::is_current_task_group_canceling`](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/task_scheduler/task_group/task_group_cls.html) in your case?

**Comment by mmmm1998** [comment]
I have write a wrapper class with `bool is_canceled` and `cancel` method, but maybe `is_current_task_group_canceling` will works too, although `currect` (state depended method) part of this function is not very convenient.

**Comment by mmmm1998** [comment]
The issue not relevant anymore, so I close it.
