### ISSUE TITLE
profiling.h causes clashes when used with Qt

### ISSUE THREAD

**Issue by Alexey-Danilchenko** [oneapi-src/oneTBB#309]
TBB profiling.h defines event struct with emit() methods even when profiling is not in use. This clashes with QT emit command in pretty much every QT application. There should be a way to disable that completely if one does not need/use profiling instead of generating empty event structure with emit method.

This is happening in TBB 2020-2021 and QT 5.15.0- 5.15.2 (i.e. last released versions)

**Comment by siyeopyoon** [comment]
From the report of Joerg Bornemann (https://bugreports.qt.io/browse/QTBUG-80990) this problem can be avoided by including tbb.h conditionally.

#if WITH_TBB && !defined(Q_MOC_RUN)
#include <tbb/tbb.h>
#endif

**Comment by alexey-katranov** [comment]
The issue is that emit is a macro defined by QT. Another workaround is to `undef` the macro, i.e.
```
#ifdef emit
#undef emit
#endif
#incude <tbb/tbb.h>
```

**Comment by Alexey-Danilchenko** [comment]
None of these are a solution. First because it prevents using TBB. Second - it will break QT.

The proper solution is to enabled QT_NO_KEYWORDS definition when compiling QT sources so there is no keyword clashes and modifying QT sources to use macros instead of keywords.
