### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by ThomasP1988** [oneapi-src/oneTBB#314]
Hi everyone,
I was previously using TBB with the following in my cmakelist

include(external/oneTBB/cmake/TBBGet.cmake)
include(external/oneTBB/cmake/TBBBuild.cmake)
tbb_get(TBB_ROOT tbb_root SOURCE_CODE)
tbb_build(TBB_ROOT ${tbb_root} CONFIG_DIR TBB_DIR)
find_package(TBB REQUIRED) 

But since today i get this error, 

Could not find a package configuration file provided by "TBB" with any of
the following names:

  TBBConfig.cmake
  tbb-config.cmake

then I downloaded the new src, built with cmake, and include TBBConfig.cmake but it doesnt work.

i can't figure out what happens here, can someone help me how to install the 2021 version please?

**Comment by AlexVeprev** [comment]
Hi @ThomasP1988, I see you've closed the issue, so I hope you've found a solution.

I'd propose the following ways:
- If you want to migrate to oneTBB you can try [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html) features to download and build oneTBB.
- If you'd like to stay on TBB 2020 you can specify tag in `tbb_get` like `tbb_get(TBB_ROOT tbb_root SOURCE_CODE RELEASE_TAG v2020.3)`.
