### ISSUE TITLE
 ‘task’ is not a member of ‘tbb’; did you mean ‘tbb::detail::d1::task’

### ISSUE THREAD

**Issue by popina1994** [oneapi-src/oneTBB#315]
I successfully installed TBB 2021.1. from source file. I tried to use TBB to run parallel algorithms in C++17. 
However, when I try to compile my program it prompts me the following error:

/usr/include/c++/10/pstl/parallel_backend_tbb.h:640:18: error: ‘tbb::task’ has not been declared                   
   640 |             tbb::task::spawn_root_and_wait(*new (tbb::task::allocate_root()) _TaskType(                           |              
                                                                                  /usr/include/c++/10/pstl/parallel_backend_tbb.h:640:55: error: ‘task’ is not a member of ‘tbb’; did you mean ‘tbb::detail::d1::task’?                                                                                                     
640 |             tbb::task::spawn_root_and_wait(*new (tbb::task::allocate_root()) _TaskType(                           |                                                                                      

In file included from /usr/local/include/oneapi/tbb/parallel_for.h:23,                                                               from /usr/local/include/tbb/parallel_for.h:17,                                                                      from /usr/include/c++/10/pstl/parallel_backend_tbb.h:20,                                                            from /usr/include/c++/10/pstl/parallel_backend.h:16,                                                                from /usr/include/c++/10/pstl/algorithm_impl.h:22,                                                                  from /usr/include/c++/10/pstl/glue_execution_defs.h:50,                                                             from /usr/include/c++/10/execution:32,                                                                              from /home/xxx:5:                           /usr/local/include/oneapi/tbb/detail/_task.h:219:31: note: ‘tbb::detail::d1::task’ declared here                      219 | class alignas(task_alignment) task : public task_traits {

**Comment by Lastique** [comment]
oneTBB 2021.1 is incompatible with previous TB releases and parallel STL. `tbb::task` is removed. https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-threading-building-blocks-release-notes.html

**Comment by popina1994** [comment]
Thanks for the answer!
I tried to use it with parallel STL.
