### ISSUE TITLE
cmake doesn't issue to build tbb [linux]

### ISSUE THREAD

**Issue by gwcew** [oneapi-src/oneTBB#316]
Hello and in Qt Creator I can't issue to build tbb project and get something like: "Built target tbb" etc.

By the way, I have used find_package and add_subdirectory. Current branch is master->8dcbd5b11bfd84d09d1af1e11d4dfd68ab3b680b

**Comment by AlexVeprev** [comment]
Hi @gwcew,

Do you see the problem only in Qt Creator? Does it work from console? 

Normally `add_subdirectory` should work in case of source code integration. Could you please post exact commands how you include oneTBB in your CMakeLists.txt and which output you get for it? If you can provide a simple reproducer it would be nice.

**Comment by gwcew** [comment]
> Hi @gwcew,
> 
> Do you see the problem only in Qt Creator? Does it work from console?
> 
> Normally `add_subdirectory` should work in case of source code integration. Could you please post exact commands how you include oneTBB in your CMakeLists.txt and which output you get for it? If you can provide a simple reproducer it would be nice.

`find_package(TBB COMPONENTS tbb REQUIRED)
add_subdirectory("./dep/oneTBB")
target_link_libraries(${PROJECT_NAME} TBB::tbb)`

I get the same log if I execute from terminal. And I have errors about linking something like this: /dep/oneTBB/include/oneapi/tbb/cache_aligned_allocator.h:59: undefined reference to `tbb::detail::r1::cache_aligned_deallocate(void*)'
/dep/oneTBB/include/oneapi/tbb/task_arena.h:223: undefined reference to `tbb::detail::r1::execute(tbb::detail::d1::task_arena_base&, tbb::detail::d1::delegate_base&)'

@AlexVeprev

**Comment by AlexVeprev** [comment]
@gwcew you are mixing two different integration approaches:

- `find_package(TBB ...)` is needed then you integrate pre-built TBB, seems it finds some pre-installed TBB on the system in your case.
- `add_subdirectory("./dep/oneTBB")` allows you to integrate oneTBB sources into your project, so the oneTBB sources will be built together with your project. 

Please remove `find_package(TBB COMPONENTS tbb REQUIRED)`, clean previous build artifacts and try again.

**Comment by gwcew** [comment]
> @gwcew you are mixing two different integration approaches:
> 
> * `find_package(TBB ...)` is needed then you integrate pre-built TBB, seems it finds some pre-installed TBB on the system in your case.
> * `add_subdirectory("./dep/oneTBB")` allows you to integrate oneTBB sources into your project, so the oneTBB sources will be built together with your project.
> 
> Please remove `find_package(TBB COMPONENTS tbb REQUIRED)`, clean previous build artifacts and try again.

@AlexVeprev I don't know how to correctly link oneTBB to my project through target_link_library, because TBB::tbb cause an error: "/usr/bin/ld: cannot find -lTBB::tbb". I have used add_subdirectory, but Qt don't issue building dependency.
