### ISSUE TITLE
2021.1.1: Test failures

### ISSUE THREAD

**Issue by Lastique** [oneapi-src/oneTBB#317]
When building oneTBB 2021.1.1 release on Kubuntu 20.10 x86_64, the following tests fail:

- 43 - test_limiter_node (INTERRUPT)
- 69 - conformance_arena_constraints (Failed)
- 125 - test_malloc_whitebox (SEGFAULT)
- 126 - test_malloc_atexit (SEGFAULT)
- 127 - test_malloc_overload (SEGFAULT)
- 128 - test_malloc_overload_disable (SEGFAULT)
- 129 - test_malloc_new_handler (SEGFAULT)

The test_limiter_node test is hanging indefinitely and in this case was interrupted with SIGINT.

The libtbbbind library CMake file was patched to be able to compile it with libhwloc 2.2.0, which is the version of the library that is available in Kubuntu 20.10 repos. This patch is here: [fix_hwloc_detection.patch.txt](https://github.com/oneapi-src/oneTBB/files/5705211/fix_hwloc_detection.patch.txt)

The library was also patched to work around https://github.com/oneapi-src/oneTBB/issues/312. This patch is here: [fix_inheriting_members.patch.txt](https://github.com/oneapi-src/oneTBB/files/5705212/fix_inheriting_members.patch.txt) (https://github.com/oneapi-src/oneTBB/pull/318)

The full log is here: [tbb_build_fail.txt](https://github.com/oneapi-src/oneTBB/files/5705207/tbb_build_fail.txt)

This was run on a Core i7 2600K.

**Comment by alexey-katranov** [comment]
Thank for the report.

Can you please clarify what issues did you have with `libtbbbind`? Notify: @AlexVeprev , @ivankochin

**Comment by Lastique** [comment]
`libtbbbind` is simply excluded from the build because CMake script does not find neither 1.11 nor 2.0 version of libhwloc on the system (because the installed version is 2.2.0). This is described in https://github.com/oneapi-src/oneTBB/issues/319.

**Comment by alexey-katranov** [comment]
@Lastique , do you use release build (not relwithdebinfo)? If so, can you try to add CXXFLAGS="-fno-ipa-cp-clone" to check if the issue relates to https://github.com/oneapi-src/oneTBB/issues/342#issuecomment-771776975. Thank you in advance.

**Comment by Lastique** [comment]
> do you use release build (not relwithdebinfo)?

Yes.

> If so, can you try to add CXXFLAGS="-fno-ipa-cp-clone"

It fixed some tests but not conformance_arena_constraints and conformance_enumerable_thread_specific. The latter one does not fail 100% of the runs, only on some runs. I'm attaching a full build log.

[tbb_build.txt](https://github.com/oneapi-src/oneTBB/files/5957415/tbb_build.txt)

Having to disable compiler optimizations makes me suspect that something is not right with the code.

**Comment by alexey-katranov** [comment]
I believe `test_eh_thread` is not really stable. @ivankochin @Iliamish , do you have any ideas how to improve it?

@Lastique , is `test_eh_thread` the only failing test in your environment?

**Comment by Lastique** [comment]
I mentioned `test_eh_algorithms` as well above. I only ran the tests twice.

**Comment by anton-potapov** [comment]
@Lastique, does https://github.com/oneapi-src/oneTBB/pull/697 helped with the `test_eh_thread` ?

**Comment by Lastique** [comment]
I built 2021.5.0 with #697 applied a coule times and got these failures:

```
The following tests FAILED:
        130 - test_malloc_atexit (SEGFAULT)
        131 - test_malloc_overload (SEGFAULT)
        132 - test_malloc_overload_disable (SEGFAULT)
        133 - test_malloc_new_handler (SEGFAULT)
```

Not `test_eh_thread` though, so I suppose it helped.

**Comment by sbonfert** [comment]
`test_eh_thread` seems to fail, if more than 1024 threads are already running when the test is started, since the outermost thread cannot be created. Maybe the thread limit should be chosen dynamically.

**Comment by Lastique** [comment]
I don't know, I haven't been running TBB tests for a while.
