### ISSUE TITLE
2021.1.1: libhwloc detection doesn't work with library versions other than 1.11 and 2.0

### ISSUE THREAD

**Issue by Lastique** [oneapi-src/oneTBB#319]
This is a problem for example on Kubuntu 20.10, where the libhwloc from the standard repo has version 2.2.0. I'm assuming this will also be a problem on any other distro where libhwloc version is different from 1.11 and 2.0.

Please, make the version check less strict and use whatever version is available on the user's system. For example, here is a patch that uses pkgconfig to detect the library and discover any necessary compiler flags: [fix_hwloc_detection.patch.txt](https://github.com/oneapi-src/oneTBB/files/5705357/fix_hwloc_detection.patch.txt)

I understand that this patch will probably not work on Windows, where pkgconfig is uncommon, which is why I'm not making it a PR. However, on most UNIX-like system pkgconfig is standard and should be used for this sort of things. I'd recommend taking this approach for UNIX-like systems.

**Comment by alexey-katranov** [comment]
@AlexVeprev , @ivankochin , can you please take a look?

**Comment by ivankochin** [comment]
@Lastique thank you for your report!
The `tbbbind` library configuring and building approach will be changed in one of the future releases.

**Comment by ivankochin** [comment]
@Lastique 

The oneTBB master branch already contains the new approach regards building the TBBbind library.
At this moment the oneTBB library supports all HWLOC versions start from 1.11, but this support makes the build process more complex.

To build the TBBbind library with HWLOC 2.2.0 you should specify the following CMake variables:
- `CMAKE_HWLOC_2_LIBRARY_PATH`  - path to the HWLOC library shared object
- `CMAKE_HWLOC_2_INCLUDE_PATH` - path to the HWLOC library include files
[Read more about TBBBind library configuration.](https://github.com/oneapi-src/oneTBB/tree/master/cmake#tbbbind-library-configuration)

I know that this mechanism does not look perfect. And possibly it will be improved and redeveloped in future releases. But if I understand your issue correctly, then this interface may help you to solve it.

**Comment by Lastique** [comment]
libhwloc 2.2.0 is the standard version that is installed in the stock system (i.e. it is installed in /usr/lib/* and /usr/include). The user should not be required to specify these paths. Why can't you use pkgconfig on UNIX-like systems?

**Comment by ivankochin** [comment]
We will consider this option and possibly implement it in future releases.

**Comment by ivankochin** [comment]
@Lastique, the `pkg-config` based approach is available in the [master](https://github.com/oneapi-src/oneTBB/tree/master) branch. 

Please confirm that your case was covered and we will close the issue.

**Comment by ivankochin** [comment]
Waiting for the fix correctness confirmation. Please reopen the issue if it still reproduces.

**Comment by Lastique** [comment]
@ivankochin I've tested revision 9e15720bc7744f85dff611d34d65e9099e077da4. It does detect libhwloc 2.2.0, as expected. However, the resulting libtbbbind library has suffix "_2_0" (the full library name is `libtbbbind_2_0.so.3.2`). Is this expected? I thought that libhwloc version is supposed to be embedded in the libtbbbind library name, in which case the suffix should be "_2_2".

**Comment by ivankochin** [comment]
Yes, it is the expected name. We have only 3 versions of the TBBbind library due to HWLOC binary compatibility and required interfaces specialty:
* tbbbind - linked with HWLOC 1.11.x versions
* tbbbind_2_0 - linked with HWLOC >=2 versions
* tbbbind_2_4 - linked with HWLOC >=2.4 versions

So the numbers suffix means only the minimal supported HWLOC version for this TBBbind library. The tbbbind that links with HWLOC 1.11.x was not expanded just for legacy reasons.

**Comment by Lastique** [comment]
@ivankochin I see this issue is still not fixed in 2021.2.0. Please reopen.

**Comment by ivankochin** [comment]
@Lastique 
The fix for this issue is available on master and will be included in one of the next releases (presumably 2021.3). Could you please use the latest master branch state to check the fix correctness?

After this information do you still insist on the issue reopening?

**Comment by Lastique** [comment]
@ivankochin I'm not sure what's the purpose of the master branch, since there is also the onetbb_2021 branch from which 2021 releases are made. And the fix was announced here in master before 2021.2.0 was released, so clearly the master branch is not used as the base for releases. So I would prefer the issue to be reopened as a reminder and closed when the fix is released.

**Comment by ivankochin** [comment]
@Lastique 
The 2021.2 release is based on the master branch. But [the commit](https://github.com/oneapi-src/oneTBB/tree/v2021.2.0) that was used for 2021.2 publishing is earlier than [the commit](https://github.com/oneapi-src/oneTBB/commit/4523a7615eaed49c4ed75654b349ca41b92c6381) to master which contains the fix for this issue.

But anyway the issue reopening is OK, there is no problem to close the issue when the required release will be available.

**Comment by ivankochin** [comment]
@Lastique, the fix should be available as a part of the [TBB 2021.3 release](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.3.0). Please try this release and confirm that issue was successfully fixed.

**Comment by Lastique** [comment]
Yes, 2021.3 does contain the commit mentioned earlier and is able to detect libhwloc 2.4.1 on Kubuntu 21.04. Thanks.
