### ISSUE TITLE
task_group and nested tasks calling

### ISSUE THREAD

**Issue by gwcew** [oneapi-src/oneTBB#324]
Does it make any sense if I use some count of task_groups and use in nested form. 

Like this

MyMethod()
 {
    tbb::task_group fork;
    
    fork.run(task1);
    fork.run(task2);
    fork.run(task3);

    fork.wait();
}

tbb::task_group fork;

fork.run([]() {MyMethod();});

fork.wait();

OR, I do this

MyMethod(tbb::task_group& fork)
{
    fork.run(task1);
    fork.run(task2);
    // etc

    fork.wait(); // ?? should I call here if I call in another stack
}

...
tbb::task_group fork;

fork.run([](){MyMethod(fork)});

fork.wait(); // ???

...

Does it make any sense to use nested tasks in nested functions???

or I should use everytime for that rule is: "One task = One function without nested tasks".

**Comment by alexey-katranov** [comment]
What do you mean with nesting? 

1. If you want to `run` a task from another task - it is a recommended pattern:
```
tbb::task_group tg;
tg.run([&tg] { 
    tg.run( ... ) { }
}
tg.run([&tg] { 
    tg.run( ... ) { }
}
tg.wait();
```
2. If you want to call `wait` inside a task within the same `task_group` - it is a deadlock:
```
tbb::task_group tg;
tg.run([&tg] { 
    tg.run( ... ) { }
    tg.wait(); // DEADLOCK
}
tg.wait();
```

**Comment by gwcew** [comment]
> What do you mean with nesting?
> 
> 1. If you want to `run` a task from another task - it is a recommended pattern:
> 
> ```
> tbb::task_group tg;
> tg.run([&tg] { 
>     tg.run( ... ) { }
> }
> tg.run([&tg] { 
>     tg.run( ... ) { }
> }
> tg.wait();
> ```
> 
> 1. If you want to call `wait` inside a task within the same `task_group` - it is a deadlock:
> 
> ```
> tbb::task_group tg;
> tg.run([&tg] { 
>     tg.run( ... ) { }
>     tg.wait(); // DEADLOCK
> }
> tg.wait();
> ```

Thank you for reply.
