### ISSUE TITLE
error when compiling (ubuntu 20)

### ISSUE THREAD

**Issue by ThomasP1988** [oneapi-src/oneTBB#329]
Hi, 

I get this error when i try to compile with new version, should i wait for a fix or is there something i could do?

Thank you

/usr/bin/ld: ../../../gnu_9.3_cxx17_64_relwithdebinfo/libtbbmalloc_proxy.a(proxy.cpp.o): in function `free':
/home/tom/Projects/cproject/build/_deps/tbb-src/src/tbbmalloc_proxy/proxy.cpp:191: multiple definition of `free'; CMakeFiles/_test_malloc_atexit.dir/tbbmalloc/test_malloc_atexit.cpp.o:/home/tom/Projects/cproject/build/_deps/tbb-src/test/tbbmalloc/test_malloc_atexit.cpp:70: first defined here
/usr/bin/ld: ../../../gnu_9.3_cxx17_64_relwithdebinfo/libtbbmalloc_proxy.a(proxy.cpp.o): in function `realloc':
/home/tom/Projects/cproject/build/_deps/tbb-src/src/tbbmalloc_proxy/proxy.cpp:197: multiple definition of `realloc'; CMakeFiles/_test_malloc_atexit.dir/tbbmalloc/test_malloc_atexit.cpp.o:/home/tom/Projects/cproject/build/_deps/tbb-src/test/tbbmalloc/test_malloc_atexit.cpp:75: first defined here
/usr/bin/ld: ../../../gnu_9.3_cxx17_64_relwithdebinfo/libtbbmalloc_proxy.a(proxy.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt9bad_alloc@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [_deps/tbb-build/test/CMakeFiles/_test_malloc_atexit.dir/build.make:90: gnu_9.3_cxx17_64_relwithdebinfo/lib_test_malloc_atexit.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:2067: _deps/tbb-build/test/CMakeFiles/_test_malloc_atexit.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by alexey-katranov** [comment]
Can you please share CMake configuration options? As I understand, you are trying to build a static version?

**Comment by ThomasP1988** [comment]
Hi Alexey,

I do it with FetchContent in that way

FetchContent_Declare(
        TBB
        GIT_REPOSITORY https://github.com/oneapi-src/oneTBB
        GIT_TAG master
)
FetchContent_MakeAvailable(TBB)

and then add TBB to my project

**Comment by anton-potapov** [comment]
@ThomasP1988 is the problem still reproducible with the latest master ?

**Comment by anton-potapov** [comment]
@ThomasP1988 please reopen if problem still exist
