### ISSUE TITLE
OneTbb 2021 is not compatible with parallel STL, what is the way forward?

### ISSUE THREAD

**Issue by AlyaMx** [oneapi-src/oneTBB#332]
Hi there,
We are building an analytics application that uses Parallel STL. So far the code links to the tbb library version 2020.3.
We recently tried upgrading to the latest version of the library (oneTBB 2021) (to take advantage of its cmake build configuration) but we quickly understood that it is not compatible with Parallel STL as per the release notes.
So, I am wondering if there is a plan to upgrade Parallel STL so it is compatible with the new tbb version?
Thanks in advance for your help,
Best,
Alya

**Comment by bduclaux** [comment]
Same problem. Any update here ?

**Comment by capatober** [comment]
Hi @AlyaMx, @bduclaux,
Parallel STL has already been updated in libstdc++ (https://github.com/gcc-mirror/gcc/commit/e957b86ca26f9a4e49acf625ed397e7dd05b0d66#diff-1818b77445468487b000c0453c59783b18c0e2558e1549e859583a28d3c84d8cR71).

**Comment by anton-potapov** [comment]
@AlyaMx, it seems that problem is solved. Can you check you on your side ?

**Comment by anton-potapov** [comment]
@AlyaMx, please re-open if the problem still exists

**Comment by pca006132** [comment]
Not sure if I should open another issue, but it seems that at least with GCC12, there are memory leaks when using PSTL with TBB backend (https://github.com/elalish/manifold/issues/787). It works fine with clang using libc++. Not sure if gcc 13 works, not yet checked.
