### ISSUE TITLE
Replacement/workaround for deleted runtime_loader

### ISSUE THREAD

**Issue by przole** [oneapi-src/oneTBB#337]
https://www.threadingbuildingblocks.org/docs/help/index.htm#reference/appendices/deprecated_features/redundant/run_time_loader.html

This feature was described as deprected and redundant. Is there another mechanism to load specific version of tbb at runtime.
I use it in some other library, which is used in an desktop app, but also in an plugin/extension of some third party software, which use oudated version of tbb. In this case I have to define the specific version which was linked to my library.

**Comment by alexey-katranov** [comment]
Unfortunately, no any direct replacement is planned. Taking into consideration that TBB 2020 is backward compatible till version 2.2, why it is required to load the old version of TBB? Can TBB 2020 be used in the application and plugin as well?

**Comment by przole** [comment]
Than you for your answer.
Our problem is by using tbb in third-party product, which use another version of tbb.
For example ESRI ArcGIS 10.x use version 4.1.0.0 (according to file version info) from 2013 (according to file version copyright info).
If we simply try to use our extension in ArcGIS, it tries to load this old version from the directory of the process executable, which is ArcGIS bin directory. To control this behaviour, we used runtime_loader, which was a part of tbb.
We always try to use a newest version of tbb and also c++ compiler.

**Comment by alexey-katranov** [comment]
It seems that the final application always has two TBB runtimes loaded into the process. While the target application uses old TBB, you can safely use oneTBB in your plugin/extension because oneTBB is not compatible with TBB and has different name (i.e. the both oneTBB and TBB will be loaded). What OS do you use?

**Comment by przole** [comment]
I use Windows. I see now, that the name of tbb dll has changed, so I can simply remove the runtime_loader part. Thanks!
