### ISSUE TITLE
Cannot find the tbb::atomic class 

### ISSUE THREAD

**Issue by JerryYan97** [oneapi-src/oneTBB#338]
Hello!

I am wondering in which header file can I find this atomic class?
oneapi/tbb.h is the header that I include in my project, but I am not able to find tbb::atomic or atomic class.
However, it looks like I also cannot find the place of it in this doc.
https://software.intel.com/content/www/us/en/develop/documentation/tbb-documentation/top/intel-threading-building-blocks-developer-guide/atomic-operations.html
Has it been deprecated?

Thanks

**Comment by kboyarinov** [comment]
Hello, @JerryYan97 

You are correct, `tbb::atomic` class (as well as multiple obsolete and compatibility features) was deprecated in TBB 2019 U9 (for more information see [TBB Revamp topic](https://community.intel.com/t5/Intel-oneAPI-Threading-Building/TBB-Revamp-Background-Changes-and-Modernization/td-p/1143528)). All of these features were removed in oneTBB 2021.

Consider using `std::atomic` as a replacement for `tbb::atomic`.

**Comment by JerryYan97** [comment]
Hi,
Thank you very much for your clarification! Besides, it looks like the doc in the link you provide doesn't work for me.
Besides, do you mean std::atomic is thread safety to operate for parallel_for or other parallel functions?
Thanks!

**Comment by alexey-katranov** [comment]
> Besides, it looks like the doc in the link you provide doesn't work for me.

Try another link: https://software.intel.com/content/www/us/en/develop/articles/tbb-revamp.html

> do you mean std::atomic is thread safety to operate for parallel_for or other parallel functions?

Yes, it is guaranteed with the C++ standard. See [cppreference](https://en.cppreference.com/w/cpp/atomic/atomic): "_If one thread writes to an atomic object while another thread reads from it, the behavior is well-defined (see memory model for details on data races)._"

**Comment by alexey-katranov** [comment]
@JerryYan97 , if you have any other questions, feel free to reopen the issue or start a new one.
