### ISSUE TITLE
Standalone OneAPI TBB is not fully compatible with Ubuntu 20.04

### ISSUE THREAD

**Issue by h6197627** [oneapi-src/oneTBB#340]
Intel OneAPI toolkits should be compatible with Ubuntu 20.04 LTS as stated [here](https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-base-toolkit-system-requirements.html)
However, standalone TBB package installed from [here](https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html#inpage-nav-10-5) is not fully compatible. **libtbbbind.so** library is linked with **libhwloc.so.5** shared library which is not accessible in Ubuntu 20.04 (it provides newer **libhwloc.so.12** library).

**Comment by h6197627** [comment]
Actually, the same problem with provided on github build library [oneapi-tbb-2021.1.1-lin.tgz](https://github.com/oneapi-src/oneTBB/releases/download/v2021.1.1/oneapi-tbb-2021.1.1-lin.tgz)

**Comment by alexey-katranov** [comment]
Thank you for the report. The issue is fixed in [2021.2.0-rc](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.2.0-rc) and in the master branch.

**Comment by h6197627** [comment]
Fixed with 2021.2, thanks @alexey-katranov!
Just one question: what the difference between libtbbbind_2_0.so and libtbbbind_2_4.so that both linked with libhwloc.so.15 from Ubuntu 20.04 and come with [standalone installer](https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html#inpage-nav-11-6)?

**Comment by h6197627** [comment]
Fixed with 2021.2, thanks @alexey-katranov!
Just one question: what the difference between libtbbbind_2_0.so and libtbbbind_2_4.so that both linked with libhwloc.so.15 from Ubuntu 20.04 and come with [standalone installer](https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html#inpage-nav-11-6)?

**Comment by alexey-katranov** [comment]
libtbbbind_2_4 is linked with hwloc 2.4 that supports for Intel(R) Hybrid Technology but hwloc 2.0 does not.
