### ISSUE TITLE
C2694 Error when compiling code with shared pointer to task_group

### ISSUE THREAD

**Issue by dahubley** [oneapi-src/oneTBB#356]
[ConsoleApplication5.zip](https://github.com/oneapi-src/oneTBB/files/6083843/ConsoleApplication5.zip)
The attached solution reproduces the error. The error appeared after updating to Visual Studio 2019 16.9.0 using TBB commit eca91f16d7490a8abfdee652dadf457ec820cc37.

**Comment by alexey-katranov** [comment]
I tried several versions of Visual Studio with the mentioned commit but I do not observe any issues with the provided code. Can you please share the error log? Thank you in advance.

**Comment by anton-potapov** [comment]
@dahubley is the problem still persist ?

**Comment by dahubley** [comment]
I'm not sure we wrapped the object in a class and haven't revisited the problem.
