### ISSUE TITLE
Cmake files in oneAPI Debian packages?

### ISSUE THREAD

**Issue by jomeng** [oneapi-src/oneTBB#363]
The packages available from the Intel Debian repository at https://apt.repos.intel.com/oneapi do not seem to include cmake config files.
One way to see this is that the list of files returned from
```
apt-rdepends intel-oneapi-tbb intel-oneapi-tbb-devel|grep -v "^ "|xargs dpkg -L
```
does not contain any `.cmake` files, or any files in `lib/cmake/tbb`. These files are present in the tarballs on the release page here on github. Can you add these files to the Debian packages?

**Comment by AlexVeprev** [comment]
@jomeng, yes, we're working with oneAPI apt repos maintainers on it, so CMake support is expected to be there in one of future releases.

**Comment by jomeng** [comment]
Thanks, @AlexVeprev !

**Comment by AlexVeprev** [comment]
@jomeng, have you checked the latest available release?

**Comment by jomeng** [comment]
Hi, yes, the latest version has `TBBConfig.cmake` as well as `TBBConfigVersion.make`. Thanks!
