### ISSUE TITLE
CMake: using tbb via add_subdirectory on Windows leaves the question where the DLLs are

### ISSUE THREAD

**Issue by christofmuc** [oneapi-src/oneTBB#366]
Hi! So far I had been using tbb as a binary download, but as I prefer using git submodules, I try to integrate any library that allows it to be included via add_subdirectory() and git submodule. Happy oneTBB does this now.

I couldn't wrap my mind around however how I can reliably find out where the DLLs are built on Windows (I need that to copy them out into the installer or just into the executable directory of the main program.)

The directory names are calculated in line 160 and around in the main oneTBB CMakeLists, but are not exported. Reproducing the naming seems to be fragile:

    set(CMAKE_${output_type}_OUTPUT_DIRECTORY_${_tbb_suffix_upper} ${CMAKE_BINARY_DIR}/${TBB_OUTPUT_DIR_BASE}_${_tbb_suffix_lower})

The official way seems to be using a cmake install, but that does not fit into the usage of oneTBB via add_subdirectory. As usual on Windows, just specifying oneTBB as target_link_lbraries() works, but won't copy the DLL to the place where it needs be. Happy to do that myself, but what is the correct variable containing the output name in the presence of multi-config build files for Visual Studio?

Concretely, currently I have hardcoded the path for Visual Studio 2017, but that breaks when I compile with Visual Studio 2019 because the compiler version number changes...

I might be missing the obvious?

**Comment by alexey-katranov** [comment]
@AlexVeprev, can you please look at the issue?

**Comment by AlexVeprev** [comment]
Hi @christofmuc,

Consider an approach with generator expression `$<TARGET_FILE:TBB::tbb>` in `add_custom_command`, here is an example based on [Fibonacci](https://github.com/oneapi-src/oneTBB/tree/master/examples/test_all/fibonacci):
```cmake
project(fibonacci CXX)

add_subdirectory(${TBB_ROOT} tbb)

find_package(Threads)
add_executable(fibonacci fibonacci.cpp)
target_link_libraries(fibonacci
                      TBB::tbb
                      Threads::Threads)

add_custom_command(TARGET fibonacci POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different
        $<TARGET_FILE:TBB::tbb>
        $<TARGET_FILE_DIR:fibonacci>
    )
```

Result with Visual Studio 2019:
```
> cmake -DTBB_ROOT=<my-tbb-root> -DTBB_TEST=OFF ..
-- Building for: Visual Studio 16 2019
...
> cmake --build . --config release
...
> dir Release
...
2021-05-07  10:55            56,320 fibonacci.exe
2021-05-07  10:55           301,568 tbb12.dll
...
> cmake --build . --config debug
...
> dir Debug
...
2021-05-07  10:57           301,568 fibonacci.exe
2021-05-07  10:57         1,861,216 fibonacci.ilk
2021-05-07  10:57         2,363,392 fibonacci.pdb
2021-05-07  10:57           864,256 tbb12_debug.dll
...
```

**Comment by AlexVeprev** [comment]
@christofmuc, I see your 👍 and consider the issue as resolved. Feel free to reopen it if you still have problems. Thanks!
