### ISSUE TITLE
tbb build error

### ISSUE THREAD

**Issue by etorth** [oneapi-src/oneTBB#369]
In file included from /home/anhong/oneTBB-2021.1.1/test/common/concurrent_unordered_common.h:24,
                 from /home/anhong/oneTBB-2021.1.1/test/tbb/test_concurrent_unordered_set.cpp:19:
/home/anhong/oneTBB-2021.1.1/test/common/concurrent_associative_common.h: In instantiation of ‘void test_scoped_allocator() [with ContainerTraits = CusetTraits]’:
/home/anhong/oneTBB-2021.1.1/test/tbb/test_concurrent_unordered_set.cpp:179:40:   required from here
/home/anhong/oneTBB-2021.1.1/test/common/concurrent_associative_common.h:1184:8: error: implicitly-declared ‘tbb::detail::d1::concurrent_unordered_set<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > >, std::hash<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > >, std::equal_to<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > >, std::scoped_allocator_adaptor<std::allocator<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > > > >& tbb::detail::d1::concurrent_unordered_set<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > >, std::hash<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > >, std::equal_to<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > >, std::scoped_allocator_adaptor<std::allocator<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > > > >::operator=(const tbb::detail::d1::concurrent_unordered_set<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > >, std::hash<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > >, std::equal_to<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > >, std::scoped_allocator_adaptor<std::allocator<AllocatorAwareData<std::scoped_allocator_adaptor<std::allocator<int> > > > > >&)’ is deprecated [-Werror=deprecated-copy]
 1184 |     c1 = c2;
      |     ~~~^~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [test/CMakeFiles/test_concurrent_unordered_set.dir/build.make:63: test/CMakeFiles/test_concurrent_unordered_set.dir/tbb/test_concurrent_unordered_set.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:816: test/CMakeFiles/test_concurrent_unordered_set.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

OS: WSL UBUNTU 20.04
cmake .. -DCMAKE_INSTALL_PREFIX=install -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Release
make -j 8
cmake version 3.16.3

**Comment by anton-potapov** [comment]
@etorth , this should be fixed in the upcoming release of oneTBB
