### ISSUE TITLE
tbb::task_group::wait returns before tasks are destroyed

### ISSUE THREAD

**Issue by Dr15Jones** [oneapi-src/oneTBB#371]
We are seeing very infrequent segmentation faults in our fast running unit tests (order 1 in 10,000 times unit test runs) which occur after the program's main has returned. We were finally able to capture a stack trace for one of the failing tests and it showed the destructor for the lambda passed to `tbb::task_group::run` was being called after main returned. This lambda had captured a `std::shared_ptr` to a resource that needs something that was missing after main returned. We surmised that the tests are being run on a heavily overutilized machine which caused the thread in question to be swapped out by the operating system. That thread was then swapped in after `tbb::task_group::wait` had finished. The unit tests run fast enough such that the time between the `tbb::task_group::wait` and the end of main is very short. Looking at the TBB internals, we found the likely culprit to be

https://github.com/oneapi-src/oneTBB/blob/eca91f16d7490a8abfdee652dadf457ec820cc37/src/tbb/custom_scheduler.h#L495-L497

We theorize that the compiler has switched the order of the call to `~task` and the following `if` which allows the tbb::task_group::wait to return before the child task is deleted. In addition, we think the thread in question just happens to be paused between those calls.

We would like to see this behavior addressed. Possible solutions which could work for us would be
- put a barrier between the call to `~task` and the `if` to prevent the compiler/hardware from reordering the calls, 
- provide an explicit mechanism to wait for all TBB threads to be in a _waiting_ state, or
- provide an explicit mechanism to shut down all TBB worker threads 

This occurs using TBB 2020 U3.

See https://github.com/cms-sw/cmssw/issues/33289#issuecomment-811882225 for the stack trace in question.

**Comment by alexey-katranov** [comment]
As I understand from the mentioned link, the issue is observer on x86_64 architecture. Theoretically, it is possible that refcount store is reordered earlier than dtor is called because there is no barrier before [`p.ref_count=0;](https://github.com/oneapi-src/oneTBB/blob/tbb_2020/src/tbb/custom_scheduler.h#L78).
Do you use pre-built binaries or do you build them from sources?

**Comment by Dr15Jones** [comment]
We build from source.

**Comment by Dr15Jones** [comment]
> Is it possible that task is run asynchronously to the wait?

That is very likely.

**Comment by alexey-katranov** [comment]
> We build from source.

You can try to add `__TBB_release_consistency_helper()` before  [`p.ref_count=0;`](https://github.com/oneapi-src/oneTBB/blob/tbb_2020/src/tbb/custom_scheduler.h#L78); however, it no-op on x86 and the compiler already cannot reorder virtual call with the assignment.  So, I would consider the supposition related to missed tasks.

I do not know your code well; however, [this code snippet](https://github.com/cms-sw/cmssw/blob/6029d3db5dce43bb95792bfc420042efc1da999c/FWCore/Concurrency/src/WaitingTaskWithArenaHolder.cc#L82-L87) can contain a logical race that task_group::wait cannot be safely used to wait for the task running inside enqueue task.
