### ISSUE TITLE
Using-declaration of assignment operators results in incorrect return type

### ISSUE THREAD

**Issue by Lastique** [oneapi-src/oneTBB#372]
There are a number of instances in oneTBB where the code imports `operator=` from a base class with a `using`-declaration. This is incorrect because the imported `operator=` that are not copy or move assignment operators will have the return type of a reference to the base class instead of the derived class. (For copy and move assignment operators the standard makes an exception, as in this case it forces the implicit generation of the assignment operators in the derived class instead of importing the operators from the base class, see [class.copy.assign]/8.) [Here](https://gcc.godbolt.org/z/orPPMEEjf) is a demonstration.

The solution is to define `operator=` in the derived classes explicitly for all argument types, and forward to the base class `operator=`. https://github.com/oneapi-src/oneTBB/pull/318 implements this for concurrent containers.

**Comment by alexey-katranov** [comment]
@kboyarinov, can you please look at the issue?

**Comment by anton-potapov** [comment]
It seems that only the following containers are affected : 
- [concurrent_unordered_map](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_unordered_map_cls.html) 
- [concurrent_unordered_multimap](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_unordered_multimap.html) 
- [concurrent_unordered_set](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_unordered_set_cls.html)
- [concurrent_unordered_multiset](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_unordered_multiset.html)
- [concurrent_map](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_map_cls.html)
- [concurrent_multimap](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_multimap_cls.html)
- [concurrent_set](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_set_cls.html)
- [concurrent_multiset](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_multiset_cls.html)
 
While specification for them is correct,  implementation is not. Conformance testing does not test for this as well.

**Comment by Lastique** [comment]
You forgot `concurrent_queue` and `concurrent_bounded_queue`. See https://github.com/oneapi-src/oneTBB/pull/318.

**Comment by anton-potapov** [comment]
@Lastique I believe `concurrent_queue` and `concurrent_bounded_queue` are covered by #373
