### ISSUE TITLE
Concurrent queue types don't define assignment operators

### ISSUE THREAD

**Issue by Lastique** [oneapi-src/oneTBB#373]
`concurrent_queue` and `concurrent_bounded_queue` define non-trivial copy and move constructor, but don't define assignment operators. The implicitly generated copy assignment will be incorrect for `concurrent_queue` and deleted (because of `std::atomic` member) for `concurrent_bounded_queue`, neither of which is expected by user.

Should be fixed by https://github.com/oneapi-src/oneTBB/pull/318.

**Comment by alexey-katranov** [comment]
@kboyarinov, can you please look at the issue and related pull request?

**Comment by anton-potapov** [comment]
while specification for [concurrent_queue](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_queue_cls.html)  and [concurrent_bounded_queue](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_bounded_queue_cls.html) are missing `operator=` in any form, it seems at least confusing as one for [concurrent_priority_queue](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_priority_queue_cls.html) has them.

**Comment by anton-potapov** [comment]
Specification patch for problem https://github.com/oneapi-src/oneAPI-spec/pull/396

**Comment by nofuturre** [comment]
@Lastique is this issue still relevant?

**Comment by Lastique** [comment]
No, it's fixed.
