### ISSUE TITLE
Make concurrent_vector ready for polymorphic allocators

### ISSUE THREAD

**Issue by mrks** [oneapi-src/oneTBB#38]
We are trying to use `tbb::concurrent_vector` with polymorphic allocators:

```
template <typename T>
using PolymorphicAllocator = boost::container::pmr::polymorphic_allocator<T>;
// this could also be std::experimental

template <typename T>
using pmr_concurrent_vector = tbb::concurrent_vector<T, PolymorphicAllocator<T>>;
```

Two problems come with this:

First, the vector tries to use the move allocator for the vector which was deleted by [p0337r0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0337r0.html). Since `propagate_on_container_move_assignment` is not set, the allocator should not be moved. Changing [concurrent_vector.h:745](https://github.com/01org/tbb/blob/tbb_2018/include/tbb/concurrent_vector.h#L745) from
```
            if (pocma_t::value) {
                this->my_allocator = std::move(other.my_allocator);
}
```
to
```
            if constexpr (pocma_t::value) {
                this->my_allocator = std::move(other.my_allocator);
}
```
would fix this.

Second, the vector is using `rebind` [here](https://github.com/01org/tbb/blob/tbb_2018/include/tbb/concurrent_vector.h#L471), which was deprecated in c++17. Any chance we can get rid of that?

**Comment by akukanov** [comment]
Apologies for long silence. We are working on support for polymorphic allocators, it will be available in a future update.

**Comment by nik-ponomarev** [comment]
@mrks, thanks for your observations regarding polymorphic allocators compilation failure with tbb::concurrent_vector. We have fixed issues that you mentioned in tbb::concurrent_vector, and rebind problem in other containers. Fixes will be available in the nearest release.

Note, that this is not full support of polymorphic_allocator (scoped allocators) and as Alexey said, we are working on proper support.

**Comment by alexey-katranov** [comment]
[The issue seems to be fixed](https://github.com/oneapi-src/oneTBB/blob/tbb_2020/CHANGES#L251-L252). Feel free to reopen the issue if it is still relevant.
