### ISSUE TITLE
Conda, major versions and backwards compatibility

### ISSUE THREAD

**Issue by karl616** [oneapi-src/oneTBB#380]
Is it correct to assume that backwards compatibility is broken between major release version of TBB? I'm asking as it seems you are using the release year as major version number.

I'm seeing this from the perspective of the conda community where currently older environments risk breaking if TBB wasn't specified correctly. Here is one example:

https://github.com/conda-forge/tbb-feedstock/issues/81

**Comment by alexey-katranov** [comment]
As for versions, there are four types of version and backward compatibility aspect:
1. The binary version is a part of the binary name or soname, e.g. 12. This version should be relatively stable. The previous change was around 2006. It provides the basic backward compatibility guarantee that you can update the binary without code recompilation. 
2. The product version is year based, e.g. 2021. The idea is that you cannot mix objects and interfaces from different product versions, i.e. the change of product version might require the recompilation of all interoperating components that use oneTBB. However, independent components can use different product version without any issues. The version is not going to be changed too often (I do not know if 2022 is introduced or we will continue with 2021). 
3. The interface version, e.g. 12030, specifies the available interfaces that can be check at compile time. In general. the code can rely that any greater version contains almost all interfaces of lower version. The major change was between TBB (<12000) and oneTBB (>=12000). 
4. Specification version, e.g. 1.0, specify the interfaces that are provided with accordance with the specification: https://spec.oneapi.com/versions/latest/elements/oneTBB/source/nested-index.html.

Note that the interface version and specification version can be independent, e.g. oneTBB specification can require more than a particular implementation of oneTBB provides and vise versa. Currently, oneTBB fully implements oneTBB specification 1.0 and provide additional interfaces described in https://software.intel.com/content/www/us/en/develop/documentation/onetbb-documentation/top/onetbb-api-reference.html

**Comment by karl616** [comment]
Thank you @alexey-katranov for the explanation

When digging further into this (and following in the footsteps of other), I learned that the two main channels I'm dependent on, conda-forge and bioconda will be pinning the oneTBB version. That should stop packages from being installed in an environment together with the wrong version of oneTBB. I will close this issue.
