### ISSUE TITLE
__TBB_mallocThreadShutdownNotification does not free memory

### ISSUE THREAD

**Issue by nkeemik** [oneapi-src/oneTBB#382]
When thread is detached (DLL_THREAD_DETACH) then memory localized to thread local storage is not freed. I am not sure whether this is by design, but I would expect OneTBB API available that allows to free memory when thread exits. 

The same applies to API `scalable_allocation_command` which also does not free the memory or allow memory area to be reused by new threads.

Below is an example code linked with tbbmalloc_proxy.dll, thread memory block allocated by std::string operator new is not freed when thread exits. It seems that mentioned "leaking" problem is present ever since. 

```cpp
#include <windows.h>
#include <thread>

#ifdef _WIN64
#pragma comment(linker, "/include:__TBB_malloc_proxy")
#else
#pragma comment(linker, "/include:___TBB_malloc_proxy")
#endif

#ifdef _DEBUG
#pragma comment(lib, "tbbmalloc_proxy_debug.lib")
#else
#pragma comment(lib, "tbbmalloc_proxy.lib")
#endif

static LONG counter;

void std_crt_test()
{
    InterlockedIncrement(&counter);
    std::string str("Thu, 01 Jan 1970 00:00:00 GMT");
    InterlockedDecrement(&counter);
}

int main(int argc, char** argv)
{
    for (int i = 0; i < INT32_MAX; i++) {
        std::thread* t = new std::thread(std_crt_test);
        if (t) {
            t->join();
            delete t;
        }
    }

    printf("OK: %d\n", counter);

    return 0;
}
```

**Comment by alexey-katranov** [comment]
I run the example and wait for several minutes. The consumed memory on my machine remained flat. Can you explain how do you detect the observed leak?

**Comment by nkeemik** [comment]
Indeed, it is a non-issue. I was experimenting with project defines (/D "__TBB_SOURCE_DIRECTLY_INCLUDED") and accidentally enabled this setting for tbbmalloc.dll. DllMain@tbbmalloc.dll was never called and caused a leak on every thread shut down.
