### ISSUE TITLE
Stack traces are disconnected when using resumable tasks

### ISSUE THREAD

**Issue by gartung** [oneapi-src/oneTBB#384]
Since CMSSW moved to using resumable tasks the results of cpu usage with our profiler [Igprof](https://github.com/igprof/igprof) have been incorrect. The reported cpu usage is on the order of 10% of the actual cpu usage. Perf was also tried but the cumulative cpu usage for functions did not add up. Profiling was also done with vtune. While vtune correctly accounts for the total cpu usage, the top down view show a majority of the cpu usage as `Skipped stack frame`.

**Comment by gartung** [comment]
Some examples of Igprof output using TBB test executables
[test_resemable_tasks from TBB 2020U4](https://gartung.web.cern.ch/gartung/cgi-bin/igprof-navigator/igprof.test_resumable_tasks.exe.14068.1618500634.783341/cumulative)
[test_resumable_tasks from onTBB 2021.2](https://gartung.web.cern.ch/gartung/cgi-bin/igprof-navigator/igprof.test_resumable_tasks.27454.1618527749.254239/cumulative)
Igprof captures the cpu perf signal to sample calls stack and libunwind to find the corresponding function calls.

**Comment by gartung** [comment]
Before the switch to Igprof reported the cumulative cpu usage correctly in [CMSSW_11_3_0_pre4](http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_11_3_0_pre4/23434.21/step3/cpu_endjob) when counting from `_start_main`.

After the switch the resumable tasks Igprof reported the cumulative cpu usage incorrectly in [CMSSW_11_3_0_pre5](http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_11_3_0_pre5/23434.21/step3/cpu_endjob)

Notice the cumulative cpu usage for CMSSW_11_3_0_pre4 was ~8000s while the cumulative cpu usage for CMSSW_11_3_0_pre5 was ~130s.

**Comment by gartung** [comment]
Example of vtune report
![image](https://user-images.githubusercontent.com/4292184/115908104-53b94100-a42f-11eb-9855-a83e1b3c27b3.png)

**Comment by gartung** [comment]
The igprof trace with usleep(10) inserted in the dummy_body so more sampling could be done. 
https://gartung.web.cern.ch/gartung/cgi-bin/igprof-navigator/igprof.test_resumable_tasks.15843.1619227899.482519/cumulative

**Comment by gartung** [comment]
From the [comment in the igprof code ](https://github.com/igprof/igprof/blob/03d16c15bd970256affcfde9e510a8404856b233/src/profile-perf.cc#L269) it seems that igprof does not count the time in clone().

**Comment by gartung** [comment]
Vtune at least record the time under clone().
![image](https://user-images.githubusercontent.com/4292184/116111756-90c64300-a67c-11eb-8db4-4073266d523d.png)

**Comment by alexey-katranov** [comment]
I suppose that resumable tasks involve stack manipulation with `ucontext`, it might cause unexpected issues with profiling tools. The issues can be caused  when the same thread is switching between different tasks that access the same tls inside the tool, i.e. the tool can observe unexpected order of tls changes.

**Comment by gartung** [comment]
It looks like igprof implemented its own set_context function to swap back and forth from the igprof thread to the process thread.
https://github.com/igprof/igprof/blob/03d16c15bd970256affcfde9e510a8404856b233/src/hook.cc#L1135
 According this page early implementations of getcontext/setcontext used setjump/longjump
https://man7.org/linux/man-pages/man3/setcontext.3.html

**Comment by gartung** [comment]
It appears that when the coroutine is created the parent context is set to 0
https://github.com/oneapi-src/oneTBB/blob/9e15720bc7744f85dff611d34d65e9099e077da4/src/tbb/co_context.h#L176
Whereas an example call to sets the parent context to the main context
https://en.wikipedia.org/wiki/Setcontext

**Comment by gartung** [comment]
It appears that when the coroutine is created the parent context is not saved
https://github.com/oneapi-src/oneTBB/blob/9e15720bc7744f85dff611d34d65e9099e077da4/src/tbb/co_context.h#L176
I think this would explain the disconnected stack traces.

**Comment by gartung** [comment]
https://man7.org/linux/man-pages/man3/makecontext.3.html

**Comment by alexey-katranov** [comment]
In the example, `uc_link` is used to specify where the coroutine should return when its function is completed. In oneTBB runtime, we do not know where to return in advance because coroutines are executed independently from each other and successor depends on execution flow.

**Comment by gartung** [comment]
I have changed igprof to track pthread_create from GLIBC_2.2. The test executable with usleep added now shows the same undercounting of time. Where the job takes 16s to run the cumulative cpu some 0.16s.
https://gartung.web.cern.ch/gartung/cgi-bin/igprof-navigator/igprof.test_resumable_tasks.4593.1619555720.824390/cumulative

**Comment by gartung** [comment]
Igprof does not handle the context swapping with the coroutines correctly. Google perftools profiler library produces output that correctly accounts for the context swapping.

**Comment by gartung** [comment]
When the coroutine is create the parent link is set to 0
When the coroutine is swapped back the thread exits after running the task. (edited) 
The IgProf threadWrapper sees the task return and disables the profiling timer.
https://github.com/igprof/igprof/blob/03d16c15bd970256affcfde9e510a8404856b233/src/profile.cc#L835
Gperftools does not ever disables the profiling timer on the main thread. Per thread timers can be enabled and are deleted when the thread exits.
