### ISSUE TITLE
Replacement for tbb::task:enqueue() that works in TBB 2019?

### ISSUE THREAD

**Issue by e4lam** [oneapi-src/oneTBB#389]
I'm trying to prepare our code base for future oneTBB versions and we're not ready to upgrade from TBB 2019 yet. So we would first like to move to the modern interfaces in TBB 2019 before upgrading.

One thing I'm not sure about is how do we replace tbb::task::enqueue() for "fire and forget" tasks? The closest I seem to think seems to be `tbb::task_arena::enqueue()` but initialize it to attach to the current task_arena first?

**Comment by alexey-katranov** [comment]
Consider the following approach (similar to https://github.com/oneapi-src/oneTBB/pull/367/files#diff-fde67e470af2b8fe40395abc14e0b4f6faef97faaa4ac29151187e8a424b54b5R451-R454):
```
template <typename F>
void enqueue(F&& f) {
    task_arena arena( task_arena::attach {});
    return arena.enqueue(std::forward<F>(f));
}
```

**Comment by e4lam** [comment]
That's what I was already doing. Thank you for the confirmation!
