### ISSUE TITLE
Possible arena object leak in single threaded environment

### ISSUE THREAD

**Issue by alexey-katranov** [oneapi-src/oneTBB#396]
The following code snippet might lead to the leak of internal arena object on a serial machine:
```
    const int numThreads = 4;
    tbb::global_control init(tbb::global_control::max_allowed_parallelism, numThreads);
    tbb::task_arena a(numThreads);
    a.execute([&] {
        tbb::parallel_for(0, N, [](int){...});
    });
```
The root cause is that the internal arena expects a worker thread to clean up its state (change state from FULL to EMPTY) when initialized with more than zero workers. The initial design supposed that the number of workers cannot be dropped at zero in runtime. Therefore, after destruction of global control object on a serial machine there is no available workers and the arena will not be destroyed.

Note, if arena is initialized with zero workers, it is not issue because it will not expect a worker for cleanup.

**Comment by pavelkumbrasev** [comment]
Should be fixed with PR#758
