### ISSUE TITLE
Feature request: rewrite index.html files in README.md format

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#4]
GitHub does not show index.html as directory description and reading index.html files is hard in plain text.
Markdown (.md) syntax is clean for direct reading (and maintaining!) and also converts easily to .html preserving all the formatting features.

E.g. online converter is here: https://pandoc.org/try/?text=&from=html&to=markdown_github

**Comment by tbbdev** [comment]
It will be hard to support two versions of documentation. We need to think how to make it optimal.

**Comment by svenevs** [comment]
How is the documentation generated?  It looks like doxygen is used (some `@ingroup` going on), but I couldn't actually find any of the tools in this repo to generate the docs.  FWIW, you can just add the markdown files to `INPUT` with doxygen.

**Comment by aleksei-fedotov** [comment]
It seems GitHub can render .rst file format as well. oneTBB is moving in this direction. So, this will be automatically covered. Therefore, I think the issue can be closed. Interested people could reopen it if they deem useful.
