### ISSUE TITLE
Idea: enable direct contributions to github via license agreement CI stage

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#40]
Please take a look how conda implements this (e.g. [here](https://github.com/conda/conda-build/pull/2513)) through additional CI stage "clahub" linked to https://www.clahub.com/agreements/conda/conda-build

**Comment by AlekSi** [comment]
Alternatively, you may want to use https://cla-assistant.io/

**Comment by anton-potapov** [comment]
@anton-malakhov I believe this is no longer applicable ? (as pull requests are welcome and CI is run on every of it)
can you close it ?

**Comment by anton-malakhov** [comment]
It is not about whether PRs are welcome, it is about license agreement. Closing anyway.
