### ISSUE TITLE
missing parallel_do.h in tbb 2021

### ISSUE THREAD

**Issue by mahrud** [oneapi-src/oneTBB#416]
I can't find any reference to this in the change logs, release notes, or the git history, and online documentation doesn't make any mention of any transitions or backwards incompatible changes involving this. Am I missing something?

**Comment by alexey-katranov** [comment]
It was removed as a part of [TBB revamp](https://software.intel.com/content/www/us/en/develop/articles/tbb-revamp.html). The direct replacement is `parallel_for_each`. I hope it will not cause difficulties to replace.

**Comment by mahrud** [comment]
I see, thank you! Certainly knowing the intended replacement for a deprecation helps. I was just surprised because I hadn't been seeing deprecation warnings about `parallel_do`, but now looking for "revamp" I definitely see references that I had missed.

**Comment by alexey-katranov** [comment]
It seems we missed deprecation warnings in TBB 2020. The motivation was that `parallel_do` is almost duplication of `parallel_for_each` and was inefficient for random access iterators. Therefore, we extended `parallel_for_each` with feeder and `parallel_for_each` is optimized for random access iterators.
