### ISSUE TITLE
Integrate static library failed

### ISSUE THREAD

**Issue by willkk** [oneapi-src/oneTBB#418]
I compiled static library by making modification like this :
![image](https://user-images.githubusercontent.com/17777977/119806134-7f3eb800-bf14-11eb-8e87-4e630c4e5659.png)

And then I integrated the 3 output files to my program: `libtbb.a`, `libtbbmalloc.a`, `libtbbmalloc_proxy.a`. But it complained this when linking:
```
/root/projects/ResMgr/src/third_party/tbb/slib/libtbbmalloc.a(tbbmalloc.cpp.o): In function `tbb::detail::r1::assertion_failure(char const*, int, char const*, char const*)':
/root/projects/ResMgr/src/third_party/tbb/src/tbbmalloc/../tbb/assert_impl.h:62: multiple definition of `tbb::detail::r1::assertion_failure(char const*, int, char const*, char const*)'
/root/projects/ResMgr/src/third_party/tbb/slib/libtbb.a(misc.cpp.o):/root/projects/ResMgr/src/third_party/tbb/src/tbb/assert_impl.h:62: first defined here
/root/projects/ResMgr/src/third_party/tbb/slib/libtbbmalloc.a(tbbmalloc.cpp.o): In function `tbb::detail::r1::runtime_warning(char const*, ...)':
/root/projects/ResMgr/src/third_party/tbb/src/tbbmalloc/../tbb/assert_impl.h:77: multiple definition of `tbb::detail::r1::runtime_warning(char const*, ...)'
/root/projects/ResMgr/src/third_party/tbb/slib/libtbb.a(misc.cpp.o):/root/projects/ResMgr/src/third_party/tbb/src/tbb/assert_impl.h:77: first defined here
```
After some checking, I found that `src/tbb/misc.cpp` did not use `assert_impl.h` at all. Then I commented out this line, and it worked.
![image](https://user-images.githubusercontent.com/17777977/119807119-6a165900-bf15-11eb-942f-1159046fc36d.png)

**Comment by willkk** [comment]
The definition and implementation can be put into separate files.

**Comment by alexey-katranov** [comment]
It will not help because the implementation is used for all three libraries (tbb, tbbmalloc, tbbmalloc_proxy) and we do not want them to have dependency on each others. I.e. even separated into special file, this file will be compiled into each of these libraries and symbols will be duplicated.

**Comment by isaevil** [comment]
@willkk Since 2021.5 oneTBB can be compiled statically without issues just using `cmake -DBUILD_SHARED_LIBS=OFF`.
 If any other questions are left, feel free to reopen this issue.
