### ISSUE TITLE
oneTBB documentation location is confusing/messy, documentation search gives many broken links

### ISSUE THREAD

**Issue by aggieNick02** [oneapi-src/oneTBB#421]
Trying to find/use the up-to-date documentation for oneTBB is currently pretty frustrating. The following are the hurdles a user will hit:

1. Many google queries lead to a result that no longer exists and redirects to the main oneTBB github page (which doesn't have the info the user is seeking). For example "tbb flow lightweight" has top reasult of https://www.threadingbuildingblocks.org/docs/help/reference/flow_graph/lightweight_policy.html with clearly useful information in the search preview snippet. But clicking that link just gets you to the main oneTBB github page.
2. The documentation linked from the main github page seems to be missing information other locations have. For example, I cannot find most of the information about the lightweight policy from https://spec.oneapi.com/versions/0.5.0/oneTBB/flow_graph/lightweight_policy.html anywhere at https://software.intel.com/content/www/us/en/develop/documentation/onetbb-documentation/top.html 
3. Document search at what seems to be the main documentation page gives a good number of broken links. If you search for "lightweight" via the left column document search at https://software.intel.com/content/www/us/en/develop/documentation/onetbb-documentation/top.html, you'll get 10 results. 9 of them lead to "Oops not found!" pages.

**Comment by omalyshe** [comment]
@aggieNick02 , thanks for your feedback. 
threadingbuildingblocks.org site is deprecated. Unfortunately, Google cache that is still refering to it is out of our control. 

The main GitHub page misses the link to [oneTBB Specification](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/nested-index.html) where you can find information about lightweght policy - [search results ](https://spec.oneapi.com/versions/latest/search.html?q=lightweight&check_keywords=yes&area=default). We will update the main page with the link to the Spec. 

Please, don't rely on the older versions of oneAPI Spec - your link above is for version 0.5 whereas the current Spec version is 1.0.

We will try to fix the issue with the outdated cache for oneTBB documentation ("Oops not found!" issue).

**Comment by aggieNick02** [comment]
Thanks for the quick response. Understood on the google cache issue. Hopefully the stale results will disappear eventually. I noticed today that while the old site is still the top result, the option to view the cached page is now gone, so it may just be a matter of time until it is gone completely. There may be steps the owners of threadingbuildingblocks.org could take to have it happen faster to basically let google now that the entire site is now just a redirect to the oneTBB github page.

Thank you for the info on the later version of the oneTBB spec. This is a problem that other code documentation seems to suffer from too. I got the link to the 0.5 version as the 3rd result for "tbb flow lightweight" and didn't know it was old/stale. The same kind of issue happens when searching for boost documentation - the result is almost always not current. For example, for "boost noncopyable", the top result is for an old version of boost:
https://www.boost.org/doc/libs/1_65_0/libs/core/doc/html/core/noncopyable.html

The boost documentation is made so that all of the stale docs actually have a big notice at the top pointing the user to the current version of the same page. A similar approach could be usefult for the oneTBB spec.
![image](https://user-images.githubusercontent.com/16806169/120363901-46b32b80-c2d2-11eb-9b89-46e16eab36ce.png)
I also imagine that having links to the curreent oneTBB spec from prominent places like the github page will eventually lead to the current oneTBB spec ranking higher than an old version like 0.5.

Thanks again!

**Comment by alexandraepan** [comment]
@omalyshe Should we close this issue? We have added the link to the new version of specs and the old one should be deprecated  by Robert.

**Comment by omalyshe** [comment]
Yes, this can be considered as fixed. 
@aggieNick02 Feel free to open the new one if you find any inconsistences.
