### ISSUE TITLE
tbb config picks up CUDA on macOS

### ISSUE THREAD

**Issue by davydden** [oneapi-src/oneTBB#44]
subj. AFAIK `tbb` does not use CUDA anyhow, there is a suggestion here on how to workaround this issue https://github.com/spack/spack/issues/6000#issuecomment-358817701 which might be a hint to a proper solution.

**Comment by alexey-katranov** [comment]
Thank you for the report. We will try to fix the issue in one of the future releases.

**Comment by alexey-katranov** [comment]
[The issue was fixed](https://github.com/oneapi-src/oneTBB/blob/tbb_2020/CHANGES#L116-L117). If the issue persists, feel free to reopen it.
