### ISSUE TITLE
No CMakeLists.txt found in 2020 update 2

### ISSUE THREAD

**Issue by joeyskeys** [oneapi-src/oneTBB#455]
hi guys,

I tried to build release 2020 update 2, there's a Makefile in the release and I can build it fine, but no install target included.
Is it by accident the CMakeLists.txt is not included or is there another way to configure and build it?

Thanks.

**Comment by alexey-katranov** [comment]
TBB 2020 does not support CMake as a build system. Consider using make: https://github.com/oneapi-src/oneTBB/blob/tbb_2020/index.html#L16 or oneTBB that supports CMake.

**Comment by joeyskeys** [comment]
@alexey-katranov hi Alex, is there anyway to install this version of tbb into another place? I think by writing a bash file can do it
But I'm a little bit confused about the header file structure, it's kinda different from 2021.2.0.
For example, in 2020 update 2, there's source file like **thread.c** in include/tbb/compat/thread.c which should not be included in the include directory of a installation.
I guess by copying all the header file in src/include folder into a include directory will be fine?

**Comment by AlexVeprev** [comment]
Hi @joeyskeys, public headers for TBB 2020.2 are located in `include` folder (https://github.com/oneapi-src/oneTBB/tree/v2020.2/include), so they should be used during the installation. Do you mean `thread` without extension? https://github.com/oneapi-src/oneTBB/blob/v2020.2/include/tbb/compat/thread. It looks like header file, but not source code file, so it's fine to install it with headers.

BTW, do you need to build and install TBB or you can consider installing pre-built packages?

**Comment by joeyskeys** [comment]
Hi @AlexVeprev , I'm trying to build a [rez](https://github.com/nerdvegas/rez) package for tbb which will need to build tbb from source.
And according to the [industry reference](https://vfxplatform.com/) the specific version of tbb 2020.2 is chosen, hence the issue.
Currently I'm trying to write a custom CMakeLists file for this version and make a patch for it.

**Comment by AlexVeprev** [comment]
@joeyskeys it is not documented approach and may not be suitable, but you may want to take a look at https://github.com/oneapi-src/oneTBB/blob/v2020.2/build/build.py

This script allows to install TBB 2020 and older versions, e.g. it was used to prepare conda packages in conda-forge channel: https://github.com/conda-forge/tbb-feedstock/blob/2020.2/recipe/meta.yaml#L14

**Comment by joeyskeys** [comment]
@AlexVeprev exactly what I need, thank you so much.
This issue could be closed.
