### ISSUE TITLE
Release builds spill full paths

### ISSUE THREAD

**Issue by ArturoBlas** [oneapi-src/oneTBB#46]
`__TBB_ASSERT_RELEASE` as defined in `tbb_stddef.h` uses the `__FILE__` macro regardless of the build type, generating binaries that contain the full path of the file invoking the macro at compile time, which may contain user information.

The way the `version_info.ver` file is generated by passing the full compiler command line also generates full paths that are embedded into the final binaries, regardless whether the library is build as a dynamic library or linked statically against another executable.

**Comment by ivankochin** [comment]
Thanks for reporting and sorry for the late response!

The full paths were removed from assertions, please try the fix that already available at the [master](https://github.com/oneapi-src/oneTBB/tree/master) branch. Please reopen the issue if this problem still exists or the fix isn't suitable for you.
