### ISSUE TITLE
How to compile oneTBB with Emscritpen?

### ISSUE THREAD

**Issue by dpar39** [oneapi-src/oneTBB#460]
Is it possible to compile oneTBB with Emscripten? There are third party libraries using oneTBB and it would be nice to get them to compile without changing the source code.

**Comment by alexey-katranov** [comment]
I do not know if someone using oneTBB with Emscripten. Have you tried to build as is?

**Comment by nofuturre** [comment]
@dpar39 is this issue still relevant?

**Comment by nofuturre** [comment]
If anyone encounter this issue in the future please open new issue with a link to this one
