### ISSUE TITLE
TBB needs pkg-config or similar interface for easy embedding into applications

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#5]
Continuum Analytics feedback: Exposing a `pkg-config` interface for TBB, or something similar (such as `llvm-config`), sounds like a good way to avoid hard-coding environment-related definitions in every third party project.
TBBROOT is not enough in order to configure application with correct compiler and linker flags needed to build an application which uses TBB.
See the issues related in this PR: https://github.com/numba/numba/pull/2217#pullrequestreview-11784936

For more information see https://people.freedesktop.org/~dbn/pkg-config-guide.html
It can be done for binary TBB package and can be generated as yet another kind of tbbvars during the build from sources

**Comment by KFilipek** [comment]
Hi,
Are there still plans for introducing pkg-config files into TBB?
Few our engines depend on the TBB and pkg-config will significantly improve experience while working with custom installation paths.
Best regards,
Krzysztof Filipek

**Comment by AlexVeprev** [comment]
Hi @KFilipek, thank you for reminding about this issue! I don't have any experience in writing pkg-config files, but I can investigate this topic. It may require some time since I'm pretty busy with other activities; feel free to submit a PR or just put a snapshot here if you already have something as your local solution.

**Comment by AlexVeprev** [comment]
@KFilipek, let me duplicate the question from PR #361:
> Is it enough for you to have pkg-config support for build from sources only? Are you interested in having it in prebuilt packages from release page (not sure how to dynamically get prefix value in this case)?

**Comment by AlexVeprev** [comment]
oneAPI packages (including oneTBB) now have support of pkg-config.

**Comment by nh2** [comment]
How does it apply to `tbbmalloc`, can that also be easily configured/linked with using the added `pkg-config` support?
