### ISSUE TITLE
Building with nvhpc

### ISSUE THREAD

**Issue by payerle** [oneapi-src/oneTBB#514]
I was trying to build intel-tbb version 2018.3 (although I have seen similar issues for versions 2017 through 2020.3) using the nvc compiler from nvhpc (version 21.5), and I am running into some issues.  (I am using spack as the build environment, but the issues are general).  This is on linux (RHEL8.3) on a x86_64 VM.

Although I notice that the documentation does not list nvhpc as a supported compiler, I thought I would share my experiences in the hopes that it would help others, and/or that nvhpc could become a supported compiler.

The intel-tbb build infrastructure seems to think that it is building for gcc; i.e. the build/linux.gcc.inc is being used.  I am not positive, but I think that the common.inc et al only check for intel compilers, and if not using intel compilers default to gcc.
I was able to successfully compile intel-tbb using nvhpc (and successfully compiled/ran some test codes using intel-tbb)  by making some minor edits to the linux.gcc.inc file --- obviously a proper solution is to use a linux.nvc.inc file but it was not obvious to me how to get the build infrastructure to use such.  However, I will describe my linux.gcc.inc modifications, which should be useful in generating the linux.nvc.inc file.

The main issue encountered causes errors like:
/software/spack/git.2021.04.28/lib/spack/env/nvhpc/nvc++ -fPIC -o libtbb_debug.so.2 concurrent_hash_map.o concurrent_queue.o concurrent_vector.o dynamic_link.o itt_notify.o cache_aligned_allocator.o pipeline.o queuing_mutex.o queuing_rw_mutex.o reader_writer_lock.o spin_rw_mutex.o x86_rtm_rw_mutex.o spin_mutex.o critical_section.o mutex.o recursive_mutex.o condition_variable.o tbb_thread.o concurrent_monitor.o semaphore.o private_server.o rml_tbb.o tbb_misc.o tbb_misc_ex.o task.o task_group_context.o governor.o market.o arena.o scheduler.o observer_proxy.o tbb_statistics.o tbb_main.o concurrent_vector_v2.o concurrent_queue_v2.o spin_rw_mutex_v2.o task_v2.o   -ldl -lpthread -lrt -shared -Wl,-soname=libtbb_debug.so.2 -m64  -Wl,--version-script,tbb.def
/bin/ld:tbb.def:12: syntax error in VERSION script

This appears to be due to the use of the C preprocessor to generate the tbb.def.  In particular, the nvhpc compilers by preinclude some header files when compiling; the contents of these header files is output when nvc++ is invoked with -E flag (preprocessor output mode), causing extraneous output in the VERSION scripts.  This can be rectified by adding the -no_preincludes flag to the PREPROC_ONLY makefile variable (i.e. PREPROC_ONLY = -E -x c++ --no_preincludes)

The linux.gcc.inc file also sets a number of compiler flags which nvc/nvc++ do not recognize (and by default will cause them to abort); namely
        WARNING_SUPPRESS = -Wno-parentheses -Wno-non-virtual-dtor
        DSE_KEY = -flifetime-dse=1
        and -fno-rtti in M_CPLUS_FLAGS
One can also pass the nvc flag '-noswitcherror' to change the behavior when an unrecognized flag is encountered (instead of being a fatal error it just generates a warning).

**Comment by AlexVeprev** [comment]
Hi @payerle,

A couple of generic questions:

1. Why do you need to build TBB with nvhpc? Have you considered use of prebuilt TBB compiling your application with nvhpc? 
2. Have you considered use of oneTBB 2021? It has CMake build system instead of pure Makefiles. It still may require some modifications to support nvhpc, but they may be more straightforward.

**Comment by payerle** [comment]
Thanks for your suggestion of looking at 
OneAPI version of TBB.

Spack indeed has a recipe for such (which appears to be downloading a prebuilt version) which seems to work for nvhpc.

You can close this ticket.

**Comment by AlexVeprev** [comment]
You are welcome!
