### ISSUE TITLE
Information on __TBB_PREVIEW_FLOW_GRAPH_NODE_SET

### ISSUE THREAD

**Issue by sbalint98** [oneapi-src/oneTBB#535]
Hi, 

While browsing the source code I came across this macro definition. This might be interesting for my use case, but unfortunately, unlike for the  `TBB_PREVIEW` macros, I couldn't find documentation for the `__TBB_PREVIEW` macros. Is there somewhere documentation available for these macros as well?

**Comment by alexey-katranov** [comment]
Any macros starting with `__TBB` are internal and not supposed to be used by oneTBB users. Their semantics can be changed without prior notification that might break user code.

Typically, `__TBB_PREVIEW` macros guard implementation of corresponding features enabled with `TBB_PREVIEW` macros.

**Comment by sbalint98** [comment]
Alright, thank you for your detailed answer!
