### ISSUE TITLE
Is TBB supported on ARM architecture？

### ISSUE THREAD

**Issue by jqu1549** [oneapi-src/oneTBB#539]
Hi all, generally my application using TBB runs on x86 architecture virtual machines. Under several cases, ARM architecture virtual machines have lower cost than x86 ones. However, is TBB supported on ARM? We are specially focusing on parallels for and pipeline.

**Comment by alexey-katranov** [comment]
oneTBB is supported by open source community on ARM. You can try to use oneTBB on your systems and if any issues feel free either to open an issue or propose a pull request.

**Comment by jqu1549** [comment]
Thanks!
