### ISSUE TITLE
Can get native thread id of a tbb thread in linux

### ISSUE THREAD

**Issue by JackYangzg** [oneapi-src/oneTBB#540]
hi, all
      Can get native thread id of a tbb thread in linux

**Comment by alexey-katranov** [comment]
What do you mean with "tbb thread"? Do you speak about deprecated `tbb_thread` or worker threads created by oneTBB to execute parallel algorithms? Have you considered `pthread_self`?

**Comment by anton-potapov** [comment]
@JackYangzg could you please specify your use case in more details ?

**Comment by anton-potapov** [comment]
@JackYangzg please reopen if needed
