### ISSUE TITLE
memory leak in sudoku example

### ISSUE THREAD

**Issue by kirkshoop** [oneapi-src/oneTBB#568]
https://github.com/oneapi-src/oneTBB/blob/40a9a1060069d37d5f66912c6ee4cf165144774b/examples/task_group/sudoku/sudoku.cpp#L238

This cancel in partial_solve does not run any of the pending tasks and thus they are not able to free the pending board allocations.

Even though the program exits, I would like it to show the idiomatic way to scope memory when cancel is used.

**Comment by anton-potapov** [comment]
@kirkshoop , IMHO idiomatic way of doing this drop manual memory management in favor of using [RAII](https://en.cppreference.com/w/cpp/language/raii) , e.g. with [std::unique_ptr](https://en.cppreference.com/w/cpp/memory/unique_ptr)  or [std::vector](https://en.cppreference.com/w/cpp/container/vector) int this particular case,  and [std::move](https://en.cppreference.com/w/cpp/utility/move) it into lambda capture (via C++14  feature of lambda capture initializers)

**Comment by kirkshoop** [comment]
That sounds great. I wondered if there was something like cleanup groups that did not depend on destructors.

**Comment by anton-potapov** [comment]
@Iliamish could you please take a look ?
