### ISSUE TITLE
2021.3.0 mac binary: libtbbmalloc has incorrect version number

### ISSUE THREAD

**Issue by TrevorThomson** [oneapi-src/oneTBB#577]
The oneapi-tbb-2021.3.0-mac.tgz file contains a libtbbmalloc with an incorrect version number, namely **libtbbmalloc.3.dylib** should be **libtbbmalloc.2.dylib**.

```
> tar -xzvf oneapi-tbb-2021.3.0-mac.tgz
> ls oneapi-tbb-2021.3.0/lib/libtbbmalloc.*
oneapi-tbb-2021.3.0/lib/libtbbmalloc.2.3.dylib* oneapi-tbb-2021.3.0/lib/libtbbmalloc.dylib@
oneapi-tbb-2021.3.0/lib/libtbbmalloc.3.dylib@
```
Thanks!

**Comment by omalyshe** [comment]
@TrevorThomson Thanks for reporting this issue. It should be resolved now. Can you please check?

**Comment by TrevorThomson** [comment]
Confirmed!  I'm able to successfully link to libtbbmalloc, now.  Thanks!
