### ISSUE TITLE
FetchContent_Declare fails to make available the project

### ISSUE THREAD

**Issue by gazsiazasz** [oneapi-src/oneTBB#587]
This line 
https://github.com/oneapi-src/oneTBB/blob/261fe22630bd61ec137b66f6dd4403ad7ab36a14/src/tbb/CMakeLists.txt#L140
should be changed to: 
`configure_file(${PROJECT_SOURCE_DIR}/integration/pkg-config/tbb.pc.in ${CMAKE_CURRENT_BINARY_DIR}/${TBB_LIB_NAME}.pc @ONLY)
`

It works, but not tested what else should be changed.

**Comment by vlserov** [comment]
Issue has been resolved with #476 
Please verify in [v2021.4.0-rc1](/oneapi-src/oneTBB/releases/tag/v2021.4.0-rc1) release
