### ISSUE TITLE
Error in dbghelp.h when building tests with MSVC 2019 v16.11.5

### ISSUE THREAD

**Issue by emmenlau** [oneapi-src/oneTBB#627]
Thanks for the awesome library. I get a minor build error on Windows with Visual Studio 2019 v16.11.5:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\dbghelp.h(91): error C3646: 'ModuleName': unknown override specifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\dbghelp.h(91): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\dbghelp.h(92): error C3646: 'hFile': unknown override specifier
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\dbghelp.h(92): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
[...]
```

A quick google search shows that supposedly one must include `windows.h` before `dbghelp.h` to get rid of these errors.

I have tried to include `windows.h` before `dbghelp.h` and I'm under the impression that the build then continues further. However I can not get a full build to work (yet) due to #628, so I can not say with certainty that the problem is resolved.

**Comment by phprus** [comment]
PR #603 fixes this problem
