### ISSUE TITLE
concurrent_multiset/concurrent_set crashes when using unsafe_erase()

### ISSUE THREAD

**Issue by MaxPHPer** [oneapi-src/oneTBB#636]
My code is as follows, I use .begin() to get the first element in the set, and it can be obtained correctly, but using .unsafe_erase(iterator) will often crash. Of course, the first line（WriteGuard)  is a write lock.

<img width="1223" alt="WX20211031-003532@2x" src="https://user-images.githubusercontent.com/16571895/139541682-9507b850-cb95-4686-a7bd-a514223f3373.png">
<img width="1295" alt="WX20211031-004603@2x" src="https://user-images.githubusercontent.com/16571895/139541855-ce1471b1-42b7-4336-a0e8-12d26a10178c.png">

I don't know why this happens, can someone give me some suggestions, thanks in advance

**Comment by anton-potapov** [comment]
@MaxPHPer what version of TBB is used ?

**Comment by MaxPHPer** [comment]
> @MaxPHPer what version of TBB is used ?

Thank you for your reply. I can not find the version from the code, but I find the README.md as follows.
![WechatIMG7](https://user-images.githubusercontent.com/16571895/139649787-4102c813-62e1-40be-8836-c9bcf1a73479.jpeg)

**Comment by vinser52** [comment]
@MaxPHPer Could you please elaborate, if `m_topLevel_restricted_free_mutex` is a read/write mutex and threads that do insert/find operations acquire this mutex for read?

**Comment by MaxPHPer** [comment]
> @MaxPHPer Could you please elaborate, if `m_topLevel_restricted_free_mutex` is a read/write mutex and threads that do insert/find operations acquire this mutex for read?

thank you for your reply.

my mutex is defined as follows:
`using SharedMutex = boost::shared_mutex;`
`using ReadGuard = boost::shared_lock<boost::shared_mutex>;`
`using WriteGuard = boost::unique_lock<boost::shared_mutex>;`

my concurrent_set variable is defined as follows:
`struct transactionWeightCompare`
`{`
`    bool operator()(std::shared_ptr<Vertex> _first, std::shared_ptr<Vertex> _second) const`
`    {`
`            return  _first->freeChildVertex > _second->freeChildVertex;`
`    }`
`};`
`tbb::concurrent_set<std::shared_ptr<Vertex>, transactionWeightCompare> m_topLevel_restricted_free;`

I use locks as follows：
1. Some threads read, I use the ReadGuard before reading.
2. Some threads insert, I use the ReadGuard before writing .
3. Some threads erase, I use the WriteGuard before erasing.

I think my usage above conforms to the documentation， the document says "It supports concurrent insertion, lookup and traversal, but does not support concurrent erasure." doesn't it？

In addition, there is an important thing I’m not sure if it’s the cause.
I have a thread that may modify the `freeChildVertex` of an element already in the concurrent_set, which will cause the elements in the set to be out of order.

Looking forward to your reply, thank you very much

**Comment by kboyarinov** [comment]
@MaxPHPer, starting from oneTBB 2021, the implementation of `concurrent_set` was redesigned and the internal implementation was changed. If it is possible, could you please try to reproduce the issue on the latest oneTBB version?
Thank you in advance.

**Comment by MaxPHPer** [comment]
> @MaxPHPer, starting from oneTBB 2021, the implementation of `concurrent_set` was redesigned and the internal implementation was changed. If it is possible, could you please try to reproduce the issue on the latest oneTBB version? Thank you in advance.



thank you for your advise. I use oneTBB v2021.4.0.
I found that this version is different from v2020.3. There is no `Makefile`, but `Cmakelists.txt`.
when I try to `make` my whole project, it always reports an errors.

The following is the cmake file of my project about using TBB，

I don't know how to modify `BUILD_COMMAND`, `INSTALL_COMMAND`  and `BUILD_BYPRODUCTS`. Can you help me? Thank you very much♪(･ω･)ﾉ


```
include(ExternalProject)

set(TBB_LIB_SUFFIX a)
if (APPLE)
    set(ENABLE_STD_LIB stdlib=libc++)
endif()

ExternalProject_Add(tbb
    PREFIX ${CMAKE_SOURCE_DIR}/deps
    DOWNLOAD_NO_PROGRESS 1
    DOWNLOAD_NAME oneTBB-2021.4.0.tar.gz
    URL https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.4.0.tar.gz
    URL_HASH SHA256=021796c7845e155e616f5ecda16daa606ebb4c6f90b996e5c08aebab7a8d3de3
    BUILD_IN_SOURCE 1
    LOG_CONFIGURE 1
    LOG_BUILD 1
    LOG_INSTALL 1
    CONFIGURE_COMMAND ""
    BUILD_COMMAND make extra_inc=big_iron.inc ${ENABLE_STD_LIB}
    INSTALL_COMMAND bash -c "/bin/cp -f ./build/*_release/libtbb.${TBB_LIB_SUFFIX}* ${CMAKE_SOURCE_DIR}/deps/lib/"
    BUILD_BYPRODUCTS ${CMAKE_SOURCE_DIR}/deps/lib/libtbb.${TBB_LIB_SUFFIX}
)

ExternalProject_Get_Property(tbb SOURCE_DIR)
add_library(TBB STATIC IMPORTED)
set(TBB_INCLUDE_DIR ${SOURCE_DIR}/include)
set(TBB_LIBRARY ${CMAKE_SOURCE_DIR}/deps/lib/libtbb.${TBB_LIB_SUFFIX})
file(MAKE_DIRECTORY ${TBB_INCLUDE_DIR})  # Must exist.
file(MAKE_DIRECTORY ${CMAKE_SOURCE_DIR}/deps/lib/)  # Must exist.

set_property(TARGET TBB PROPERTY IMPORTED_LOCATION ${TBB_LIBRARY})
set_property(TARGET TBB PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${TBB_INCLUDE_DIR})
add_dependencies(TBB tbb)
unset(SOURCE_DIR)


```

<img width="900" alt="WechatIMG126" src="https://user-images.githubusercontent.com/16571895/139803268-37ddf971-1d3e-4d91-b87d-ac35884f5014.png">


![QQ20211102-0](https://user-images.githubusercontent.com/16571895/139803197-66ea7d2d-67eb-484e-b2a7-997949eb6aa7.png)



@kboyarinov @vinser52

**Comment by AlexVeprev** [comment]
Hi @MaxPHPer,

I would suggest you to try [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html), here is the simplest example:
```cmake
cmake_minimum_required(VERSION 3.14)  # FetchContent_MakeAvailable is available since 3.14

project(my_app LANGUAGES CXX)

# Create application
add_executable(my_app)
target_sources(my_app PRIVATE my_app.cpp)

# Download oneTBB during configuration phase
include(FetchContent)
FetchContent_Declare(
  onetbb
  URL https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.4.0.tar.gz
  URL_HASH SHA256=021796c7845e155e616f5ecda16daa606ebb4c6f90b996e5c08aebab7a8d3de3
)

# Customize oneTBB configuration
option(TBB_TEST OFF)

# Make oneTBB source tree available in this project (like add_subdirectory)
FetchContent_MakeAvailable(onetbb)

# Connect imported oneTBB core target to our application
target_link_libraries(my_app PRIVATE TBB::tbb)
```

It will download oneTBB on configuration phase and include it just like `add_subdirectory`.

See details about oneTBB configuration here: https://github.com/oneapi-src/oneTBB/blob/master/cmake/README.md

I see you use `big_iron.inc` and assume you want static library. oneTBB developers don't recommend such approach: https://github.com/oneapi-src/oneTBB/blob/cb885710ab1408bf3fd49ef99f7487e897438838/CMakeLists.txt#L114
but you can control static build using BUILD_SHARED_LIBS variable set before `FetchContent_MakeAvailable(onetbb)` call.

**Comment by AlexVeprev** [comment]
@MaxPHPer one more note: since oneTBB uses CMake configuration all the options you specify for your project will be applied to oneTBB configuration as well unless you change them just before `FetchContent_MakeAvailable(onetbb)` call. E.g. if you build the project with `-DCMAKE_BUILD_TYPE=Debug` you will get Debug version of oneTBB built and connected to your project. So the configuration is very transparent and straightforward.

**Comment by MaxPHPer** [comment]
> Hi @MaxPHPer,
> 
> I would suggest you to try [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html), here is the simplest example:
> 
> ```cmake
> cmake_minimum_required(VERSION 3.14)  # FetchContent_MakeAvailable is available since 3.14
> 
> project(my_app LANGUAGES CXX)
> 
> # Create application
> add_executable(my_app)
> target_sources(my_app PRIVATE my_app.cpp)
> 
> # Download oneTBB during configuration phase
> include(FetchContent)
> FetchContent_Declare(
>   onetbb
>   URL https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.4.0.tar.gz
>   URL_HASH SHA256=021796c7845e155e616f5ecda16daa606ebb4c6f90b996e5c08aebab7a8d3de3
> )
> 
> # Customize oneTBB configuration
> option(TBB_TEST OFF)
> 
> # Make oneTBB source tree available in this project (like add_subdirectory)
> FetchContent_MakeAvailable(onetbb)
> 
> # Connect oneTBB core target to our application
> target_link_libraries(my_app PRIVATE TBB::tbb)
> ```
> 
> It will download oneTBB on configuration phase and include it just like `add_subdirectory`.
> 
> See details about oneTBB configuration here: https://github.com/oneapi-src/oneTBB/blob/master/cmake/README.md
> 
> I see you use `big_iron.inc` and assume you want static library. oneTBB developers don't recommend such approach:
> 
> https://github.com/oneapi-src/oneTBB/blob/cb885710ab1408bf3fd49ef99f7487e897438838/CMakeLists.txt#L114
> 
> 
> but you can control static build using BUILD_SHARED_LIBS variable set before `FetchContent_MakeAvailable(onetbb)` call.

thank you so much. I am a newcomer to C++, it is too difficult for me, so I plan to continue trying the original method

**Comment by AlexVeprev** [comment]
@MaxPHPer, ok, but I'm afraid the original method modification will be harder than using my approach.
Actually the core  part of my approach is
```cmake
# Download oneTBB during configuration phase
include(FetchContent)
FetchContent_Declare(
  onetbb
  URL https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.4.0.tar.gz
  URL_HASH SHA256=021796c7845e155e616f5ecda16daa606ebb4c6f90b996e5c08aebab7a8d3de3
)

# Customize oneTBB configuration
option(TBB_TEST OFF)

# Make oneTBB source tree available in this project (like add_subdirectory)
FetchContent_MakeAvailable(onetbb)
```
Then you just need to connect `TBB::tbb` with your application using `target_link_libraries`: e.g. `target_link_libraries(my_app PRIVATE TBB::tbb)`

Anyway, feel free to ask questions if you have any troubles with oneTBB CMake integration.

**Comment by MaxPHPer** [comment]
> @MaxPHPer, ok, but I'm afraid the original method modification will be harder than using my approach. Actually the core part of my approach is
> 
> ```cmake
> # Download oneTBB during configuration phase
> include(FetchContent)
> FetchContent_Declare(
>   onetbb
>   URL https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.4.0.tar.gz
>   URL_HASH SHA256=021796c7845e155e616f5ecda16daa606ebb4c6f90b996e5c08aebab7a8d3de3
> )
> 
> # Customize oneTBB configuration
> option(TBB_TEST OFF)
> 
> # Make oneTBB source tree available in this project (like add_subdirectory)
> FetchContent_MakeAvailable(onetbb)
> ```
> 
> Then you just need to connect `TBB::tbb` with your application using `target_link_libraries`: e.g. `target_link_libraries(my_app PRIVATE TBB::tbb)`
> 
> Anyway, feel free to ask questions if you have any troubles with oneTBB CMake integration.

Thank you. Everyone is very warm-hearted
