### ISSUE TITLE
I am very confused about which operations can be concurrent

### ISSUE THREAD

**Issue by MaxPHPer** [oneapi-src/oneTBB#640]
Hello everyone ^_^，I have a question to consult.

As stated in the document (https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_unordered_map_cls.html).

tbb::concurrent_unordered_map is a class template that represents an unordered associative container. It stores key-value pairs with unique keys and supports **concurrent insertion, lookup, and traversal, but does not support concurrent erasure**.

Does it mean the following？

1. A thread with an **insertion** can be concurrent with another thread with an **insertion** without using locks.
2. A thread with an **insertion** can be concurrent with another thread with a **lookup** without using locks.
3. A thread with an **insertion** can be concurrent with another thread with a **traversal** without using locks.
4. A thread with an **insertion** can be concurrent with another thread with an **erasure** without using locks.
5. A thread with an **lookup** can be concurrent with another thread with an **erasure** without using locks.
5. ......
6. A thread with an **erasure** can not be concurrent with another thread with an **erasure** without using locks.

Am I right? Looking forward to your reply, thank you very much.

**Comment by kboyarinov** [comment]
Hi, @MaxPHPer,

Thank you for your question! You are right, `concurrent_unordered_map` can be used by different threads with insertion, traversal and lookup without any additional synchronization. 

Erasure operations (as well as any other operations, such as `clear`, assignment operators, bucket interfaces, `swap`, etc.) can not be used simultaneously with other operations. Such a methods can only be used in "serial" parts of the application, when other threads do not perform any operations on the container. In concurrent part, it can be achieved with writer lock around the unsafe operation.

Feel free to ask any additional questions, if any.

**Comment by MaxPHPer** [comment]
> Hi, @MaxPHPer,
> 
> Thank you for your question! You are right, `concurrent_unordered_map` can be used by different threads with insertion, traversal and lookup without any additional synchronization.
> 
> Erasure operations (as well as any other operations, such as `clear`, assignment operators, bucket interfaces, `swap`, etc.) can not be used simultaneously with other operations. Such a methods can only be used in "serial" parts of the application, when other threads do not perform any operations on the container. In concurrent part, it can be achieved with writer lock around the unsafe operation.
> 
> Feel free to ask any additional questions, if any.

thank you for your interpretation

**Comment by jieisme2000** [comment]
1, A thread with an insertion can be concurrent with another thread with an insertion without using locks. --yes 
2, A thread with an insertion can be concurrent with another thread with a lookup without using locks.   --yes
3, A thread with an insertion can be concurrent with another thread with a traversal without using locks.  --yes
4, A thread with an insertion can be concurrent with another thread with an erasure without using locks. --??
5, A thread with an lookup can be concurrent with another thread with an erasure without using locks. --??
6, A thread with an traverse can be concurrent with another thread with an erasure without using locks. --??
......
7, A thread with an erasure can be concurrent with another thread with an erasure without using locks. --no

could you help me about of item4，5，6? yes or no?

**Comment by jieisme2000** [comment]
1, A thread with an insertion can be concurrent with another thread with an insertion without using locks. --yes
2, A thread with an insertion can be concurrent with another thread with a lookup without using locks. --yes
3, A thread with an insertion can be concurrent with another thread with a traversal without using locks. --yes
4, A thread with an insertion can be concurrent with another thread with an erasure without using locks. --??
5, A thread with an lookup can be concurrent with another thread with an erasure without using locks. --??
6, A thread with an traverse can be concurrent with another thread with an erasure without using locks. --??
......
7, A thread with an erasure can be concurrent with another thread with an erasure without using locks. --no

could you help me about item4，5，6 of above? yes or no?

**Comment by kboyarinov** [comment]
@jieisme2000, for `concurrent_unordered_map` items 4-6 are not concurrently safe. Erasure from the unordered container can only be done in the serial part of the code. It means that if you need to erase elements concurrently from the container - you need to use a lock that should be acquired on each concurrent operation (insertion, lookup, erasure). In this case I would consider using `concurrent_hash_map` container that provides different non STL-like API, but supports concurrent insertion, lookup and erasure.
