### ISSUE TITLE
hwloc is missed in TBBConfig.cmake for static build case

### ISSUE THREAD

**Issue by ilya-lavrenov** [oneapi-src/oneTBB#653]
I've tried to build TBB in static mode (`BUILD_SHARED_LIBS=OFF`) and have the following `TBBConfig.cmake` config after install:
```cmake
# Create imported target TBB::tbbbind_2_5
add_library(TBB::tbbbind_2_5 STATIC IMPORTED)

set_target_properties(TBB::tbbbind_2_5 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<CONFIG:DEBUG>:TBB_USE_DEBUG>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "HWLOC::hwloc_2_5"
)
```

I've passed options:
```cmake
        CMAKE_HWLOC_${hwloc_version}_LIBRARY_PATH AND
        CMAKE_HWLOC_${hwloc_version}_DLL_PATH AND
        CMAKE_HWLOC_${hwloc_version}_INCLUDE_PATH
```
When configured TBB cmake project.

In static build all dependencies should be exposed via cmake interface.

So, this code should be part of TBBConfig.cmake as well:
https://github.com/oneapi-src/oneTBB/blob/2915b9b93f721adcc0e8c54d7d1b552764749f4d/cmake/hwloc_detection.cmake#L28-L38

BTW, could you please add support of static hwloc? E.g. if shared library path is not provided, we can import library as static

**Comment by ivankochin** [comment]
The static build has very limited support. And also, the TBBBind libraries, that require the HWLOC existence, are designed to be dynamic. So the simples solution is just to remove the TBBBind libraries from the static build. It was done in #656.

There is no HWLOC dependency in the static package anymore, so I close the issue. Please reopen the issue if you have any questions.
