### ISSUE TITLE
Update system requirements with "community based" supported platforms 

### ISSUE THREAD

**Issue by anton-potapov** [oneapi-src/oneTBB#675]
Need to mention that there known integrations of community supported platforms such as MinGW and FreeBSD

**Comment by anton-potapov** [comment]
arm/arm64 on Windows /MacOS should be mentioned as well

**Comment by isaevil** [comment]
@omalyshe @alexandraepan Could you please take a look?

**Comment by alexandraepan** [comment]
@isaevil will add info and request review
