### ISSUE TITLE
[CMake] Add CMake files into TBB packages in PyPI wheels

### ISSUE THREAD

**Issue by SimonHeybrock** [oneapi-src/oneTBB#682]
#141 addressed missing cmake files in distribution packages. As far as I can tell, these files (such as `TBBConfig.cmake`) are still missing from the package installed with `pip install tbb-devel`, which makes building wheels for cmake-based projects difficult.

Could they be added? Thanks!

**Comment by AlexVeprev** [comment]
@SimonHeybrock, thank you for the request. We should consider it more deeply. Generally it is possible, but will require a bit different implementation from what we have now in oneAPI distribution and in assets in GitHub releases because `pip` installs `tbb-devel` to different layout. We use templates https://github.com/oneapi-src/oneTBB/blob/master/cmake/templates to prepare TBBConfig files, but seems they are not suitable for `pip` installation. Again, we need to check it deeper, but feel free to share your proposals through PR or comments here.

**Comment by SimonHeybrock** [comment]
@AlexVeprev thanks for you answer. I am anything but an expert, so I cannot really propose a concrete solution. But maybe you have a suggestion on how to use (include and link) with TBB installed via `pip install tbb-devel`? Is there any other mechanism you would recommend, since we cannot use `find_package(TBB)`?

For context:
- We are attempting to make a wheel for a C++ application (with Python bindings), using `scikit-build` and `cibuildwheel`.
- The shared libraries that are built as part of this project dynamically link with TBB.
- For our conda builds we use `tbb-devel` from conda forge with `find_package(TBB)` in the cmake lists files, which works well.

**Comment by AlexVeprev** [comment]
@SimonHeybrock, I can experiment with some workarounds, but for stability and consistency it would be better to use `find_package(TBB)`. BTW, are you ok to wait? It may be months to enable the solution not because of complexity but because of release cycle.

**Comment by SimonHeybrock** [comment]
@AlexVeprev 
> BTW, are you ok to wait? It may be months to enable the solution not because of complexity but because of release cycle.

I think I would need to figure out a workaround until then, any suggestions are welcome.

I have considered just copying the `cmake/tbb` folder from the conda package into the installed `pip` library dir (since it should only be required during the actual package build), but above you mention that the conda package structure is different, so that might not work?

**Comment by AlexVeprev** [comment]
@SimonHeybrock

> above you mention that the conda package structure is different, so that might not work?

Not exactly, I mentioned oneAPI distribution and assets in GitHub releases. oneTBB from conda-forge should have pretty similar layout to pip. I'm not sure if it is 100% stable workaround, but it may work.
BTW, here you can find how I build tbb-devel for conda-forge channel. I believe it's pretty easy to reproduce it locally to dive into details: https://github.com/conda-forge/tbb-feedstock/blob/master/recipe/meta.yaml#L70

Locally you need smth like:
```bash
cmake -DTBB_TEST=OFF -DCMAKE_INSTALL_PREFIX=/my/custom/experimental/folder /path/to/oneTBB/repo/root
cmake --build .
cmake -DCOMPONENT=devel -P cmake_install.cmake  # or just "make install" to install tbb/tbb-devel components
```
More details on installation process are here: https://github.com/oneapi-src/oneTBB/blob/master/INSTALL.md#installation-from-sources

**Comment by SimonHeybrock** [comment]
@AlexVeprev I seem to be successful "patching" the `pip`-installed `tbb-devel` with the `cmake/TBB` folder extracted from the `conda-forge` `tbb-devel` packages. Combined with `install(IMPORTED_RUNTIME_ARTIFACTS TBB::tbb)` this appears to be working.

I will post details of this hack later when I have a cleaned-up solution.

**Comment by SimonHeybrock** [comment]
Here it is: https://github.com/scipp/scipp/pull/2317/commits/1897a52b2cf6d4114d43c8051b612fbb53b090d6. I am *not* proud of this, but it appears to work on the systems we have tried so far. Fingers-crossed for a nicer (upstream) solution in the future?

**Notes:**

Ignore the files in ` lib/.tbb/*/TBB/`, those are just copied over from the conda-forge `tbb-devel` packages. The relevant parts are:
- [patch-pip-tbb-devel.cmake ](https://github.com/scipp/scipp/pull/2317/commits/1897a52b2cf6d4114d43c8051b612fbb53b090d6#diff-78b0a67e84f01555bd6d8fb2b7a43cf6ee49718b5a3a371d44029817b9de68be)
- Used as:
  ```cmake
  include(patch-pip-tbb-devel)
  find_package(TBB CONFIG REQUIRED)
  install(IMPORTED_RUNTIME_ARTIFACTS TBB::tbb RUNTIME DESTINATION
          ${PYTHONDIR}
  ```

The latter requires cmake>=3.21 and will install the TBB shared library along the library being built, i.e., this will end up getting shipped with our wheel. We thus also do not need `tbb` as a `install_requires` in our `setup.py`.

**Comment by AlexVeprev** [comment]
@SimonHeybrock, that's cool you was able to apply the w/a! Special thanks for the detailed explanation.

> Fingers-crossed for a nicer (upstream) solution in the future?

Sure, let's keep this issue open to track the status.

**Comment by nofuturre** [comment]
@SimonHeybrock is this issue still relevant?

**Comment by SimonHeybrock** [comment]
On our side, as you can see in https://github.com/scipp/scipp/issues/2323#issuecomment-1092454900, we moved to TBB via conan so this is not relevant in that sense. The issue reported here stands as it is (I think), I suppose you can decide if it is of wider interest.
