### ISSUE TITLE
file INSTALL cannot find tbb12.dll

### ISSUE THREAD

**Issue by lyh1028** [oneapi-src/oneTBB#708]
cmake version 3.21.2  
win11  x64

when I try to install tbb （use ‘cmake --install .’）It shows 'CMake Error at src/tbb/cmake_install.cmake:51 (file):
  file INSTALL cannot find
  "D:/ComputerGragh/oneTBB/build/msvc_19.22_cxx_64_md_release/tbb12.dll": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:80 (include)'  

How can i deal with it.

**Comment by anton-potapov** [comment]
@lyh1028 what version do you use ?

**Comment by lyh1028** [comment]
@anton-potapov  CMake(cmake-gui) version 3.21.2 and visual studio 2019

**Comment by anton-potapov** [comment]
@lyh1028 [which ](https://github.com/oneapi-src/oneTBB/releases) version of oneTBB is used ?

**Comment by lyh1028** [comment]
@anton-potapov oneTBB 2021.5.0  sorry for misunderstanding. 
And I just use 'Example of Installation' in doc. INSTALL.md to install it.

**Comment by AlexVeprev** [comment]
Hi @lyh1028, looks like you missed [build step](https://github.com/oneapi-src/oneTBB/blob/master/INSTALL.md#build-onetbb). 
Normally the flow should be: configure -> build [-> test] -> install. Testing is optional, so you can use -DTBB_TEST=OFF to disable tests.

The example you're referring to is valid for GNU Make, Ninja and other single-configuration generators. For Visual Studio I'd recommend to use a bit different approach: specify configuration during build/installation, e.g. `relwithdebinfo` or just `release`:

```
cmake -DTBB_TEST=OFF ..  # use CMAKE_INSTALL_PREFIX to customize installation location.
cmake --build . --config relwithdebinfo
cmake --install . --config relwithdebinfo
```

@alexandraepan, FYI, maybe we should consider improvements for INSTALL.md.

**Comment by lyh1028** [comment]
> Hi @lyh1028, looks like you missed [build step](https://github.com/oneapi-src/oneTBB/blob/master/INSTALL.md#build-onetbb). Normally the flow should be: configure -> build [-> test] -> install. Testing is optional, so you can use -DTBB_TEST=OFF to disable tests.
> 
> The example you're referring to is valid for GNU Make, Ninja and other single-configuration generators. For Visual Studio I'd recommend to use a bit different approach: specify configuration during build/installation, e.g. `relwithdebinfo` or just `release`:
> 
> ```
> cmake -DTBB_TEST=OFF ..  # use CMAKE_INSTALL_PREFIX to customize installation location.
> cmake --build . --config relwithdebinfo
> cmake --install . --config relwithdebinfo
> ```
> 
> @alexandraepan, FYI, maybe we should consider improvements for INSTALL.md.

forgot to say thanks~ the problem has been solved
