### ISSUE TITLE
Migration Guide is dead link in README.md

### ISSUE THREAD

**Issue by e4lam** [oneapi-src/oneTBB#709]
In the README.md, there is a link to the "Migrating from TBB to oneTBB" documentation guide for:
    https://oneapi-src.github.io/oneTBB/tbb_userguide/Migration_Guide.html

However, upon visiting this link, it is missing and gives error 404.

EDIT: Perhaps you meant this instead? https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Migration_Guide.html ... There might be other similar dead links around but I have not checked.

**Comment by alexey-katranov** [comment]
@alexandraepan , it seems we broke the links when moving the documentation into `main` subfolder. Can you please investigate what else could be affected?

**Comment by e4lam** [comment]
Thanks for the fix!
