### ISSUE TITLE
build for Android failed

### ISSUE THREAD

**Issue by leleliu008** [oneapi-src/oneTBB#710]
https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.5.0.tar.gz

Android-NDK: 23.1.7779620

Build System: CMake

[CMakeLists.txt#L281](https://github.com/oneapi-src/oneTBB/blob/master/CMakeLists.txt#L281)

**`ANDROID_STL` is empty, `${ANDROID_STL}`  should be enclosed in quotation marks.**

![10](https://user-images.githubusercontent.com/3040852/147872888-028adc74-27c9-4afb-bfd9-cfc9467b4888.PNG)

**Comment by anton-potapov** [comment]
@leleliu008 pull requests are welcome!
