### ISSUE TITLE
Build fails on Linux m68k since the code assumes at least 32-bit alignment

### ISSUE THREAD

**Issue by glaubitz** [oneapi-src/oneTBB#718]
Building `tbb` on Linux m68k (in this case Debian unstable) fails since the code assumes that the host architecture always has at least 32-bit alignment.

```
g++ -c -MMD -O2 -g  -DUSE_PTHREAD -pthread   -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -specs=/usr/share/dpkg/pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DTBB_SUPPRESS_DEPRECATED_MESSAGES=1 -fno-rtti -fno-exceptions -D__TBBMALLOC_BUILD=1 -Wno-parentheses -Wno-sized-deallocation -fPIC -flifetime-dse=1 -I../../src -I../../src/rml/include -I../../include -I../../src/tbbmalloc -I../../src/tbbmalloc ../../src/tbbmalloc/large_objects.cpp
In file included from ../../src/tbbmalloc/Customize.h:21,
                 from ../../src/tbbmalloc/TypeDefinitions.h:54,
                 from ../../src/tbbmalloc/tbbmalloc_internal.h:21,
                 from ../../src/tbbmalloc/backend.cpp:19:
../../src/tbbmalloc/backend.cpp: In member function ‘rml::internal::FreeBlock* rml::internal::Backend::findBlockInRegion(rml::internal::MemRegion*, size_t)’:
../../src/tbbmalloc/backend.cpp:1215:68: error: static assertion failed: Atomic applied on LastFreeBlock, and we put it at the end of region, that is uintptr_t-aligned, so no unaligned atomic operations are possible.
 1215 |     MALLOC_STATIC_ASSERT(sizeof(LastFreeBlock) % sizeof(uintptr_t) == 0,
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
../../include/tbb/tbb_stddef.h:553:58: note: in definition of macro ‘__TBB_STATIC_ASSERT’
  553 | #define __TBB_STATIC_ASSERT(condition,msg) static_assert(condition,msg)
      |                                                          ^~~~~~~~~
../../src/tbbmalloc/backend.cpp:1215:5: note: in expansion of macro ‘MALLOC_STATIC_ASSERT’
 1215 |     MALLOC_STATIC_ASSERT(sizeof(LastFreeBlock) % sizeof(uintptr_t) == 0,
      |     ^~~~~~~~~~~~~~~~~~~~
```

However, on Linux/m68k, the natural alignment is 16 bits despite the architecture being 32 bits.

Full build log: https://buildd.debian.org/status/fetch.php?pkg=tbb&arch=m68k&ver=2020.3-1&stamp=1641578091&raw=0

**Comment by anton-potapov** [comment]
@glaubitz, the problem you report is against tbb 2020, which is no longer maintained. 
The source code has changed significantly during the [revamp](https://www.intel.com/content/dam/develop/external/us/en/documents/tbbrevamp.pdf). 

Is [moving to oneTBB](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Migration_Guide.html) considered ?

**Comment by glaubitz** [comment]
> @glaubitz, the problem you report is against tbb 2020, which is no longer maintained. The source code has changed significantly during the [revamp](https://www.intel.com/content/dam/develop/external/us/en/documents/tbbrevamp.pdf).
> 
> Is [moving to oneTBB](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Migration_Guide.html) considered ?

Thanks for the insight, I wasn't aware of that. I was reporting tbb 2020 since that's what's currently being used in Debian.

> https://tracker.debian.org/pkg/tbb

I will ask the maintainer of the Debian package whether he has any plans to upgrade to oneTBB.

**Comment by anton-potapov** [comment]
FIY: Debian [request](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987689) to track migration to oneTBB

**Comment by anton-potapov** [comment]
closing as Debian bookworm seems [migrated](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987689) to oneTBB
