### ISSUE TITLE
Kindly add installation of Windows debugger files (pdb)?

### ISSUE THREAD

**Issue by emmenlau** [oneapi-src/oneTBB#730]
This is a kind feature request. Thanks for this great library! I've seen that when built on Windows, it generates debugger information. However I think the `*.pdb` files are not installed with `make install`. Therefore it can not be found during debugging, and i.e. it is lost when the build tree is removed.

Would it be possible to add this file to the install target on Windows? I guess something like this may be a good start for shared library builds:
```
if(MSVC AND BUILD_SHARED_LIBS)
    install(FILES $<TARGET_PDB_FILE:${PROJECT_NAME}>
        DESTINATION "${CMAKE_INSTALL_BINDIR}"
        OPTIONAL)
endif()
```
It works a bit different for static libraries, though, and I do not have copy-paste-instructions for that case. See https://stackoverflow.com/a/40860436/7200132 for a good start...

**Comment by emmenlau** [comment]
I just wanted to add that its also possible to generate and store `pdb` files for static library builds. However requires that the `COMPILE_PDB_NAME` is set in cmake for the target. So something along those lines would need to be added in addition to the install command from above, too:
```
if (MSVC AND NOT BUILD_SHARED_LIBS)
    # Set the output name for debugger files, otherwise they are not generated:
    set_target_properties(${PROJECT_NAME}
        PROPERTIES
        COMPILE_PDB_NAME_DEBUG ${PROJECT_NAME}
        COMPILE_PDB_NAME_RELEASE ${PROJECT_NAME}
        COMPILE_PDB_NAME_MINSIZEREL ${PROJECT_NAME}
        COMPILE_PDB_NAME_RELWITHDEBINFO ${PROJECT_NAME})
endif()
```
Then the install command should work for the static and the shared case.

PS: I'm assuming here that the library target is called `${PROJECT_NAME}`. Otherwise please replace this with the library target(s).

**Comment by anton-potapov** [comment]
@alexey-katranov , @AlexVeprev do see any possible problems here ? As for me this sound reasonable.

**Comment by anton-potapov** [comment]
As official asset files does contain .pdb files, I believe this request is reasonable.   

@emmenlau, pull requests are welcome! :)

**Comment by emmenlau** [comment]
@anton-potapov thanks a lot for the thumbs up! I've created a similar request over at https://github.com/open-mpi/hwloc/issues/512, and there is some more information collected there. But I do not know more details, sorry...

**Comment by emmenlau** [comment]
Thanks @isaevil !
