### ISSUE TITLE
`task_group::run` sometimes does not execute the given lambda

### ISSUE THREAD

**Issue by mirkootter** [oneapi-src/oneTBB#738]
For our software, we use tbb, mainly because its composability.

However, we ran into trouble on stress tests: In rare cases, `task_group::run` does not execute the given lambda function, even if all tbb threads are idling.

Reproduce: The following code will block indefinitely after a few iterations (usually about ~10.000 to 200.000, should not take more than a few seconds)

```
#include <atomic>
#include <iostream>
#include <tbb/task_group.h>

int main()
{
  tbb::task_group tbb_group;
  
  for (int i = 0; i < 10000000; ++i)
    {
      if (i % 10000 == 0)
        std::cout << "Iteration #" << i << std::endl;
    
      std::atomic_bool done = false;
      tbb_group.run([&done] () { done = true; });
      while (!done) ;
    }

  tbb_group.wait();
  
  return 0;
}
```

Note: I guess the problem is that I do not use `task_group::wait` (the one in the end is never reached). This example could be very easily fixed by replacing the `while` loop by a wait.

However, this only works in this simplified example, because waiting for the `done` flag to be set is the same as waiting for the whole thread pool - this is not the case in our main software. We wait for certain results calculated by the worker threads, and we usually have more than one. We do not want to wait for everything.

And it seems really ugly to spin up *another* thread so that we have something to call `tbb_group.wait()`...

**Comment by pavelkumbrasev** [comment]
It happens because task_group.run() doesn't guarantee that task you summited will be done until you call wait on task_group. For purpose that you describe it is possible to use task_arena::enqueue ([spec link](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.html)) that guarantee  task will be execute without explicit waits.
Your example can be rewrite on:
```
#include <atomic>
#include <iostream>
#include <tbb/task_arena.h>

int main()
{
  tbb::task_arena tbb_arena;
  
  for (int i = 0; i < 10000000; ++i)
    {
      if (i % 10000 == 0)
        std::cout << "Iteration #" << i << std::endl;
    
      std::atomic_bool done{false};
      tbb_arena.enqueue([&done] () { done = true; });
      while (!done) ;
    }
  
  return 0;
}
```
