### ISSUE TITLE
Where can I get binaries for old version of TBB? 

### ISSUE THREAD

**Issue by rajendrasp** [oneapi-src/oneTBB#757]
Hi
I want to compile old program which is dependent on version 4.2. Where can I download it?
Thanks

**Comment by alexey-katranov** [comment]
The oldest available version is 4.4. Basically, all TBB versions up to 2020.3 are fully source compatible. oneTBB 2021.1 (and later) are mostly source compatible with all previous versions. So, if your application worked with 4.2 or can try any available version. Or do you need exactly 4.2 for some reason?

As for binary compatibility, TBB 2020.3 and older are fully compatible with 4.2, i.e. any application build with 4.2 will work with 2020.3.

**Comment by rajendrasp** [comment]
I used latest one and fixed some issues in the code and it is working now. Thanks. It was mostly related to deprecated tbb/task_scheduler_init.h
