### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [oneapi-src/oneTBB#76]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [concurrent_queue_base](https://github.com/01org/tbb/blob/615bb971db8784ab6c005a856e8ed3e8cea61d9b/src/old/concurrent_queue_v2.cpp#L217 "Destructor for concurrent_queue_base")
* [function_input_base](https://github.com/01org/tbb/blob/d7e150913467f3c168ba6319c985cf341fd81012/include/tbb/internal/_flow_graph_node_impl.h#L115 "Destructor for function_input_base")
* [video::terminate](https://github.com/01org/tbb/blob/d31fcc68980efbe912dc8cec4978fbb77fb3cf9f/examples/common/gui/gdivideo.cpp#L118 "video::terminate function")

**Comment by alexey-katranov** [comment]
Good catch. Feel free to send a pull request.

**Comment by anton-potapov** [comment]
It seems that for oneTBB only examples code is affected : 

https://github.com/oneapi-src/oneTBB/blob/9e15720bc7744f85dff611d34d65e9099e077da4/examples/common/gui/d2dvideo.cpp#L167-L169

https://github.com/oneapi-src/oneTBB/blob/9e15720bc7744f85dff611d34d65e9099e077da4/examples/common/gui/macvideo.cpp#L90-L92

https://github.com/oneapi-src/oneTBB/blob/9e15720bc7744f85dff611d34d65e9099e077da4/examples/common/gui/convideo.cpp#L92-L94

https://github.com/oneapi-src/oneTBB/blob/9e15720bc7744f85dff611d34d65e9099e077da4/examples/common/gui/gdivideo.cpp#L126-L135
