### ISSUE TITLE
task_arenas numa constraints leads to partial cpu usage

### ISSUE THREAD

**Issue by pranasge** [oneapi-src/oneTBB#773]
I cannot seem to get `task_arenas` that are binded to numa nodes to use all cpus resources.
Simple test that alloc memory and then reads it uses all cpus when unbinded and only about 80% of all cpus when binded.
```
TEST(NumaTest, tbbFlowBind)
{
	static const int BUFFER_COUNT{ 1000 * 10 };
	static const int BUFFER_SIZE{ 20 * 1024 * 1024 };
	static const int THREAD_COUNT{ 48 };

	std::vector<std::unique_ptr<char[]>> buffers{ BUFFER_COUNT };
	std::vector<std::thread> threads(THREAD_COUNT);

	for (int i = 0; i < THREAD_COUNT; i++)
		threads[i] = std::thread([&, i]() {
			for (int x = 0; x < BUFFER_COUNT; x++)
				if (x % THREAD_COUNT == i)
				{
					buffers[x] = std::unique_ptr<char[]>(new char[BUFFER_SIZE]);
					std::fill(buffers[x].get(), buffers[x].get() + BUFFER_SIZE, x % 10);
				}
		});
	for (auto & thread : threads)
		thread.join();

	std::vector<tbb::numa_node_id> numa_nodes = tbb::info::numa_nodes();
	std::vector<tbb::task_arena> numa_arenas;
	for (auto i = 0; i < numa_nodes.size(); i++)
		numa_arenas.emplace_back(tbb::task_arena::constraints(numa_nodes[i]));

	tbb::flow::graph graph;
	tbb::flow::function_node<std::tuple<int, char*>, std::tuple<int, char*>> func{ graph, tbb::flow::unlimited, [&](const std::tuple<int, char*> & value) {
			auto groupIndex = std::get<int>(value) % numa_nodes.size();
			auto charPtr = std::get<char*>(value);
			numa_arenas[groupIndex].execute([&] {
				for (int i = 0; i < 30; i++)
					ASSERT_TRUE(std::none_of(charPtr, charPtr + BUFFER_SIZE, [](char i) { return i == -1; }));
			});
			return value;
		}
	};

	for (int x = 0; x < buffers.size(); x++)
		func.try_put(std::make_pair(x, buffers[x].get()));

	graph.wait_for_all();
}
```
In my tests that allocate memory on same numa nodes that process that memory `numa.h` binding showed performance improvements, but it seems that idle CPUs removes all performance gains from binding numa nodes in tbb case.

Version: v2021.5.0 and v2021.3.0

**Comment by isaevil** [comment]
Could you please provide more information about your system configuration? I also wonder what system monitoring tools did you use to see CPU usage for your app?

**Comment by pranasge** [comment]
I expected that there is something wrong with my code or tbb constrains. As I could bind nodes with `numa.h` and get expected performance. What info could help in this case? 
```
~# numactl numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 4 5 6 7 8 9 10 11 24 25 26 27 28 29 30 31 32 33 34 35
node 0 size: 193111 MB
node 0 free: 170559 MB
node 1 cpus: 12 13 14 15 16 17 18 19 20 21 22 23 36 37 38 39 40 41 42 43 44 45 46 47
node 1 size: 193530 MB
node 1 free: 170251 MB
node distances:
node   0   1
  0:  10  21
  1:  21  10
```
```
~# uname -a
Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```
At first i timed read part of the execution. That showed no improvement in execution time versus unbinded. And `htop` showed that this tests during graph execution uses ~4000% cpu while test where `numa_arenas.emplace_back(tbb::task_arena::constraints(numa_nodes[i]));` is changed to `numa_arenas.emplace_back();` used ~4800%

**Comment by vlserov** [comment]
The problem is how test shares work between numa nodes.
Basically, you have default `task_arena`, which contains all cpus in all  numa nodes and it's used by `flow graph`, and `arenas`, which have been created for all numa nodes. 
`tbb::task_arena::execute` is a synchronous call.  So there are 2 cases, which may happen here:
1. if `tbb::flow::function_node` function is executed by the cpu attached to the same numa node to which work should be addressed, then work is immediately executed by current cpu.
2. If numa node of cpu is different from the numa to which work should be addressed, work will be spawned into required `task_arena` and the current cpu will wait till the end of execution those work by another cpu.


Try to use `tbb::task_arena::enqueue` instead of `tbb::task_arena::execute`.

**Comment by pranasge** [comment]
Thanks, this explains everything.
If execute blocks cpu and enqueue does not wait for results I will need async node to get execution on expected node without blocking. Yes? Or i am missing something.

**Comment by vlserov** [comment]
Do you really need to use `flow graph`? If you need only to synchronize tasks execution, it's better to use `task_groups` instead.
Since selection numa nodes is not related to with execution thread, all tasks can be separated in main thread into corresponding numa nodes. `task_groups::wait` will guaranty wait execution all spawned tasks into corresponding arena.
```
    std::vector<oneapi::tbb::numa_node_id> numa_nodes = oneapi::tbb::info::numa_nodes();
    std::vector<oneapi::tbb::task_arena> numa_arenas(numa_nodes.size());
    std::vector<oneapi::tbb::task_group> task_groups(numa_nodes.size());

    for (int i = 0; i < numa_nodes.size(); i++) {
        numa_arenas[i].initialize(oneapi::tbb::task_arena::constraints(numa_nodes[i]));
    }

    for (int x = 0; x < buffers.size(); x++) {
        int groupIndex = x % numa_nodes.size();
        char* charPtr = buffers[x].get();
        numa_arenas[groupIndex].execute([&task_groups, groupIndex, charPtr] {
            task_groups[groupIndex].run([charPtr] {
                ASSERT_TRUE(std::none_of(charPtr, charPtr + BUFFER_SIZE, [](char i) { return i == -1; }));
            });
        });
    }

    for (int i = 0; i < numa_nodes.size(); i++) {
        numa_arenas[i].execute([&task_groups, i] {
            task_groups[i].wait();
        });
    }
```

And just for the note: `std::thread` is not guaranty execution on the specific cpu or numa nodes. In worse situation, `std::thread` can be executed only on the one numa node and it gains performance penalty for using memory between numa nodes.

**Comment by pranasge** [comment]
This test is more to show problem i am having. I have bigger flow graph that executes my logic and I am trying to extend it with numa constrains. There is node that allocates memory and later other node performs operation on that memory.

Will using task_group::wait(); block current worker thread?

I am thinking of 
```
tbb::flow::function_node f(g, unlimited, [](){
    task_group group{};
    numa_arena[index].enqueue([](){  // in my code there can be more than one enqueue
        group.run([](){
            // work
        })
    };
    group.wait();
});
```

**Comment by pranasge** [comment]
It seems that my example fails as `execute` still blocks worker and `enqueue` does not happen before I ask to `wait`.
So `async_node` seems like only option.

**Comment by vlserov** [comment]
`task_group` creation and `task_group::wait` call should be made outside of `function_node`. `task_group::run` just inserts task to proper arena for future execution, so is shouldn't violate performance.
```
std::vector<oneapi::tbb::task_group> task_groups(numa_nodes.size());
// Skip some code...

tbb::flow::function_node f(g, unlimited, [](){
    numa_arena[index].execute([](){  // in my code there can be more than one execute
        task_groups[index].run([](){
            // work
        })
    };
});

for (int i = 0; i < numa_nodes.size(); i++) {
    numa_arenas[i].execute([&task_groups, i] {
        task_groups[i].wait();
    });
}
```

Could you provide more details about your task? Are allocated buffers shared between numa nodes? If buffers are processed independently by numa nodes, may be creating identical `flow graph`  for each numa node and attaching to corresponding node. For example:
```
std::vector<oneapi::tbb::numa_node_id> numa_nodes = oneapi::tbb::info::numa_nodes();
std::vector<oneapi::tbb::task_arena> numa_arenas(numa_nodes.size());
std::vector<tbb::flow::graph> graphs(numa_nodes.size());

for (int i = 0; i < numa_nodes.size(); i++) {
    numa_arenas[i].initialize(oneapi::tbb::task_arena::constraints(numa_nodes[i]));
    numa_arenas[i].execute([](){
        // This reinitializes the graph, including recapturing the task arena.
        graphs[i].reset();
    });
    // Some code to initialization graph
    ...
}
...
for (int i = 0; i < numa_nodes.size(); i++) {
    // Execute in proper arena whatever it's called
    func[i].try_put(...)
}

for (int i = 0; i < numa_nodes.size(); i++) {
    graph[i].wait_for_all();
}
```

**Comment by pranasge** [comment]
> `task_group::run` just inserts task to proper arena for future execution, so is shouldn't violate performance.
Yes, `task_group::run` does not, but `task_arena::execute` does and as you said it will block my worker in case cpu numa missmatch. So even if `function_node` is quick if no needed numa cpus are available worker will block for long time.

> Could you provide more details about your task?
I read my tasks directly to `flow graph` and need fifo ordering between them so havig multiple `flow graph`s would not work.

>Are allocated buffers shared between numa nodes?
No, but tasks but task can touch one or all numa nodes.

I am currently implementing `async_node` that maps task to numa node calls `enqueue` and that seems to solve all my problems. Is there so problem with my approach that I am not aware of?

**Comment by vlserov** [comment]
There is no problem with using `async_node`, I've just wanted to let you know about other options. If `async_node` suits you better, It's ok for using it.
