### ISSUE TITLE
Add a section in INSTALL.md to detail how to produce a released package

### ISSUE THREAD

**Issue by ycollet** [oneapi-src/oneTBB#788]
I was trying to reproduce the package you ship on github and was not able to do so.
Can you add some notes in INSTALL.md to explain how to do this ?
For example, it doesn't seems to exist a rule to produce the env directory.
On Windows, the dll are stored in the bin and not in the redist directory.

**Comment by AlexVeprev** [comment]
Hi @ycollet, packages from [Releases](https://github.com/oneapi-src/oneTBB/releases) page are built using internal scripts, so they can't be easily recreated from public source code. Could you please clarify the use case where you need this?

**Comment by isaevil** [comment]
@ycollet is this issue still relevant for you? Could you please respond?

**Comment by isaevil** [comment]
Our release packages are built with internal and non-trivial way so it can't be put publicly documented. I would kindly suggest you to do that manually.
