### ISSUE TITLE
concurrent_unordered_base::contains is not thread safe

### ISSUE THREAD

**Issue by DougRogers** [oneapi-src/oneTBB#794]
```
    bool contains( const key_type& key ) const {
        return find(key) != end();
    }
```
An interruption between _find_ and _end_ that alters the list may crash since _end_ may have changed.

**Comment by anton-potapov** [comment]
[`iterator`](https://github.com/oneapi-src/oneTBB/blob/09346731f1279feb23c81f569eabe6010c620872/include/oneapi/tbb/detail/_concurrent_unordered_base.h#L55-L113) of concurrent unordered associative containers (in  `concurrent_unordered_base`) is implemented as wrapper over [pointer to internal node](https://github.com/oneapi-src/oneTBB/blob/09346731f1279feb23c81f569eabe6010c620872/include/oneapi/tbb/detail/_concurrent_unordered_base.h#L112) of the container.  
[`end()` iterator contains `nullptr` ](https://github.com/oneapi-src/oneTBB/blob/09346731f1279feb23c81f569eabe6010c620872/include/oneapi/tbb/detail/_concurrent_unordered_base.h#L401-L403) , thus it is not changed during operations over container
