### ISSUE TITLE
Remove usage of depreciated POSIX ucontext

### ISSUE THREAD

**Issue by kallisti5** [oneapi-src/oneTBB#795]
ucontext was outdated by POSIX issue 7.  It's used in ```src/tbb/arena.cpp``` via ```src/tbb/co_context.h```

Pure POSIX platforms don't have ucontext.h available.  As the source code notes, Mac OS X is already issuing depreciation warnings about its use.

Overall, oneTBB needs converted over to standard pthreads on Linux/unix platforms

**Comment by brad0** [comment]
I went to build on OpenBSD and ran into this. OpenBSD doesn't have ucontext and never will. As you said it has been long deprecated by POSIX.

**Comment by arunparkugan** [comment]
@brad0 is this issue still relevant?

**Comment by brad0** [comment]
> @brad0 is this issue still relevant?

Nope, resolved by https://github.com/oneapi-src/oneTBB/pull/1055

**Comment by arunparkugan** [comment]
As this enhancement issue is already resolved in the ticket #1055, am closing it.
