### ISSUE TITLE
Apple silicon release package

### ISSUE THREAD

**Issue by jnjaeschke** [oneapi-src/oneTBB#806]
Currently I cannot find the Apple Silicon version of TBB anywhere from where I can download them "scripted". I can download it via brew and also via conda, but not directly from the github releases page (as for osx-64, windows and linux).

For our custom build and dependency system it would be very helpful to have the apple silicon package also as a tgz file which can be downloaded so we can build our tbb dependency packages in a linux-CI.

**Comment by omalyshe** [comment]
@jnjaeschke Thanks for waiting. The request is being discussed internally. We will notify you about the decison.

**Comment by omalyshe** [comment]
@jnjaeschke  Thanks for waiting. The internal decision has been made to continue to not distribute oneTBB binaries for Apple Silicon via this GitHub project
