### ISSUE TITLE
Return value of bounded concurrent queue pop()

### ISSUE THREAD

**Issue by FloopCZ** [oneapi-src/oneTBB#807]
Hi everyone,

the [OneAPI spec](https://github.com/oneapi-src/oneAPI-spec/blob/9174607fce771d5f232d403e688a5bebe7838256/source/elements/oneTBB/source/containers/concurrent_bounded_queue_cls.rst) claims that concurrent bounded queue `pop()` function returns `void`:
```
void pop( value_type& result );
```

However, the implementation returns a `bool`:
https://github.com/oneapi-src/oneTBB/blob/05023723ff17dc436668a989a5f2c1873e994e72/include/oneapi/tbb/concurrent_queue.h#L380

What is the purpose of this boolean return value? Thank you.

**Comment by alexey-katranov** [comment]
It is always [returns `true`](https://github.com/oneapi-src/oneTBB/blob/05023723ff17dc436668a989a5f2c1873e994e72/include/oneapi/tbb/concurrent_queue.h#L511). It seems like misalignment with specification. However, changing the return value to `void` might break the existing code.

**Comment by FloopCZ** [comment]
ok, thank you for the info
Maybe it could be changed in the next major version or mentioned in the docs, what do you think?

**Comment by alexey-katranov** [comment]
Yes, it makes sense to mention somewhere, e.g. in release notes. I will follow up with the team.

The next major version is also an option but there is no any plans about the next major version.

**Comment by alexey-katranov** [comment]
During team discussion, we agreed that it is a bug that can be fixed without waiting for the major version.
