### ISSUE TITLE
How to link TBB dll to my library

### ISSUE THREAD

**Issue by Veronizlada** [oneapi-src/oneTBB#814]
Hello everyone, 

I have built tbb in both debug and release mode, I generated msvc_19.31_cxx_64_md_debug and msvc_19.31_cxx_64_md_release, as well as x64 folder. I also put ***\oneTBB\include as an additional include library in VS. Now I have to set up the dll. The way I do it when I own the library is I add a post build action in premake, which copies my dll in the other exe/dll. Now I am not the owner of tbb and I don't want to play with the cmake coming with it. Should I just manually copy the dll in my library? Sounds a bit hacky. Could you please help me?

Error: 
------ Build started: Project: tests, Configuration: Debug x64 ------
2>LINK : fatal error LNK1104: cannot open file 'tbb12.lib'
2>Done building project "tests.vcxproj" -- FAILED.

Thank you!

**Comment by anton-potapov** [comment]
@Veronizlada It seems that you need to add path to the built library  (tbb12.lib) to linker options (library path)

@Veronizlada BTW why do you need to build the library from sources?

**Comment by Veronizlada** [comment]
@anton-potapov fixed it! But I don't know how to do it in premake.
@anton-potapov I don't know the difference between source and other options.

**Comment by isaevil** [comment]
@Veronizlada is this issue still relevant?

**Comment by isaevil** [comment]
Closing it since no response.
