### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Tim1797** [oneapi-src/oneTBB#817]
I'm really struggling with the installation. I executed the installation example for single-configuration generators, but I can not figure out how the setting of the environment variables works. In the installation I did not provide a prefix so my installation directory should be `/usr/local` and in this directory are the header files (in`/usr/local/include/oneapi/tbb`), but I can not find the mentioned `vars.sh` script there. (Ubuntu 20.4)

**Comment by alexey-katranov** [comment]
If the package is installed inside system directories, you do not need any additional scripts. The system paths should be searched by the tools (compiler, linker, etc.).

**Comment by Tim1797** [comment]
Thank you!
