### ISSUE TITLE
Segfault: std::memset() is optimized out in allocate_scheduler() by GCC7

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#83]
Anaconda compiles TBB for [their Linux packages](https://anaconda.org/anaconda/tbb/files) using [their GCC7](https://anaconda.org/anaconda/gxx_linux-64/files). Compilation flags deducted from version strings of that package:
```
TBB: VERSION            2018.0
TBB: INTERFACE VERSION  10004
TBB: BUILD_DATE         Mon Jun 11 16:40:27 UTC 2018
TBB: BUILD_HOST         c874576f-722a-47c9-4338-ed2356bcc7d0 (x86_64)
TBB: BUILD_OS           CentOS release 6.9 (Final)
TBB: BUILD_KERNEL       Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017
TBB: BUILD_GCC          ../../build/version_info_linux.sh: line 27: g++: command not found
TBB: BUILD_LIBC 2.12
TBB: BUILD_LD           GNU ld version 2.20.51.0.2-5.46.el6 20100205
TBB: BUILD_TARGET       intel64 on cc_libc2.12_kernel4.4.0
TBB: BUILD_COMMAND      /tmp/build/80754af9/tbb_1528735158845/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++ -DDO_ITT_NOTIFY -g -O2 -DUSE_PTHREAD -m64 -fPIC -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -std=c++11 -I../../src -I../../src/rml/include -I../../include -I.
```
Unfortunately, while improving TBB threading for Numba, we found that default TBB on conda segfaults.
My [investigation ](https://github.com/numba/numba/pull/3202#issuecomment-415939206) suggests that [a call to std::memset()](https://github.com/01org/tbb/blob/tbb_2018/src/tbb/custom_scheduler.h#L119) in allocate_scheduler() is optimized out during compilation, causing uninitialized memory to be used in allocate_task().

**Comment by alexey-katranov** [comment]
It looks like that TBB is built without the `-flifetime-dse=1` flag. Starting from GCC6 this flag should be used to build TBB. This flag [was firstly enabled in TBB 2017 ](https://github.com/01org/tbb/blob/tbb_2018/CHANGES#L377-L378).

**Comment by anton-malakhov** [comment]
If it is so critically important, why it's not enforced by the make system? Anaconda builds TBB using build.py which in turn just calls make. They set their own C & CXXFLAGS for additional flags though.

**Comment by akukanov** [comment]
It is enforced in the makefiles for GCC>=6.
The idea about memset_s is a good one, thanks.
