### ISSUE TITLE
Missing 2021.6.0 release tag?

### ISSUE THREAD

**Issue by gtkramer** [oneapi-src/oneTBB#837]
For what it's worth, I work in Technology Development and members on the teams I work with use oneTBB internally for their software development.  We are in the process of upgrading all of the libraries we use from Intel's Software Development products.

As a part of this upgrade process, we started with the oneAPI Base Toolkit 2022.2.  This installs oneTBB 2021.6.0.  However, I only see a 2021.6.0-rc1 tag on GitHub.  Should there also be a 2021.6.0 tag that's been verified like we have for 2021.5.0 and 2021.4.0?  Is this tag missing, or was the code that was tagged as 2021.6.0-rc1 what was used in our product?

We'd like to use the latest tested, stable, released, verified, etc version of oneTBB.  GitHub indicates this is 2021.5.0, but our oneAPI Base Toolkit product indicates it should be 2021.6.0.  What's the right version here?

**Comment by ValentinaKats** [comment]
Hello @gtkramer, the latest oneTBB version is 2021.6.0. GitHub release will be available later. If you need oneTBB 2021.6.0 from GitHub, please use 2021.6.0-rc1 tag.

**Comment by gtkramer** [comment]
Thank you, @ValentinaKats!  One more question.  Are the sources on GitHub.com the same sources used to build the binaries for the oneTBB release in our oneAPI Base Toolkit?

**Comment by ValentinaKats** [comment]
@gtkramer, the sources on GitHub are the same sources used for building the binaries for Toolkit.
