### ISSUE TITLE
tbb_remove_compile_flag removes part of flag

### ISSUE THREAD

**Issue by felixonmars** [oneapi-src/oneTBB#847]
In Arch Linux, our C/CXXFLAGS contains "-Werror=format-security". Unfortunately when passing `-DTBB_STRICT=OFF` the first part of the flag got removed by `tbb_remove_compile_flag`, left only an ill-formatted string `=format-security` as a flag, resulting in compilation errors.

**Comment by thesamesam** [comment]
Fixed by #716, I think.

**Comment by egfefey** [comment]
Yes, the merged patch [#716](https://github.com/oneapi-src/oneTBB/pull/716) fixes this issue. Please update your repo. Please let us know if the issue persists for you after the update.

**Comment by isaevil** [comment]
@felixonmars please update your repo to have latest update and feel free to reopen if issue still exists.
