### ISSUE TITLE
Use tbbmalloc_proxy

### ISSUE THREAD

**Issue by 1003581** [oneapi-src/oneTBB#857]
I had a c++ code that uses tbbmalloc_proxy and this improved the performance alot on Windows 10
I packaged c++ code as python interfaceI using SWIG but it seems that SWIG ignores tbb and just uses the malloc implmenetation from ntddll.dll
Any ideas how to overcome this issue ?

**Comment by no-ponomarev** [comment]
@1003581 did you try to use a linker option or header file option from [documentation](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Windows_C_Dynamic_Memory_Interface_Replacement.html)?

**Comment by 1003581** [comment]
> @1003581 did you try to use a linker option or header file option from [documentation](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Windows_C_Dynamic_Memory_Interface_Replacement.html)?
I add tbbmalloc_proxy.h to my source code，but it dose not work.

**Comment by CRD1998** [comment]
Was this issue resolved? I am having a similar issue. I have a DLL which includes 'tbbmalloc_proxy.h' and when called from Python, TBB's allocator is not being used. Is there anyway to use 'tbbmalloc_proxy.dll' without linking Python against it? I am only concerned with allocations inside the DLL in which I have included 'tbbmalloc_proxy.h'.

**Comment by 1003581** [comment]
> Was this issue resolved? I am having a similar issue. I have a DLL which includes `tbbmalloc_proxy.h` and when called from Python, TBB's allocator is not being used. Is there any way to use `tbbmalloc_proxy.dll` without linking Python against it? I am only concerned with allocations inside the DLL in which I have included `tbbmalloc_proxy.h`.

NO. I overload the new/delete functions for specific classes, this avoids the use of ”tbbmalloc_proxy.h“. Maybe you can see if this helps.  https://github.com/swig/swig/issues/2324#event-7022785347

**Comment by nofuturre** [comment]
@1003581 is this issue still relevant?

**Comment by nofuturre** [comment]
If anyone encounter this issue in the future please open new issue with a link to this one
