### ISSUE TITLE
Quick Question: Where can I find the Circula Buffer Please?

### ISSUE THREAD

**Issue by Veronizlada** [oneapi-src/oneTBB#873]
Refered to here: https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Using_Circular_Buffers.html

Could you please help me find the circula buffer in the tbb files? 

Couldn't find it in the include director and not sure where the source file is?

Thanks Very Much!

**Comment by kboyarinov** [comment]
@Veronizlada, 
Currently, oneTBB does not provide any API implementing Circular buffer.
I would suggest to use [Boost implementation](https://www.boost.org/doc/libs/1_45_0/libs/circular_buffer/doc/circular_buffer.html) if it is suitable for your use case.

**Comment by Veronizlada** [comment]
@kboyarinov Thanks so much! DONE :)

**Comment by kboyarinov** [comment]
@Veronizlada, I would close the issue for now.
Feel free to re-open the issue or create a separate one if needed:)
