### ISSUE TITLE
tbbind in ubuntu 22.04

### ISSUE THREAD

**Issue by ilya-lavrenov** [oneapi-src/oneTBB#879]
Hi,

TBB uses plugin mechanism to try different HWLOC versions to understand system capabilities. Since HWLOC versions are not compatible sometimes, TBB uses several TBBBind versions tbbind, tbbbind_2_0, tbbbind_2_5.
For example, to understand whether processor has big / little cores tbbbind_2_5 is needed.

The question: how system TBB (installed via apt-get install libtbb-dev) understands HW capabilities on ubuntu 22.04 without TBBBind? I have not found any TBBBind packages on that system, but as far as I know, U22 contains a kernel better optimized for scheduling on big / little cores. So, having TBBBind is mandatory if I want to schedule work only for big cores

Is it a bug?

**Comment by pavelkumbrasev** [comment]
Hi @ilya-lavrenov, do you mean that TBBBind not being part of apt-get install libtbb-dev is a bug?

**Comment by ilya-lavrenov** [comment]
Hi @pavelkumbrasev 
Right. Or at least tbbbind needs to have its own package, but it's bot available at all.

**Comment by ilya-lavrenov** [comment]
Waiting for https://launchpad.net/ubuntu/+source/onetbb

**Comment by isaevil** [comment]
Seems like the problem is on Ubuntu maintainers' side. If any other questions are left, feel free to reopen this issue.

**Comment by ilya-lavrenov** [comment]
BTW, in Ubuntu 22.10 tubing library is present
