### ISSUE TITLE
Memory leak when passing bigger data types between nodes

### ISSUE THREAD

**Issue by kopalja** [oneapi-src/oneTBB#881]
Hi, I put together a minimal working example where I observe a memory leak. It is happening when I send struct of size 153 bytes (or larger) between two function nodes (the type of nodes does not matter I believe). Compiled with either `gcc 12.1.1` or `clang 14.0.6` on `5.19.2-arch1-1` memory usage goes to infinity (16Gb on my system).

```
#include <tbb/tbb.h>

using namespace oneapi::tbb::flow;

int main()
{
    using l_array_t = std::array<std::uint8_t, 153>; // 152 doesn't leak on my system
    graph g;
    function_node<int, l_array_t> n1(g, 1, [](auto x) { return l_array_t{}; });
    function_node<l_array_t, int> n2(g, 1, [](auto x) { return 0; });
    make_edge(n1, n2);
    while (true) {
        n1.try_put(0);
        g.wait_for_all();
    }
    return 0;
}
```
Also, all cores are 100% utilized which seems suspicious.

**Comment by FloopCZ** [comment]
Hi everyone, thank you @kopalja for the issue, I am able to reproduce it on my machine and all our servers.
```
Linux 5.19.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 Aug 2022 18:55:22 +0000 x86_64 GNU/Linux
gcc version 12.2.0
clang version 14.0.6
```
The leakage rate is about 80MB/s. With array size set to 152 bytes, the leak is gone indeed.

@kboyarinov Maybe a larger array, e.g., 500 would work for you? The first thing that came to mind after seeing this was the `small_object_pool`, but its threshold is set to 256 bytes which is pretty far from 152 (even with a bit of `std::array` overhead).

**Comment by kopalja** [comment]
Thanks @kboyarinov for your response.
I built `oneTbb` from source and wasn't able to reproduce this issue either. Maybe it's time for a new release?
Thanks.
