### ISSUE TITLE
Stoping a running node

### ISSUE THREAD

**Issue by Veronizlada** [oneapi-src/oneTBB#884]
Supose in **extreme** cases I have to stop a node from executing **queued** inputs and all inputs, is there a way to do so? Or even cancel all the graph while a node is running. Please note this an extreme case where things went wrong and need to stop **immediately**?

Thanks very much!

**Comment by kboyarinov** [comment]
@Veronizlada,

Consider creating [`oneapi::tbb::task_group_context`](https://spec.oneapi.io/versions/1.1-rev-1/elements/oneTBB/source/task_scheduler/scheduling_controls/task_group_context_cls.html) and passing it into the constructor of the `graph`  object.
Calling `task_group_context::cancel_group_execution()` method will cancel the execution of all tasks created by all nodes belongs to the graph that were not executed yet.
You can also handle the cancelation of the running task using some interruption in the node body.

**Comment by Veronizlada** [comment]
@kboyarinov Thanks so muc for your help, really appreciated!! This answer is what I needed.
