### ISSUE TITLE
What's new of the tag of v2021.7.0-rc1?

### ISSUE THREAD

**Issue by zepingWww** [oneapi-src/oneTBB#890]
I noticed there was a newest tag of v2021.7.0-rc1, which is not the latest version of release. So I have two questions as following:
1. What's new of the tag of v2021.7.0-rc1?
2. Being compared with v2021.5.0, which is more stable or more worth using?

**Comment by ValentinaKats** [comment]
@zepingWww, thank for reaching us. 

1.  v2021.7.0-rc1 tag is used to mark a release candidate of oneTBB 2021.7.0. However, it's not the final release yet. 
2. If you can use source code and want to get the latest changes, feel free to use v2021.7.0-rc1 tag or code directly from master branch. If you want a built version of oneTBB, check the latest available release in https://github.com/oneapi-src/oneTBB/releases.

**Comment by zepingWww** [comment]
> @zepingWww, thanks for reaching us.
> 
> 1. v2021.7.0-rc1 tag is used to mark a release candidate of oneTBB 2021.7.0. However, it's not the final release yet.
> 2. If you can use source code and want to get the latest changes, feel free to use v2021.7.0-rc1 tag or code directly from master branch. If you want a built version of oneTBB, check the latest available release in https://github.com/oneapi-src/oneTBB/releases.

Thanks!
