### ISSUE TITLE
one problem when throwing exception in flow graph

### ISSUE THREAD

**Issue by andrewmabc** [oneapi-src/oneTBB#903]
Hi,

There is one problem when throwing exception in flow graph.

I have read the following webpages, and try to throw some exception in some nodes. main thread can succeed in catch some exception from some nodes. But the program is pending, when some exception is thrown from some nodes.

https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Flow_Graph_exception_tips.html

Do you have this kind of problem? Thanks

regards

andrew

**Comment by kboyarinov** [comment]
@andrewmabc,

Could you please add more details on which nodes are you using and what scenario causes an issue.
Thank you in advance.

**Comment by isaevil** [comment]
@andrewmabc is this issue still relevant for you? Could you please respond?

**Comment by andrewmabc** [comment]
I can't reproduce the issue now. I will post the sample code if I have the issue again.

**Comment by isaevil** [comment]
Closing this since we didn't hear from you for some time. If any other questions are left, feel free to reopen this issue
