### ISSUE TITLE
tag for release 2021.6.0

### ISSUE THREAD

**Issue by gvollant** [oneapi-src/oneTBB#905]
Hello
on site https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#onetbb there is a "release 2021.6.0"

But there is no tag 6.0 on github

regards
Gilles Vollant

**Comment by thesamesam** [comment]
The tarballs seem to have rc1 in them -- is that intentional? Thanks!

**Comment by ValentinaKats** [comment]
@thesamesam, thanks for noticing! It was an overlook, the release tag is updated. The difference between tags is documentation updates.

**Comment by thesamesam** [comment]
Thank you!

**Comment by gvollant** [comment]
Thank you also.
As I understand, 7.0 is currently really at "rc" stade?

**Comment by ValentinaKats** [comment]
@gvollant, yes, oneTBB 2021.7.0 is at "rc" stage. rc stands for release candidate.

**Comment by isaevil** [comment]
Seems like the problem is solved. If any other questions are left, feel free to reopen this issue.

**Comment by gvollant** [comment]
I'll reopen the same issue for 7.0...
