### ISSUE TITLE
Parallel pipelines of serially dependent functions

### ISSUE THREAD

**Issue by Hvass-Labs** [oneapi-src/oneTBB#906]
Hello,

Have I understood correctly from your [docs](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/algorithms/functions/parallel_pipeline_func.html) and [tutorial](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Working_on_the_Assembly_Line_pipeline.html), that it is not possible to create a parallel pipeline that runs serially dependent functions / filters in parallel on multiple CPU cores? Because the filters have to be specified as `serial_in_order` or `serial_out_of_order` and these create bottle-necks that cannot be parallelized.

I recently came up with a way of making serially dependent functions run in parallel on streaming data, which is useful e.g. in audio processing to get much better multi-core CPU usage without having to modify the code for the audio effects. But I don't know if this kind of parallel pipeline is an original invention, or if it is already a well-known method among experts in parallel programming.

If you have a moment to look at the example I made, and if the method already exists then please let me know its name, and perhaps give me a reference to a paper that describes the method. That would be greatly appreciated.

Thanks very much!

https://github.com/Hvass-Labs/Parallel-Pipelines

**Comment by pavelkumbrasev** [comment]
Hi @Hvass-Labs, I kind of don't understand what type of pipeline do you want to implement.  
Will it be something like this-> read_data -> process F() -> process G() -> "other functions" -> save result?
For proposed pipeline it could be implemented via passing for example index `i` between stages. Hence, computation will be done in parallel and read and save in serial manner,

**Comment by Hvass-Labs** [comment]
Thanks for taking a look!

It is perhaps better explained in the PDF paper that is also available in the repository linked to above.

Briefly stated, the idea is to improve multi-core CPU efficiency for audio software (e.g. Ableton Live, BitWig, Cubase, Logic, Reaper, etc.) which are normally only "naively" parallelized as they let the different audio tracks and their effects run in different CPU threads, but when the audio tracks are mixed together and then more effects are applied to the mixed signal, it all becomes serially dependent and the audio software is unable to run it in parallel, so it is all run on a single CPU core.

Using the "buffered parallel pipelines" that I propose, it is actually possible to run serially dependent audio effects in parallel on multiple CPU cores - even within a single audio track, and that is what I try to demonstrate using the more abstract functions F and G, which could be two different audio effects that will process the incoming audio signal, one after the other. So the output of the function F will be used as the input in function G.

I'm not quite sure I understand your proposal of just using the index `i` as I don't think that would be sufficient. The intermediate results of the functions need to be buffered in order for the parallel pipeline to work.

My question is whether this kind of "buffered parallel pipeline" is a new invention or if it is already known, and under which name? And is it already possible to implement this using your library oneTBB, and perhaps I just misunderstood your docs?

Thanks again!

**Comment by Hvass-Labs** [comment]
I think I know what caused the confusion, so let me elaborate.

We want to compute `y[i] = G(F(x[i]))` in parallel where the functions `F` and `G` are run in two different threads and `x[i]` is the input stream and `y[i]` is the output stream.

In the description I had written that the functions are **serially dependent**. Perhaps I should clarify that this means we **must** work on the data in the correct order. So we **must** compute `F(x[i])` before we compute `F(x[i+1])`, and similarly we **must** compute `G(F(x[i]))` before we compute `G(F(x[i+1]))`.

For people with experience in audio processing this is quite obvious, because when `F` and `G` are audio effects, they usually have an internal state that gets updated on each call, so they must always be called in order, and that is why it is challenging to run the functions in parallel.

**Comment by pavelkumbrasev** [comment]
Oh, I see. I think the proposed idea kind of a basic pipeline concept and could be implemented with oneTBB using series of serial filters that would be executed one by one but in different threads. 
```cpp
    std::size_t i{0};
    tbb::filter<void, string> first_filter(tbb::filter_mode::serial_in_order, [&i, &x_vec] (tbb::flow_control& fc) -> string {
        if (i < x_vec.size()) {
            return x_vec[i++];
        } else {
            fc.stop();
            return string{};
        }
    });

    tbb::filter<string, string> second_filter(tbb::filter_mode::serial_in_order, [] (string input) {
        return F(input);
    });

    tbb::filter<string, string> third_filter(tbb::filter_mode::serial_in_order, [] (string input) {
        return G(input);
    });

    tbb::filter<string, void> fourth_filter(tbb::filter_mode::serial_in_order, [] (string G_result) {
        cout << "G result: " << G_result << endl;
    });
    int max_threads = /* amount of stages */ 4;
    tbb::parallel_pipeline(max_threads, first_filter & second_filter & third_filter & fourth_filter);

```
The proposed implementation should show similar performance as parallel version.

**Comment by Hvass-Labs** [comment]
Thanks very much for the code-sample, and I'm sorry for my late response!

I was under the impression that filters designated with `filter_mode::serial_in_order` were executed in serial-mode and not parallel-mode, so that a serialized "bottle-neck" is created for those filters? Or am I wrong, so your code-sample creates exactly the kind of buffered parallel pipeline that I need to process streams sequentially using multiple CPU threads?

Perhaps it would be a good idea to elaborate the examples in your docs.

**Comment by pavelkumbrasev** [comment]
It is a basic pipeline idea, when one stage is ready next one could be executed and in this moment both of stages might be executed in parallel.
We might consider this example for parallel_pipeline, so if you don't mind you can create a PR [there ](https://github.com/oneapi-src/oneTBB/tree/master/doc/main/tbb_userguide).

**Comment by Hvass-Labs** [comment]
Thanks again for your help!

It would be helpful with an example in your docs of how to create this kind of parallel pipeline, but I am not really familiar with your library so your dev-team better write it themselves. And please post a link in this thread so I get notified, and it may also help others find it in the future.
