### ISSUE TITLE
oneTBB compilation takes forever

### ISSUE THREAD

**Issue by de-gozaru** [oneapi-src/oneTBB#909]
Hi,

I'm trying to install a previous version of `oneTBB`, specifically `2018_U5`.
I used the following steps:
```bash
cd ~
mkdir tbbsrc
cd tbbsrc/
wget https://github.com/01org/tbb/archive/2018_U5.tar.gz
tar xvzf 2018_U5.tar.gz
cd oneTBB-2018_U5/
make all
```

However, after 1h of `make`, a small window started rendering some balls, and it took more than 20 hours and still going, it appears that this because of the command `./tachyon.tbb dat/balls.dat`.

Is this normal? how to correct this?

Thank you in advance!

**Comment by pavelkumbrasev** [comment]
@de-gozaru It is possible that there is some issue in example or even in library. Could you please test the same with latest version of oneTBB?

**Comment by isaevil** [comment]
@de-gozaru do you experience any issues like that with oneTBB?

**Comment by isaevil** [comment]
@de-gozaru have you considered trying latest version of oneTBB? Could you please respond?

**Comment by isaevil** [comment]
@de-gozaru Closing it since no response. Feel free to reopen if any questions are left. Our default suggestion is to use newer versions like 2021.7 (latest), these are currently supported versions.
