### ISSUE TITLE
Standard variables are not used by makefile rules for TBB examples

### ISSUE THREAD

**Issue by anton-malakhov** [oneapi-src/oneTBB#91]
According to https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html, `CPPFLAGS` is supposed to be used for invoking C/C++ compiler. But e.g., examples/test_all/fibonacci uses CXXFLAGS only. It also does not use `LDFLAGS` for specifying linker flags. As result, additional effort is required for running TBB examples in a correctly set environment like with conda's `tbb-devel` package: https://github.com/conda-forge/tbb-feedstock/pull/35#discussion_r218660892

I had to specify the following command line as a test for `tbb-devel` package: `make -C examples/test_all/fibonacci CXXFLAGS="$CPPFLAGS $LDFLAGS" TBBROOT=$PREFIX`.
Please also note that `TBBROOT` is required for OS X for setting rpath. But a development environment might want to set it itself through e.g. `CXXFLAGS` while not defining `TBBROOT`. So, I suggest the logic to be corrected to add rpath flag only if TBBROOT is defined.

**Comment by ivankochin** [comment]
The library and examples build system was migrated to CMake in the oneTBB 2021 release so this point is irrelevant now. Please reopen the issue if you still have any concerns.
