### ISSUE TITLE
oneTBB cannot be compiled as universal binary on OSX 12.5

### ISSUE THREAD

**Issue by ilya-lavrenov** [oneapi-src/oneTBB#910]
Steps to reproduce:
```sh
% cmake -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" ../
% cmake --build .
```
Compilation errors:
```
[ 41%] Building CXX object src/tbb/CMakeFiles/tbb.dir/itt_notify.cpp.o
[ 43%] Building CXX object src/tbb/CMakeFiles/tbb.dir/main.cpp.o
In file included from /Users/sandye51/Documents/Programming/git_repo/oneTBB/src/tbb/arena.cpp:17:
In file included from /Users/sandye51/Documents/Programming/git_repo/oneTBB/src/tbb/task_dispatcher.h:24:
/Users/sandye51/Documents/Programming/git_repo/oneTBB/src/tbb/scheduler_common.h:230:9: error: always_inline function '_tpause' requires target feature 'waitpkg', but would be inlined into function 'prolonged_pause' that is compiled without support for 'waitpkg'
        _tpause(0, time_stamp + 700);
        ^
[ 46%] Building CXX object src/tbb/CMakeFiles/tbb.dir/market.cpp.o
1 error generated.
make[2]: *** [src/tbb/CMakeFiles/tbb.dir/arena.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 48%] Linking C shared library ../../appleclang_14.0_cxx11_64_relwithdebinfo/libtbbmalloc.dylib
make[1]: *** [src/tbb/CMakeFiles/tbb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Built target tbbmalloc
make: *** [all] Error 2

```

**Comment by pavelkumbrasev** [comment]
@isaevil Could you please take a look?

**Comment by isaevil** [comment]
@ilya-lavrenov Could you please clarify, what version of oneTBB are you trying to build? Is that Mac the one with x86 CPU?

**Comment by ilya-lavrenov** [comment]
latest master

**Comment by phprus** [comment]
For a multi-arch configuration (if the CMAKE_OSX_ARCHITECTURES variable is defined), we need to check the CMAKE_OSX_ARCHITECTURES array items, not the value of the CMAKE_SYSTEM_PROCESSOR variable.

https://github.com/oneapi-src/oneTBB/blob/2eccd5f998aba26ba4a6be4c9a3ec33a057507ea/cmake/compilers/AppleClang.cmake#L34-L37

Suggested fix:

```cmake
# Enable Intel(R) Transactional Synchronization Extensions (-mrtm) and WAITPKG instructions support (-mwaitpkg) on relevant processors
if (CMAKE_OSX_ARCHITECTURES)
    set(TARGET_ARCHITECTURES "${CMAKE_OSX_ARCHITECTURES}")
else()
    set(TARGET_ARCHITECTURES "${CMAKE_SYSTEM_PROCESSOR}")
endif()
if ("${TARGET_ARCHITECTURES}" MATCHES "(x86_64|amd64|AMD64)") # OSX systems are 64-bit only
    set(TBB_COMMON_COMPILE_FLAGS ${TBB_COMMON_COMPILE_FLAGS} -mrtm $<$<NOT:$<VERSION_LESS:${CMAKE_CXX_COMPILER_VERSION},12.0>>:-mwaitpkg>)
endif()
```

@ilya-lavrenov, please check it.

**Comment by ilya-lavrenov** [comment]
> For a multi-arch configuration (if the CMAKE_OSX_ARCHITECTURES variable is defined), we need to check the CMAKE_OSX_ARCHITECTURES array items, not the value of the CMAKE_SYSTEM_PROCESSOR variable.
> 
> https://github.com/oneapi-src/oneTBB/blob/2eccd5f998aba26ba4a6be4c9a3ec33a057507ea/cmake/compilers/AppleClang.cmake#L34-L37
> 
> Suggested fix:
> 
> ```cmake
> # Enable Intel(R) Transactional Synchronization Extensions (-mrtm) and WAITPKG instructions support (-mwaitpkg) on relevant processors
> if (CMAKE_OSX_ARCHITECTURES)
>     set(TARGET_ARCHITECTURES "${CMAKE_OSX_ARCHITECTURES}")
> else()
>     set(TARGET_ARCHITECTURES "${CMAKE_SYSTEM_PROCESSOR}")
> endif()
> if ("${TARGET_ARCHITECTURES}" MATCHES "(x86_64|amd64|AMD64)") # OSX systems are 64-bit only
>     set(TBB_COMMON_COMPILE_FLAGS ${TBB_COMMON_COMPILE_FLAGS} -mrtm $<$<NOT:$<VERSION_LESS:${CMAKE_CXX_COMPILER_VERSION},12.0>>:-mwaitpkg>)
> endif()
> ```
> 
> @ilya-lavrenov, please check it.

At least compilation has passed.

**Comment by phprus** [comment]
PR: #919
