### ISSUE TITLE
Compiling tbb 2021.6.0 with TBB_ENABLE_IPO flag : error plugin needed to handle lto object

### ISSUE THREAD

**Issue by fdiedler** [oneapi-src/oneTBB#923]
Hi,

I try to compile under Windows 10 with GCC 11.2 the last current version of TBB with the TBB_ENABLE_IPO flag using Cmake like depicted int he screenshot.

![cmake](https://user-images.githubusercontent.com/42271872/193411513-b21488be-3bb7-435c-ac22-b716747729cb.png)

I got this error 

> [ 74%] Linking CXX shared library ..\..\gnu_11.2_cxx11_64_release\libtbb12.dll
C:\nuwen-18.0\bin\ar.exe: CMakeFiles/tbb.dir/address_waiter.cpp.obj: plugin needed to handle lto object
make[3]: [C:\Users\florent\AppData\Local\Temp\ccvecFPQ.mk:6: C:\Users\florent\AppData\Local\Temp\cce1JjHy.ltrans1.ltrans.o] Error 1 (ignored)
make[3]: [C:\Users\florent\AppData\Local\Temp\ccvecFPQ.mk:3: C:\Users\florent\AppData\Local\Temp\cce1JjHy.ltrans0.ltrans.o] Error 1 (ignored)
make[3]: [C:\Users\florent\AppData\Local\Temp\ccvecFPQ.mk:9: C:\Users\florent\AppData\Local\Temp\cce1JjHy.ltrans2.ltrans.o] Error 1 (ignored)

What does it mean ? And how to use the link time optimization (LTO) when compiling TBB ?

Thanks,

**Comment by isaevil** [comment]
@fdiedler These errors seems to be toolchain-specific and not caused by TBB itself. Does `nuwen mingw` provide `gcc-ar.exe`  additionally to `ar.exe`? To enable LTO when compiling TBB passing `-DTBB_ENABLE_IPO=ON` should be enough.
