### ISSUE TITLE
cmake-gui compile errors on Windows

### ISSUE THREAD

**Issue by guyuezuntinggithub** [oneapi-src/oneTBB#927]
hi guys
I build tbb project with cmake gui on windows. 
when I build it , coccurs many errors like the following
>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_debug.lib”
4>已完成生成项目“_test_malloc_used_by_lib.vcxproj”的操作 - 失败。
11>------ 已启动生成: 项目: test_malloc_used_by_lib, 配置: Debug x64 ------
3>LINK : fatal error LNK1104: 无法打开文件“..\..\msvc_19.16_cxx_64_md_debug\tbbmalloc_debug.lib”
3>已完成生成项目“tbbmalloc_proxy.vcxproj”的操作 - 失败。
12>------ 已启动生成: 项目: _test_malloc_atexit, 配置: Debug x64 ------
13>------ 已启动生成: 项目: test_malloc_new_handler, 配置: Debug x64 ------
14>------ 已启动生成: 项目: test_malloc_overload, 配置: Debug x64 ------
15>------ 已启动生成: 项目: test_malloc_overload_disable, 配置: Debug x64 ------
7>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_debug.lib”
7>已完成生成项目“test_malloc_pools.vcxproj”的操作 - 失败。
9>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_debug.lib”
5>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_debug.lib”
5>已完成生成项目“test_malloc_compliance.vcxproj”的操作 - 失败。
9>已完成生成项目“test_malloc_regression.vcxproj”的操作 - 失败。
6>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_debug.lib”
6>已完成生成项目“test_malloc_init_shutdown.vcxproj”的操作 - 失败。
12>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_proxy_debug.lib”
12>已完成生成项目“_test_malloc_atexit.vcxproj”的操作 - 失败。
11>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\_test_malloc_used_by_lib_debug.lib”
11>已完成生成项目“test_malloc_used_by_lib.vcxproj”的操作 - 失败。
16>------ 已启动生成: 项目: test_malloc_atexit, 配置: Debug x64 ------
14>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_proxy_debug.lib”
14>已完成生成项目“test_malloc_overload.vcxproj”的操作 - 失败。
15>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_proxy_debug.lib”
15>已完成生成项目“test_malloc_overload_disable.vcxproj”的操作 - 失败。
10>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_debug.lib”
10>已完成生成项目“test_scalable_allocator.vcxproj”的操作 - 失败。
16>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\_test_malloc_atexit_debug.lib”
16>已完成生成项目“test_malloc_atexit.vcxproj”的操作 - 失败。
13>LINK : fatal error LNK1104: 无法打开文件“..\msvc_19.16_cxx_64_md_debug\tbbmalloc_proxy_debug.lib”
13>已完成生成项目“test_malloc_new_handler.vcxproj”的操作 - 失败。

**Comment by isaevil** [comment]
@guyuezuntinggithub is this still an issue? Could you please respond?

**Comment by isaevil** [comment]
@guyuezuntinggithub we weren't able to reproduce this issue. Closing it since no response. Feel free to reopen with more details and steps on how to reproduce such error.
