### ISSUE TITLE
tag for release 2021.7.0

### ISSUE THREAD

**Issue by gvollant** [oneapi-src/oneTBB#929]
Hello
on site https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#onetbb there is a "release 2021.7.0"

But there is no tag 7.0 on github (there is only 7.0rc1)

regards
Gilles Vollant

It look like #905 for 6.0 @ValentinaKats

**Comment by omalyshe** [comment]
v2021.7 tag has been created https://github.com/oneapi-src/oneTBB/tree/v2021.7.0.

**Comment by gvollant** [comment]
thank you, but page https://github.com/oneapi-src/oneTBB did not list 7.0

**Comment by isaevil** [comment]
https://github.com/oneapi-src/oneTBB/releases/tag/v2021.7.0 is now available on main page.

**Comment by gvollant** [comment]
hello
there is a 8.0 final download for linux at https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#onetbb 

so I suggest adding a 8.0 final tag also @omalyshe @isaevil
