### ISSUE TITLE
TBB with hyperthreading

### ISSUE THREAD

**Issue by Tim1797** [oneapi-src/oneTBB#948]
Hi,
I am currently working with TBB for my master thesis. I tested my implementations on two different hardware systems. One uses a CPU with 8 cores without hyperthreading, and the other has 16 cores with hyperthreading. The problem I ran into is that the speedups differ significantly depending on which hardware system I use. On the system with 16 cores, the speedups are worse than they are with just the 8 cores. This is also true if I limit the number of available threads on the system with 16 cores to 8 by setting the  `max_allowed_parallelism` parameter in the `global_control` class. Is it possible that TBB does not distribute the tasks to the processing units in an efficient way because hyperthreading is enabled?

**Comment by pavelkumbrasev** [comment]
Hi @Tim1797, in your case it might be several factors that lead to worse scaling. (hyperthreading shouldn't be a problem)
It is hard to give a exact answer without all data but there are some ideas and assumptions: 
Your algorithm might not scale on more than 8 threads.  
The hyperthreading will not give perfect scaling. What results do you observe?

**Comment by Tim1797** [comment]
My algorithm do not scale very well which could explain why the speedups are worse if I use 16 or 32 threads (with hyperthreading), but what confuses me is the fact that the speedups are also worse with 8 threads. On the machine with 8 cores, I see speedups of around 6 which are reduces on the other machine to around 2 even though I limit the available threads to 8.

**Comment by pavelkumbrasev** [comment]
It might be dependent on CPU frequency, so you might calculate max scaling by yourself.
You might also experiment with taskset if you use Linux or process affinity if Windows.

**Comment by Tim1797** [comment]
Even if I limit to 8, the affinity mask always shows that all processors #0 through #31 are used. If I look with htop, 7 threads are created.

![image](https://user-images.githubusercontent.com/53017505/199476677-3d7d722c-5a6b-45c4-a6dc-2684b4b45fd9.png)

I am not sure what you mean with the dependence on CPU frequency...

**Comment by pavelkumbrasev** [comment]
Some processors might work faster than other because of higher frequency that why they are not scaling even on 8 threads it is not enough work for them.

**Comment by Tim1797** [comment]
The 16 core system has 3.2 GHz and the 8 core system has 3.8 GHz, so I guess this should not be the issue.

**Comment by Tim1797** [comment]
![image](https://user-images.githubusercontent.com/53017505/199490771-39e51d53-d85d-4d13-9818-b0dc2c8ebbb3.png)
![image](https://user-images.githubusercontent.com/53017505/199491461-17922040-eed3-4e38-a745-f67e3abe5d84.png)

**Comment by pavelkumbrasev** [comment]
On the first machine there is two NUMA nodes that might lead to problem with memory access.
Please try to use taskset -c 0-7 ./app_name. It will execute your application on first NUMA node on 8 first cores.
If it is NUMA effects you might use also[ task_arena API](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.html) to specify particular NUMA.

**Comment by Tim1797** [comment]
Ok that probably makes sense. Thank you!
