### ISSUE TITLE
Clarify TBB/oneTBB relationship in README

### ISSUE THREAD

**Issue by asmaloney** [oneapi-src/oneTBB#961]
I landed on the oneTBB GitHub page having used TBB but not having heard of oneTBB. So the first question I had was: Is this a fork or an official replacement for TBB?

It took quite a bit of searching to find the relationship between TBB and oneTBB. I looked all over the oneAPI site - but that didn't tell me anything (about anything, really 😄 - lots of buzzwords). I found an answer... on [StackOverflow](https://stackoverflow.com/a/69479217).

I realize there's a migration guide linked in the README, but no info about how the projects are related.

So I would suggest adding a one-sentence clarification in the README that this is the official replacement for TBB.

**Comment by Timmmm** [comment]
Yeah this was also the first question I had when I just discovered oneTBB. The readme should really clarify the relationship between oneTBB and TBB, and what the differences are, who is behind it etc.

[This page](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onetbb.html#gs.io7w8j) has a very concise answer:

> †Intel® Threading Building Blocks (Intel® TBB) is now called Intel oneAPI Threading Building Blocks (oneTBB) to highlight that the tool is part of the oneAPI ecosystem.

I have no idea what oneAPI is but it answers all the questions: it's not a fork, it's just a rebranding, and Intel are still developing it. I suggest copying that sentence to the README somewhere.

**Comment by aavbsouza** [comment]
Hello, I believe that would be useful to link to this document (about some expected changes https://www.intel.com/content/www/us/en/developer/articles/technical/tbb-revamp.html. I do not know if this is the latest version of this document).

**Comment by alexandraepan** [comment]
@asmaloney @Timmmm @aavbsouza Thanks for your feedback! Have added a note to README.md, let us know if something is wrong :)
