### ISSUE TITLE
Cannot compile on Windows ARM64EC

### ISSUE THREAD

**Issue by MoeMod** [oneapi-src/oneTBB#966]
oneTBB\include\oneapi\tbb\detail\_machine.h(39): warning C4163: '__rdtsc': not available as an intrinsic function
Tested on MSVC 14.34.31931
Seems like there is no __rdtsc intrinsic on ARM64EC

**Comment by nofuturre** [comment]
@MoeMod is this issue still relevant?

**Comment by nofuturre** [comment]
If anyone encounter this issue in the future please open new issue with a link to this one
