### ISSUE TITLE
Memory not being release after call to tbb::task_arena::execute

### ISSUE THREAD

**Issue by Dr15Jones** [oneapi-src/oneTBB#967]
In order to isolate different sets of tasks from one another (so that task from one set do not get execute by the thread running `tbb::task_group::wait` of another set)  we make use of `tbb::task_arena::execute`. This worked fine until I used such isolation in a case that was being called frequently. In that case, I noted that under Linux the VSize of the job was growing alarmingly fast and eventually the jobs were being killed because the exceeded the shell's allowed VSize of an executable. 

By looking at the call stacks which triggered the memory violation as well as dumping the information about the memory pages being used by the job (via the executable smap) it looks like the problem is under the hood `tbb::task_arena::execute` ultimately calls mmap (which running under the debugger confirmed) but the corresponding calls to munmap are not occurring (again via tracing under the debugger). This hypothesis is further strengthened when I moved the call to `execute` further up our call hierarchy so the call was happening about 1/1000th as often and then the VSize stabilized. [Moving the placement of the call isn't really a good option as it breaks encapsulation within our system but was good for a test.]

A simplified test program can be found below. While it is running it, one can watch the VSize of the executable steadily grow. If `ARENA_INSIDE_FOR_LOOP` is set the code make as a `tbb::task_arena` for each of the inner for loop iterations. In that case, the VSize grows steadily (and the program is quite slow). If `ARENA_INSIDE_FOR_LOOP` the `tbb::task_arena::execute` call is moved outside of the inner most for loop and the VSize of the job is very stable (and the program runs very fast).

```C++
#include "oneapi/tbb/task_arena.h"
#include "oneapi/tbb/task_group.h"
#include "oneapi/tbb/global_control.h"
static constexpr int kConcurrency = 8;
static constexpr int kIterations = 10000000;

#define ARENA_INSIDE_FOR_LOOP

int main() {


  oneapi::tbb::global_control threads(oneapi::tbb::global_control::max_allowed_parallelism, kConcurrency);
  oneapi::tbb::global_control  stackSize(oneapi::tbb::global_control::thread_stack_size, 10*1024*1024);

  tbb::task_arena topArena(kConcurrency);

  topArena.execute([]()
   {
     //the task we want to run often
     auto innerTask = []() {
        tbb::task_group g2;
        g2.run([](){});
        g2.wait();
     };

     //task within the for loop
#if defined(ARENA_INSIDE_FOR_LOOP)
     auto loopTask = [innerTask]() {
        tbb::task_arena bottomArena(kConcurrency);
        bottomArena.execute(innerTask);
                     };
#else
       auto loopTask = innerTask;
#endif

     auto loop = [loopTask]() {
       for(int j=0; j<kIterations;++j) { loopTask();} };

#if defined(ARENA_INSIDE_FOR_LOOP)     
     auto groupTask = loop;
#else
     auto groupTask = [loop]() {
          tbb::task_arena bottomArena(kConcurrency);
          bottomArena.execute([loop](){ loop(); });
     };
#endif
       
     
     tbb::task_group g;
     for(int i = 0; i< kConcurrency; ++i) {
       g.run(groupTask);
     }
     g.wait();
   });
  return 0;
}
```

**Comment by Dr15Jones** [comment]
As a follow up, moving the construction of the inner `tbb::task_arena` to be outside of the inner most for loop and then reusing it inside the loop also avoids the rapid memory increase (but there is still a much slower increase). 

In addition, switching to `tbb::this_task_arena::isolate` also works (and is actually what we tend to do in other places of our code).

**Comment by nofuturre** [comment]
@Dr15Jones is this issue still relevant?

**Comment by nofuturre** [comment]
If anyone encounter this issue in the future please open new issue with a link to this one
