### ISSUE TITLE
[Document] Wrong namespace of filter mode of pipeline.

### ISSUE THREAD

**Issue by sukeya** [oneapi-src/oneTBB#972]
Hello,
The following document says the filter modes of pipeline in namespace `filter`, but the actual namespace is `filter_mode` in /include/oneapi/tbb/parallel_pipeline.h.

/main/tbb_userguide/Working_on_the_Assembly_Line_pipeline.html
line 118, 121, 124

**Comment by isaevil** [comment]
It is also `filter_mode` in [spec](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/algorithms/functions/parallel_pipeline_func/filter_mode_enum.html).
@alexandraepan can you take a look?
