### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by FloopCZ** [oneapi-src/oneTBB#973]
Hi, would it be possible to draft a new release? It has been quite some time since 2021.7.0 with plenty of bug fixes and improvements and some distributions are still waiting for an official version.

**Comment by isaevil** [comment]
@FloopCZ public release of 2021.7 on GitHub was about a month ago. So it hasn't been long enough since then. I can only suggest to use master branch if it is urgent to have newer version.

**Comment by FloopCZ** [comment]
Thank you for your reply, I have not realized that the release names are not based on their release dates.
