### ISSUE TITLE
Crash on exit when TBB used in dynamically loaded library

### ISSUE THREAD

**Issue by bissonm** [oneapi-src/oneTBB#977]
Repro case:
* A DLL links against TBB and contains a function using a simple TBB parallel construct
* An application doesn't link directly against the DLL, but loads it dynamically (dlopen/dlsym) and calls the function
* When the application exist, it crashes.

I was able to get the crash on Linux and OSX, I was not able to get the crash on Windows (therefore the simplified repro case I attached here is meant for Linux and OSX, but it's probably very easy to adapt to Windows, just changing the build instructions).

Note that the crash is not 100% reproducible, so there seems there is a race involved.
Note that if the application links against TBB, then the crash is not reproducible.  My guess is that because TBB ends up being unloaded BEFORE the end of the process (since the reason it gets loaded is because a DLL links against it and that DLL is unloaded dynamically from the process) and then something happens at the end of the process but TBB is already unloaded...?

See attached file: [crash_repro.zip](https://github.com/oneapi-src/oneTBB/files/10181984/crash_repro.zip)

The simple "plugin" is:

```
#include "reproplugin_export.h"

#include <tbb/parallel_for.h>
#include <tbb/blocked_range.h>

#include <iostream>
#include <mutex>


extern "C" REPROPLUGIN_EXPORT void plugin_function()
{
    std::cout << "Implementation of \"" << __func__ << "()\"" << std::endl;

    std::mutex m;
    tbb::parallel_for(tbb::blocked_range<int>(0, 20),
        [&](tbb::blocked_range<int> r)
        {
            for (int i = r.begin(); i < r.end(); ++i)
            {
                const std::lock_guard<std::mutex> lock(m);
                std::cout << "Iteration #" << i << std::endl;
            }
        });
}
```

The application is simply loading the DLL and calling the function:

```
#include <filesystem>
#include <iostream>
#include <memory>
#include <string>

#include <dynalo/dynalo.hpp>

int main(int argc, const char* argv[])
{
    auto folderPath = std::filesystem::path(argv[0]);
    folderPath.remove_filename();

    // Load a DLL.
    const std::string libraryName{ "ReproPlugin" };
    const auto libraryPath = (folderPath / dynalo::to_native_name(libraryName)).string();
    std::unique_ptr<dynalo::library> library;
    try {
        library = std::make_unique<dynalo::library>(libraryPath);
    }
    catch(...){
        std::cerr << "Unable to load \"" << libraryName << "\"." << std::endl;
        return 1;
    }

    // Get the symbol.
    const std::string operatorString{ "plugin_function" };
    using OperatorSignature = void();
    OperatorSignature* function = nullptr;
    try {
        function = library->get_function<OperatorSignature>(operatorString);
    }
    catch (...) {
        std::cerr
            << "Library \"" << libraryName << "\" : Symbol \"" << operatorString << "\" not found."
            << std::endl;
        return 2;
    }

    // Call the function.
    (*function)();

    return 0;
}
```

The build script gets TBB, builds it, build the application and plugin, then runs it a bunch of times until it crashes (usually almost instantaneously):

```
#!/bin/bash
set -e

WORKING_FOLDER=~/crash_repro
BUILD_TYPE=Release

rm -rf $WORKING_FOLDER

# Check out and build TBB
# 2021.7.0 was the latest available version.
git clone --branch v2021.7.0 https://github.com/oneapi-src/oneTBB.git $WORKING_FOLDER/oneTBB/oneTBB
cmake -S $WORKING_FOLDER/oneTBB/oneTBB -B $WORKING_FOLDER/oneTBB/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTBB_TEST=OFF
cmake --build $WORKING_FOLDER/oneTBB/build -j$(nproc)
cmake --install $WORKING_FOLDER/oneTBB/build --prefix $WORKING_FOLDER/oneTBB/install --strip

# Build the application.
cmake -S "$(dirname "$0")" -B $WORKING_FOLDER/crash_app/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DTBB_ROOT=$WORKING_FOLDER/oneTBB/install
cmake --build $WORKING_FOLDER/crash_app/build

# Run a few time to get the crash.
while true
do
    $WORKING_FOLDER/crash_app/build/ReproApp
done
```

Note that the repro case uses dynalo (for cross-platform dynamic library loading) to simplify things, it is included in the repro case zip.

**Comment by pavelkumbrasev** [comment]
Hi @bissonm, dynamic library unload is tricky moment for oneTBB because worker threads finishing their routine or a least trying to finish it and once library unloaded they might touch non-existant addresses. Could you try use [task_scheduler_handler ](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/task_scheduler/scheduling_controls/task_scheduler_handle_cls.html)in "Library" code? It will force oneTBB workers to end up their routine and finish.

**Comment by bissonm** [comment]
Hi @pavelkumbrasev, thanks for your answer.  We've tried to use it because it looked like what we need to make sure things clean up properly before we unload and/or exit the process, but we have a bit of complication, maybe you can provide some guidance...?

The repro case I provided above is really the minimal way I was able to repro the problem, but the real setup is just a bit more involved.  In the real setup (actually I'm still simplifying but you'll get the picture), the actual project is not an application, but a library (let's call it Library.so).  This library can dynamically load extensions, like the plug-in presented in the use case, which can link with TBB (let's call it Plugin.so).  Now the tricky thing is that Library.so can be integrated in different contexts.  It can be integrated in an application which does not use TBB (and therefore doesn't want to link with TBB directly and won't call any task_scheduler_handle stuff), but it can also be used in applications which fully use TBB (which may or may not call the task_scheduler_handle stuff).  When the application uses TBB, we make sure we use the TBB from the application so we can get all the goodies of TBB's nested parallelism, etc.

In such a setup, where should we make the call to `finalize()`?  It seems we are in a catch 22, because if we rely on the application to do it, it forces the application to link with TBB even if it doesn't want to care about that "implementation detail". 
 If we do it on our side of the fence, either in Library.so or when Plugin.so gets unloaded, we are in trouble in case the host application in which we integrate also uses TBB and might either call `finalize()` or wants to still use TBB.

From what I read in the doc, if the main application uses task_scheduler_handle and our library also does, one of the calls to `finalize()` will fail until there is only one handle left.  And that's great.  But here is the problem...  If the host application (we don't control all host applications) uses TBB, but doesn't use task_scheduler_handle, then our library might call `finalize()` even if the main application still wants to use TBB...

I know this is a complicated use case, but any guidance on how we could use the API in a way that would work for those cases and still work cleanly?

It almost seems what we need would involve requiring ALL users of TBB to have a ref-count object that would allow knowing if TBB is still "in use"...

**Comment by bissonm** [comment]
Thanks for the tip about `tbb::finalize()` throwing, I think I hit this in my early tries, and at first I thought it was a crash, not an uncaught exception...!

What do you mean by "any public references on TBB"?  Do you mean if someone else is holding a `task_scheduler_handle`?

I'm asking because my worry is that if "application" still uses TBB, but doesn't use the `task_scheduler_handle` API, then calling `finalize()` from the plugin will mess things up for the application still using TBB, right?

**Comment by bissonm** [comment]
How about something like the following:

```
// The main application does some work in parallel.
tbb::parallel_for(0, 100, [] (int) { /* some work */ });

// The application loads and unloads the plugin.
loadPlugin();
// The next line will call tbb::finalize() internally, on the plugin side.
unloadPlugin();

// The main application does some work in parallel.
tbb::parallel_for(0, 100, [] (int) { /* some work */ });
```

In something like this, no reference is kept, so the `finalize()` call in the plugin will succeed and mess up the work for the main application, right?

I just tried it, the call to `finalize()` worked, and things seem to still be working after for the second `parallel_for()`.  So is it safe to assume that TBB is still perfectly usable **after** calls to `finalize()`, potentially re-initializing some stuff internally?

**Comment by pavelkumbrasev** [comment]
In provided example the thread that execute the `parallel_for` will keep the public_reference and your `finilize` will be NOP. 
If the application have no public references it is ok to `finilize` it because on the next access it will initialize it again.

**Comment by bissonm** [comment]
Alright, so I gave it a try, and based on the content of this thread, I think we have a solution that works for us in all the different types of integrations mentioned above.  So that's great.

One last question though: in some situation we are still stuck using TBB 2018_U6.  It doesn't offer the `tbb::finalize()` API, but it offers something very similar through the `tbb::task_scheduler_init` object.  Using something like:

```
#define TBB_PREVIEW_WAITING_FOR_WORKERS    1
#include <tbb/task_scheduler_init.h>

class TBBContext
{
public:
    TBBContext() : m_tbb_scheduler_obj() {}
    ~TBBContext() { m_tbb_scheduler_obj.blocking_terminate(std::nothrow_t{}); }

private:
    tbb::task_scheduler_init m_tbb_scheduler_obj;
};
```

seem to behave very much like the `task_scheduler_handle` and `tbb::finalize()` stuff: `blocking_terminate()` throws if there is still a reference to something, it's ok to re-initialize threads after having called it, etc.

Do you know if those assumptions are right for this (older) API?  Should it behave pretty much like the newer API:

```
#include <tbb/global_control.h>

class TBBContext
{
public:
    TBBContext() : m_handle(tbb::attach{}) {}
    ~TBBContext() { tbb::finalize(m_handle, std::nothrow_t{}); }

private:
    tbb::task_scheduler_handle m_handle;
};
```

**Comment by pavelkumbrasev** [comment]
@bissonm I'm not pro in older version but I believe newer API was build upon old idea. Also [migration guide](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Migration_Guide/Task_Scheduler_Init.html) noted that this is same.

**Comment by bissonm** [comment]
Thanks.  And is there a reason why TBB doesn't call `finalize()` itself upon static destruction?  It seems that it would be safe to do if someone is still using TBB, and otherwise it would be just some clean-up?  There might be good arguments, but I'm just wondering...

**Comment by pavelkumbrasev** [comment]
TBB by itself release all resources when there is no references that prolongs its lifetime. Basically, `finilize()` use the same mechanism but it is a API to force TBB to shutdown when for example it is unsafe to rely on default behavior.

**Comment by bissonm** [comment]
I'm under the impression that if TBB was releasing all resources by itself, the original problem reported by this issue would not exist...

If we don't do anything, we get a crash, but with an explicit call to `finalize()`, we avoid the crash...  Some something seems to be missing from the "default behavior"...?

**Comment by pavelkumbrasev** [comment]
As you known in concurrent environment we can not rely only on timings because it is hard to predict the operation flow.
In scenario where you don't explicitly call `finalize` thread finishes the work with TBB and unload library meanwhile TBB workers are might work with some static objects the are loaded in process memory but once library is unloaded you will get a crash.
With explicit `finalize` call you wait (or try wait) until library will join all worker threads.

**Comment by pavelkumbrasev** [comment]
Please reopen this issue if you still have a questions.
