### ISSUE TITLE
Windows Release building error from add_subdirectory 

### ISSUE THREAD

**Issue by yinzeq** [oneapi-src/oneTBB#986]
I have meet a building error in windows release type by add_subdirectory . However, there is no problem when I use debug type or build libraries in a single solution.
Code is from master branch.

Error log is: 

d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: 命令“setlocal [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: cd E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: E: [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -E __create_def E:/viscanner/barcode-sdk/build_win_Release/modules/hpc/modules/oneTBB/src/tbb/tbb.dir/Release/exports.def E:/viscanner/barcode-sdk/build_win_Release/modules/hpc/modules/oneTBB/src/tbb/tbb.dir/Release//objects.txt [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: :cmEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: :cmErrorLevel [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: exit /b %1 [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: :cmDone [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]
d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(150,5): error MSB3073: :VCEnd”已退出，代码为 -1073741819。 [E:\viscanner\barcode-sdk\build_win_Release\modules\hpc\modules\oneTBB\src\tbb\tbb.vcxproj]

How to fix it ?

**Comment by isaevil** [comment]
@yinzeq Could you please send more verbose log? I can only see Visual Studio-specific errors with no information what went wrong. I tried to do such thing using VS 2022 with such folder structure:
```
build
CMakeLists.txt
main.cpp
oneTBB
```
I tried to do `add_subdirectory(${CMAKE_SOURCE_DIR}/oneTBB)` and make a release build and didn't face any errors.

**Comment by isaevil** [comment]
Closing it since no response. Feel free to reopen if issue still persists.
