### ISSUE TITLE
how to make libtbb.so for android?

### ISSUE THREAD

**Issue by linyuan0** [oneapi-src/oneTBB#99]
I want to compile the tbb dynamic library under android, I git the latest code, using android-ndk-r18b version can not compile normally; I would like to ask which ndk version can compile tbb normally?
I saw that the compiled zip has compiled so, but only x86_64 and x86; I want arm64-v8a, so I have to compile it myself.

**Comment by nik-ponomarev** [comment]
@linyuan870, supported NDK version could be found in [release notes](https://github.com/01org/tbb/blob/tbb_2019/doc/Release_Notes.txt).
So, android-ndk-16 should work correctly. Use this command to compile tbb from source:
```
export NDK_ROOT=%PATH_TO_NDK%
ndk-build tbb tbbmalloc arch=arm target=android compiler=clang ndk_version=16 -j -B
```
andoid-ndk-r17b will be supported in the next release.

**Comment by linyuan870** [comment]
@nik-ponomarev thanks , it really helped me!
I would like to ask if the dynamic library or static library is compiled by different versions of ndk,can it be run normally after running to android? Still better to compile with the same version?

**Comment by nik-ponomarev** [comment]
@linyuan870, I didn't really understand the question. Are you asking about compatibility between NDK and Android version?

**Comment by linyuan870** [comment]
@nik-ponomarev 
Suppose I have a libtestA.so compiled by android-ndk-16 and a libtestC.so compiled by android-ndk-12; LibtestC.so links to libtestA.so, and then my android program calls libtestC.so;I would like to ask a so compiled in two different NDK versions. Can my android program normally call the functions in libtestC.so and libtestA.so?

**Comment by nik-ponomarev** [comment]
@linyuan870, that is a rather wide question, that depends not only on NDK, but on Android platform version. There shouldn't be a problem with libtestC.so and libtestA.so linkage since NDK versions are compatible.  But when building the library for the platform you should look at [API level](https://developer.android.com/ndk/guides/stable_apis) that you are targeting and what platforms support it.

**Comment by linyuan870** [comment]
@nik-ponomarev ok，thanks！
