### ISSUE TITLE
High CPU observed with TBB when the loop size is increased.

### ISSUE THREAD

**Issue by Dush27** [oneapi-src/oneTBB#991]
Hi Team,
       Below is my code where I have used task_arena implementation as suggested in https://github.com/oneapi-src/oneTBB/issues/105 since i was facing similar high CPU issues as discussed in the link.
       In the below code, tbb::info::default_concurrency() and tbb::this_task_arena::max_concurrency() evaluates to 8 in my system.

        **tbb::global_control global_limit(tbb::global_control::max_allowed_parallelism, tbb::info::default_concurrency());
        int max_threads = tbb::this_task_arena::max_concurrency() 
                                     + tbb::info::default_concurrency() /* the number of IO threads to reserve slots inside the arena */;
        tbb::task_arena arena(max_threads, tbb::info::default_concurrency());
        arena.execute([&] {
            tbb::this_task_arena::isolate([&] {
                tbb::parallel_for(tbb::blocked_range2d<int>(kSize, (height - kSize), kSize, (width - kSize)),
                    [&](tbb::blocked_range2d<int> r)
                    {
                               //parallel operation
                    });
                });
            });**

I could see with above code, application's CPU varies from 40%-60% when the parallel operation is performed.
I don't find exact usage from the samples of this repo or documentation of TBB.

**QUESTIONS:**

1. Am I doing something incorrect here or can the above code be improved ?
2. As we have reserved the tbb::info::default_concurrency() in task_arena, why do we still see the increase in CPU when the loop size increases?

**Comment by pavelkumbrasev** [comment]
Hi @Dush27, what do you mean by "high CPU observed with TBB when the loop size is increased"? What do you expect to see?
1) What the purpose of `global_control` in this code sample?
2) CPU utilization might increase with bigger loop size because oneTBB worker threads will have time to participate in task.

**Comment by Dush27** [comment]
Hi @pavelkumbrasev,

1. W.r.t global_control, just wanted to set the max parallelism. Is it not required?
2. I see that high CPU of around 40-60% with TBB enabled because of below thread spin overhead. Can this be avoided with TBB. Same high CPU is not observed when TBB is not used.

![image](https://user-images.githubusercontent.com/114069851/207544989-cd1452f9-d776-43a9-8285-d80fddb032e6.png)

Thanks in advance for your help.

**Comment by pavelkumbrasev** [comment]
1) `global_control` limits the TBB concurrency. If you want to limit it to some particular `P` you should also apply it to `task_arena`: `task_arena arena(IO_threads_number+ P, IO_threads_number)`  
2) I would expect bigger CPU utilization with TBB since more cores are busy processing parallel work. Do you expect different results? Is overall time reduced with TBB?

**Comment by Dush27** [comment]
1. I am doing the same in task_arena as below.

    int max_threads = tbb::this_task_arena::max_concurrency() 
                                 + tbb::info::default_concurrency() /* the number of IO threads to reserve slots inside the arena */;
    tbb::task_arena arena(max_threads, tbb::info::default_concurrency());

2. If we are pre-allocating the threads, we shouldn't see much time spent by CPU to spin the threads in runtime is the expectation. Intel's VTune profiles clearly shows that lot of time is spent by TBB in spin overhead.
I had tried using OpenMP also as an alternative where i see there is no such issues but it requires an system environment variable to be set as discussed here(https://stackoverflow.com/questions/74743259/can-omp-wait-policy-gomp-spincount-environment-variable-be-set-using-c-api-or).

**Comment by pavelkumbrasev** [comment]
It add red flag to the [WaitForSingleObject](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject) that is used in oneTBB semaphore implementation. That is used for thread sleep.
Are you observe increased spin time with bigger loops or opposite?

**Comment by pavelkumbrasev** [comment]
So in your scenario you have several IO threads(8) that submit parallel loops inside TBB and you observe increased spin time inside TBB once loops become bigger. 
It might happen if task size is small could you try to adjust the task size via grainsize? ([spec link](https://spec.oneapi.io/versions/latest/elements/oneTBB/source/algorithms/blocked_ranges/blocked_range2d_cls.html)) The average size of the task should be > 10k CPU clocks to hide TBB scheduling overheads.

**Comment by Dush27** [comment]
I tried with possible grainsizes but I doubt it is reaching such a big task size. I could still see similar high CPU issues.

Any other possible solutions ??
   -option to avoid the spin time in TBB?
   -option to avoid thread sleep inside TBB semaphore implementation and let them be always awake?

**Comment by pavelkumbrasev** [comment]
On both questions answer is no. TBB always brings some level of overheads but we can reduce it. In good scenarios TBB overheads for overall performance is less than 4%.
So in your case what is the real TBB overhead? Do you observe performance improvement with TBB?

**Comment by Dush27** [comment]
With TBB, performance improvement is observed with cost of CPU usage by around 45-75% which is not acceptable in my application.

Without TBB, performance is not achieved but CPU usage is normal around 25-30%.

**Comment by Dush27** [comment]
With following code, I could see CPU usage vary around 35-40%.
In addition to what you suggested, I set the grainSize to height/(tbb_max_threads_/2) to achieve this. If not, I was still seeing higher CPU utilization.

Any suggestions from your side to improve it even further?


int tbb_max_threads_ = tbb::this_task_arena::max_concurrency();
tbb::global_control global_limit(tbb::global_control::max_allowed_parallelism, tbb_max_threads_/2);
tbb::task_arena arena_((tbb_max_threads_/2)+8, 8);			
arena_.execute([&] {
    tbb::this_task_arena::isolate([&] {
        tbb::parallel_for(tbb::blocked_range<int>(kSize, (height - kSize), height/(tbb_max_threads_/2)),
            [&](tbb::blocked_range<int> r)
			{
			   //loop code
			   
            });
        });
    });

**Comment by pavelkumbrasev** [comment]
Please reopen this issue if you still have questions.
